### ISSUE TITLE
[BUG] Unable to verify Gitcoin Grant stamp

### ISSUE THREAD

**Issue by chibie** [gitcoinco/passport#1001]
**Overview**
https://discord.com/channels/562828676480237578/1078110515550756955/1081211484115316826

**Steps To Reproduce**
1. Go to passport.gitcoin.co dashboard
2. Try to verify Gitcoin Grant stamp

**Observed  behavior**
The Grant stamp verification fails

**Expected behavior**
Grant stamp should be verified successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/6025509/222739397-51cccfb7-fc34-4762-b67c-52e78f2295e5.png)
![image](https://user-images.githubusercontent.com/6025509/222739531-376f2318-b859-444e-8392-1b0a76bdcd7a.png)

**Additional context**

**Comment by nutrina** [comment]
Pushed to production last friday.
