### ISSUE TITLE
Update the redirect URIs for the oauth2 stamps on staging

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1003]
The redirect URI for the oauth2 platforms is a mismatch. These should be change din the individual oauth2 apps:

**Review**
- [x] Google
- [x] Twitter
- [x] LinkedIn
- [x] Facebook
- [x] Discord
- [x] Github 

**Staging**
- [x] Google
- [x] Twitter
- [x] LinkedIn
- [x] Facebook
- [x] Discord
- [x] Github

**Comment by lucianHymer** [comment]
Do we know where the LinkedIn and Google logins are? Also, could I be added as an admin to the Passport repo (and the scorer repo)? I'm not able to see/change the env variables in github. Thanks!

**Comment by lucianHymer** [comment]
I'm having issues connecting to the review and staging IAM backends. Wondering if it's a DNS problem

**Comment by lucianHymer** [comment]
All web2 stamps updated on review besides discord. Will fix staging once backend DNS is fixed

**Comment by Kweiss** [comment]
@lucianHymer - Lets do it :) What do you need for each of these?

**Comment by Jeremy-Gitcoin** [comment]
@lucianHymer do you still need @Kweiss for this ticket? I think it was in the blocked column but moved back to the backlog?

**Comment by lucianHymer** [comment]
Tim got Github working and I sent the details over to Kyle for the Discord settings

**Comment by Jeremy-Gitcoin** [comment]
@erichfi If we need Kyle, just need to grab 15min on his calendar to fix the Discord Issue(s)

**Comment by lucianHymer** [comment]
I've scheduled a meeting with Kyle on Thursday!
