### ISSUE TITLE
Scorer UI - unable to log in from domain `www.scorer.gitcoin.co`

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1004]
Login is only possible from `scorer.gitcoin.co`
We should enable both domains, for the sake of user experience.

**Comment by nutrina** [comment]
What is the desired behavior when the user tries to access `www.scorer.gitcoin.co`?
a. should we serve the content (same as we would, if he would access `scorer.gitcoin.co`
b. should we redirect (HTTP 302 redirect) to `scorer.gitcoin.co`

@Kweiss @erichfi

**Comment by Kweiss** [comment]
Got this updated for both www.passport and www.scorer
