### ISSUE TITLE
Copy requirements on new scorer flow

### ISSUE THREAD

**Issue by chibie** [gitcoinco/passport#1005]
We need the following information for the Choose Mechanism page of the new scorer flow

* The URL for the "Learn More" link in the "Gitcoin Scoring Mechanisms" tooltip 

* Copy for "Custom Scoring Mechanism" tooltip

* The description for the "Cost of Forgery" mechanism is the same as the "Unique Humanity (Binary)". Can we have a new copy for the cost of forgery?

ref: https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=677%3A26771&t=LxLYOJBAa4ztjsO6-0

discord: https://discord.com/channels/562828676480237578/1073190200404103218/1081231004049608754

**Comment by Kweiss** [comment]
Figma was updated with these details
