### ISSUE TITLE
Error verifying Facebook Stamp

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#1011]
**Overview**
We are getting reports from customers as they are unable to verify their Facebook stamp. I was able to reproduce this after I removed my stamp, cleared cache and tried to add it again

**Steps To Reproduce**
1. Go to Passport page
2. If you already have a facebook stamp, remove it and clear your cache
3. Attempt to add the stamp again
4. On the page to sign in to Facebook, you get an "App no active" error message

**Observed  behavior**
User unable to authenticate Facebook in order to add the stamp

**Expected behavior**
A page allowing the user to authenticate Facebook should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/88308638/225025557-3bae5e7d-8227-45ff-a9fb-732535f607ae.png)

**Additional context**
Here's a loom video 
https://www.loom.com/share/9be1a182f1364de282047df86303b4ce

**Comment by nutrina** [comment]
This has been solved in the mean time. It should work now.
