### ISSUE TITLE
[BUG] Error handling when creating scorers

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1015]
**Overview**
When creating a scorer, the following errors are not handled properly:
- user entered a duplicate scorer name
- user has already 5 scorers

**Steps To Reproduce**
1. Go to the scorer dashboard
2. Try adding new scorer with a duplicate name
3. Go through the entire creation process

**Observed  behavior**
A generic error is shown.

**Expected behavior**
A specific error like:
- [  ] `A scorer with this name already exists`
- [  ] `The maximum number of scorer has been reached`

**Screenshots**
This is the generic error:
![image](https://user-images.githubusercontent.com/8137830/225840961-5fc736de-3e2f-45f1-bc7b-4b110adc2ed5.png)

**Additional context**
Checking for maximum number of API Keys already works, we should use similar error handling (preferably re-use the code):
![image](https://user-images.githubusercontent.com/8137830/225841975-eddb905f-7d49-42c0-bc8f-daaf98acd7f3.png)

**Comment by chibie** [comment]
@nutrina how were you able to get to the modal?

according to design, the "+ API Key" button should be inactive immediately it hits the limit of 5.
