### ISSUE TITLE
[BUG/FEATURE] Confusion on landing page

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1017]
**Overview**
When I go to the landing page, I see a functional "Sign in with Ethereum Button".
I click it, and then 2 things happen:
- I am directly redirected to the dashboard, where my data gets loaded (because I was already signed in)
- and at the same time, I am asked to sign that login message

**Steps To Reproduce**
1. You need to have previously logged in
2. Go to the landing page
3. Click on the sign in button before being redirected
4. You should encounter the situation described above

**Observed  behavior**
You are allowed to trigger a login process before you actual login status is determined.

**Expected behavior**
Make it impossible for the user to trigger a login, before we finish the verification of his existing session. For example:
 - disable / hide the "Sign in with Ethereum" Button
 - show a message saying "Loading, please wait ..."
 - if the user is already logged in display "Go to app" instead of "Sign in ..."
 
 Or we might even disable the automatic redirect.

**Screenshots**
![image](https://user-images.githubusercontent.com/8137830/225853600-d29e0dc7-8af8-42f3-92ce-ec35e8570544.png)

**Additional context**
n. a.

**Comment by Kweiss** [comment]
I think this is my preference:
> Or we might even disable the automatic redirect.

It is jarring to land on a page, and have it change after 2 or 4 seconds without any action. We should not try to redirect without a user taking action. Every time I land on scorer.gitcoin.co I should be asked to SIWE, and if I want to navigate to the dashboard directly, as a user I would enter that route
