### ISSUE TITLE
Add a Gitcoin Allo stamp for verifying participation in Allo programs

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1024]
### User Story:
As a user,
I want to verify my participation as a funder or grantee in one of the Gitcoin Allo programs and receive a Gitcoin Passport stamp,
So that I can showcase my involvement in the ecosystem.

### Acceptance Criteria
GIVEN that I have participated as a funder or grantee in one of the Gitcoin Allo programs (Climate Alpha Round - Alpha, Open Source Round - Alpha, or Ethereum Infrastructure Round - Alpha)
WHEN I submit a request to add the stamp to my Gitcoin Passport based on my public wallet address
THEN my participation in the program should be verified, and a stamp should be added to my Gitcoin Passport.

GIVEN that I have not participated as a funder or grantee in one of the Gitcoin Allo programs
WHEN I submit a request to add the stamp to my Gitcoin Passport
THEN I should receive an error message indicating that I am not eligible for the stamp.

#### Product & Design Links:
Stamp image: ![Grants Stack Stamp](https://user-images.githubusercontent.com/100154376/230375174-93effb1a-18e4-44be-a674-c822ff5e909c.svg)

#### Tech Details:
- Minimum funding level worth $USD 10

#### Open Questions:
- What data can we get from Allo? Can we distinguish between matching-eligible and non-eligible contributions?

#### Notes/Assumptions:
This feature will enhance the Gitcoin Passport by providing users with a stamp that highlights their participation in Gitcoin Allo programs, further verifying their unique humanity and contributions to the ecosystem.

**Comment by Etovardesign** [comment]
Hey @erichfi, not sure when you wanted to have this creative ready but MMM is currently working on branding Allo. They just kicked off that work so it should be ready in the coming days. Lmk if this is an issue, happy to coordinate accordingly or come up with a placeholder if needed.

**Comment by Etovardesign** [comment]
Hey @erichfi waiting on final confirmation from Laura H.

**Comment by Etovardesign** [comment]
@erichfi let's use this and will confirm if we need to swap for a new version tomorrow after my chat with Laura H.
![Grants Stack Stamp](https://user-images.githubusercontent.com/100154376/230375174-93effb1a-18e4-44be-a674-c822ff5e909c.svg)

**Comment by Jeremy-Gitcoin** [comment]
@erichfi I added the April Beta round label to this one as I think it's probably important. Have we talked with Alex about how to set a score for this if we include it?

**Comment by Jeremy-Gitcoin** [comment]
@erichfi Is this in the icebox waiting on the stamp revamp work you're doing?
