### ISSUE TITLE
Implement 404 handler, in the scorer UI, for the case when the path cannot be matched

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1029]
When somebody goes to a bad link like this:

https://review.scorer.gitcoin.co/#/this/is/a/bad/link

then that person does not see anything at the moment.

@Etovardesign What we would need in this case is a 404 page.

[Figma design](https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=1920%3A30641&t=uq0sNapNBFC9uH9H-1)

Design is here:
https://www.figma.com/file/61l4GXuZTNIR8gfSybFqfo/Gitcoin-Passport---Lunar?node-id=434-11757&t=0EpsUPyde6FfUng2-0

**Comment by Etovardesign** [comment]
One more note: I'm not sure which channel we should link to in the "Contact us on **Discord**" section but I'd assume "passport-suuport" cc. @Kweiss

**Comment by nutrina** [comment]
@Etovardesign could you provide me that image from the design as PNG (or SVG), but make sure it preserves the transparency?

**Comment by nutrina** [comment]
Putting this on hold as we wait for the 404 image from MMM
