### ISSUE TITLE
Integrate Idena stamp into Gitcoin Passport and deploy to staging

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1042]
Integrate Idena as a stamp into Gitcoin Passport and deploy the updated code to staging for testing. The integration of the Idena stamp will enable Passport users to verify their Idena account and add it to their identity score.

Acceptance Criteria:

1. The Idena stamp integration code is rebased and merged into the Gitcoin Passport codebase.
2. The Idena stamp is visible and selectable as an option for Passport users to verify and add to their identity score.
3. The Idena stamp verification process is working correctly and accurately adds the user's Idena web ID to their identity score.
4. The updated Gitcoin Passport code with the Idena stamp integration is deployed to staging for testing.

Tasks:

- [x] Review the [Idena stamp integration PR](https://github.com/gitcoinco/passport/pull/671) and merge it into the Gitcoin Passport codebase.
- [x] Implement the necessary changes to the Passport codebase to support the Idena stamp integration.
- [x] Add the Idena stamp as an option for Passport users to verify and add to their identity score.
- [x] Test the Idena stamp verification process to ensure it is working correctly and accurately adds the user's Idena account to Passports.
- [ ] Deploy the updated Gitcoin Passport code with the Idena stamp integration to staging for testing.

**Comment by lucianHymer** [comment]
Going to wait to decide how to handle auth process after https://github.com/gitcoinco/passport/issues/869

**Comment by midenaio** [comment]
The [Idena stamp integration PR](https://github.com/gitcoinco/passport/pull/671) has been rebased onto the latest master and is ready to be merged

**Comment by Jeremy-Gitcoin** [comment]
@midenaio I pinged in Telegram group, looking for an activation code so I can test once we merge.

**Comment by midenaio** [comment]
Hey @Jeremy-Gitcoin, please check your Telegram pm for the code

**Comment by Jeremy-Gitcoin** [comment]
@midenaio Thank you!

**Comment by lucianHymer** [comment]
Alright I've merged the caching mechanism to main and provided Idena with an updated branch to review.

I also asked Idena to add unit tests and to clarify my thoughts around local testing.

I added documentation about the context and caching [here](https://www.notion.so/gitcoin/Community-Stamps-PR-Checklist-c0df3888c5e9465c901770b9e819e166?pvs=4#2d60a75237844c8cac707e4d7c70f544). Let me know if you'd like me to prepare something more user-facing or work with one of the devrel guys to put something together.

**Comment by lucianHymer** [comment]
The Idena team provided some updates, and this should be good to go! We just need to decide if we want to accept the updates to the expiration_date as-is (i.e. letting Idena set their own expiration dates).

This depends on where we settle with our on-chain and ComposeDB schemas. It sounds like we're leaning towards making the expiration date optional and allowing providers to configure their own expiration dates. In which case, the PR is good to merge.

**Comment by lucianHymer** [comment]
Hit me up for testing credentials if needed
