### ISSUE TITLE
New Users - Onboarding and One-Click Verification

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1052]
### User Story:
As a new user,
I want to be guided through the onboarding process and have the option to quickly verify my web3 stamps using the one-click verification feature,
So that I can easily understand the benefits of Passport and efficiently verify my identity.

### Acceptance Criteria:
GIVEN a new user accesses the Passport app,
WHEN they are presented with the onboarding wizard,
THEN they understand the purpose and benefits of Passport, including privacy-first verification and Passport Scores (Step 1),
AND they are introduced to the Unique Humanity Score (Step 2),
AND they are introduced to the one-click verification feature (Step 3),
AND they have the option to skip or proceed with discovering stamps,
AND if they choose to proceed, the app searches for their web3 stamps while showing a progress indicator,
AND if stamps are found, the user can confirm or cancel the verification process,
AND if no stamps are found, the user is directed to the dashboard to explore more stamp options.

#### Product & Design Links:
[Design files for onboarding wizard](https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=2411-35412&t=lPvshkIhAWhZEd8K-0)

#### Notes/Assumptions:

- Don't start this before https://github.com/gitcoinco/passport/issues/1053 is done -- this will be super helpful and lay the groundwork for this issue.

**Comment by schultztimothy** [comment]
Here is the PR that added multiple evm signers https://github.com/gitcoinco/passport/pull/799 The flow is super similar to what this will implement. Here is the call that will make the requests to all of the evm platforms to check eligibility https://github.com/gitcoinco/passport/blob/main/app/signer/utils.ts#L157

The one big difference between this feature and the new onboarding check is that the previous implementation is meant to check eligibility for an additional signer, not the logged in account.
