### ISSUE TITLE
Returning Users - One-Click Verification

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1053]
### User Story:
As a returning user,
I want to be welcomed back and have the option to quickly verify my web3 stamps using the one-click verification feature,
So that I can easily update my identity with minimal effort.

### Acceptance Criteria:
GIVEN a returning user accesses the Passport app,
WHEN they are presented with the Welcome Back screen,
THEN they are informed about the one-click verification feature,
AND they have the option to skip or proceed with verifying their identity,
AND if they choose to proceed, the app searches for their web3 stamps while showing a progress indicator,
AND if stamps are found, the user can confirm or cancel the verification process,
AND if no stamps are found, the user is directed to the dashboard to explore more stamp options.

#### Product & Design Links:
[Design files for one-click verification](https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=2411-35412&t=lPvshkIhAWhZEd8K-0)

#### Notes/Assumptions:

- As part of this, create the check boxes for selecting data points within a stamp that was found.
- Make the verification through multiple calls from the UI.

**Comment by aminah-io** [comment]
Per @schultztimothy:

> Here is the PR that added multiple evm signers https://github.com/gitcoinco/passport/pull/799 The flow is super similar to what this will implement. Here is the call that will make the requests to all of the evm platforms to check eligibility https://github.com/gitcoinco/passport/blob/main/app/signer/utils.ts#L157

> The one big difference between this feature and the new onboarding check is that the previous implementation is meant to check eligibility for an additional signer, not the logged in account.

**Comment by Jeremy-Gitcoin** [comment]
@aminah-io this looks awesome, the demo Friday was great!. @erichfi I'd prefer to default to all of the stamps as 'enabled' on the stamps found screen so that it's quicker and easier for users to create a new passport. How do you feel about that change?
