### ISSUE TITLE
Need Analytics Jupyter Notebooks deployed for Scorer on Prod

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1065]
The repo holding the notebook is this: https://github.com/gitcoinco/passport-scorer-analytics

**Comment by Jeremy-Gitcoin** [comment]
@nutrina It sounds like we're going to shutdown Sagemaker now? Is this something that we'll remove from the backlog?

**Comment by nutrina** [comment]
Yes, closing this as Sagemaker has been shut down.
