### ISSUE TITLE
Redesign the Landing Page of Gitcoin Passport App

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1067]
### User Story:
As a Gitcoin Passport user,
I want to experience a visually appealing and user-friendly landing page,
So that I can navigate seamlessly and access relevant information and call-to-actions.

### Acceptance Criteria:
GIVEN the updated landing page,
WHEN a user visits the landing page,
THEN the user should be able to navigate through the page seamlessly and have access to all the relevant information and call-to-actions.

#### Product & Design Links:
[Figma file for the new landing page design](https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=1510%3A26283&t=TpxacB7o4aTlJOE5-1)

#### Notes/Assumptions:

**Comment by lucianHymer** [comment]
Good to go on the ui-redesign branch. Waiting for Dashboard updates before merging to main
