### ISSUE TITLE
Redesign the Passport Stamp Dashboard

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1068]
### User Story:
As a Gitcoin Passport user,
I want to experience a visually appealing and user-friendly Stamp Dashboard,
So that I can view and interact with my Passport Stamps seamlessly and access relevant information and functionality.

### Acceptance Criteria:
GIVEN the updated Passport Stamp Dashboard,
WHEN a user accesses the dashboard,
THEN the user should be able to view and interact with their Passport Stamps seamlessly, having access to all relevant information and functionality.

#### Product & Design Links:
[Figma file for the new Stamp Dashboard design](https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=2498%3A36862&t=FWih6QmElRmJZRWx-1)

#### Notes/Assumptions:

**Comment by lucianHymer** [comment]
Good to go on the ui-redesign branch, not merged to main
