### ISSUE TITLE
Integrate Guild Stamp to Gitcoin Passport

### ISSUE THREAD

**Issue by Kweiss** [gitcoinco/passport#1075]
### User Story:
As a community member in the [ABC] Community
I want to verify my membership and status I have accumulated through the Guild app (guild.xyz)
So that I can prove I am a unique human and earn more stamps

### Acceptance Criteria
GIVEN I have a Guild account
WHEN I verify my stamp
THEN I should earn the verification of Guild

Verifications / credentials should include:
- Member of more than 5 guilds and > 15 roles across those guilds (guilds over 250 members)
- Owner (Guild Master) or Administrator (Guild Admin) of one or more guilds (over 500 members)
- Member with 1 or more roles in Passport Guild (https://guild.xyz/gitcoinpassport) 

#### Product & Design Links:
<links>

#### Tech Details:
Guild has APIs we can leverage to check to see which guilds a wallet address is part of, and how many roles they have earned within each community/guild they have joined.
https://www.npmjs.com/package/@guildxyz/sdk

Get Guilds Joined by a User
https://api.guild.xyz/v1/user/membership/:address

Get Guild by ID
https://api.guild.xyz/v1/guild/:id

#### Notes/Assumptions:
I would love to set this up

**Comment by Jeremy-Gitcoin** [comment]
@erichfi Here's the updated VCs I'd suggest, love your thoughts or we can move it back to the backlog

**Comment by Jeremy-Gitcoin** [comment]
@schultztimothy I have cleaned up the language on the VCs a little:
Member of more than 5 guilds and more than 15 roles*
Owner or Administrator of one or more guilds*
Member with 1 or more roles in Gitcoin Passport Guild

*Qualifying guilds have more than 250 members

This would require you changing the logic of the 2nd VC (sorry!) 

Also let's feature flag this 'off' for production until we have a thumbs up and score from Alex.

**Comment by Jeremy-Gitcoin** [comment]
That is perfect, thank you! @schultztimothy

**Comment by schultztimothy** [comment]
Sweet! These changes have been merged in and it should be feature flagged

**Comment by Jeremy-Gitcoin** [comment]
I can't see them in review, but that might be b/c it's feature flagged off? :)

**Comment by schultztimothy** [comment]
Ah yeah I just turned the FF on should be g2g :)

**Comment by Jeremy-Gitcoin** [comment]
@schultztimothy Perfect! Feature flag it back OFF and we should be ready! Moving it to ready to deploy.
