### ISSUE TITLE
Integrate intercom in Passport and Scorer UI

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1082]
See: https://github.com/gitcoinco/grants-stack/issues/1373

**Comment by chibie** [comment]
hey @michaelgreen06, 

i've assigned this to you as it looks like a good task you could take on to get familiar with the frontend.

**Comment by michaelgreen06** [comment]
Yay!!! Thanks @chibie I was thinking this was a perfect issue for me as well.
