### ISSUE TITLE
Bringing All Stamps On-Chain

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1084]
### User Story:
As a Passport holder,
I want to bring all my stamps on-chain and pay the on-chain fee per transaction,
So that I can have a secure, decentralized record of my stamps.

### Acceptance Criteria
GIVEN I am a Passport holder with one or more stamps
WHEN I click on the "Bring All My Stamps On-Chain" button
THEN my stamps should be moved on-chain as a single transaction, and I should be prompted to pay the required on-chain fee (approximately $2 US worth of ETH in addition to the gas fees, adjusted dynamically based on ether prices)

#### Product & Design Links:

- Add a "Bring All My Stamps On-Chain" button to the Passport dashboard.
- Upon clicking the button, display a progress indicator to inform users that their stamps are being moved on-chain and prompt them to pay the on-chain fee (approximately $2 US worth of ETH in addition to the gas fees, adjusted dynamically based on ether prices).
- Once the process is complete and the fee is paid, show a success message confirming the completion of the on-chain transfer.

#### Tech Details:

- [ ] The process must be secured using an EIP-712 signature for all the stamps that are written to the blockchain.
- [x] This should work on the Sepolia test network for now.
- [x] This functionality should be feature-flagged as we will only enable it in the review environment.
- [ ] The fees should be directed to the GitcoinDAO treasury account (`0x57a8865cfB1eCEf7253c27da6B4BC3dAEE5Be518`).

This depends on: #1072

#### Notes/Assumptions:

- Charging per transaction was deemed more reasonable than charging per stamp.
- The on-chain fee is set at a benchmark of $2 US worth of ETH, in addition to the gas fees, which will be adjusted dynamically as needed based on ether prices.

**Comment by nutrina** [comment]
Next steps:
- [ ] create API en IAM to return signed payload for the verifier
    - [ ] this will receive an array of VCs as input
    - [ ] VCs must be validated first (issuer, receiver / did, didkit validation)
- [ ] deploy contracts to local network
- [ ] implement button in Passport, to trigger the process of bringing stamps on-chain & test on local
    - [ ] needs to be feature flagged
- [ ] deploy verifier contract to Sepolia and test integration
- [ ] release to review

**Comment by nutrina** [comment]
Moving this back to "In Progress".
We want to make sure the user is on the Sepolia network, in order to avoid hims losing the transaction fee.

**Comment by nutrina** [comment]
This seems one, and was merged to main.
