### ISSUE TITLE
On-Demand Update of On-Chain Gitcoin Passport for New Stamps and Score Changes

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1085]
### User Story:
As a Passport holder,
I want an on-demand update of my on-chain Passport when I receive new credentials or when my score changes,
So that my on-chain representation accurately reflects my current Gitcoin Passport status.

### Acceptance Criteria
GIVEN I am a Passport holder who has received new credentials or experienced a score change
WHEN I select "Update my on-chain Passport"
THEN my on-chain Passport should immediately be updated, accurately reflecting all new credentials, updated score, and any other relevant changes.

#### Product & Design Links:
Link to feature request for batch transactions: [Batch Transactions Feature Request](https://github.com/gitcoinco/passport/issues/1309)

#### Tech Details:
1. Update feature request [#1309](https://github.com/gitcoinco/passport/issues/1309) to support batch processing of both credentials and score in a single transaction.
2. Update the /eas endpoint within the iAM server to:
  - Retrieve the score for the given address from the Scorer API.
  - Sign the score using the EAS encoded representation of { score: number, scorer_id: bytes32, stamps: bytes32 }.
  - Include the signed credential and score data in the response.
3. Modify the Gitcoin Passport Smart Contract to:
  - Adjust signature verification to encompass score data and score schema.
  - Update getMultiAttestRequest to return both score schema and score attestation as parts of the MultiAttestationRequest.
  - Invoke attester.addPassport(getMultiAttestRequest(schema, passport)); with the unified data.
4. The update process should compute a differential between off-chain and on-chain Passport states. This will be facilitated by solutions proposed in issue [#1087](https://github.com/gitcoinco/passport/issues/1087).
5. Enforce a $2 Fee for each transaction, dynamically calculated based on the current prices of the native network token.

#### UI Details:
- Enhance the existing "Bring Passport On-Chain" button on the Gitcoin Passport dashboard to also function as the "Update my on-chain Passport" control. This enhancement will allow users to not only initially bring their Passport on-chain but also initiate any subsequent on-chain updates.
- The button should display a disabled state (e.g., greyed out) when there are no changes to be updated, i.e., when the user's on-chain and off-chain Passports are identical.
- When new credentials have been added or scores have changed, the button should switch to an enabled state, indicating to the user that they can initiate an on-chain update.
- After the user initiates an on-chain update, the button should display a loading state (e.g., a spinning icon), indicating to the user that the update is in progress.
- Once the update completes successfully, the button should revert to its disabled state, and a notification should confirm the successful update to the user. 

#### Notes/Assumptions:

- It's assumed that batch transaction processing for the on-chain Passport, including score and credential integration, has been successfully implemented and tested.
- Future-proofing should be a consideration during implementation, enabling compatibility with potential enhancements like more flexible payloads that might include other attributes besides scores and credentials.

**Comment by schultztimothy** [comment]
Putting this back in to the Backlog. It should be quick to implement once https://github.com/gitcoinco/passport/issues/1288 is complete

**Comment by nutrina** [comment]
The documentation about the passport attestation is here: https://github.com/gitcoinco/eas-proxy/blob/main/docs/01-on-chain-passport-attestation.md
