### ISSUE TITLE
Error Handling and User Feedback

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1086]
### User Story:
As a Passport holder,
I want to be informed if any errors occur during the process of bringing stamps on-chain or updating my on-chain Passport copy,
So that I can take appropriate action.

### Acceptance Criteria
GIVEN I am a Passport holder using the on-chain features
WHEN an error occurs during the process of bringing stamps on-chain or updating the on-chain Passport copy
THEN I should be informed of the error, its cause, and any suggested actions to resolve the issue.

#### Product & Design Links:
- If an error occurs during the on-chain process, display an error message with clear and concise information about the cause of the error.
- Provide guidance on how users can resolve the issue, or direct them to contact support for assistance.

#### Notes/Assumptions:
- Don't start this, before the team finished https://github.com/gitcoinco/passport/issues/1084 and https://github.com/gitcoinco/passport/issues/1085.

**Comment by nutrina** [comment]
A preview of the messages:


![Image](https://github.com/gitcoinco/passport/assets/8137830/618fa345-6aa7-4596-a03c-ae7d5a72f6a1)


The user can also expand this to copy the receipt for our support:


![Image](https://github.com/gitcoinco/passport/assets/8137830/f39d49cd-0b33-47f6-8ace-3b0d8cb2bc70)



And we also have more specific messages, depending on the case like:



![Image](https://github.com/gitcoinco/passport/assets/8137830/a92ab534-9352-440b-889e-771c5f0403b9)


And:



![Image](https://github.com/gitcoinco/passport/assets/8137830/484d58e2-c8e5-4782-89ae-403039c7043e)
