### ISSUE TITLE
Displaying On-Chain Status of Individual Stamps

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1087]
### User Story:
As a Passport holder,
I want to see the on-chain status of my individual stamps/credentials,
So that I can understand which stamps are already on-chain and which are not.

### Acceptance Criteria
GIVEN I am a Passport holder viewing my Passport dashboard
WHEN I look at my individual stamps
THEN I should see an indicator showing the on-chain status of each stamp/credential.

#### Product & Design Links:
- For each stamp on the Passport dashboard, include a clear visual indicator (e.g., an icon or label) to show its on-chain status.
- Ensure the on-chain status of stamps is updated whenever the user brings their stamps on-chain or updates their on-chain Passport copy.

#### Tech Details:
This depends on: https://github.com/gitcoinco/passport/issues/1073

**Comment by nutrina** [comment]
So this added open point remains:
- [ ] highlight the on-chain status next each credential in the side bar cause there might edge cases where indicator per stamp does not reflect nuances across the credentials within the stamp

**Comment by chibie** [comment]
> Also I'm getting the on-chain symbol for all credentials in the app, before and after hitting the move stamps on-chain button. It should only be shown for the credentials that one has on-chain though.

@erichfi We chose to always display the on-chain symbol for all credentials to prevent UI alignment issues. Instead credentials not on-chain have a greyed out on-chain symbol while those on-chain are green.

> When we see that there are no discrepancies between the on-chain and DB version of the Passport, can we disable the "move stamps on-chain button"?

i'd say a new ticket be created for this, it's not a straightforward fix to be within scope of this ticket
