### ISSUE TITLE
Use Github Releases to track releases for the Passport repository

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1090]
### User Story:
As a developer
I want to be able to see the releases and draft releases of the passport repository
So that I can understand and track what has been deployed to staging and production.

Draft releases should reflect what is on staging.
Releases should reflect what is in production.

#### Tech Details:
See the github workflow that was created for the passport scorer, and that aims to automate this process.

**Comment by lucianHymer** [comment]
I noticed that we're currently running releases only in the API action for the scorer repo, and not the interface action. And the releases are tagged with the "app" namespace.

Should we do the other things listed here, i.e. add change_path and custom major and minor patterns to each task, and then add a release step to the interface workflow as well? https://github.com/PaulHatch/semantic-version#using-multiple-versions-in-the-same-repository

Or, do we just want a single version per repo? In which case we could drop the namespace. We should probably replicate the release task to the different parts of the app (api, interface) or at least establish a process where we always run the action with the release steps. I believe we could just define these steps once and then call it from each "Deploy ___ to Prod/Staging" workflow that we have. https://docs.github.com/en/actions/using-workflows/reusing-workflows This is my preferred opion

**Comment by nutrina** [comment]
Having a single version per repo make sense to me.
Also I like the reusable workflows. How would that look, we would have a single action saying: "Release to Production", and this would publish the UI and the BE, and then create the Release?

**Comment by lucianHymer** [comment]
Let's define a release process and then wrap up these workflows.

One potential workflow is...

1. On Release to Staging: Create a draft release based on the latest main commit (or requested commit? maybe defaulting to latest main?)
2. On Release to Production: Require that a draft release exists, create a full release WITH THE SAME COMMIT as the draft release

Or, do we want something more flexible? Like...

- always deploy the latest version of main (or specified commit) whether it's staging or prod
- don't require a draft release on prod
- if a draft release exists, promote it to a full release but overwrite it with the latest version of main (or specified commit)

The latter is the simpler version. But it's all doable. Let's discuss!

**Comment by lucianHymer** [comment]
Okay my latest thought is this: What if we create a full (non-draft) release when we push to staging, and then automatically push this exact release to production every Tuesday. With an ENV variable that can be used to skip a release.

**Comment by lucianHymer** [comment]
We settled on setting up the staging + production release as a single WF that we kick off manually. Using the "Required Reviewers" feature, we are pausing the WF to wait before pushing to prod.

Once this is fully tested (probably end-of-day May 23rd), this will be merged and closed out.
