### ISSUE TITLE
[BUG] Passport App Only Checks Last 500 Transactions for 0.5+ ETH Gas Expenditure Verification

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1093]
**Overview**
As a Passport holder attempting to verify that I have spent more than 0.5 ETH in gas on the main net, the Passport app only checks my last 500 transactions and does not look further out to verify this fact about myself.

**Steps To Reproduce**

1. Go to the Passport app
2. Navigate to the stamp for spending more than 0.5 ETH in gas on the main net
3. Attempt to verify this stamp for an account that has spent more than 0.5 ETH in gas but in transactions beyond the last 500

**Observed  behavior**
The Passport app only checks the last 500 transactions of the user and does not verify the fact correctly if the user has spent more than 0.5 ETH in gas beyond those 500 transactions.

**Expected behavior**
The Passport app should check more than just the last 500 transactions, if needed, to verify if the user has spent more than 0.5 ETH in gas on the main net.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
This issue might lead to incorrect verification of a user's gas expenditure, resulting in the user not being able to showcase their true Ethereum main net activity.

**Comment by schultztimothy** [comment]
The ETH tx stamp should now take into account ERC20 transactions as well as internal and normal txs
