### ISSUE TITLE
UI and Documentation updates to GTC Staking App

### ISSUE THREAD

**Issue by schultztimothy** [gitcoinco/passport#1101]
- [x] Update `More Info` button to link to valid notion page. It currently link [here](https://gitcoin.notion.site/About-Staking-on-Grants-Round-15-768f88d430ff4335ba23b17876b6e981) the [Gitcoin knowledge base](https://support.gitcoin.co/gitcoin-knowledge-base/gitcoin-passport/identity-staking-questions) about the staking app also has information on it. @je
![Image](https://user-images.githubusercontent.com/6887938/231803545-453eb8d7-f608-43a9-825b-a11f1da8e45e.png)
- [x] Link to deployed contract on [Etherscan](https://etherscan.io/address/0x0e3efd5be54cc0f4c64e0d186b0af4b7f2a0e95f). There are no designs for this but could be useful for users to review the contract before depositing coins into it
- [x] Update the `Gitcoin Grants Alpha Round` to `The Gitcoin Grants Beta Round`
![Image](https://user-images.githubusercontent.com/6887938/231816980-75521c19-aa5a-418e-a127-1949c8e98e7f.png)

**Comment by michaelgreen06** [comment]
I updated the linked notion page w/ accurate info
I renamed to Beta round. The dates displayed on the staking app should display the correct info from the beta round when that IDStaking contract is deployed.
