### ISSUE TITLE
GTC Staking subgraph improvements

### ISSUE THREAD

**Issue by schultztimothy** [gitcoinco/passport#1102]
# Context
There were delays last round between when a user staked GTC and the subgraph updating to account for this. Causing errors when users tried to claim stamps

Options:

1. Keep existing subgraph, add additional GRT to fund more queries through the round, improve messaging around stamp claim process and indicate that there is a possibility that users will not be able to claim their stamp until subgraph has indexed the transaction
2. Index all events from the staking contract and use that database as the source of truth for stamp issuance. Would need to setup infrastructure to do so or use scorer-api-db
3. Query contract directly. This is a bit unreliable since the relevant events are not indexed and it is not possible to filter by address. So we would have to pull all events on the contract then filter them in the browser by address. For example there are 2329 community staking events we would have to check. This number will likely double or triple. This would only apply to indicating in the UI that a user has staked on someone else. We are able to query the contract directly for users that have staked on themselves

**Comment by schultztimothy** [comment]
The team met after standup to discuss possible solutions to this. I updated the above options and added a couple more

1. Keep existing subgraph, add additional GRT to fund more queries through the round, improve messaging around stamp claim process and indicate that there is a possibility that users will not be able to claim their stamp until subgraph has indexed the transaction
2.  Index all events from the staking contract and use that database as the source of truth for stamp issuance. Would need to setup infrastructure to do so or use scorer-api-db. EDIT: I did a good amount of research on how allo is indexing events and put together this [PR](https://github.com/gitcoinco/allo-indexer/compare/gtc-staker-index?expand=1#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R84) that could act as indexer for the staking contracts. Its a pretty simple setup. We could ask them if they are willing to host the staking contract's events, or deploy our own instance. You can structure how the data is stored to provide a bit of filtering and aggregation.
3. ~~Query contract directly. This is a bit unreliable since the relevant events are not indexed and it is not possible to filter by address. So we would have to pull all events on the contract then filter them in the browser by address. For example there are 2329 community staking events we would have to check. This number will likely double or triple. This would only apply to indicating in the UI that a user has staked on someone else. We are able to query the contract directly for users that have staked on themselves~~ we felt like this would be too much strain on the system since we can't predict the number events and they would all need to be queried and filtered
4. Edit and redeploy the staking contract. We could make edits to how events are emitted so that they could be filtered by address. The downside here is that we would have to account for two contracts in the UI, for users who have already staked. We would also need to have two ways of querying a user's staked balance since we would be updating the event types

imo option 3 seems best at the moment since allo has done a lot of the work deploying and building the indexer, even if they don't want to host the data.

Very open to other suggestions as well :)

**Comment by nutrina** [comment]
We have settled for option #1 (keep the current subgraph).

TODOs:
- [ ] test that the subgraph is up & running
- [ ] check any necessary funding (with GRT tokens) that might be required

**Comment by schultztimothy** [comment]
I was able to confirm that the subgraph is up and running. For billing I believe this account is linked to @lucianHymer wallet

**Comment by michaelgreen06** [comment]
@nutrina is adding the popup explaining possible delays supposed to be included in this ticket or is it a separate ticket?

**Comment by lucianHymer** [comment]
I added GRT to the subgraph and updated the staking app to reference the beta round

**Comment by lucianHymer** [comment]
You'll see that https://www.staking.passport.gitcoin.co/ is working with the new beta round data
