### ISSUE TITLE
Read Me & Setup File Updates

### ISSUE THREAD

**Issue by michaelgreen06** [gitcoinco/passport#1112]
### User Story:
As a developer I want to easily get the passport & passport scorer app working on my local machine so that I can develop on passport. 

### Acceptance Criteria
GIVEN A developer follows every step of the read me & setup docs for passport & passport scorer respectively they can get the apps working on their local machine w/ no additional troubleshooting required.

**Comment by nutrina** [comment]
See also these messages:
- https://discord.com/channels/562828676480237578/986222591096279040/1110578208891473960
- https://discord.com/channels/562828676480237578/986222591096279040/1110235085787111536

**Comment by lucianHymer** [comment]
We should add a note about this process: https://discord.com/channels/562828676480237578/986222591096279040/1113851461676318740
