### ISSUE TITLE
Update Credential Weights in Unique Humanity Scorer

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1128]
### User Story:
As a Passport developer,
I want the Unique Humanity Scorer (both _gradual_ and _boolean_) to update the weights for each credential,
So that the scoring system reflects the most recent and accurate assessment of a Passport holder identity.

### Acceptance Criteria
GIVEN a Passport holder with verified credentials,
WHEN the Unique Humanity Scorer calculates their score,
THEN the updated weights for each credential are used,
AND the user's score is accurately reflected based on the new weights.

#### Product & Design Links:
- [File with updated weights](https://docs.google.com/spreadsheets/d/1ZR4yC-du-2HbGCMwwABBuKW9_pKL2rSXiD1X_D2Sam4/edit?usp=sharing)

#### Tech Details:
- Update the weights for each credential in the Unique Humanity Scorer based on the provided file.

#### Open Questions:
- Are there any additional factors to consider when updating the weights?
- Will there be a need for a migration or any additional steps to ensure compatibility with existing data?

#### Notes/Assumptions:
- The updated weights are provided in the attached file and should be integrated into the scoring system.
- The changes should not affect the functionality of existing scoring instances.

**Comment by nutrina** [comment]
`EthGasProvider` is missing.
Waiting for that.
