### ISSUE TITLE
Update Checkbox Color in 1-Click Verification Flow

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1135]
**Description:**
The checkboxes for credentials underlying a stamp in the 1-click-verification flow have a black/white color scheme that is unintuitive. Update the checked status color to purple.

**Acceptance Criteria:**

- Change the color of the checkboxes to purple when checked.
- Ensure the updated color scheme is applied consistently throughout the 1-click verification flow.

**Comment by schultztimothy** [comment]
It looks like the checkboxes were already updated, but I removed the outline on the accordian. This was default styling from chakra ui and is added to make elements more WAI-ARIA compliant. It might be a nice feature to make our apps a bit more compliant @Etovardesign
