### ISSUE TITLE
Infinite loop during "Sign-in-with-Ethereum" due to "Datasource connection error"

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1136]
**Overview**
While attempting to sign in using "Sign-in-with-Ethereum," a "Datasource connection error" occurs. When the user clicks "Done" after encountering this error, they are redirected back to the landing page. Upon trying to sign in again, the same error appears, creating an infinite loop. The only way to break this loop is to click "Try again."

**Steps To Reproduce**

1. Go to the Passport landing page
2. Click on "Sign-in-with-Ethereum"
3. Encounter the "Datasource connection error"
4. Click "Done"
5. Get redirected back to the landing page
6. Attempt to sign in again and observe the same error, creating an infinite loop

**Observed  behavior**
The user encounters a "Datasource connection error" while trying to sign in and is caught in an infinite loop of being redirected back to the landing page.

**Expected behavior**
The user should be able to sign in successfully using "Sign-in-with-Ethereum" without encountering any loops or errors.

**Screenshots**

**Additional context**
Clicking "Try again" allows the user to break out of the infinite loop, but this issue should be resolved to ensure a seamless sign-in experience.

**Comment by schultztimothy** [comment]
@erichfi what would be a better way to handle Datasource connection error's? The app is pretty much unusable without the datasource so I think that was why it is logging out the user. Ideally the datasource is never down, but maybe we could give more explanation as to why they can't connect?

**Comment by nutrina** [comment]
I was not able to reproduce right now.
Hence putting this in blocked.

**Comment by nutrina** [comment]
I was not able to reproduce this any more. I still keep my eyes on this, if I see the error again, I will dive in and debug.
