### ISSUE TITLE
Display Success Toast with Waiting Time Info for GTC Staking Stamp Verification

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1140]
### User Story:
As a GTC staker,
I want to see a success toast with information about the waiting time until my GTC Staking stamp is verifiable,
So that I can better understand the process and set my expectations accordingly.

### Acceptance Criteria
GIVEN a user successfully stakes GTC,
WHEN the staking transaction is confirmed,
THEN a success toast is displayed with information about the waiting time (e.g., "Your GTC Staking stamp will be verifiable in approximately 5 minutes.").

#### Product & Design Links:
- Figma link for success toast design: https://www.figma.com/file/61l4GXuZTNIR8gfSybFqfo/Gitcoin-Passport---Lunar?node-id=291%3A74917&t=6LoFQzipPcqc2eXe-1

#### Tech Details:
- Implementation can leverage existing toast components with modifications to include the waiting time information.

#### Open Questions:
- Are there any edge cases where the waiting time may differ significantly from the estimated 5 minutes?
- Should we include any additional information in the success toast?

#### Notes/Assumptions:
- The waiting time is based on the time it takes for the GTC Staking activity to propagate through the system.
- This feature is intended to improve the user experience and provide clearer communication about the staking process.

**Comment by aminah-io** [comment]
Will this be shown on the Passport Dashboard? Here's the flow I'm imagining, correct me if I'm wrong:
- the user visits the Identity Staking app
- when the user clicks the "Stake" button, they're returned to the Passport Dashboard where they see the GTC Staking sidebar along with the Success modal + time info...

**Comment by lucianHymer** [comment]
Available for testing here (using real GTC and ETH, will be staked until the round is over)  https://main.dshoxaxrgsb58.amplifyapp.com/
