### ISSUE TITLE
[BUG] Grants Stamp Verification Failing

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#1148]
**Overview**
Grants Stamp Verification Failing

**Steps To Reproduce**
We have some users unable to verify their grant stamp but claims to have donated in previous rounds. I could also see from their gitcoin profile

 - User 1:  Wallet address: 0xDe827Ab61F94B5568811ce223F2049aE084Ac5a5, profile: https://bounties.gitcoin.co/michaelji233/grants
 - User 2: wallet address: 0x8477cd6eC6af9770B352A31CAE45F73360c812e1, profile: https://bounties.gitcoin.co/va1337/grants

**Observed  behavior**
They are unable to verify the stamp even though they meet the criteria

**Expected behavior**
They should be able to get the stamp

**Screenshots**
![image](https://user-images.githubusercontent.com/88308638/233340933-ccddc656-0819-4239-b250-b1272c1efa27.png)

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

 > Yes I confirm that I did everything you said but it still didn't work. <br>- Gitcoin username: @michaelji233<br>- Browser used: Google Chrome<br>- Wallet address: 0xDe827Ab61F94B5568811ce223F2049aE084Ac5a5<br>- Operating System: MacOS 10.14.6<br>- Screenshot of Console Log -

**Link:** [Conversation with raimoons233@gmail.com](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/20291)

The second user provided their console log

`to load resource: net::ERR_BLOCKED_BY_CLIENT
[api.scorer.gitcoin.co/ceramic-cache/stamps/bulk:1](http://api.scorer.gitcoin.co/ceramic-cache/stamps/bulk:1) Failed to load resource: the server responded with a status of 404 ()
vendor-modern.0d2d903d.js:2 WebSocket connection to 'wss://[nexus-websocket-a.intercom.io/pubsub/5-WELJ9QpLhH8gwWcKy9HIJ1ydz7qrD3kjf1xTMPYcRVswxtS3WpFk0jWAEztygfP8i3ZsYbdCGcLWhSDlFTv2pl_aIdTCN-azNFBa?X-Nexus-New-Client=true&X-Nexus-Version=0.9.0&user_role=undefined](http://nexus-websocket-a.intercom.io/pubsub/5-WELJ9QpLhH8gwWcKy9HIJ1ydz7qrD3kjf1xTMPYcRVswxtS3WpFk0jWAEztygfP8i3ZsYbdCGcLWhSDlFTv2pl_aIdTCN-azNFBa?X-Nexus-New-Client=true&X-Nexus-Version=0.9.0&user_role=undefined)' failed: WebSocket is closed before the connection is established.
(anonymous) @ vendor-modern.0d2d903d.js:2
DevTools failed to load source map: Could not load content for chrome-extension://opcgpfmipidbgpenhmajoajpbobppdil/dapp-interface.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://rum.browser-intake-datadoghq.eu/api/v2/rum?ddsource=browser&ddtags=sdk_version%3A4.19.1%2Cenv%3Aprod%2Cservice%3Apassport-frontend&dd-api-key=pub25d6786acb4a59f5bdcf700a82bda0bd&dd-evp-origin-version=4.19.1&dd-evp-origin=browser&dd-request-id=a3e943a4-e804-46bf-a2ee-5fed76643931&batch_time=1681913813193 with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.
(anonymous) @ _app-b6a0bc1b8ec51c44.js:1
sendOnExit @ _app-b6a0bc1b8ec51c44.js:1
t.flush @ _app-b6a0bc1b8ec51c44.js:1
t.flushOnExit @ _app-b6a0bc1b8ec51c44.js:1
(anonymous) @ _app-b6a0bc1b8ec51c44.js:1
h @ _app-b6a0bc1b8ec51c44.js:1
(anonymous) @ _app-b6a0bc1b8ec51c44.js:1
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://logs.browser-intake-datadoghq.eu/api/v2/logs?ddsource=browser&ddtags=sdk_version%3A4.19.1%2Cenv%3Aprod%2Cservice%3Apassport-frontend&dd-api-key=pub25d6786acb4a59f5bdcf700a82bda0bd&dd-evp-origin-version=4.19.1&dd-evp-origin=browser&dd-request-id=fb091580-10d7-42fe-8609-99d78c2b0d5f with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.
(anonymous) @ _app-b6a0bc1b8ec51c44.js:1
sendOnExit @ _app-b6a0bc1b8ec51c44.js:1
t.flush @ _app-b6a0bc1b8ec51c44.js:1
t.flushOnExit @ _app-b6a0bc1b8ec51c44.js:1
(anonymous) @ _app-b6a0bc1b8ec51c44.js:1
h @ _app-b6a0bc1b8ec51c44.js:1
(anonymous) @ _app-b6a0bc1b8ec51c44.js:1`

**Customer:** [raimoons233@gmail.com](https://app.intercom.com/a/apps/xaafeyri/users/6440ab8c6adb881ce94494e1/all-conversations)
**Customer ID:** 00482049-3cae-4e0c-bbd5-aa5053ff9cf2
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/20291) when this issue is closed.

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/15655

**Comment by nutrina** [comment]
@jesuloluwao , I have left some messages here: https://discord.com/channels/562828676480237578/1094887548570046504

**Comment by nutrina** [comment]
@jesuloluwao do we have any feedback on this from the users?
