### ISSUE TITLE
[BUG] GTC Staking Stamp failing 

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#1149]
**Overview**
Users are facing two errors and I'm not certain if they are related. 
 1. On the identity staking page their GTC balance shows as 0 when they have GTC in their wallet
 2. They are get the stamp even though they have staked

**Steps To Reproduce**
I made a loom video https://www.loom.com/share/86bc08ad3c9a4f2994d6af94ca621e29

Sample of affected wallets. 0x3e1404e9af1c94c9eAf8FA92E2C2e1A936ed8701, 0x6964F870Aa07461521BA2f947837A00e0A4c008b

**Observed  behavior**
Some users reported they are seeing 0 GTC on their identity staking page as their wallet value. And then they are unable to get the stamp after they have staked

**Expected behavior**
Their GTC wallet balance should be reflected appropriately in the UI, and they should be able to get the stamp

**Screenshots**
Loom video attached above

 > <div class="intercom-container"><img src="https://downloads.intercomcdn.com/i/o/715959821/22c8083883ac42d7549343ae/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE+2023-04-20+110627.png"></div>

**Link:** [Conversation with diorkingman@yahoo.com](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/4619)

**Customer:** [diorkingman@yahoo.com](https://app.intercom.com/a/apps/xaafeyri/users/6436e006a36ae41ea44aaa80/all-conversations)
**Customer ID:** 726de066-71a5-43a3-bfa1-a863aad6cfdf
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/4619) when this issue is closed.

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/22845

**Comment by lucianHymer** [comment]
Hey! So I updated the staking app yesterday to use the new round, but the Passport app is still looking at the previous round data. The fix should be out today. Ticket here https://github.com/gitcoinco/passport/issues/1104

**Comment by lucianHymer** [comment]
We actually don't have access to intercom! This is merged and will be available on review shortly. Should be pushed to prod later today

**Comment by jesuloluwao** [comment]
@lucianHymer the act of closing this issue is what triggers a note for us in intercom. Would you mind closing out the issue only once it is live in production? As this is the point we actually need to know.

If it's impossible, would you mind tagging me here once it's deployed?

**Comment by jesuloluwao** [comment]
@lucianHymer just wanted to check again if the issue of GTC balance was checked also

**Comment by lucianHymer** [comment]
@jesuloluwao Hmm can that be customized in intercom? Our process is to tie pull requests to issues, and when we merge the pull request to main (which happens before the release, potentially a week before) then it automatically closes the issue.

We can avoid doing this for support requests if necessary.

The GTC staking stamp fix is released.

As far as the GTC balance goes, I haven't been able to recreate that. Sometimes it's 0 when the page loads, but it should refresh roughly every block (12 seconds). It's just querying the Infura API through their wallet extension (metamask), maybe the API times out sometimes? Let me know if you see a way to reproduce the issue.
