### ISSUE TITLE
Add 'Skip Onboarding Flow' Checkbox to 1-Click Verification Onboarding

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1152]
### User Story:
As a Passport user,
I want to have the option to skip the 1-click verification onboarding flow in the future,
So that I can access the main features of the app faster if I'm already familiar with the process.

### Acceptance Criteria
GIVEN a user is going through the 1-click verification onboarding flow,
WHEN they reach the final step,
THEN they are presented with a checkbox and a message allowing them to skip the onboarding flow in the future.

#### Product & Design Links:
- https://www.figma.com/file/61l4GXuZTNIR8gfSybFqfo/Gitcoin-Passport---Lunar?node-id=356%3A8401&t=j2GiYSRGwsY2Vrjd-1

#### Tech Details:
- Store user's choice to skip onboarding in their app settings

#### Open Questions:
- How should the user's choice be stored and applied for future sessions?

#### Notes/Assumptions:
- The checkbox and message should be displayed in a clear and user-friendly manner

**Comment by Jeremy-Gitcoin** [comment]
@erichfi Is this only the 'onboarding' or is this also the 1-click flow? Right now you'll need to redo that flow at least every 90days and there's no way to get to it form the dashboard so I don't want users to lose that ability!

**Comment by schultztimothy** [comment]
@erichfi @Jeremy-Gitcoin 
Here are some screenshots of where the checkbox was implemented. In terms of implementation, it will store a timestamp in localstorage. On load of the app it checks how old that timestamp is, and if the timestamp is less than three months old it skips the onboard process. If the timestamp is greater than three months old it removes it from localstorage and directs the user to the onboard process


![Image](https://user-images.githubusercontent.com/6887938/235192901-e56169e3-1e93-4c99-a905-cda2c097e201.png)
![Image](https://user-images.githubusercontent.com/6887938/235192900-353075d4-a304-4af6-8ab1-0d172ac7691a.png)
