### ISSUE TITLE
Integrate Intercom Support Widget with GTC Staking App

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1154]
### User Story:
As a GTC Staking app user,
I want to have access to the Intercom support widget,
So that I can easily get help and communicate with the support team when needed.

### Acceptance Criteria
GIVEN a user is on the GTC Staking app,
WHEN they need assistance or have a question,
THEN they can access the Intercom support widget on the app,
AND interact with the support team to resolve their issues or get answers to their questions.

#### Product & Design Links:
- [Intercom Widget Integration Documentation](https://developers.intercom.com/installing-intercom/docs/intercom-javascript)
- See [passport.gitcoin.co](https://passport.gitcoin.co/) for reference implementation and associated PR: https://github.com/gitcoinco/passport/pull/1083

#### Tech Details:
- Integrate the Intercom support widget with the GTC Staking app by adding the necessary code snippet provided in the documentation to the appropriate location within the app.

#### Open Questions:
- Are there any specific customizations required for the Intercom widget?

#### Notes/Assumptions:
- The integration should be seamless and not interfere with the app's performance or user experience.
- The Intercom widget should be accessible on all pages within the GTC Staking app.

**Comment by michaelgreen06** [comment]
The intercom app has been integrated and can be tested at:

https://main.dshoxaxrgsb58.amplifyapp.com/
