### ISSUE TITLE
Build Django command to index successful Gitcoin Grants contributions upon user complaints and create documentation for Support

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1155]
### User Story:
As a Passport holder who contributed to Gitcoin Grants using the deprecated app,
I want to have my successful contributions indexed and verified,
So that I can claim the associated credentials in my Passport.

### Acceptance Criteria
GIVEN a user complains that they can't verify their cGrants stamp,
WHEN support checks the transaction manually in Django admin and on-chain,
THEN they mark the transaction as successful.

GIVEN the transaction is marked as successful,
WHEN the support engineer runs the Django command to reindex that transaction,
THEN the transaction is indexed as part of the cGrants API.

GIVEN the transaction is indexed,
WHEN the user attempts to verify their stamp,
THEN they can claim the associated credentials if applicable.

#### Product & Design Links:
N/A

#### Tech Details:

- Create a Django command that queries the database, takes the contribution ID, and inserts it into the index table only if the transaction is successful.
- Ensure that the support team can mark transactions as successful in the Django admin database when applicable and upon user complaints.
- Synthesize the indexed transaction into the cGrants DB API, allowing Passport holders to claim the associated credentials.

#### Open Questions:
N/A

#### Notes/Assumptions:

- Provide lean documentation for the support team and support engineer on how to handle these situations.
- The Django command should only index contributions if the transaction is marked as successful and upon user complaints.

**Comment by nutrina** [comment]
Command exists in web repository: https://github.com/gitcoinco/web/commit/9210595ef554653db194a3465bab249f44388069
Documentation is still pending.
