### ISSUE TITLE
Passport Score Indicator not reflecting Google Account stamp weight

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1179]
**Overview**
The Passport score indicator is not reflecting the correct score based on the Google Account stamp's weight (1.67), showing zero instead.

**Steps To Reproduce**

1. Go to the Passport Scoring application dashboard
2. Add a Google Account stamp to the Passport with a weight of 1.67
3. Check the score indicator on the dashboard
4. See the incorrect score display

**Observed  behavior**
The score indicator on the dashboard displays zero, not reflecting the Google Account stamp's weight.

**Expected behavior**
The score indicator should display the correct score, accounting for the Google Account stamp's weight (1.67).

**Screenshots**
![Screenshot from 2023-04-24 16-46-34](https://user-images.githubusercontent.com/59769856/234033603-fb6bf869-048f-4797-8c39-72b7a1ba2f9c.png)

**Additional context**

**Comment by michaelgreen06** [comment]
@erichfi Just tried to reproduce this but my score is reflecting the weight accurately. 

Moving to blocked until you can confirm it's still happening
