### ISSUE TITLE
Updated Language on 1 click verification flow

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#1181]
Users often get confused with the I click verification. There should be appropriate wording to explain that "no eligible stamps" means there’s no unverified stamp they are able to receive.

![image](https://user-images.githubusercontent.com/88308638/234035310-7d40a55c-dfac-4b7c-9810-cbca947faedb.png)

**Comment by Jeremy-Gitcoin** [comment]
Let's change the wording from:
"view the dashboard to explore more stamp options" to the following "There are no unverified stamps currently eligible.  Please return to the dashboard and select additional stamps to receive by connecting to external accounts (examples include Gmail, Discord, etc) or perform the actions required to qualify for a stamp and resubmit for that stamp through the dashboard."
