### ISSUE TITLE
[FEEDBACK] UI improvements for expired stamps

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#1186]
> Other suggestion: people will be very frustrated to see when logging into passport that all their stamps have expired yet again and there is no explanation on why. Suggestion: 

1) When you click 'remove expired stamps' in the box that opens add a link saying 'Why have my stamps expired'? 

2) Create a quick KB article explaining why stamps expire (does not seem to exist)

**Link:** [Conversation with kris@hotmail.be](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/28121)

**Customer:** [kris@hotmail.be](https://app.intercom.com/a/apps/xaafeyri/users/6436a498493bdd1de62e754c/all-conversations)
**Customer ID:** 6dbc5fb9-b0a4-42df-b78d-4ca43f445938
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/28121) when this issue is closed.

**Comment by michaelgreen06** [comment]
Adding a link to the [passport FAQ ](https://support.gitcoin.co/gitcoin-knowledge-base/gitcoin-passport/identity-staking-questions/gtc-staking-faq)

Q: Why have my stamps expired?

A: Stamps expire and need to be renewed every 90 days. This helps Passport be confident in your unique humanity and makes it more challenging for sybil users to attack the system. The expiration and renewal cycle also enables humans to re-use stamps and credentials w/ new wallets if they ever lose access to the wallet they used to create a passport.

**Comment by jesuloluwao** [comment]
@michaelgreen06 This is the link to the article https://support.gitcoin.co/gitcoin-knowledge-base/gitcoin-passport/common-questions/why-have-my-stamps-expired. Can you confirm if it will be added to the product as suggested?

**Comment by michaelgreen06** [comment]
@jesuloluwao Thanks for tagging this!

I had it linked [here ](https://support.gitcoin.co/gitcoin-knowledge-base/gitcoin-passport/what-are-stamps), but will update to your link which makes finding the answer easier! Thanks for sharing this new link!
