### ISSUE TITLE
[BUG] Unable to claim Twitter stamp

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#1187]
**Overview**
This use was unable to claim their Twitter stamp. I checked their profile and they are eligible. 

**Steps To Reproduce**
No reproduction. The issue is specific to this user. Here are the details:
 - Browser used: Chrome 112.0.5615.138
 - Wallet address: 0x940214134c5e8d81DBD5E9015908c697dAB5e0DD
 - Twitter username: @Jim20082
 - Screenshot of Console Log: see attachent
![image](https://user-images.githubusercontent.com/88308638/234185057-cd5dbee6-0c6f-44d7-adc2-031db7ec7280.jpeg)

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
 > my twitter should have met all the requirements, correct?  I can get verified in previous rounds without any problem, so I don't know where is wrong this time. Please help

**Link:** [Conversation with superlucky1299@gmail.com](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/37764)

**Customer:** [superlucky1299@gmail.com](https://app.intercom.com/a/apps/xaafeyri/users/644647657627ad5fab941c7d/all-conversations)
**Customer ID:** 0b0d5134-b5c0-49ba-9364-83e2ee71309a
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/37764) when this issue is closed.

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/37823

**Comment by lucianHymer** [comment]
@jesuloluwao Were you ever able to confirm if this user was completing the process (including signing) within a minute?

**Comment by akathm** [comment]
Additional thought here - but can we check whether this could be because of duplicate treatment (twitter had been submitted 1x before).

**Comment by lucianHymer** [comment]
It's fine to claim a stamp with the same credentials in different wallets or the same wallet. The only factor is that, within a particular round, that stamp will only count towards the unique personhood score for the first to submit it. But claiming the stamp should always work.

**Comment by lucianHymer** [comment]
Also we resolved the error that was showing up in the console here and it was unrelated. The fix might not be in prod yet. But it would not have prevented this user from claiming this stamp.

**Comment by Jeremy-Gitcoin** [comment]
@lucianHymer and @jesuloluwao I'm going to close this now that round is over and we were not able to validate this behavior with other users.
