### ISSUE TITLE
UI updates to the Passport Holder Experience

### ISSUE THREAD

**Issue by Etovardesign** [gitcoinco/passport#1191]
There are a few updates needed in both the desktop and mobile experiences under the review environment.

I placed everything on one Figma page for easy access. It's separated into 2 sections: UI Screenshots & Updated Designs. All changes below should be documented and reflected on either section.

[Figma Link](https://www.figma.com/file/61l4GXuZTNIR8gfSybFqfo/Gitcoin-Passport---Lunar?node-id=364%3A8610&t=sWPxD1PtZ2qU5DIQ-1)

**Mobile**
Onboarding "Welcome to Passport"
- The image on Step 1 is broken.
- The copy and stepper are overlapped on most pages.

Onboarding "Get Started"
- Buttons should have 16p margins from the sides of the screen.
- Buttons should be in a single line not two.

One-Click Verification "No Eligible Stamps"
- Update designs to match the Figma mockup.
- Update the top-center icon and add a close button to the top-right corner.

Dashboard "Loading Stamps"
- The toast does not tell users to go sign their wallets. Feels like they're stuck.

Dashboard
- The tooltip should be horizontally centered on the screen and have 16p L/R margins.
- Stamp cards should fit text-copy width to fit in a single line not two.

Passport JSON Modal
- Header should be White (#FFFFFF)
- Text-copy should be Moon-300)
- Background should be Moon-800 (#000000) 
- Outline should be Wave-800 (#083A40)
- Update buttons to fit new design styles.

Stamp Details
- Update colors to fit the design mockups.
- Remove the background on the Close button and make the icon white.
- Change the "Select All" button to Lichen 600 (#8AF214)
- Change toggle-off mode to have a solid background and icon in Wave-800.
- The "More Details Component" should have a background in Moon-800 and updated copy color changes.

**Desktop**
Onboarding "Get Started" 
- Brand fonts are not rendering.

One-Click Verification "No Eligible Stamps"
- Update designs to match the Figma mockup.
- Update the top-center icon and add a close button to the top-right corner.

Dashboard
- The stamp card text-copy should be Moon-300.
- JSON buttons should be 40p by 40p and have a 1p outline in Wave-800.

Passport JSON Modal
- Header should be White (#FFFFFF)
- Text-copy should be Moon-300)
- Background should be Moon-800 (#000000) 
- Outline should be Wave-800 (#083A40)
- Update buttons to fit new design styles.

Stamp Details
- Same as mobile
- Match the updated Figma designs.

**Comment by schultztimothy** [comment]
**Mobile**
Onboarding "Welcome to Passport"
- The image on Step 1 is broken. - I was unable to reproduce this
- The copy and stepper are overlapped on most pages. ✅

Onboarding "Get Started"
- Buttons should have 16p margins from the sides of the screen. ✅
- Buttons should be in a single line not two. ✅

One-Click Verification "No Eligible Stamps"
- Update designs to match the Figma mockup. ✅
- Update the top-center icon and add a close button to the top-right corner. ✅

Dashboard "Loading Stamps"
- The toast does not tell users to go sign their wallets. Feels like they're stuck. - I updated the text to what is shown below
![Image](https://user-images.githubusercontent.com/6887938/235516494-dbaad6cb-4d29-446a-b460-64fcf83564fd.png)


Dashboard - ✅
- The tooltip should be horizontally centered on the screen and have 16p L/R margins.  ✅
- Stamp cards should fit text-copy width to fit in a single line not two.  ✅

Passport JSON Modal - ✅
- Header should be White (#FFFFFF)  ✅
- Text-copy should be Moon-300)  ✅
- Background should be Moon-800 (#000000)  ✅
- Outline should be Wave-800 (#083A40)  ✅
- Update buttons to fit new design styles.  ✅

Stamp Details
- Update colors to fit the design mockups. - ✅
- Remove the background on the Close button and make the icon white.
- Change the "Select All" button to Lichen 600 (#8AF214)
- Change toggle-off mode to have a solid background and icon in Wave-800.
- The "More Details Component" should have a background in Moon-800 and updated copy color changes.

**Desktop**
Onboarding "Get Started" 
- Brand fonts are not rendering.

One-Click Verification "No Eligible Stamps"
- Update designs to match the Figma mockup.
- Update the top-center icon and add a close button to the top-right corner.

Dashboard
- The stamp card text-copy should be Moon-300.
- JSON buttons should be 40p by 40p and have a 1p outline in Wave-800.

Passport JSON Modal
- Header should be White (#FFFFFF)
- Text-copy should be Moon-300)
- Background should be Moon-800 (#000000) 
- Outline should be Wave-800 (#083A40)
- Update buttons to fit new design styles.

Stamp Details
- Same as mobile
- Match the updated Figma designs.

**Comment by Jeremy-Gitcoin** [comment]
I'm getting this thick white bar on the right side of the dashboard on mobile @schultztimothy 

![Image](https://user-images.githubusercontent.com/129878085/236538300-b9c8e245-b497-4caa-a8ba-aa4a042f195a.PNG)

**Comment by Jeremy-Gitcoin** [comment]
@schultztimothy Also the #083A40 outline for the modal when clicking the JSON button doesn't seem to be showing in either Mobile or desktop

**Comment by nutrina** [comment]
@Jeremy-Gitcoin what browser are you using?
I am using the metamask app on my iPhone and I browse to passport here
and here I cannot reproduce this

**Comment by Jeremy-Gitcoin** [comment]
@nutrina I'm using iPhone X with Metamask app as well and still seeing the white bar on the side

**Comment by schultztimothy** [comment]
Finally tracked it down :) and merged in a fix jsut now. Should be on review in 15-20 minutes

**Comment by Jeremy-Gitcoin** [comment]
awesome, looks great, thank you!
