### ISSUE TITLE
[BUG] Can't connect to Passport with Argent Wallet

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#1216]
**Overview**
User is getting a Data Source connection error while trying to connect with an Argent wallet. I verified the same

**Steps To Reproduce**
1. Have an argent wallet, or download one and create at argent.xyz
2. Browse to passport.gitcoin.co
3. Connect with wallet connect and scan the QR code on your mobile

**Observed  behavior**
A data source connection error is seen and the following error is shown on the console 
![image](https://user-images.githubusercontent.com/88308638/235773378-c123319b-0ccb-4793-ad86-aea852b1b5de.png)

See loom video here https://www.loom.com/share/0e9a9f67cd5045ada3e7542ed4d8ca24

My argent wallet id is 0x2d17fee4ec32a491016aa4064a6502b18cf6cfb6,

The end user's address is hardymathieu.argent.xyz

**Expected behavior**
The user should be able to connect their wallet

 > Hey.<br>I'm verifying for hardymathieu.eth<br>but I "think" I may have, in the past, created a passport for hardymathieu.argent.xyz.

But I can't check, or undo the stamps in the argent wallet because it looks like Ceramic isn't working and it has been throwing errors for months.

But I'm afraid I'm gonna get sniped by the "anti-sybil team" as an attacker with the second passport I've created.

**Link:** [Conversation with Indigo Jellyfish from Emelgem](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/44205)

**Customer:** [Indigo Jellyfish from Emelgem](https://app.intercom.com/a/apps/xaafeyri/users/6450e52fa77048c6b151f984/all-conversations)
**Customer ID:** 6f1ddb8f-6528-4633-8364-69b49d075ccf
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/44205) when this issue is closed.

**Comment by Graciela985** [comment]
It's an issue with some wallets apparently.I had a similar issue. I contacted metamask/binance directly and they had it resolved for me. alarcongraciela985@gmail.com
Send them a mail. They'll help you out.
