### ISSUE TITLE
Integrate Hypercerts stamp into Gitcoin Passport

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#1236]
### User Story:
As a user of Hypercerts
I want to verify my hypercert(s)
So that I can prove I am a unique human and earn more stamps

### Acceptance Criteria
GIVEN I have claimed a Hypercert 
WHEN I verify my stamp
THEN I should earn the credentials of holding a Hypercert

GIVEN that I'm Passport holder qualifying for a Hypercerts stamp
WHEN I run through the 1click verification flow
THEN I should find the Hypercerts stamp as verifiable

Verifications / credentials should include:
Holds at least 1 Hypercert

#### Product & Design Links:
Stamp description under logo:
"Connect your wallet to verify that you hold a Hypercert"

The window at the bottom above 'save' on the side bar should read as the following
You can claim your Hypercerts at https://hypercerts.org/ (link the link)

#### Tech Details:
Website: https://hypercerts.org/

From Carl:
This should be quite easy ... we have a subgraph: https://thegraph.com/hosted-service/subgraph/hypercerts-admin/hypercerts-optimism-mainnet and could provide a list of approved token IDs

![HyperCert](https://user-images.githubusercontent.com/129878085/236573817-120a1c17-8bf1-4b21-b5d8-bc6d0115bfe3.png)

#### Notes/Assumptions:
- carl can support if we have any questions through Discord (he's a Gitcoin Steward)
- This depends on #1124

**Comment by schultztimothy** [comment]
I changed the image to one pulled from the https://hypercerts.org/app/dashboard/ its a little dark but seemed to go with the rest of the site a bit better. Very easy to switch it out to the provided image if you all would prefer. 
![Image](https://github.com/gitcoinco/passport/assets/6887938/d1dc36e4-bc0d-4ba4-9a74-92f1f3a8ad61)

**Comment by schultztimothy** [comment]
Just wanted to note that the criteria for obtaining the stamp is that you have at least one token/hypercert. Looking into things a bit more this is pretty easy to get since anyone can create a hypercert.

**Comment by Jeremy-Gitcoin** [comment]
Per slack, good on the image, updating the credential to "need to have at least 2 hypercerts owned for over 15 days?"
