### ISSUE TITLE
Unable to stake GTC

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1246]

**Comment by lucianHymer** [comment]
To test

1. Make sure you have some sepolia eth
2. Mint 100 fake sepolia GTC [here](https://sepolia.etherscan.io/address/0x0E3efD5BE54CC0f4C64e0D186b0af4b7F2A0e95F#writeContract) (Connect to Web3, mintAmount, enter 100000000000000000000, Write). I can also just send you some if you want to DM me.
3. Go to https://main.dshoxaxrgsb58.amplifyapp.com/StakeDashboard
4. Stake some amount, approve the same amount +1
5. Stake again, just 1 additional this time. It should NOT prompt you to up your allowance
6. Stake again, any amount should cause it to prompt you to adjust your allowance when you submit

**Comment by lucianHymer** [comment]
I deployed the contract to sepolia and started a round, so no need to use real eth or GTC to test. The code updates are deployed to the review server.

This is ready for testing here:  https://main.dshoxaxrgsb58.amplifyapp.com/
