### ISSUE TITLE
Remove 100 Facebook Friends Credential from Facebook Stamp

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1267]
We need to remove the 100 Facebook Friends credential from the Facebook stamp. This task involves updating the IAM validation and rendering logic for the Facebook stamp.

### Tech Details

- Update the credential validation logic to remove checks for the 100 Facebook Friends credential.
- Update the rendering logic to not display the 100 Facebook Friends credential for the Facebook stamp.
- Ensure the changes do not affect other credentials or other parts of the Facebook stamp.

### Open Questions:
Do we need to handle any potential data migration for users who currently have the 100 Facebook Friends credential?

**Comment by Jeremy-Gitcoin** [comment]
@akathm Heads up that we're removing the Facebook friends credential as we talked about this week.
