### ISSUE TITLE
[BUG] Get score API returns a 500 error

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#1280]
The passport score on the passport.gitcoin.co dashboard is showing 0.0 for all users. 

I checked and can see the get score endpoint is returning a 500 error
![image](https://github.com/gitcoinco/passport/assets/88308638/ff2f0134-3d38-4ef9-8671-27e855b77af0)

![image](https://github.com/gitcoinco/passport/assets/88308638/571f97dc-5166-4705-807b-743dc7767617)

Please help check

 > My passport score turn 0 when i connect my twitter

**Link:** [Conversation with Indigo Spaceship from Madrid](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/50064)

**Customer:** [Indigo Spaceship from Madrid](https://app.intercom.com/a/apps/xaafeyri/users/64634f36bb114500fcee4438/all-conversations)
**Customer ID:** e1bfb69c-cb91-4abc-938b-9b94314fe035
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/50064) when this issue is closed.

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/50067

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/50066

**Comment by lucianHymer** [comment]
This is should resolved, a deployment was taking place and this happened between the initial deployment and the database migration.

We should automate database migration, or at least figure out how to do it earlier in the process.
