### ISSUE TITLE
Integration of Gitcoin Passport Score On-Chain as Part of the Batch Transaction Process

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1309]
### User Story:
As a Gitcoin Passport holder,
I want to bring both my stamps and the score from my Gitcoin Passport dashboard on-chain,
So that I can verify my digital identity in a more transparent and decentralized manner.

### Acceptance Criteria
GIVEN I am a Gitcoin Passport holder with earned stamps and a score on my Gitcoin Passport dashboard,
WHEN I click on the "Bring my stamps on-chain" button and complete the necessary steps for a batch transaction,
THEN both my stamps and the score from my Gitcoin Passport dashboard are successfully written on the blockchain (Sepolia network) as part of my digital identity, and this information will be reflected in my Gitcoin Passport dashboard.

#### Tech Details:
Our solution to this feature involves several key components and steps that are detailed below:

1. **Data Structure Modification:** We will need to modify the existing data structure used for on-chain transactions. This structure currently holds the stamp data, and we'll extend it to hold the score from the Gitcoin Passport dashboard and the Scorer ID. The new schema will look like this: `{ score: number, scorer_id: bytes32 }`. The 'stamps' will be a hashed representation of the user's verified `PROVIDER_IDS` while 'scorer_id' could be the hashed primary key of the scorer_id in the API.
2. **Encoding EasScore:** We will implement an `EasScore` type, including the EAS encoded representation of the new score schema (`{ score: number, scorer_id: bytes32 }`). This will be incorporated into our data structure as `encodedData`. The EasScore type will look like this:

```
export type EasScore = {
  encodedData: string;
};

export type EasScore = {
  score: EasScore;
  recipient: string;
  expirationTime: any;
  revocable: boolean;
  refUID: string;
  value: any;
  nonce: number;
  fee: any;
};
```

3. **Signature Verification:** We will use an EIP712 signature of the `EasScore` for signature verification. This approach is simpler and more gas efficient than verifying a Verifiable Credential (VC) on-chain.
4. **Smart Contract Modification:** The smart contract that handles the on-chain transactions will need to be updated to handle the new score data. This includes updating the "addPassport" function in the GitcoinAttester contract to accept the new score data as part of the MultiAttestationRequest[] input.
5. **Batch Transaction Process:** During the process of bringing stamps on-chain, the Passport App will create a payload with the data to be written on-chain. This data will now include both the stamps and the score from the Gitcoin Passport dashboard. This payload will then be sent to the IAM Service.
6. **Data Validation:** The IAM service will validate the data and sign it using the EIP-712 procedure. The signed data is then sent back to the Passport App, which will call the "addPassportWithSignature" function in the GitcoinVerifier contract.
7. **Data Attestation:** If the data signature is validated, the function "addPassport" in the GitcoinAttester will be called to write the data (including the new score data) to the EAS protocol. This data will then be available on-chain.
8. **Fee and Replay Protection:** The small fee required for each dataset written on-chain will continue to apply. We will maintain the current mechanisms for replay protection, involving a unique nonce per recipient.

The modifications in the IAM server, adjustments to the `/eas` endpoint, and updates in the contract will facilitate the inclusion of the score and stamp data in a single transaction. This approach should allow us to bring both stamps and scores from the Gitcoin Passport dashboard on-chain in a single batch transaction, enhancing the Gitcoin Passport experience for our users.

#### Open Questions:
How will the score from the Gitcoin Passport dashboard be presented alongside the stamps in the Passport dashboard? Until we figure this out, don't worry about the "on-chain" display of the score in the Passport app.

#### Notes/Assumptions:
- Check this out: https://github.com/gitcoinco/passport/issues/1303

**Comment by nutrina** [comment]
For reference, see this research ticket: https://github.com/gitcoinco/passport/issues/1303

**Comment by schultztimothy** [comment]
This should be working as expected. There isn't currently an indication in the UI that your score has been written on chain, but you can view the attestations for your address or by this schema which represents the score: https://sepolia.easscan.org/schema/view/0xd43bc76510fcedd3ee4cac1a439ed4a130736b8faba0f4a814050e948942cdc0

The score is stored as a bignumber so it can represent a decimal, and there is a `decimals` field on the attestation for converting the bignumber back to a decimal
