### ISSUE TITLE
[BUG] Unable to verify staking stamp after staking GTC in Gitcoin season 18

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#1340]
Users are unable to verify the stamp after staking on https://www.staking.passport.gitcoin.co/StakeDashboard. I tried myself and I was able to reproduce. https://www.loom.com/share/6c26f676036e48b3bad34df568773c18

Here's my wallet id: 0x69f9e121702461eA52F627A6147ea3c6dc2DEF31
And a couple IDs who have also reported the same:
0x32af38af29E6151450b138F7cd578ca5ED7FE446
0xE0Ca860B4cb42659F56b65E499A9c08C430Ec150

 > <div dir="ltr">Already staked 10 GTC in Gitcoin Season 18<div>But i cannot complete GTC Staking Stamp in Gitcoin Passport </div><div>Please help me. Image attached</div><div>My address ETH metamask : </div><div><br></div><div>0x32af38af29E6151450b138F7cd578ca5ED7FE446</div><div><br></div><div>Thank you.</div></div>

**Link:** [Conversation with Tuan Phucs Nguyen](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/53819)

**Customer:** [Tuan Phucs Nguyen](https://app.intercom.com/a/apps/xaafeyri/users/647f8e331607130b8a527768/all-conversations)
**Customer ID:** 6809328b-66f4-4611-9af2-5667673b066c
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/53819) when this issue is closed.

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/shared/mentions/conversation/53939
https://app.intercom.com/a/inbox/xaafeyri/inbox/shared/mentions/conversation/53764
https://app.intercom.com/a/inbox/xaafeyri/inbox/shared/mentions/conversation/53839

**Comment by michaelgreen06** [comment]
In this ticket I also addressed the issue w/ the confusing text:
"Staking only affects your Passport score when GTC is staked for an active round
Once the round completes, GTC may be unstaked"
