### ISSUE TITLE
[BUG] Issues loading Passport stamps

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#1352]
We're seeing issues when loading passport. I can see on the console that alchemy api seems to return a rate limit error 429, and 
 https://api.scorer.gitcoin.co/account/nonce returns a 500 error. No stamps are being loaded as seen in the screenshot
![image](https://github.com/gitcoinco/passport/assets/88308638/9b4b1852-8359-4817-bcb2-fb2e5ecf859c)

 > hello I am trying to verify my gitcoin donations but I can't it says you do not fulfill the requirements but I'm sure I do

**Link:** [Conversation with hasanmostafavi74@gmail.com](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/55760)

**Customer:** [hasanmostafavi74@gmail.com](https://app.intercom.com/a/apps/xaafeyri/users/645f82133097041c8259dd56/all-conversations)
**Customer ID:** 15c169ef-974d-4447-8927-8c5756817306
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/55760) when this issue is closed.

**Comment by Jeremy-Gitcoin** [comment]
@jesuloluwao This should be resolved based on the new enterprise Alchemy account we created
