### ISSUE TITLE
[BUG] Github verification stamp error

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#1355]
Here's a loom video showing the error https://www.loom.com/share/4b8e1e4f7b704270958f54e76db40ca0?sid=957407c8-bfc9-4425-ae1c-3432ee8fbef8

Multiple users are also reporting this error

 > GitHub saying failed 

**Link:** [Conversation with opokeabraham@gmail.com](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/59857)

**Customer:** [opokeabraham@gmail.com](https://app.intercom.com/a/apps/xaafeyri/users/64873998139735dd22a82759/all-conversations)
**Customer ID:** fe10ed44-4d33-42a0-a2c9-82d8b52f9a74
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/59857) when this issue is closed.

**Comment by lucianHymer** [comment]
This is due to rate-limiting in the github API. I am exploring our options. I believe we should be able to use the user's rate limit if we do this correctly, so that should fix this issue.

**Comment by jesuloluwao** [comment]
btw. I'm just adding these ticket links so each individual ticket is linked to this issue
https://app.intercom.com/a/inbox/xaafeyri/inbox/team/6464831/conversation/59942
https://app.intercom.com/a/inbox/xaafeyri/inbox/team/6464831/conversation/59958
https://app.intercom.com/a/inbox/xaafeyri/inbox/team/6464831/conversation/59996
https://app.intercom.com/a/inbox/xaafeyri/inbox/team/6464831/conversation/60018
