### ISSUE TITLE
Document Current Alarms and Implement Additional Alarms

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1358]
### User Story:
As a systems administrator,
I want to document the current alarms and implement additional meaningful alarms,
So that I can better monitor our system's health.

### Acceptance Criteria
GIVEN a system component such as Redis Cluster, DB, or certain tasks,
WHEN the component exceeds predefined thresholds (CPU, MEM, storage, response times),
THEN an alarm should be triggered and logged.

#### Product & Design Links:
N/A

#### Tech Details:
This task involves documenting the current alarms in a Notion document and creating new alarms for the Redis Cluster, DB, and specific tasks.

Implement the alarms via DataDog -> PagerDuty. @chibie is a good contact for DataDog questions.

#### Open Questions:
What specific thresholds should trigger the new alarms?

#### Notes/Assumptions:
Assumes that additional alarms will enhance our ability to detect and respond to potential issues before they become critical.

**Comment by nutrina** [comment]
Thinking more about this here a list of things we should monitor (in order of priority):
- error rate HTTP
  - how many timeouts
  - how many 5xx errors?
- duration of time for score calculation in the UI
  - should be less than 30 s for example

**Comment by chibie** [comment]
Current alarms are being documented here https://www.notion.so/gitcoin/Passport-Monitors-444bfbe603d146ecbdd54211e1646957

**Comment by Jeremy-Gitcoin** [comment]
@nutrina Can you move this to done when you've had a chance to review? I can't approve this issue :)

**Comment by nutrina** [comment]
Some of the alarms are outdated, the ECS scorer instance has changed.
Have highlighted this in the notion doc: https://www.notion.so/gitcoin/Passport-Monitors-444bfbe603d146ecbdd54211e1646957
