### ISSUE TITLE
Implement Better Celery Monitoring to Show Queue Size

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1360]
### User Story:
As a backend developer,
I want to implement better Celery monitoring,
So that I can easily see the size of the task queues.

### Acceptance Criteria
GIVEN a task queue,
WHEN I check the Celery monitoring system,
THEN I should see the current size of the queue.

#### Product & Design Links:
N/A

#### Tech Details:
This task involves enhancing the Celery monitoring system to provide clear visualizations of the size of each task queue.

#### Open Questions:
Which third-party tool should we use to provide these visualizations, considering that Celery has removed such visualizations?

#### Notes/Assumptions:
Assumes that better visualization of queue size will aid in managing task queues and help developers identify and address performance issues more quickly.

**Comment by lucianHymer** [comment]
I wonder if we could set this up as a metric for auto-scaling? Currently we're using the CPU usage, and it basically doesn't work. With a few large workers (16vCPU), tasks are processed quickly but they're mostly just waiting on the DB so the CPU usage is low so they do not auto-scale. With many small workers (0.25vCPU), the CPU usage actually is higher and auto-scaling works, but this is way less efficient (celery likes fewer top-level work and wastes time duplicating messages when there are more workers) and this method basically doesn't work (too slow to catch up to demand spikes).

So, I'm thinking we should probably use fewer, larger CPUs and set up auto-scaling using perhaps this queue size metric?

**Comment by nutrina** [comment]
This looks good. I am going to test by pushing a number of items into the queues ...

What is still open: deploy the ddog agent via pulumi

**Comment by nutrina** [comment]
Works great:

![Image](https://github.com/gitcoinco/passport/assets/8137830/432bf76f-00f5-4b06-b25c-2533a5c42c21)
