### ISSUE TITLE
Documentation for Passport Attestation - Option 2

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1363]
### User Story:
As a developer or contributor working on the On-Chain Passport project,
I want to have a finalized and comprehensive documentation for the Passport Attestation - Option 2,
So that I can understand its functionalities and use it more effectively in the project's development.

### Acceptance Criteria
GIVEN that I am a contributor to the On-Chain Passport project
WHEN I visit the documentation link
THEN I should find a detailed, clear, and consistent documentation for Passport Attestation - Option 2, which is devoid of typographical errors, grammatical mistakes, or technical inaccuracies.

#### Product & Design Links:
~~[On-Chain Passport Project Documentation](https://github.com/gitcoinco/passport/blob/on_chain_docs/docs/on_chain.md)~~
[On-Chain Passport Attestations](https://github.com/gitcoinco/eas-proxy/blob/on_chain_docs/docs/01-on-chain-passport-attestation.md)

#### Tech Details:
The documentation should include a comprehensive explanation of the technical aspects of Option 2, including but not limited to the functionality, the workflow, and any coding standards or conventions used.

#### Open Questions:
Are there any specific aspects of Option 2 that need to be emphasized in the documentation?

#### Notes/Assumptions:
This documentation is for Option 2 of the Passport Attestation in the On-Chain Passport project. It is assumed that the primary audience has a basic understanding of blockchain technology.

**Comment by nutrina** [comment]
Documentation & research is in this PR: https://github.com/gitcoinco/eas-proxy/pull/20

Docs are here:
- https://github.com/gitcoinco/eas-proxy/blob/on_chain_docs/docs/00-on-chain-data.md
- https://github.com/gitcoinco/eas-proxy/blob/on_chain_docs/docs/01-on-chain-passport-attestation.md
