### ISSUE TITLE
Ensure Inclusion of Credential Issuance Dates in the Passport Attestation Schema

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1367]
### User Story:
As a developer or contributor working on the On-Chain Passport project,
I want the attestation schema to include the issuance dates for each credential,
So that I can have more granular information about the user's activity and trustworthiness.

### Acceptance Criteria
GIVEN I am a developer or contributor to the On-Chain Passport project,
WHEN I inspect the on-chain Passport attestation,
THEN I should be able to see not only the credentials held by a user but also the dates each of these credentials were issued.

#### Product & Design Links:
https://github.com/gitcoinco/eas-proxy/blob/main/docs/01-on-chain-passport-attestation.md

#### Tech Details:
The enhancement of the schema will require the creation and minting of attestations that include the issuance dates of all the respective credentials.

- [ ] Create a new schema in EAS.
- [ ] Adjust the way we format the attestations. 

#### Open Questions:
- Will the inclusion of issuance dates increase the on-chain transaction costs significantly?

#### Notes/Assumptions:
This feature request is for Option 2 of the Passport Attestation in the On-Chain Passport project. It is assumed that the addition of issuance dates will provide valuable context and history about the passport holder's activity, aiding in more accurate trust assessments.

**Comment by nutrina** [comment]
This is covered in the documentation in this PR: https://github.com/gitcoinco/eas-proxy/pull/20

Docs are here:
- https://github.com/gitcoinco/eas-proxy/blob/on_chain_docs/docs/00-on-chain-data.md
- https://github.com/gitcoinco/eas-proxy/blob/on_chain_docs/docs/01-on-chain-passport-attestation.md

**Comment by nutrina** [comment]
@erichfi given that the issuance date is of importance, shall we also include the expiration date of the individual stamps in the attestation schema?
We do have the option to set an expiration date for the entire attestation, but this would apply for the entire passport.
Instead, I think we should add one in the schema, such that we can track expirations for individual stamps.

**Comment by nutrina** [comment]
Open points for this task:
- [ ] decision if to also include expiration date for individual stamps (similar array as the issuanceDates)
    - [ ] if yes, then the docs also need update
- [ ] review tests + add tests for more scenarios
- [ ] add an equivalent test as `app.post("/api/v0.0.0/eas", (req: Request, res: Response): void => { ...` but for the new stamp
- [ ] call the new endpoint from the Passport app
