### ISSUE TITLE
[BUG] ZKSync Era stamp not adding to the user's score

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#1373]
This user already claimed the Zksync stamp through a transaction on Zksyn era. I have checked their passport and I can see that they have the stamp.

When I did a summation of their stamps, I can see that the Zksync era stamp is not added. I think there's no score associated with the zksync era stamp. I would assume it should be same as Zksync. In the score sheet, the score is only associated with "ZKSync" provider, but when you claim with era, the provider is set as "ZkSyncEra"

Here's the user details:
My address : 0x09aB3669Bb6F1A51Af4D283824C1672948bf3295
My Tx: https://explorer.zksync.io/tx/0xb3b7dae71717a268b10fb5b99bc706be4914a9b50e7e301ec62e6dc244e9cdb1

 > <font face="Hei" size="2">My address :<span style="color: rgb(36, 39, 42); white-space: pre; ">0x09aB3669Bb6F1A51Af4D283824C1672948bf3295</span></font><div><font face="Hei" size="2">My Tx:https://explorer.zksync.io/tx/0xb3b7dae71717a268b10fb5b99bc706be4914a9b50e7e301ec62e6dc244e9cdb1

**Link:** [Conversation with 赵胜男](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/60374)

**Customer:** [赵胜男](https://app.intercom.com/a/apps/xaafeyri/users/648a8f86b2edca0beeecb020/all-conversations)
**Customer ID:** 6f9b118e-780c-42bd-9914-800d45aba6bb
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/60374) when this issue is closed.

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/shared/mentions/conversation/60378

**Comment by chibie** [comment]
tracking score update with this ticket https://github.com/gitcoinco/passport/issues/1374
