### ISSUE TITLE
Inclusion and Updating of Weights for Credentials within zkSync Stamp in Passport's Unique Humanity Scoring Model

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1374]
### User Story:
As a Passport administrator,
I want to include the zkSync Era credential in the scoring model and adjust the weights for both zkSync Lite and zkSync Era credentials,
So that I can better reflect the value these credentials bring to the unique humanity scoring model.

### Acceptance Criteria
GIVEN that a user has earned either the zkSync Lite or zkSync Era credential within the zkSync Stamp,
WHEN the unique humanity score is calculated,
THEN the updated weights for these credentials should be applied in the scoring model.

#### Tech Details:
This feature update will require adjustments to the scoring algorithm within the Passport system. The current weight for the zkSync Lite credential is `1.67`. The new weight for _both_ zkSync Lite and zkSync Era credentials will be set to `0.835`. This change includes adding the zkSync Era credential to the scoring model.

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/60378
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/60374
