### ISSUE TITLE
[BUG] User unable to claim Grants stamp

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#1378]
This user has donated to the a gitcoin round before gr15 but still unable to claim the stamp.

 > I have synced the backend of the profile. The txid appeared now but user still cannot verify the Grants stamp. I have a feeling it is because the frontend have the donation date mixed up. The txid is dated back in June last year, but frontend picked it up as 1 day ago. <br>txid: <a href="https://etherscan.io/tx/0x3459de6bb9587eb4ccd306041f1f3f9bf670ec5b8880ea433def6cc03429d18a" target="_blank">https://etherscan.io/tx/0x3459de6bb9587eb4ccd306041f1f3f9bf670ec5b8880ea433def6cc03429d18a</a><br>Gitcoin's profile: https://bounties.gitcoin.co/vasyanj<br><br>Please assist. Thank you. 

**Link:** [Conversation with vasyan1406@gmail.com](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/60235)

**Customer:** [vasyan1406@gmail.com](https://app.intercom.com/a/apps/xaafeyri/users/6489bbe8c1d38a660347f178/all-conversations)
**Customer ID:** ac804cdc-d765-4966-9bf0-c7b27996314a
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/60235) when this issue is closed.

**Comment by lucianHymer** [comment]
When first digging into this, it seemed like switching Celery over to use gevent threading would really help. The idea being that we don't need to be blocking (consuming workers) when waiting on the DB, and mostly our workers are just waiting on the DB. This would hopefully stop our current situation where we're not using our available CPU.

However, gevent isn't playing nice with the Django DB operations. I haven't been able to get it all working yet, but I'm seeing results similar to this. https://zapier.com/engineering/why-zapier-doesnt-use-gevent-yet/

I think I'm going to abandon going down this route. There doesn't seem to be a mature way to use django/celery/gevent together

**Comment by lucianHymer** [comment]
I will do some more testing after the production release this week

**Comment by lucianHymer** [comment]
@nutrina I need some help figuring out how to access the cgrants backend. I assume it's similar to the scorer backend, but I'm getting DB connection errors.
