### ISSUE TITLE
Research Deduplication for Humanode

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1383]

**Comment by Jeremy-Gitcoin** [comment]
This is dependent on #1249 as we need some additional fields in the VC to store the Epoch

**Comment by nutrina** [comment]
The open point was around how to set custom expiration time.

This is possible as shown here in this example: https://github.com/gitcoinco/passport/blob/739bd2c78ac74d8c0e9f8413bc2b3a4df942d06c/platforms/src/Civic/Providers/civic.ts#L47C16-L47C16

**Comment by nutrina** [comment]
@erichfi  this can be closed, no further action needed.
