### ISSUE TITLE
Tracking Deduplicated Stamps per Scorer ID

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1390]
### User Story:
As a Passport administrator,
I want to track and map scorer IDs to the passports that have been deduplicated and record the Ethereum addresses associated with the duplicate stamps,
So that I can gain deeper insights into the relationships between users and understand how the deduplication impacts scoring.

### Acceptance Criteria
GIVEN a scoring instance with a specific scorer ID,
WHEN there are multiple passports associated with Ethereum addresses that share a unique hash through a credential (indicating duplicate stamps),
THEN the system should track these Ethereum addresses, group them based on the shared hash, and map these groups to the scorer ID that performed the deduplication.

#### Product & Design Links:
E.g., `address`, `duplicate hash`, `scorer id`

#### Tech Details:
This feature requires enhancements to our database schema to track the associations between Ethereum addresses that share a unique hash through a credential, and to map these groups to the appropriate scorer IDs. This might involve creating additional tables or records. The precise technical details would need to be further explored during the design and development phases.

#### Notes/Assumptions:
- The primary use of this feature is for internal auditing and analysis, to provide insights into stamp usage, and to understand the relationships between users.
- We are assuming that this feature will help improve the effectiveness of the Passport system by providing a more granular view of how duplicate stamps are used across different Ethereum addresses.

**Comment by lucianHymer** [comment]
The info is all available in the DB already to do this.

In django, we can get it with:
```
from django.contrib.postgres.aggregates import ArrayAgg
Stamp.objects.values('hash','passport__community').annotate(addresses=ArrayAgg("passport__address")).filter(addresses__len__gt=1)
```

Or to get values for a specific scorer ID
```
Stamp.objects.filter(passport__community__id=SCORER_ID).values('hash','passport__community').annotate(addresses=ArrayAgg("passport__address")).filter(addresses__len__gt=1)
```

(Note this only works with postgres. But the equivalent can be done with multiple queries on other DBs. Our servers all run postgres.)

This is a fairly slow query (~10seconds), but if we're using this for internal/analytics purposes, that should be fine. I would rather leave the data as-is and do this slow query on occasion rather than add additional DB writes during the scoring or caching process.

If that makes sense, we then have a couple options.

1. Add an endpoint in our analytics API to return this data, using the query above
2. Just post-process the stamp data in whatever analytics tool we're using. I can provide the SQL statement that could be used to set up a temporary table in an analytics DB.

**Comment by lucianHymer** [comment]
Blocked on https://github.com/gitcoinco/passport/issues/1399

**Comment by lucianHymer** [comment]
SQL statements for duplicates:
```
SELECT "registry_stamp"."hash", "registry_passport"."community_id", ARRAY_AGG("registry_passport"."address" ) AS "addresses" FROM "registry_stamp" LEFT OUTER JOIN "registry_passport" ON ("registry_stamp"."passport_id" = "registry_passport"."id") GROUP BY "registry_stamp"."hash", "registry_passport"."community_id" HAVING CASE WHEN ARRAY_AGG("registry_passport"."address" ) IS NULL THEN NULL ELSE coalesce(array_length(ARRAY_AGG("registry_passport"."address" ), 1), 0) END > 1
```

```
SELECT "registry_stamp"."hash", "registry_passport"."community_id", ARRAY_AGG("registry_passport"."address" ) AS "addresses" FROM "registry_stamp" INNER JOIN "registry_passport" ON ("registry_stamp"."passport_id" = "registry_passport"."id") WHERE "registry_passport"."community_id" = 123 GROUP BY "registry_stamp"."hash", "registry_passport"."community_id" HAVING CASE WHEN ARRAY_AGG("registry_passport"."address" ) IS NULL THEN NULL ELSE coalesce(array_length(ARRAY_AGG("registry_passport"."address" ), 1), 0) END > 1
```

**Comment by lucianHymer** [comment]
Here's a link to this page in Redash! http://35.92.62.56:5000/queries/5#5

**Comment by lucianHymer** [comment]
Deduplication events are now available in the django admin on the Events page

**Comment by nutrina** [comment]
That should be in: https://api.review.scorer.gitcoin.co/admin/login/?next=/admin/  - that is the review environment
