### ISSUE TITLE
Remove Github from Cyberconnect's scorer ID (700) 

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#1398]
Cyberconnect has seen bots accumulating a passing score through our Github stamp:

From Peiwen:
"We recently discovered that most of these bots quickly accumulate passport scores above 21 through GitHub. We would like to know when the custom scorer functionality will be available, so that we can exclude GitHub scores."

### Acceptance Criteria
GIVEN a passport is submitted for scorer ID 700
WHEN they have Github stamps
THEN those will not increase the score

Let's set ALL of the Github credentials for score Id 700 to 0

#### Product & Design Links:
<links>

**Comment by nutrina** [comment]
This is done
