### ISSUE TITLE
Read Replica Setup for Passport Scorer Database

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1399]
### User Story:
As a Passport administrator,
I want to set up a new database as a read replica of the Passport Scorer Database,
So that I can enhance the system's redundancy and facilitate analytical reporting without affecting the main operational database.

### Acceptance Criteria
GIVEN a new, dedicated database for the read replica
WHEN the system finishes the daily backup routine of the Passport Scorer Database
THEN a synchronized copy of the data should be available in the read replica database.

#### Tech Details:
- The read replica will need to be set up in a way that ensures the data synchronization happens every 24 hours.
- We need to ensure that the process of creating a read replica does not affect the performance of the Passport Scorer Database.
- For the database technology, we can use the same DBMS as the Passport Scorer DB to ensure compatibility: PostgreSQL. However, this decision will also depend on the infrastructure and cost requirements.

#### Notes/Assumptions:
We are assuming that the read replica will help us in running heavy analytical queries without affecting the performance of the main database.

**Comment by lucianHymer** [comment]
Handled here https://github.com/gitcoinco/passport-scorer/pull/293
