### ISSUE TITLE
Revamp of GitHub Stamp: Updating Verification Credentials

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1401]
### User Story:
As a Passport Holder,
I want the ability to verify updated credentials about my GitHub activity,
So that my Passport more accurately reflects my activity and longevity on GitHub.

### Acceptance Criteria
GIVEN a Passport Holder with GitHub activity
WHEN I verify my GitHub credentials on my Passport
THEN the following updated verification credentials should be considered:

- Account Creation Date: More than 90, 180, 365 days ago
- Number of days contributions made: More than 30, 60, 120 days

AND

GIVEN a Passport Unique Humanity scorer
WHEN it scores any of these credentials
THEN it assigns a weight of `1.875` to each of them.

#### Product & Design Links:

> Account Creation
> - Created at least 90 days ago
> - Created  at least 180 days ago
> - Created at least 365 days ago

> Contribution Activity
> - Contributions on at least 30 distinct days
> - Contributions on at least 60 distinct days
> - Contributions on at least 120 distinct days

Contributions = Use the same concept of contribution as within Github profile, can pull the data from Github's graphQL API

#### Tech Details:
The verification system should update its criteria for GitHub based on the new thresholds. **The old verification options should be removed from the interface; yet, we should not remove old credentials from the DB.**

#### Open Questions:
How will these changes affect the existing GitHub verification credentials?
How do we get this data out of Github?
How do we get this data with the least amount of API calls?

#### Notes/Assumptions:
We are assuming that these new verification credentials will more accurately reflect users' activity and longevity on GitHub.

**Comment by lucianHymer** [comment]
https://stackoverflow.com/questions/18262288/finding-total-contributions-of-a-user-from-github-api

**Comment by lucianHymer** [comment]
https://docs.github.com/en/graphql/reference/objects#contributioncalendarday
This one looks like a good way to pull the info

**Comment by schultztimothy** [comment]
@erichfi This is currently feature flagged and the weights for both the new github stamps as well as the old ones are currently in the scorer api. Moving this to blocked until we complete the work for rescoring all stamps based on this comment https://discord.com/channels/562828676480237578/1094982282894389298/1125566113397346405 and this ticket: https://github.com/gitcoinco/passport/issues/1400

I have a follow up PR https://github.com/gitcoinco/passport-scorer/pull/305 to remove the old weights once we remove the feature flag. All scoring should work as expected without this PR but it will be useful to clean up the scores
