### ISSUE TITLE
Update GitcoinAttester and GitcoinVerifier Smart Contracts for Pausability and Upgradability

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1408]
### User Story:
As a developer, 
I want the GitcoinAttester and GitcoinVerifier smart contracts to be pausable and upgradeable
To ensure control, security, and future enhancements.

### Acceptance Criteria
**Pausability:**
GIVEN I am an authorized entity,
WHEN there is a need to halt operations temporarily (for maintenance or security concerns),
THEN I should be able to pause the GitcoinAttester and GitcoinVerifier smart contracts.

**Upgradability:**
GIVEN I am an authorized entity,
WHEN there is a requirement to add new features, optimize the contracts or fix potential issues,
THEN I should be able to upgrade the GitcoinAttester and GitcoinVerifier smart contracts.

#### Product & Design Links:
n/a

#### Tech Details:
Implement the pausability and upgradability features using the [OpenZeppelin Upgrades](https://docs.openzeppelin.com/learn/upgrading-smart-contracts#:~:text=Smart%20contracts%20in%20Ethereum%20are,an%20unbreakable%20contract%20among%20participants) library.

#### Open Questions:
n/a

#### Notes/Assumptions:
Adding these features will offer a high level of control and adaptability over the smart contracts.

**Comment by schultztimothy** [comment]
Here is testnet GitcoinAttester contract https://goerli.basescan.org/address/0x5bbBC733E12f50e6834c40A90066F2f9FFb820e0#events that has been through upgrades and ownership changes. As well as state changes from the test multisig. Happy to pair on testing this out :)
