### ISSUE TITLE
Deploy On-Chain Passport Application to Optimism L2 Network and Configure Associated Settings

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1423]
### User Story:
As a developer,
I want to deploy the Passport on-chain application to the Optimism L2 network, ensuring that the Gnosis Safe - `0x16883ef6737bd243BB638Bd09b0C31c47F34D258` - has ownership over the deployed contracts,
So that our users can benefit from the on-chain Passport features in a scalable and cost-effective environment while ensuring the capability to direct minting fees to the designated Gnosis Safe.

### Acceptance Criteria
GIVEN the Optimism L2 network,
WHEN deploying the Passport on-chain application,
THEN all the necessary contracts are deployed with the specified Gnosis Safe as the owner, and relevant configurations are set up correctly.

The following tasks need to be performed:

- [x]  Deploy the Passport Resolver Smart Contract (SC) on Optimism and set the Gnosis Safe as the owner.
- [ ]  Create the Passport EAS schema on Optimism.
- [ ]  Ensure the Passport resolver SC is specified in the schema.
- [ ]  Deploy the Passport Verifier SC on Optimism and set the Gnosis Safe as the owner.
- [ ]  Deploy the Passport Attester SC on Optimism and set the Gnosis Safe as the owner.
- [ ]  Configure the Passport Attester.
- [ ]  Register the validators in the Passport Attester configuration.
- [ ]  Configure the Passport Resolver, record the trusted entities.
- [ ]  Register Passport EAS in the Resolver configuration.
- [ ]  Register the trusted Passport Attester in the Resolver configuration.
- [ ]  Ensure the capability exists to direct minting fees to the Gnosis Safe.
- [ ] Update the ENV variables to include the Optimism chain ID, ensuring the frontend operates seamlessly with Optimism on the review environment. If necessary, modify the `/eas/passport` endpoint to include a parameter for the chain ID and adjust related configurations.

#### Tech Details:
Schema Registry and EAS addresses for Optimism are available:

- Schema Registry: [0x4200000000000000000000000000000000000020](https://optimistic.etherscan.io/address/0x4200000000000000000000000000000000000020)
- EAS: [0x4200000000000000000000000000000000000021](https://optimistic.etherscan.io/address/0x4200000000000000000000000000000000000021)

#### Notes/Assumptions:
The Gnosis Safe - `0x16883ef6737bd243BB638Bd09b0C31c47F34D258` - should have full ownership over the deployed Passport on-chain contracts. This ensures secure and transparent management, with the capability to direct minting fees to the Safe when necessary.

**Comment by lucianHymer** [comment]
The frontend side of things should be configured to work smoothly already, the ENV vars just need to be updated to include the OP chain ID.

The IAM currently only works with a single chain. If we just want OP to work for now, we can change the ENV var to the OP chain ID. Otherwise, we'll need to modify the /eas/passport endpoint to include a parameter for the chain ID, and we'll need to move around a few things (i.e. build the domain separator dynamically with the request instead of once at the top of the file). It should be a fairly minimal lift.

**Comment by YogiAnwar** [comment]
Ok
