### ISSUE TITLE
zkSync Era Verification Issue: 403 Error when Retrieving Transaction List for Addresses in Gitcoin Passport Application

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1438]
**Overview**
A user has encountered an issue while trying to verify the zkSync Era credential in the Gitcoin Passport application, even though they seem to meet the requirements. The system seems to have difficulty retrieving transaction lists for certain wallet addresses, returning a 403 error. This problem is preventing users from claiming the ZKSync stamp and adding it to their passport.

**Steps To Reproduce**
1. Go to the Gitcoin Passport application.
2. Sign in using your account credentials.
3. Open the zkSync stamp sidebar.
4. Attempt to verify the zkSync Era credential with a valid transaction history. (In this case, wallet address: 0x002403ee4590e27b4d3f72295ce61a5e3f967f86)
5. See error

**Observed  behavior**
When the user attempts to verify the zkSync Era credential, the system fails to validate the transactions, even though the user has a valid transaction history on the zkSync network. The API response from https://passport-iam.gitcoin.co/api/v0.0.0/verify is: [{"error":"Error getting transaction list for address","code":403}]. As a result, the user cannot claim the ZKSync stamp or add it to their passport.

**Expected behavior**
When a user who meets all requirements attempts to verify the zkSync Era credential, the system should successfully validate their transaction history and grant the ZKSync stamp. This stamp should then be addable to their passport.

**Screenshots**
N/A

**Additional context**
This issue appears to occur specifically when attempting to retrieve a transaction list for certain addresses. The user in question has a wallet address of 0x002403ee4590e27b4d3f72295ce61a5e3f967f86 and their transaction history can be verified manually via zkSync explorer (https://explorer.zksync.io/tx/0x2156cdc4b3bf318c2a06dcf14bbdd8f15fcf4d14ce2c1c957d9965899ec4724f). This suggests a potential issue with the API or the permissions/settings it operates under. Further investigation is required to understand the root cause and extent of this problem.

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/62012
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/62015

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/62001

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/54539

**Comment by aminah-io** [comment]
@jesuloluwao @erichfi zkSync have removed access to the endpoint that allowed retrieval of the transactions list within the last few days. We need to update the codebase to use the JavaScript SDK.
