### ISSUE TITLE
WalletConnect Issue

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#1451]
**Overview**
Users are having trouble connecting to Passport using wallet connect (Zerion wallet) due to changes with the WalletConnect integration 

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by schultztimothy** [comment]
This PR should be all that is needed to resolve this, unless web3onboard releases another update to accommodate metamask mobile. This issue should provide progress updates

**Comment by Adamj1232** [comment]
Hi @schultztimothy!
X-posting here as well - we have pinpointed the issue. MetaMask when handling a connection through WalletConnect requires a URL to be passed. 
This previously was populated within the WalletConnect package as the `web3OnboardInit.appMetaData.explorer` property.
I have an [open PR](https://github.com/blocknative/web3-onboard/pull/1822) to add a WC init prop to define this more clearly as well as enhanced validation and documentation around this.
To resolve this issue in the short term please pass in the dapp URL into `web3OnboardInit.appMetaData.explorer` or you can wait until the noted PR is in alpha to test with the walletconnect init prop `dappUrl`

**Comment by schultztimothy** [comment]
Hi @Adamj1232 sounds good thanks for following up here!
