### ISSUE TITLE
One-Time Update of Unique Humanity Scoring Model with New Weights

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1453]
### User Story:
As a Passport administrator,
I want to manually update the unique humanity scoring model with weights from the designated Google Sheet,
So that the Gitcoin Passport can accurately and efficiently verify each participant's unique identity.

### Acceptance Criteria
GIVEN the Google Sheet with updated weights ("Gitcoin Passport - Unique Humanity Scoring Weights"),
WHEN the unique humanity scoring model evaluates a participant's data,
THEN it should utilize the manually updated weights from the Google Sheet to provide a more accurate verification score.

#### Product & Design Links:
[Google Sheet - Gitcoin Passport - Unique Humanity Scoring Weights](https://docs.google.com/spreadsheets/d/16VTsKxNISECeNAyu1tgtOQ53UpRNmL5fLcINrhw-AfU/edit?usp=sharing)

#### Tech Details:
The unique humanity scoring model should be updated manually to reflect the new weights provided in the linked Google Sheet. This update should be thoroughly tested to ensure it does not impact the performance of the identity verification process or introduce any bugs.

#### Notes/Assumptions:
1. We are assuming that the weights provided in the Google Sheet are accurate and have been developed using a comprehensive understanding of our diverse user base.
2. If any further updates to the Google Sheet are made, a new request will be necessary to incorporate those changes into the scoring model.
3. This update should also incorporate the variable names of the revamped GitHub and Twitter stamps as per issues [#1401](https://github.com/gitcoinco/passport/issues/1401) and [#1402](https://github.com/gitcoinco/passport/issues/1402) respectively.

**Comment by lucianHymer** [comment]
We should add a ticket to investigate an automated way to compare the scorer weights to the real provider IDs in the passport app. I think it'd be pretty straightforward, the scorer app already has a function for pulling in the stamp metadata from the passport app. I feel like this would be an easy thing to mess up.

FYI a few of the names were off in this one: ZkSync, ZkSyncEra, and EthGasProvider
