### ISSUE TITLE
Integration of New Credentials in Gitcoin Passport

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1454]
**Description:**
This chore involves ensuring the full integration of various new credentials into the Gitcoin Passport. These credentials have been implemented as feature flags. The chore also requires managing any credential removals/replacements as needed.

- [ ] Integrate the following credential checks:
- githubContributionActivityGte#30
- githubContributionActivityGte#60
- githubContributionActivityGte#120
- githubAccountCreationGte#90
- githubAccountCreationGte#180
- githubAccountCreationGte#365
- twitterAccountCreationGte#180
- twitterAccountCreationGte#365
- twitterAccountCreationGte#730
- twitterConsistentEngagementGte#30
- twitterConsistentEngagementGte#60
- twitterConsistentEngagementGte#120
- Hypercerts
- phiSilver
- phiGold
- Holonym
- idenaNewbie
- idenaVerified
- idenaHuman
- idena1kiDNA
- idena10kiDNA
- idena100kiDNA
- idena5epochs
- idena10epochs
- FiftyOrMoreGithubFollowers
- FirstEthTxnProvider
- FiveOrMoreGithubRepos
- ForkedGithubRepoProvider
- GitcoinContributorStatistics#numGrantsContributeToGte#100
- Github
- gtcPossessionsGte#10
- gtcPossessionsGte#100
- StarredGithubRepoProvider
- TenOrMoreGithubFollowers
- Twitter
- TwitterFollowerGT100
- TwitterFollowerGT500
- TwitterFollowerGT5000
- TwitterFollowerGTE1000
- TwitterTweetGT10
- CivicCaptchaPass
- CivicLivenessPass
- CivicUniquenessPass
- [ ] Handle credential removals/replacements as required.
- [ ] Document any changes, challenges, or findings during the process.

**Comment by schultztimothy** [comment]
@erichfi @Jeremy-Gitcoin Should this ticket be responsible for setting the necessary feature flags? Or removing the older versions of twitter and github? It looks like both versions of Github and Twitter are listed.

Is there also a link to the most recent scoring spreadsheet?

Thanks!
