### ISSUE TITLE
[BUG] Can't connect to passport with Wallet connect

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#1459]
The user is unable to connect to Passport with walletconnect. I tried too and I couldn't. Here's the console error I'm getting.

When I scan the code, nothing happens

<img width="1189" alt="image" src="https://github.com/gitcoinco/passport/assets/88308638/c05aa639-9775-46ca-bc61-74b252dd13b9">

**Link:** [Conversation with dfzxfy@126.com](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/37040)

**Customer:** [dfzxfy@126.com](https://app.intercom.com/a/apps/xaafeyri/users/6444a89c1b03bec06670ef0d/all-conversations)
**Customer ID:** 6a74d928-23a9-4aa9-bec1-63abdf40df88
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/37040) when this issue is closed.

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/team/6471950/conversation/62216

**Comment by hardiktheprogrammer** [comment]
@jesuloluwao  I would like to work on this I have good understanding of passport code base 
can  you please assign me

**Comment by Jeremy-Gitcoin** [comment]
@jesuloluwao we'll close this out as the wallet connect issues should no longer exist, except for instances with Safe wallets which is a known issue that wallet connect is working to resolve.

@hardiktheprogrammer Sorry just saw that you offered to help on this one, happy to have you involved with Passport if there's anything you'd like to pitch-in on?!
