### ISSUE TITLE
Metrics: Human & Sybil list w/ Passport Data

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#1465]
### User Story:
As a PM at Gitcoin Passport
I want to pull all of the passports data for Sybils & humans
So that I can create a take-home problem for our data science candidates 

### Acceptance Criteria
GIVEN all human and sybil addresses on the lists
WHEN the address has passport data
THEN create an array of the address with the credentials they have

We need eth/wallet address and then stamp credentials that passport contains into 2 files labelled:
- Humans
- Sybils

For both files we can either include or remove all address that would have 'none' for the stamp credentials, either way is fine whatever is easier

#### Product & Design Links:
We have 2 human lists
- Karma50 - contains 230 records
- Human verification tracking - contains 595 records

And one Sybil list - Cleaned Sybil List 14,878 (you can just grab the first 1k records that have Passport data if that's easier?)

[Cleaned Sybil List with QA Outcomes 6_20 - sybil_list1.csv](https://github.com/gitcoinco/passport/files/12009764/Cleaned.Sybil.List.with.QA.Outcomes.6_20.-.sybil_list1.csv)
_Human Verification Tracking - Sheet1.csv_ - deleted and replaced
[Karma50 - Karma50.csv](https://github.com/gitcoinco/passport/files/12009763/Karma50.-.Karma50.csv)

**Comment by Jeremy-Gitcoin** [comment]
Replace the Human list with new v2 humans

[Human Verification Tracking - Human Listv2.csv](https://github.com/gitcoinco/passport/files/12021593/Human.Verification.Tracking.-.Human.Listv2.csv)

**Comment by schultztimothy** [comment]
Here is the output for [Cleaned Sybil List with QA Outcomes 6_20 - sybil_list1.csv](https://github.com/gitcoinco/passport/files/12009764/Cleaned.Sybil.List.with.QA.Outcomes.6_20.-.sybil_list1.csv)
- First 1000 addresses from the list: https://tmp-public-tfm4i.s3.us-west-2.amazonaws.com/first_1000_cleaned_sybil_addresses_owned_stamps.csv
- First 7000 addresses from the list: https://tmp-public-tfm4i.s3.us-west-2.amazonaws.com/first_7000_cleaned_sybil_addresses_owned_stamps.csv

[Human Verification Tracking - Human Listv2.csv](https://github.com/gitcoinco/passport/files/12021593/Human.Verification.Tracking.-.Human.Listv2.csv) - CSV results [address, passport, confidence_score] - https://tmp-public-tfm4i.s3.us-west-2.amazonaws.com/human_list_w_confidence_score_and_passport.csv

[Karma50 - Karma50.csv](https://github.com/gitcoinco/passport/files/12009763/Karma50.-.Karma50.csv) - CSV Results [address, passport] - https://tmp-public-tfm4i.s3.us-west-2.amazonaws.com/karma_list_w_address_and_passport.csv

**Comment by schultztimothy** [comment]
Here are the updated lists

Sybil: https://tmp-public-tfm4i.s3.us-west-2.amazonaws.com/cleaned_sybil_list_data_science_test.csv
Humans: https://tmp-public-tfm4i.s3.us-west-2.amazonaws.com/aggregated_human_list_deduplicated_data_science_test.csv
