### ISSUE TITLE
Historical Score Storage and Retrieval

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1477]
### User Story:
As a developer using the Gitcoin Scorer API,
I want the system to automatically store every passport score associated with my scorer ID and the timestamp,
So that I can retrieve any previous score of a passport and understand the evolution of the scores over time.

### Acceptance Criteria
GIVEN a passport has been scored using my scorer ID,
WHEN this scoring process takes place,
THEN the system should automatically associate the score with my scorer ID and the current timestamp, and store it, while preserving previous scores.

GIVEN a request to fetch a score associated with my scorer ID and a specific timestamp,
WHEN the system processes this request,
THEN it should return the score of the passport that was recorded most recently before the given timestamp.

#### Tech Details:
- The backend database schema needs to be updated to allow for the storage of multiple scores per scorer ID, each with its associated timestamp.
- The Scorer API should be extended to include an endpoint for fetching a score by scorer ID and timestamp.
- Optimizations may be needed to ensure efficient storage and retrieval of scores, given the potential increase in data volume.
- Potentially, we might be able to borrow some of the technical logic applied in https://github.com/gitcoinco/passport/issues/1390 to log deduplication events.

#### Notes/Assumptions:

- This feature is expected to enhance the functionality of the Scorer API by allowing developers to access a more comprehensive history of scoring data.
- The system is capable of handling the additional load resulting from these changes.

**Comment by digitalmnt** [comment]
Here is a WIP PR that saves the values to the events table. https://github.com/gitcoinco/passport-scorer/pull/391

**Comment by lucianHymer** [comment]
We ran a timed query to see the effect that changing the Event table indices may have

```
>>> import datetime
>>> now = datetime.datetime.utcnow()
>>> import time
>>> def timeQuery(query):
...     start = time.monotonic()
...     result = query[0]
...     end = time.monotonic()
...     return {"result": result, "time": end - start}
... 

>>> timeQuery(Event.objects.filter(action="LDP", address="0x39c879a8365d018cfb18530e95a4fc297cc6debf", created_at__lt=now))

{'result': <Event: Event object (1)>, 'time': 0.008447812055237591}
```

**Comment by lucianHymer** [comment]
I ran some tests locally to determine the best indexing, it was cool! I ended up moving created_at to the end. There's a pretty major variance with some of the queries depending on the index order! Looking forward to doing some tests with other tables.

I added an analyze_queries command that can be modified to do similar tests.

Results [here](https://drive.google.com/file/d/1WgKK8cZ63ccBq59VurIno3oyE0XzRZil/view?usp=drive_link), the indexes are listed at the top of each file.

**Comment by lucianHymer** [comment]
The `timestamp` query param has been added to `registry/score/{scorer_id}/{address}`, but we probably want similar functionality in `registry/score/{scorer_id}`, right? That would basically let integrators get an easy snapshot of their scores.

But how exactly do we want to do that? The scorer_id endpoint currently has the last_timestamp__gt and last_timestamp__gte fields. Do we add last_timestamp__lt and last_timestamp__lte and use the Events table for those queries? And if so, should we rename the `timestamp` field on the other endpoint to match?

**Comment by nutrina** [comment]
@lucianHymer please make sure you make the API adjustments for V2, I don't think we want to support V1 any more.

**Comment by nutrina** [comment]
@lucianHymer I think it would makes sense to have a completely different endpoint for historical scores. There is no need to complicate the existing API request handlers.

For historical data I would suggest to always create different endpoints, because using the same request handler to serve both current & historical data increases the complexity, and will make further maintenance more difficult. Also for historical data we might want to use different filter arguments in some cases (there might also exist different requirements for that).

I would suggest:
- create this endpoint for historical scores: `https://api.scorer.gitcoin.co/registry/v2/score/{scorer_id}/history`
- that should get the following query parameters:
    - `timestamp` - **required** 
    - `address` - optional

This would allow reading all scores at `timestamp` or only 1 score (if `address` is specified)
