### ISSUE TITLE
On-Chain Sidebar

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1479]
### User Story:
As a passport holder,
I want to see information about moving my passport on-chain when I click the "Go On-Chain" icon,
So that I understand what the process involves and when it's necessary.

### Acceptance Criteria
GIVEN that the "Go On-Chain" icon is clicked,
WHEN the sidebar opens,
THEN it should contain information about the process and when it's necessary to move my passport on-chain.

#### Product & Design Links:
https://www.figma.com/file/AhR5wUbfYPFc593QeJ6wTp/On-Chain-July-15?type=design&node-id=0-1&mode=design&t=IhAog5RubN9Zje7y-0

#### Tech Details:

- Implementation of a sidebar that appears when "Go On-Chain" icon is clicked.
- Sidebar should include the necessary information about moving passport on-chain, including the circumstances under which it's required and the associated fees.

**Comment by orbmis** [comment]
PNGs of logo for Linea:

![Linea_Logo-Black (RGB)](https://github.com/gitcoinco/passport/assets/2395301/7146d897-5780-4766-9403-620e7c19d1e9)
![Linea_Logo-White (RGB)](https://github.com/gitcoinco/passport/assets/2395301/90a98e17-9d05-4e7b-bd83-5a04fd1d51e1)

**Comment by schultztimothy** [comment]
@erichfi  Is this the right logo for linea? https://github.com/gitcoinco/passport/issues/1479#issuecomment-1658139353

A square 1:1 would work better with our designs if possible
