### ISSUE TITLE
Go On-Chain Button

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1480]
### User Story:
As a passport holder,
I want to see an icon on my dashboard that represents the "Go On-Chain" functionality,
So that I understand I have the option to check or move my passport on-chain.

### Acceptance Criteria
GIVEN that I'm logged into the Passport dashboard,
WHEN I view my profile,
THEN I should see a blockchain-themed icon that represents the "Go On-Chain" functionality and it should always be enabled.

#### Product & Design Links:
https://www.figma.com/file/AhR5wUbfYPFc593QeJ6wTp/On-Chain-July-15?type=design&node-id=0%3A1&mode=design&t=IhAog5RubN9Zje7y-1

#### Tech Details:

- Implementation of the "Go On-Chain" icon on the main dashboard.
- Make sure the icon is always enabled to open the sidebar.

#### Notes/Assumptions:
- Tooltip wording change to "On-Chain Passport".

**Comment by lucianHymer** [comment]
FYI I plan to update the actual calls to put the passport/score on-chain as part of this ticket: https://github.com/gitcoinco/passport/issues/1085

So it seems like the ticket here is really just the icon change and small logic update so this is always displayed
