### ISSUE TITLE
Wallet Transaction Popup

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1482]
### User Story:
As a passport holder,
I want to confirm the blockchain transaction with details,
So that I can understand the charges and the action I am taking.

### Acceptance Criteria
GIVEN that I have selected a blockchain network and the "Go On-Chain with [Blockchain Name]" button is enabled,
WHEN I proceed with the process,
THEN a wallet popup should appear with transaction details for me to confirm.

#### Product & Design Links:
https://www.figma.com/file/AhR5wUbfYPFc593QeJ6wTp/On-Chain-July-15?type=design&node-id=0-1&mode=design&t=IhAog5RubN9Zje7y-0

#### Tech Details:
Implement a wallet popup (like Metamask) that shows transaction details including network fees and the $2 Gitcoin service charge.

#### Notes/Assumptions:
Assumption is that all necessary data for the transaction is already known and can be displayed to the user.

**Comment by Jeremy-Gitcoin** [comment]
@erichfi we can't change the message when executing a wallet transaction. we cannot put anything custom here. we're going to pull this out of the prioritized backlog
