### ISSUE TITLE
[BUG] Issue authenticating twitter

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#1486]
I am unable to authenticate twitter anymore. 

Here's a loom and you should be able to reproduce this too. https://www.loom.com/share/92b1f96fdb264ca28a313f031d114bdf?sid=17098b87-b951-4c6a-98b9-2c6a41d4b79f

<div class="intercom-container"><img src="https://downloads.intercomcdn.com/i/o/785442180/5ca9567fe2887e1048ccac88/image.png"></div>

**Link:** [Conversation with amirihosen246@gmail.com](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/62380)

**Customer:** [amirihosen246@gmail.com](https://app.intercom.com/a/apps/xaafeyri/users/64b17a1903a25fdd27fcfe21/all-conversations)
**Customer ID:** da572326-08b6-4a3d-891a-b0bc128bffcf
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/62380) when this issue is closed.

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/team/6464831/conversation/62386
https://app.intercom.com/a/inbox/xaafeyri/inbox/team/6464831/conversation/62391
https://app.intercom.com/a/inbox/xaafeyri/inbox/team/6464831/conversation/62393
https://app.intercom.com/a/inbox/xaafeyri/inbox/team/6464831/conversation/62415
https://app.intercom.com/a/inbox/xaafeyri/inbox/team/6464831/conversation/62413

**Comment by aminah-io** [comment]
Fixed by updating the callback url in Fleek
