### ISSUE TITLE
Update Gitcoin stamp for Alpha & Beta rounds

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#1489]
### User Story:
As a pervious Gitcoin Grants donator or grantee 
I want to capture the Gitcoin Stamp credentials
So that I can prove my humanity

### Acceptance Criteria
GIVEN I have contributed to a Gitcoin grant
WHEN I verify the Gitcoin stamp and save the credential(s)
THEN I capture the credentials I qualify for within the stamp

Update the stamp to count all Gitcoin grant activity including:
- Gitcoin Grants round 1-15 (current functionality)
- Allo Beta rounds
- Citizen rounds 

This should be all activity prior to July 15th! 

#### Product & Design Links:
<links>

#### Tech Details:
- Get data
- Load in DB
- Create API to query from IAM server
- Refactor the existing Gitcoin Grants stamp to take this contribution into account

#### Open Questions:

- [ ] Can Allo give us an export of Alpha, Beta, Citizens contributions?

**Comment by Jeremy-Gitcoin** [comment]
Grants stack indexer - https://github.com/gitcoinco/allo-indexer

**Comment by nutrina** [comment]
The data seems to be here: https://indexer-grants-stack.gitcoin.co/data/

This will be fun ...
As far as I can tell, contributions are stored in files like:
https://indexer-grants-stack.gitcoin.co/data/1/contributors/0x0000/00797b/D48D0e/15f0Ea/C88D21/52A9F5/f06957.json

This path was build like: https://indexer-grants-stack.gitcoin.co/data/<chain id>/contributors/<ETH address of contributor with '/' after each 4 chars>.json

**Comment by nutrina** [comment]
https://github.com/gitcoinco/passport-scorer/pull/322 - has been merged in, as this work is needed also for the follow-up tickets.

https://github.com/gitcoinco/passport/pull/1496 - this is not required

**Comment by nutrina** [comment]
All relevant changes have been merged, hence this can be closed.
