### ISSUE TITLE
Passport Banner

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#1490]
### User Story:
As a product manager or support for Gitcoin Passport
I want to be able to update a banner on the Gitcoin passport site
So that I can let useres know about current known issues (broken stamps, delays, etc) or recent changes (new releases, score changes) and link to outside content (tweets or blog post announcements)

As a Passport holder / user 
I want to be able to receive notifications on important content
So that I do not have to go to support or product team with questions 

### Acceptance Criteria
GIVEN an admin user goes to the content management page
WHEN they turn the banner on and provide content
THEN it will appear on the Passport site for all users

GIVEN a user goes to passport.gitcoin.co
WHEN the banner is activated
THEN the user will see the content at the top of the page

Admins:
- can toggle the banner off / on
- can update the content to show up in the banner for all new rendered pages
- can create links to be shown that enable users to click off
- when clicking the links, open a new page in a new tab

Users:
- can close the banner
- can acknowledge the banner so it doesn't appear again
- scroll to continue to see the stamps

#### Product & Design Links:
Utilize the existing expired stamps banner (change color?)
Stretch it below 'my stamps' & score header for up to 3 lines
close botton
Small 'do not show again' 

#### Tech Details:
Create the admin to toggle on/off banner and update the content within the Django admin: https://api.scorer.gitcoin.co/admin/

Steps:

- [ ] define model
- [ ] create admin UI
- [ ] group for access within the UI
- [ ] expose info via API
- [ ] Pull this info from API to the UI
- [ ] Display in the UI

#### Open Questions:

- [x] Where do we have the admin and content management?
- [ ] Do we have a limit on the amount of content that can appear on the page? (3 lines?)

**Comment by schultztimothy** [comment]
@erichfi @Jeremy-Gitcoin How does this design look?

![Image](https://github.com/gitcoinco/passport/assets/6887938/2d518fc7-cadf-4597-9d87-5b032c1af3ce)

**Comment by Jeremy-Gitcoin** [comment]
@schultztimothy Looks good! How many lines can this new banner go?

**Comment by schultztimothy** [comment]
Perfect! Here is what it looks like for multipl banners as well as with a bunch of text



![Image](https://github.com/gitcoinco/passport/assets/6887938/f6a6a780-4d14-4bda-a35e-f044fbb355f1)
