### ISSUE TITLE
Regular data dumps of new stamps

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1492]
We want to create a dump of new stamps on a weekly schedule:

- [ ] the dump should contain all the new stamps that have been created since the last dumps timestamp
- [ ] should be in jsonl format
- [ ] the filename

The purpose of this is to have a dataset (the source of truth) that we can use to compare against the data stored in ceramic

**Comment by Jeremy-Gitcoin** [comment]
Django script and export to S3

**Comment by Jeremy-Gitcoin** [comment]
This will be the first task as a requirement for
