### ISSUE TITLE
Index Alpha round grant data for Allo stamp

### ISSUE THREAD

**Issue by Jkd-eth** [gitcoinco/passport#1499]
### User Story:
As a pervious Gitcoin Grants donator or grantee
I want to capture the Gitcoin Stamp credentials
So that I can prove my humanity

### Acceptance Criteria
GIVEN I have contributed to a Gitcoin grant
WHEN I verify the Gitcoin stamp and save the credential(s)
THEN I capture the credentials I qualify for within the stamp

Index all of the Alpha data so that it's available for the creation of #1507 

### Tech Details:
- [x] Get data
- [x] Load in DB
- [x] Create API to query from IAM server
- [x] Refactor the existing Gitcoin Grants stamp to take this contribution into account

Open Questions:

**Comment by Jeremy-Gitcoin** [comment]
Continue the work from #1489 as getting access to Alpha data has turned out to be difficult and needs additional time

**Comment by Jeremy-Gitcoin** [comment]
Open question on Approach:
1) modify indexer - do we have the events data needed to pull this in?
2) Pull directly from smart contract interaction

Does either include the contributions before Sybil silencing or after silencing?

**Comment by nutrina** [comment]
As per suggestion from @gravityblast ( see https://discord.com/channels/562828676480237578/1131907711324405820/1133532379256991784 )I have pulled the transactions from etherscan and decoded the data.
The work is in this repo: https://github.com/gitcoinco/alpha_round_data_retriever

The code in the above repo:
- pulls the transactions
- extract the votes, and donation amounts

Open the open points include:
- [ ] convert the donations into dollar values (at rate of the transaction time)
- [ ] import data into scorer db

**Comment by aminah-io** [comment]
Sure thing. We're waiting to hear back from anyone that may have squelching data for the alpha and beta rounds so that we can filter out the successful donations.

**Comment by schultztimothy** [comment]
It looks like this endpoint was already created. The endpoint has been created and all data is imported.
