### ISSUE TITLE
Introduction of Gitcoin Grants Stack Stamp

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1507]
### User Story:
As a Passport Holder,
I want to verify credentials about my contributions to Gitcoin Grants Stack rounds,
So that my Passport more accurately reflects my engagement in the Gitcoin ecosystem, independently from the Gitcoin Grants stamp.

### Acceptance Criteria
GIVEN a Passport Holder who has contributed to Gitcoin Grants Stack rounds,
WHEN I verify my contribution credentials on my Passport,
THEN the following verification credentials should be considered:
1. Number of Projects Contributed To: Contributed to at least 3, 5, or 7+ unique projects within the rounds.
2. Number of Matching Fund Programs Participated In: Participated in at least 2, 4, or 6+ unique matching fund programs as a contributor (not a grantee).

AND

GIVEN a Passport Unique Humanity scorer,
WHEN it scores any of these credentials,
THEN it assigns a weight of 1.07 to all credentials.

#### Product & Design Links:
_Gitcoin Grants Stack logo for stamp:_ https://drive.google.com/file/d/14Fd6iv98w5Fkixh6U48XAacCCeBvIP4G/view?usp=sharing

_Credential Wording:_

> Projects Contributed To:
> - Supported 3+ unique projects
> - Supported 5+ unique projects
> - Supported 7+ unique projects
> 
> Matching Fund Programs Participation:
> - Contributed to 2+ unique programs.
> - Contributed to 4+ unique programs.
> - Contributed to 6+ unique programs.

_Banner:_

> Note: Only Alpha and Beta rounds run by Gitcoin are included. For the Alpha program, only donations larger than $1 are counted. For the Beta program, only matching-eligible contributions are counted.

#### Tech Details:
The verification system should incorporate new credentials for Allo Protocol contributions based on the updated thresholds. Data for these credentials will be sourced from the Grants Stack API.

From Connor's lists in the [Google Drive link](https://drive.google.com/drive/folders/16_RyXAc7iMMueJtbtHRyOpBu5ZZcCB1J):
- Contributions with a coefficient of "1" indicate a passing passport score and are considered matching-eligible for the Beta Round.
- Contributions with a coefficient of "0" were not matching-eligible as they didn't meet the unique humanity requirements for the Beta Round.

For the Alpha round, any contribution can be counted.

**Attention:** As part of this, kill the Gitcoin Grants stamp grantee credentials. This is due to the low number of users that would qualify for these credentials, and to streamline the score update process.

#### Notes/Assumptions:
We are assuming that these new verification credentials will more accurately reflect users' engagement in the Gitcoin ecosystem. These credentials will exist independently from the Gitcoin Grants stamp. These credentials are about the participation of the user as a contributor, not as a grantee.

**Comment by nutrina** [comment]
For clarification:
- a program is for example `0x12bb5bbbfe596dbc489d209299b8302c3300fa40`: https://explorer.gitcoin.co/#/round/1/0x12bb5bbbfe596dbc489d209299b8302c3300fa40.  (aka round)
- a project is this: https://explorer.gitcoin.co/#/round/1/0x12bb5bbbfe596dbc489d209299b8302c3300fa40/0x12bb5bbbfe596dbc489d209299b8302c3300fa40-49

Is this correct?

**Comment by nutrina** [comment]
@erichfi  we will need the SVG version of the logo: https://drive.google.com/file/d/1ctn_SxGpogidTY9eKmnT8fdQdOWv1vpt/view


Thanks

**Comment by nutrina** [comment]
Putting this to blocked, as we do not have the squelching / matching data yet.
