### ISSUE TITLE
Make Resolver smart contract more generic

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1520]
- [x] **1. Make resolver more generic**
Currently the Resolver smart contract stores:
- passport attestations
- score attestations

```sol
    mapping(address => bytes32) public passports;
    mapping(address => bytes32) public scores;
    mapping(address => mapping(bytes32 => bytes32)) public attestations;
```

The goal is to make this more generic, such that the Resolver smart contract is able to store other attestation created by our attester with the same characteristics (meaning only the last one is relevant), without changes.
This would require to store the attestation in a map like: address => schema ID => attestation ID
```sol
    mapping(address => mapping(bytes32 => bytes32)) public attestations;
```

- [x] **2. Drop the events**
Regarding the events:
```sol
    // Emitted when a passport is added to the passports mapping
    event PassportAdded(address recipient, bytes32 recipientUid);
    // Emitted when a passport is removed from the passports mapping
    event PassportRemoved(address recipient, bytes32 recipientUid);

    // Emitted when a score is added to the scores mapping
    event ScoreAdded(address recipient, bytes32 recipientUid);
    // Emitted when a score is removed from the scores mapping
    event ScoreRemoved(address recipient, bytes32 recipientUid);

```

I don't think it is really required to have these, and would propose to drop them.
EAS already emits events when attestations are issued. One could simply use those for indexing the blockchain data if required (or use the EAS indexer directly probably).
See: https://github.com/ethereum-attestation-service/eas-contracts/blob/master/contracts/IEAS.sol#L83-L96

The same goes for:
```sol
    event UpdatedPassportSchema(bytes32 passportSchema);
    event UpdatedScoreSchema(bytes32 scoreSchema);
```

These can be dropped as we will not store the 2 schemas any more after doing point 1.

**Comment by lucianHymer** [comment]
As part of this ticket, we need to update the Passport frontend in app/utils/onChainStamps to call the right function and pass in the schema addresses
