### ISSUE TITLE
Improve Sort results/registry/score/{scorer_id} endpoint: Ascending Sort by Timestamps & Identify Latest Timestamp

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1524]
### User Story:
As a developer using the Gitcoin Passport API,
I want the Sort results/registry/score/{scorer_id} endpoint to return a list sorted in ascending order by timestamps,
So that I can easily identify the latest timestamp for use as a filter criterion in subsequent API calls.

### Acceptance Criteria
GIVEN a call to the Sort results/registry/score/{scorer_id} endpoint,
WHEN the API response is received,
THEN the list of scores should be sorted in ascending order by timestamps,
AND the latest timestamp should be easily identifiable.

#### Tech Details:
Current behavior: The list returned by Sort results/registry/score/{scorer_id} is not sorted in ascending order by timestamps, and the latest timestamp is not easily identifiable.

Expected behavior: The list returned by Sort results/registry/score/{scorer_id} should be sorted in ascending order by timestamps, and the latest timestamp should be easily identifiable.

#### Open Questions:

1. Are there any other factors influencing the sorting mechanism?
2. What is the expected behavior in cases where multiple entries share the same timestamp?

#### Notes/Assumptions:
- The sorting feature is being implemented to assist partners in retrieving scores updated since their last API call.
- The latest timestamp will be used as the filter criterion in subsequent API calls.

**Comment by bard** [comment]
`items.at(-1)['timestamp']` is certainly nicer than `sort(items.map(i => i.timestamp)).at(-1)`, but something like this might be clearer:

```js
{
  items: [ /* ... */],
  count: /* ... */,
  lastTimestamp: /* ... */
}
```

i.e. just like for `count`, pagination- and update- related metadata is explicit and doesn't need to be derived from the actual data.
