### ISSUE TITLE
Removal of FIFO Deduplication Method from Passport API and Frontend

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1532]
### User Story:
As a Product Manager of Passport,
I want to remove the FIFO deduplication method from the Passport API,
So that I can simplify the deduplication process and reduce potential confusion for developers and users.

### Acceptance Criteria
GIVEN a developer is initializing a Gitcoin Scorer instance,
WHEN they are selecting the deduplication method,
THEN only the LIFO deduplication method should be available as an option.

GIVEN a developer is using the Passport API,
WHEN they are submitting a stamp that has already been submitted by another Passport holder,
THEN the API should only use the LIFO deduplication method to handle the duplicate stamp.

GIVEN a developer is using a FIFO scorer API, 
WHEN they score a Passport
THEN the system should score it based on the LIFO method. 

#### Product & Design Links:
[Passport API Documentation](https://docs.passport.gitcoin.co/building-with-passport/scorer-api)

#### Tech Details:

- The backend needs to be updated to remove the FIFO deduplication method from the Passport API.
- The frontend needs to be updated to remove the FIFO option from the deduplication method selection when initializing a Gitcoin Scorer instance.

#### Open Questions:

Are there any existing users or applications that are heavily reliant on the FIFO deduplication method? If so, how will they be affected by this change?

#### Notes/Assumptions:

- We are assuming that the LIFO deduplication method is sufficient for handling duplicate stamps in all use cases.
- We are assuming that removing the FIFO deduplication method will not negatively impact the functionality or performance of the Passport API.

**Comment by nutrina** [comment]
Waiting to pair & review
