### ISSUE TITLE
Add Identity Provider Links to Passport Stamp Sidebar

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1533]
### User Story:
As a Gitcoin Passport user,
I want to have direct links to each identity provider's website on the sidebar of each stamp,
So that I can easily navigate to the respective platforms for more information or to manage my credentials.

### Acceptance Criteria
GIVEN I am a Gitcoin Passport user,
WHEN I am viewing a stamp and its sidebar,
THEN I should see a clickable link that directs me to the respective identity provider's website.

#### Product & Design Links:
Sheet with links and terminology here: https://docs.google.com/spreadsheets/d/1u-lgkI25rvaXul7JSXxl50f52q4SeDfMqNmy1hURaKU/edit?usp=sharing

#### Tech Details:
This feature would require updating the UI on the sidebar of each stamp to include a clickable link to the respective identity provider's website. The link should be placed in a location that is easily visible and accessible to users.

#### Notes/Assumptions:
We assume that adding these links will improve user experience by providing easy access to information and management options for their credentials. This feature request is based on feedback received from support.

**Comment by QuickMythril** [comment]
https://github.com/gitcoinco/passport/pull/1571
i created this pull request before seeing this issue.

**Comment by digitalmnt** [comment]
Thanks @QuickMythril ! I rebased your commit into https://github.com/gitcoinco/passport/pull/1890

@erichfi This are a few providers missing links, just lmk if I should add those in. THanks!

**Comment by digitalmnt** [comment]
Moving to blocked. Just waiting on a review on the PR and clarification for missing links
