### ISSUE TITLE
[BUG] Users unable to claim grants stamp

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#1534]
He had the contributions, but it does not verify in Passport. I have tried to resync his profile, still not working. Please have a look.Thanks

Affected users:
0x63C2c6BC822CaC9DE857193ED42Edf3AD0Ba5243, id: thatguy247
0x1426FBd146942e153653863cbe633780c17268DA, id: l-kh
0xF3f78c87E63C73D9F2fF96D6d45678730c29cb84, id: bossmanfm
0x1dE8355dA82CFB8D2453A5EC3FC4C871281ab4Bc, id: mr-biii

**Link:** [Conversation with some0ne24.ae@gmail.com](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/63042)

**Customer:** [some0ne24.ae@gmail.com](https://app.intercom.com/a/apps/xaafeyri/users/64c4d2cf0a7dda1cbcedef36/all-conversations)
**Customer ID:** 0c6fbdc4-6aa5-4a08-8ccc-ba9088ec52bf
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/63042) when this issue is closed.

https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/63233?view=List

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/63246?view=List

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/63386?view=List

**Comment by nutrina** [comment]
Need to implement fix for users that have changed their handle, as suggested here: https://discord.com/channels/562828676480237578/1136227088890859530/1136342756218900700

**Comment by nutrina** [comment]
What I would propose is to add an additional field to a users profile, which is the github_id.
This field should never change, and we should be able to use that instead of the handle to make the verification (we will need to switch from handle to id in the API that is called from IAM).

After we add this field, we will backfill it from the data we have on record.
