### ISSUE TITLE
Implementing New Stamp Format Support in the Passport App

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1542]
### User Story:
As a developer of the Passport App,
I want to add support for the new stamp format,
So that the app can interact with the updated IAM and scorer endpoints and write stamps to Compose.

### Acceptance Criteria
GIVEN I am a user of the Passport App,
WHEN I open the passport application,
THEN the passport application will load the stamps from the scorer API (ceramic cache) in the new format,
AND the passport application will correctly indicate which stamps I have written on-chain.

GIVEN I am a user of the Passport App,
WHEN I claim or refresh a stamp,
THEN the passport application will create the stamp in the new format using the new IAM endpoint,
AND it will store the stamp in the scorer DB (ceramic cache),
AND it will also write the stamp to Compose.

GIVEN I am a user of the Passport App,
WHEN I have new stamps (new format) that are not on-chain,
THEN I can bring my passports on-chain,
AND the on chain label will be properly displayed after that operation for all my stamps.

#### Product & Design Links:
This depends on [Implement ComposeDatabase for Reading & Writing from Compose](https://github.com/gitcoinco/passport/issues/1545)

#### Tech Details:

- The app should use the new IAM endpoints.
- The app should use the new scorer endpoints.
- The app should write stamps to Compose.

#### Notes/Assumptions:

- The new schema format is specified in issue #1540.
- The ComposeDatabase class should be a drop-in replacement for the current CeramicDatabase.

**Comment by digitalmnt** [comment]
These changes became pretty tightly coupled with #1545 checkout 1545-compose-db-ts before spending any time on this
