### ISSUE TITLE
Create and Rollout a Reference Implementation for IAM Error Management using the Twitter Stamp

### ISSUE THREAD

**Issue by lucianHymer** [gitcoinco/passport#1552]
### User Story:
As a developer and user of the IAM,
I want to create and rollout a reference implementation for IAM error management using the Twitter stamp,
So that we can have a standardized approach to streamline error handling and improve the user experience.

### Acceptance Criteria
**Review of Current Error Handling in the Twitter Stamp:**
GIVEN the current IAM system and the Twitter stamp,
WHEN examining the usage of ProviderError,
THEN any misuse should be identified and corrected.

**Standardized Error Handling in .verify() for the Twitter Stamp:**
GIVEN the .verify() function in the Twitter stamp,
WHEN handling errors,
THEN either a single error or an array of errors should be handled, with the variable renamed accordingly.

**Endpoint Error Management for the Twitter Stamp:**
GIVEN the /check and /verify endpoints for the Twitter stamp,
WHEN an error occurs,
THEN custom error types should be caught, their messages returned, and also logged for review.

#### Tech Details:

- Focus on creating a prototype or reference implementation for error management using the Twitter stamp.
- Identify areas where logs can be minimized and error messages can be enhanced.
- Implement the changes from the reference model to the main system.
- Monitor the system for any unexpected behaviors or errors.

#### Open Questions:
What metrics will we use to measure the success of the rollout?

#### Notes/Assumptions:
- The Twitter stamp serves as the ideal reference for this phase.
- The success and insights from this phase are critical for the next phase's provider improvements.

**Comment by nutrina** [comment]
Consider addressing this together with: https://github.com/gitcoinco/passport/issues/1536

**Comment by nutrina** [comment]
I like this.
I think long-term this will make our provider more robust, easier to troubleshoot and will also reduce the number of support requests.
We should however be aware that when we roll this out, it might result in an increased number of "bugs" to be reported (given that we tread unhandled errors as bugs), and will need to address these until the implementations become robust enough.

**Comment by lucianHymer** [comment]
Testing notes:
With any "Verify" request, you should now see a "Show details" link in the success/error toast. This will show the raw data coming back from our Verify endpoint.

For twitter, if you fail to get the stamp, the details should include the reason (either a real API error, or "your account isn't old enough"). All providers will have these details soon.

We swapped out the Twitter SDK to a newer version.

We made it so that during verification, platforms are always processed in parallel while providers within a platform are processed in series. This makes caching more reliable. This shouldn't change anything from the user perspective (besides potentially speeding things up), but make sure both successful, unsuccessful, and 1-click verification works as expected.

Thanks! I hope you dig these changes as much as I do.
