### ISSUE TITLE
Granting Read-Only Access to Read Replica for Data Analysis

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1553]
### User Story:
As a data analyst, Joel needs access to our read replica to facilitate data analysis and reporting. Specifically, he needs to generate a CSV file that contains all the Beta round donor Ethereum addresses and the detailed credentials currently held in their passports.

### Acceptance Criteria
GIVEN Joel's email ([joel@gitcoin.co](mailto:joel@gitcoin.co))
WHEN a specific user account with read-only permissions is created
THEN Joel should be able to access the necessary data from our read replica
AND the integrity and security of our database should be maintained.

#### Product & Design Links:
<links>

#### Tech Details:
This task involves creating a specific user account with read-only permissions for Joel. The account should be configured to access our read replica. Ensure the extraction process does not impact the performance of the live database.

#### Open Questions:
Are there any specific security protocols we need to follow while granting this access?

#### Notes/Assumptions:
This task is crucial to facilitate data analysis and reporting. It's important to ensure that the access granted is read-only to maintain the integrity and security of our database. The assumption is that the Beta round donors' Ethereum addresses and their corresponding passport credentials are available in the Passport database.

**Comment by lucianHymer** [comment]
I created a user for Joel in Redash and emailed a link so he can set his password
