### ISSUE TITLE
Creating a Step-by-Step Guide for Utilizing the Custom Banner Feature

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1555]
### User Story:
As a member of the product, support, or marketing team, 
I want a clear and concise guide on how to use the custom banner feature 
So that we can communicate with users effectively.

### Acceptance Criteria
GIVEN the custom banner feature
WHEN a step-by-step guide is created
THEN team members from product, support, or marketing should be able to understand and utilize the banner feature effectively for user communication.

#### Product & Design Links:
[Context Link](https://github.com/gitcoinco/passport/issues/1490)

#### Tech Details:
This task involves creating a comprehensive guide that details the steps required to use the custom banner feature. The guide should cover all aspects of the feature, including how to customize the banner, how to set it up for different user groups, and how to publish it.

#### Open Questions:

1. Are there any specific use cases or scenarios that the guide should cover?
2. Are there any limitations or restrictions of the banner feature that should be highlighted in the guide? 

#### Notes/Assumptions:
The custom banner feature has been developed and is ready for release. This guide will facilitate its usage across different teams for effective user communication. It's important to ensure that the guide is easy to understand and covers all necessary details about the feature.

**Comment by schultztimothy** [comment]
Here is the step by step guide for adding and removing a banner: https://www.notion.so/gitcoin/Support-Banner-b864e0f074ca417096989e25381aa1c6

**Comment by hardiktheprogrammer** [comment]
@erichfi  can Work on this  really Want to contribute in Passport project  can you please assign me
