### ISSUE TITLE
Remove GitPOAP Stamp

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1559]
### User Story:
As a Gitcoin Passport administrator,
I want to remove the GitPOAP stamp from the available stamps,
So that users no longer have the option to claim or view this particular stamp.

### Acceptance Criteria

- The GitPOAP stamp should no longer be visible or accessible to users in the Passport application.
- Users who previously claimed the GitPOAP stamp should no longer see it in their Passport.
- Any API or backend calls related to the GitPOAP stamp should be deprecated and removed.

#### Product & Design Links:
![Image](https://user-images.githubusercontent.com/59769856/258765069-196f7d98-7002-4a0b-a50d-282d3e7d03dc.png)

#### Tech Details:

- The GitPOAP stamp might have dependencies or links in the codebase that need careful removal.
- Ensure that removing the stamp does not affect the functionality of other stamps or features.

#### Open Questions:

- Are there any data or analytics related to the GitPOAP stamp that we need to archive or retain?
- How should we communicate this change to the users, if at all?

#### Notes/Assumptions:

- The decision to remove the GitPOAP stamp is final and has been discussed with relevant stakeholders.
- There might be users who have queries or concerns about the removal of this stamp, and we should be prepared to address them.

**Comment by aminah-io** [comment]
Are we sure we want to remove this from users' wallets, or just let it expire and give it score of 0 in the meantime @erichfi ?
