### ISSUE TITLE
Improve All Providers with the New IAM Error Management System

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1560]
### User Story:
As a developer and user of the IAM,
I want to enhance all providers with the new IAM error management system,
So that we can provide a consistent and improved user experience across all services.

### Acceptance Criteria
**Credential Validation:**
GIVEN a set of credentials,
WHEN validating them,
THEN descriptive messages for invalid credentials should be logged.

**Error Logging:**
GIVEN an error in the system,
WHEN logging it,
THEN a wrapper function should be used to either log errors to Datadog or throw fatal errors locally.

**Frontend Enhancements:**
GIVEN a generic error message on the frontend,
WHEN users view it,
THEN they should see a "details" link to view the full response

#### Product & Design Links:
<links>

#### Tech Details:

- Implement the new error management system across all providers.
- Use the Twitter stamp as a guideline for the implementation.

#### Open Questions:

- Are there any other specific error types or scenarios that need to be addressed?
- How will the frontend "details" link be implemented to ensure user-friendliness?

#### Notes/Assumptions:

- Collaboration between the team will be crucial for the success of this phase.
- The improvements in this phase are dependent on the successful creation and rollout of the reference implementation in Phase 1 using the Twitter stamp: https://github.com/gitcoinco/passport/issues/1552
- The new error management system should be more user-friendly and developer-friendly, reducing the number of support requests.

**Comment by lucianHymer** [comment]
Here are the links to some TODOs I left in the code

- [ ] https://github.com/gitcoinco/passport/blob/1148c679ba86299a2b48c36a5cf824ccc355c311/platforms/src/utils/providers.ts#L73
- [ ] https://github.com/gitcoinco/passport/blob/1148c679ba86299a2b48c36a5cf824ccc355c311/platforms/src/utils/providers.ts#L89
- [ ] https://github.com/gitcoinco/passport/blob/1148c679ba86299a2b48c36a5cf824ccc355c311/types/src/index.d.ts#L78

**Comment by lucianHymer** [comment]
If somebody besides me picks this up, pull me in to pair or at least for a quick sync up! I have some ideas to discuss.
