### ISSUE TITLE
Update onchain Sidebar Text and Formatting

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1561]
**Objective:**
Refine the text and presentation in the onchain sidebar for clarity and consistency.

**Tasks:**

- [x] Ensure "Passport" and "Stamps" are always capitalized.
- [x] Update the blurb to:

> Minting your Passport onchain creates a tamper-proof record of your Gitcoin Passport onchain. This is only required if you're using applications that fetch Gitcoin Passport data onchain. Note: Minting your Passport onchain involves blockchain network fees and a $2 minting fee, which is directed to the Gitcoin treasury.

**Rationale:**
Consistent terminology and clear formatting enhance user experience and understanding.

**Comment by lucianHymer** [comment]
Ready for dev review and merge!
