### ISSUE TITLE
Data Query Setup for LIFO Deduplication Metrics Analysis

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1600]
### User Story:
As a data analyst,
I want to set up Jupiter Notebooks for specific metrics related to LIFO deduplication events,
So that I can gain insights into the behavior and distribution of these events.

### Acceptance Criteria
**1. Query for Passports with Shared Credentials**
GIVEN a table of LIFO deduplication events in Django admin,
WHEN I run the Jupiter Notebook query,
THEN I should get the number and percentage of passports that have at least one shared credential.

**2. Query for Dedup-Event-Triggering Passports Submitted to Scoring ID Other Than 335**
GIVEN a table of LIFO deduplication events in Django admin,
WHEN I run the Jupiter Notebook query,
THEN I should get the number and percentage of dedup-event-triggering passports that have been submitted to a scoring ID other than 335.

**3. Distribution of Deduplication Events by Credential Provider**
GIVEN a table of LIFO deduplication events in Django admin,
WHEN I run the Jupiter Notebook query,
THEN I should get a distribution of deduplication events categorized by each credential provider.

**4. Query for Unique Accounts Involved in Dedup Events**
GIVEN a table of LIFO deduplication events in Django admin,
WHEN I run the Jupiter Notebook query,
THEN I should get a list of all unique Ethereum addresses involved across the dedup events including the associated scorer_IDs.

**5. Query for Total GTC Staked on Unique Accounts Involved in Dedup Events**
GIVEN a table of LIFO deduplication events in Django admin and GTC stake amounts onchain,
WHEN I run the Jupiter Notebook and GTC staking data query,
THEN I should get the total amount of GTC staked on the addresses by themselves and by others.

#### Tech Details:

- Data Source: Django admin events table, Alchemy API
- Expected Output: Number, percentage, and distribution values for the specified metrics

#### Notes/Assumptions:

- The data in the Django admin events table is up-to-date and accurate.
- LIFO deduplication events are uniquely identifiable in the table.
- This issue depends on https://github.com/gitcoinco/passport-scorer/issues/326.

**Comment by nutrina** [comment]
My previous scripts are here: https://github.com/gitcoinco/passport-scorer-analytics

**Comment by nutrina** [comment]
Including this into the GG18 analysis

**Comment by aminah-io** [comment]
Spoke with @nutrina on this topic, and believe we need to get some more details on how to best implement (Redash vs Streamlit)

**Comment by aminah-io** [comment]
You can find the dashboard here: https://redash.api.scorer.gitcoin.co/dashboard/lifo-deduplication-metrics_1

**Comment by Jeremy-Gitcoin** [comment]
Pulled out the fifth item into #1667
