### ISSUE TITLE
Documenting the Deployment Process of Passport On-Chain Features

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1601]
### Objective:
To understand and document the process, costs, and time required to deploy Passport's on-chain features to a blockchain, given that the Passport multisig and EAS are already live.

### Tasks:
- [x] **1. Deployment Process:**

- Detail the step-by-step process to deploy Passport's on-chain features.
- Identify any prerequisites or dependencies that need to be in place before deployment.
- Highlight any potential challenges or roadblocks that might arise during deployment.

- [x] **2. Gas Costs:**

- Estimate the gas costs associated with deploying each feature.
- Provide a breakdown of costs for different actions (e.g., contract creation, function calls).
- Highlight any opportunities for gas optimization.

- [x] **3. Time Estimation:**

- Estimate the time required for each step of the deployment process.
- Consider factors like network congestion, transaction confirmation times, and any manual steps involved.

- [x] **4. Environment Variables Configuration:**

List all environment variables that need to be set or updated for the deployment.
Provide guidance on sourcing values for these variables and any security considerations.

- [x] **5. Post-Deployment Verification:**

- Outline steps to verify that the features have been deployed correctly and are functioning as expected.
- Include any tools or scripts that can assist in this verification process.

### Expected Outcomes:

- A comprehensive document detailing the deployment process of Passport's on-chain features.
- Clear cost and time estimations to aid in planning and budgeting for future deployments.
- A checklist or guide that can be followed by the team for future deployments.

**Comment by lucianHymer** [comment]
Here are those docs! https://github.com/gitcoinco/eas-proxy/blob/main/docs/03-new-deployment.md

They're linked in the top-level README
