### ISSUE TITLE
Release and Optimize V2 of the Public API for Improved Performance

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1608]
### User Story:
As a member of the Gitcoin team,
I want to finalize and release V2 of our public API,
So that we can offer improved performance, better pagination, and enhanced features to our users.

### Acceptance Criteria
**1. Interactive Documentation for V2 API**
GIVEN I am a passport integrator
WHEN I go to `https://api.scorer.gitcoin.co/docs/v2`
THEN I want to see the interactive version of the docs for V2 of the API.

**2. Improved Response Times with Token-Based Pagination**
GIVEN I am a passport integrator
WHEN I am using V2 of the score API available at `https://api.scorer.gitcoin.co/registry/v2/score`
AND that API is using token-based pagination
THEN I want to have better response (on average) times compared to the V1 of the API for any page I might request.

#### Tech Details:

- Implement an improved pagination system based on prev/next page tokens.
- Eliminate the use of skipping/offsetting in queries for better performance.
- Remove the count queries which have shown to be time-consuming.
- Introduce features like sorting & filtering scores based on timestamps to V2.
- Ensure the docs page for V2 is visible and interactive.
- Add support for testing the API from the live docs as indicated [here](https://github.com/gitcoinco/passport-scorer/blob/main/api/scorer/api.py#L18-L70).

#### Open Questions:
Are there any other features or optimizations that need to be considered for V2 before its release?

#### Notes/Assumptions:

- Once the Grants Stack team adopts the new API, we expect a significant drop in DB CPU usage for this API.
- We anticipate a complete elimination of the `SELECT COUNT` query, which currently ranks 3rd in terms of resource consumption, once the Grants Stack Team adopts this new API.

Screenshots:

![Image](https://github.com/gitcoinco/passport/assets/8137830/1d875db7-0e15-4c2a-a22b-2cd425641913)

**Comment by nutrina** [comment]
Whoever picks up this task, please loop in @bard regarding how to pull in the new scores.

**Comment by lebraat** [comment]
My general recommendation for versioning webpages:

Make sure the latest version is always located at the base URL, and all older versions at */vX.

In this case, I'd recommend the following:

V2 URL:
https://api.scorer.gitcoin.co/docs

V1 URL:
https://api.scorer.gitcoin.co/docs/v1

This is important for a couple of different reasons:
1. If third-party content writers and tool developers link off to the base URL in version X, we want to make sure their link is always pointing to the latest version as time goes on. 
2. SEO builds up on the base URL. Starting to send people to a new URL each time a new version comes out means you loose the SEO benefits.
