### ISSUE TITLE
Ledger Live Connection Issues

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1623]
**Overview**
Users experience difficulties when attempting to connect with Ledger. The initial connection often fails without providing a clear error message to the user.

**Steps To Reproduce**

1. Attempt to connect using Ledger.
2. Scan the Ledger Live QR code.
3. Observe the error messages and connection status.

**Observed  behavior**
Scanning the Ledger Live QR code leads to errors, suggesting the app isn't up to date.

**Expected behavior**
Successful connection with Ledger without any errors.

**Screenshots**

**Additional context**
This issue has been observed by multiple users and has been reported to customer support multiple times.

**Comment by nutrina** [comment]
This is the error if I try via the desktop app:

<img width="591" alt="image" src="https://github.com/gitcoinco/passport/assets/8137830/a2e9a639-5f08-4010-b316-6b8c3ac50fe8">

**Comment by nutrina** [comment]
And it is the same issue with Ledger Live mobile.
So we need to update our libs & setup.

What works however is using Ledger via Metamask
@erichfi we can recommend this for the users for now.

**Comment by nutrina** [comment]
https://onboard.blocknative.com/docs/wallets/walletconnect#main-sidebar

**Comment by nutrina** [comment]
Testing Ledger connections:
| Header | Header | Header | Header |
|--------|--------|--------|--------|
| Passport | Wallet | Details | Cell |
|--------|--------|--------|--------|
| WalletConnect | Ledger Live Desktop | Copy & paste WalletConnect link | Cell |
| Cell | Cell | Cell | Cell |
| Cell | Cell | Cell | Cell |

**Comment by nutrina** [comment]
Interestingly the logs say user has rejected however, I have not pressed reject:

**Comment by nutrina** [comment]
The fix will update the ledger live module in web3-onboard.
This does not work yet on local, but it is worth having it tested in review, staging & prod.
