### ISSUE TITLE
Feature-Flagged On-Chain 'Go' Button for Optimism Fails Despite Meeting All Requirements

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1636]
**Overview**
When using the feature-flagged URL for on-chain features, hitting the "Go" button for Optimism results in a bug, despite being signed in to Optimism, having a verified Discord stamp, and a score.

**Steps To Reproduce**

1. Navigate to the feature-flagged URL for on-chain features.
2. Ensure you are signed in to Optimism.
3. Verify that you have a Discord stamp and a score.
4. Click the "Go" button for Optimism. 

**Observed  behavior**
Upon clicking the "Go" button, the system encounters a bug and fails to proceed as expected.

**Expected behavior**
The system should successfully proceed to the next step, given that all the required conditions (signed in to Optimism, Discord stamp verified, and a score) are met.

**Screenshots**
![Screenshot from 2023-08-23 15-17-33](https://github.com/gitcoinco/passport/assets/59769856/9b1ed2a3-199a-4eb2-9d33-d7b31244632f)

**Additional context**

**Comment by nutrina** [comment]
This has been fixed. It was only a misconfiguration in our backend.
