### ISSUE TITLE
Only Accept Hypercerts Claimed Using batchMintClaimsFromAllowlists Function

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1637]
### User Story:
As a system administrator,
I want to only accept hypercerts that were claimed using the `batchMintClaimsFromAllowlists` function,
So that I can mitigate the issue of spam hypercerts and maintain the integrity of our verification process.

### Acceptance Criteria
GIVEN a hypercert is submitted for verification,
WHEN the system checks the method used for claiming the hypercert,
THEN it should only accept the hypercert if it was claimed using the `batchMintClaimsFromAllowlists` function.

Add banner: 

> Only allowlisted Hypercerts count in this stamp.

#### Product & Design Links:
[Hypercerts Dune Dashboard](https://dune.com/hypercerts/op-hypercerts)

#### Tech Details:
The feature will require changes in the verification logic to include a check for the method used in claiming the hypercert.

#### Notes/Assumptions:
This feature is considered high priority due to the recent influx of spam hypercerts.

**Comment by lucianHymer** [comment]
This isn't currently indexed in the subgraph we use for hypercert info. And it's not something we can determine with a contract call.

I've reached out to Carl at Hypercerts to see if he had an idea for the source. We could add it to the Hypercerts subgraph pretty easily, or we could index it on our side. I think we could also potentially query it directly from Dune, but I'm not sure of all the implications of that.

**Comment by lucianHymer** [comment]
Blocked on this: https://github.com/hypercerts-org/hypercerts/issues/1052

**Comment by bitbeckers** [comment]
hi @lucianHymer jumping in here from the Hypercerts end. I've made some updates on [the issue](hypercerts-org/hypercerts#1052) and you can inspect the updated subgraph [here](https://thegraph.com/hosted-service/subgraph/hypercerts-admin/hypercerts-testnet)

If you use the query below you should be able to identify tokens from the allowlist by checking `claimToken.claim.allowlist !== null`

```
{
  claimTokens {
    claim {
      allowlist {
        id
        root
      }
    }
    id
    units
  }
}
```

Would that suffice for the passport usecase?

**Comment by lucianHymer** [comment]
That will be perfect!! Thanks so much @bitbeckers

**Comment by lucianHymer** [comment]
Carl reached out and recommended that we instead just check that `claim.creator !== claim.owner`, so this is unblocked!

**Comment by lucianHymer** [comment]
Blocked on trying to understand exactly what the `claim.creator !== claim.owner` indicates

**Comment by bitbeckers** [comment]
hi @erichfi yes we can, in theory. IPFS support in the Graph is relatively new, but this is a good usecase to implement it. We're currently focussing on a release of a new product for FTC but I'm trying to sneak the Graph update in before then. 

Did @lucianHymer update you on our chats?
