### ISSUE TITLE
Wallet Connectivity Issues

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1642]
Meta issue for 
- [x] #1623 
- [x] #1624
- [x] #1625
- [ ] #1626

**Comment by nutrina** [comment]
Next steps: update the ledger setup in the dapp wo use WalletConnect V2 for #1623

**Comment by nutrina** [comment]
Added test results for LedgerLive: https://github.com/gitcoinco/passport/issues/1623#issuecomment-1696827826
