### ISSUE TITLE
Analysis: Gitcoin Grants 18

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#1644]
### User Story:
As a Passport PM
I want to determine if there were Sybils in the Grants Round 18
So that I can update our Sybil's list(s) and help improve our methodology to detect Sybils in the grants program

### Acceptance Criteria
GIVEN a user is on Gitcoin Grants Donations List (Data TBD)
WHEN they are a Sybil
THEN we should label them and add to our Sybils lists for future rounds

GG18 round had n# users who donated to one or more grants. We should run the [same analysis that we did for Shapeshift campaign](https://github.com/gitcoinco/passport/issues/1581)
Scripts used for analytics are in this repo: https://github.com/gitcoinco/passport-scorer-analytics

Steps:

- [ ] Obtain Grants Round 18 data from Umar
- [ ] Add a new tab with the addresses
- [ ] Run the scripts to determine if they violate any of the rules (duplicate credentials, external sybil list, OP or ETH first funding transaction)
- [ ] Create out for each of the four rules identical to the [Shapeshift Sybils combined ](https://docs.google.com/spreadsheets/d/1696SIot00K0TxTHY8cnVyqaolQNyACslVJ18bF3joNA/edit#gid=1991455101)
- [ ] Jeremy to close the loop with Umar on Sybils we detected for GG18 and update our Sybils list with the new Sybils detected 

We need to run analysis against the list to determine which accounts are clearly Sybils and label with the rule(s) violated

**Comment by ufkhan97** [comment]
[gg18_voter_passports.csv](https://github.com/gitcoinco/passport/files/12470000/gg18_voter_passports.csv)

Attached are GG18 Voter Wallet Addresses and Passport Scores. 

BTW I can't access the repo: https://github.com/gitcoinco/passport-scorer-analytics

Thanks for working on this!

**Comment by AugustusTonia** [comment]
I have participated in grant 18 and it's cool. Supported either 10 projects or so. Havnt found any bug yet. Will surely report if any. Thanks

**Comment by nutrina** [comment]
To summaries:
- scripts have been updated, the README is also up to date: https://github.com/gitcoinco/passport-scorer-analytics
- have also created a streamlit app, that allows combining any of the list of known sybils that we currently have: https://github.com/gitcoinco/passport-sybil-verification
