### ISSUE TITLE
[BUG] User unable to claim Grant stack stamp even though they donated to OSS in Beta round

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#1648]
From their contributions history, you can see they donated in the Beta round. https://explorer.gitcoin.co/#/contributors/0x055fdA7Eb509cc338C898b0F698B7624387AB813 to 5 projects but the error from passport says their donation is 0.

https://etherscan.io/tx/0x43f5db49a372e347267643c86a7210767c3bee6c662f86fb6e1b41134a23fa46

 > [<br>	{<br>		"code": 403,<br>		"error": "projectCount: 0 is less than 3"<br>	},<br>	{<br>		"code": 403,<br>		"error": "projectCount: 0 is less than 5"<br>	},<br>	{<br>		"code": 403,<br>		"error": "projectCount: 0 is less than 7"<br>	},<br>	{<br>		"code": 403,<br>		"error": "programCount: 0 is less than 2"<br>	},<br>	{<br>		"code": 403,<br>		"error": "programCount: 0 is less than 4"<br>	},<br>	{<br>		"code": 403,<br>		"error": "programCount: 0 is less than 6"<br>	}<br>]<br>

**Link:** [Conversation with bytzu007@gmail.com](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/64741)

**Customer:** [bytzu007@gmail.com](https://app.intercom.com/a/apps/xaafeyri/users/64c7b9a6b10c12065e215f7b/all-conversations)
**Customer ID:** 32dd3942-f12f-4e9b-bf6c-920bc1d0e255
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/64741) when this issue is closed.

**Comment by lucianHymer** [comment]
Fixes here:
https://github.com/gitcoinco/passport-scorer/pull/373
https://github.com/gitcoinco/passport/pull/1651
