### ISSUE TITLE
Update Pulumi Libraries

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1650]

**Comment by nutrina** [comment]
Hey @lucianHymer . The goal is to be able to specify https://www.pulumi.com/registry/packages/aws/api-docs/ecs/taskdefinition/#ephemeralstorage_nodejs for our scheduled tasks.
Unfortunatly this is not possible with the current awsx libs, we need newer version (like 1.0.5, see https://www.npmjs.com/package/@pulumi/awsx ).
This however breaks a lot of the code, so we need to fix this.

**Comment by lucianHymer** [comment]
I just moved this over while handling an urgent ticket for the release!

**Comment by lucianHymer** [comment]
At this point, this is mostly working (for the staging ENV). I've just been running `pulumi preview`, so nothing is changed in AWS yet.

The last thing I'm a bit confused about is how exactly the TargetGroups get associated to the FargateServices. We're creating a TargetGroupAttachment for redash, but not for any of the other services.
