### ISSUE TITLE
Migrate Passport Data to Dedicated Passport Indexer

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#1652]
### User Story:
As a Passport Data Integrator,
I want a centralized data indexer for all Passport scores,
So that I can:
- Anonymously access Passport data without revealing which Ethereum addresses I am interested in.
- Streamline data access by avoiding one-by-one API calls.

### Acceptance Criteria
GIVEN a user navigates to public.scorer.gitcoin.co
WHEN they access the site
THEN they should be able to download an up-to-date JSON file containing all Passport scores.

- Update Frequency: Scores should be refreshed twice an hour (every 30 minutes).
- Data Format: The JSON data will adhere to the newly established export sample format (JSONL not attachable here).

#### Tech Details:

- [x]  Implement a new URL to access the JSON data dump.
- [ ]  Set up monitoring and alerts to notify if the Passport Indexer is offline or experiencing issues.

#### Open Questions:

How do we coordinate with the Grants Stack team to redirect users to our new URL? This is essential for any external parties who are currently utilizing the existing indexer but whom we might not have visibility on.

#### Notes/Assumptions:
The primary objective is to provide seamless and efficient access to Passport scores, catering to diverse use-cases without compromising data integrity or user privacy.

**Comment by digitalmnt** [comment]
A few notes on this. It looks like objects can only be served via http. Here is the updated url for the export on staging public.api.staging.scorer.gitcoin.co. More info on http serving of s3 objects https://repost.aws/knowledge-center/cloudfront-https-requests-s3 only available over http

It looks like monitoring for this export can
