### ISSUE TITLE
Implement New Identity Staking Round for GTC Staking App

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1655]
### User Story:
As an admin of the GTC Staking App,
I want to seamlessly start a new identity staking round,
So that users can continue staking without interruption as the current round ends.

### Acceptance Criteria
GIVEN the current staking round is ending,
WHEN the admin initiates the start of a new round,
THEN a new round should immediately be available for users to participate in, independent of the ending round.

#### Tech Details:
No new function needed; this is about timing the start of a new round as the current one ends.

#### Notes/Assumptions:
Initiating a new round has no impact on existing or ending rounds.

**Comment by AugustusTonia** [comment]
When is the new round starting?
