### ISSUE TITLE
Add Documentation for Scoring Attestation Onchain

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1663]
### User Story:
As a developer working on or integrating with the Gitcoin Passport,
I want to have detailed documentation on how scoring attestation works onchain,
So that I can understand the functionality, troubleshoot issues, and integrate more efficiently.

### Acceptance Criteria
GIVEN there is an attestation onchain,
WHEN a user queries the GitcoinPassportDecoder contract with a user address,
THEN the contract should query the GitcoinResolver with the user's address and the passport schema UID, load the attestation, and decode the attestation into a standard, human-readable passport object

GIVEN a dev needs to add a new provider onchain,
WHEN the dev sends an addNewProvider transaction to the GitcoinPassportDecoder contract with the new provider's name,
THEN the provider is added to the end of the current version

GIVEN a dev needs to create a new version to delete and/or reorder the provider mapping
WHEN the dev sends a createNewVersion transaction to the GitcoinPassportDecoder contract with the providers'
 names,
THEN a new version is created with these names, and the current version is incremented

GIVEN there is a docs folder in the GitHub repository,
WHEN a developer accesses this folder,
THEN they should find comprehensive documentation explaining how scoring attestations work onchain.

#### Product & Design Links:
[To be added to the documentation folder](https://github.com/gitcoinco/eas-proxy/tree/main/docs)

#### Tech Details:

- Use Markdown for documentation
- Cover how to query scoring attestation
- Explain the smart contracts involved and how they interact
- Provide code samples for better understanding
- Add FAQ for common issues or questions around this feature

#### Notes/Assumptions:

- This feature is of medium priority but will be very useful for both internal and external developers.
- Once completed, the documentation should be reviewed for accuracy and comprehensibility before being merged.

**Comment by Jeremy-Gitcoin** [comment]
@lucianHymer Will update with creating the new smart contract to resolve the Bitmap, new ticket to be created to update and read from the smartcontract / onchain (app + IAM read from onchain, vs. having an offchain)

**Comment by lucianHymer** [comment]
So for this ticket, we will first want to create a contract for decoding the passport onchain.

Currently we store the mapping from bit position to Provider Name offchain. We'll move this onchain.

The contract will keep a mapping of
version => bitPosition => provider
or something equivalent. We may want to store the other way around too, version => provider => bitPosition (for looking up the correct bit for a provider from the IAM when encoding a passport)

If new providers are added, they just need to be appended to the array. If we ever want to remove and/or reorder providers, we'll increment the version to reset it.

We probably need some kind of counter like currentVersionBits that gets incremented with each new provider and resets to 0 with a new version.

Here's rough psuedocode for the contract:

PassportDecoder:

mapping version => bitPosition => provider
mapping version => provider => bitPosition

public uint32 version
public uint32 currentVersionBits

addProvider(name): Adds the new provider to the end of the current version, increment currentVersionBits

createNewVersion(names): Creates a new version with the given provider names, reset currentVersionBits to the # of names

getPassport(address): Calls GitcoinResolver to get the passport, uses the provider mapping to decode the bits in the provider bitmap.


We won't actually change the frontend to use this onchain mapping as the source-of-truth, that will be handled in a later ticket.
