### ISSUE TITLE
Spike: Verax implementation

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#1666]
Linea is close with the Verax attestation

Outcome:
- [ ] What is needed to enable onchain for Linea?
- [ ] What is the order of operations of how/what we push to enable it?

**Comment by lucianHymer** [comment]
- [ ] Write EASWrappedVeraxPortal (based on https://github.com/Consensys/linea-attestation-registry/blob/dev/src/example/EASPortal.sol)
  - this should support and interface for EAS's functions of multiAttest, multiRevoke, and getAttestation and then call the matching Verax functions 
  - multiAttest and multiRevoke should also make calls to GitcoinResolver
  - This contract's address will be used for the EAS address on Linea.
- [ ] Register the portal and schemas for Verax

**Comment by Jeremy-Gitcoin** [comment]
Per standup on Weds 9/6 we're going to include in the spike making a working prototype pushing to the Verax registry from Passport

**Comment by lucianHymer** [comment]
Blocked on feedback from Verax
