### ISSUE TITLE
Cleanup old redash instance

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1668]
Cleanup the old redash instance resources, delete anything that is not used:
- [x] destroy the ec2 instance
- [x] destroy the unused DB
- [x] destroy DNS records
- [ ] ~destroy the SMTP related stuff (not sure about this, we might probably use the same SMT config for our current redash instance)~

**Comment by aminah-io** [comment]
Checked in RDS and see there's a Redash database, a t3 micro. Is this associated with the old redash instance? @nutrina @digitalmnt

**Comment by aminah-io** [comment]
@nutrina I will leave the SMTP/SES because it doesn't cost anything unless we're sending/receiving emails
