### ISSUE TITLE
Update monitoring alarms

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1676]
This is a follow-up for this ticket: https://github.com/gitcoinco/passport/issues/1358
Also relevant is: https://www.notion.so/gitcoin/Passport-Monitors-444bfbe603d146ecbdd54211e1646957

Given that our infrastructure can change (services can be destroyed and recreated, hence their ID / ARN might change), it is difficult to track these changes and adjust the monitors that we have currently in place.

Hence it would make sense to create the alarms automatically from pulumi, such that they are created and maintained together with all the infrastructure changes, without any further manual intervention.

The setup would probably look like:

create:

(1) CloudWatch Alarm -> (2) send event SNS -> (3) write event to PD via events API V2

Steps 1 and 2 can be managed from pulumi.
Step 3 is a one-time setup of the event endpoint in PD

This setup shall be applied for:
- [ ] the scorer service instances to monitor for 
    - [ ] cpu exceeding threshold 
    - [ ] memory exceeding threshold 
    - [ ] 5xx error rate above threshold 

**Note:** custom CloudWatch alarms could also be used in combination with autoscaling settings

**Comment by lucianHymer** [comment]
This has been updated! I left the Datadog alarms active but muted them, so we can see if there are any alerts that we miss before we delete them.

**Comment by lucianHymer** [comment]
I also added the "Unhandled Error" alert for the IAM to pulumi
