### ISSUE TITLE
[UI] Customize wallet signing text message when saving passport to cGrants

### ISSUE THREAD

**Issue by brentmartin** [gitcoinco/passport#168]
As a Passport holder, I want to grant consent to gitcoin.co to store the score, so that I'm in control of my data

GIVEN I have connected my passport to Gitcoin.co
WHEN I click "Save Score"
THEN I see a message in my wallet where I can confirm that it's okay for Gitcoin to save my score 

**Messages to write for:**
- saving score on gitcoin trust page -> "I am signing to confirm that I am saving my Passport score to Gitcoin Grants."

**Technical notes:**
Also explore the potential for implementing https://eips.ethereum.org/EIPS/eip-4361 or https://eips.ethereum.org/EIPS/eip-712

**Comment by leoneric** [comment]
@Etovardesign, any thoughts on a better message?

**Comment by Etovardesign** [comment]
@leoneric I think something like this works for now, "I am signing to confirm that I would like to save my stamps and Trust Bonus score to Gitcoin."

![Image](https://user-images.githubusercontent.com/100154376/175089157-d7a59198-840b-4191-96dd-b6edb8e025fb.png)

**Comment by gdixon** [comment]
@nutrina has a PR for this here: https://github.com/gitcoinco/web/pull/10711

**Comment by leoneric** [comment]
Thanks -- this looks good to deploy!
