### ISSUE TITLE
Switch to Alchemy RPC URLs in frontend

### ISSUE THREAD

**Issue by lucianHymer** [gitcoinco/passport#1680]
We should use Alchemy RPC URLs in the fronted for Optimism and Polygon mainnets.

We should create make sure to use the "Allowlist Domains" setting in Alchemy to restrict the keys to only our frontends (review, staging, prod).

**Comment by nutrina** [comment]
This relates to this discussion: https://discord.com/channels/562828676480237578/1149471846044012595
