### ISSUE TITLE
Improved Stamp Cards with Clarified Sorting Mechanism

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1683]
### User Story:
As a user,
I want to see an updated, visually appealing stamp card interface with a clear sorting mechanism,
So that I can easily track my progress, activities, and focus on the most rewarding actions.

### Acceptance Criteria
GIVEN a user is logged in
WHEN they navigate to the stamp card section
THEN they should see the new design as per Figma drafts
AND the cards should be sorted based on verification status and available points left.

#### Product & Design Links:
[Figma Drafts](https://www.figma.com/file/Tx5sYqRNzfCuu1Lz4l7x1q/Passport-S19_Production-Ready?type=design&node-id=5211%3A1038&mode=design&t=et3svAT202CGfxUZ-1)

[Stamp card hovering animation](https://www.figma.com/proto/evPwuavS56Y27pob9cDR55/feedback-passport-(v2)?page-id=0%3A1&node-id=2-100&t=XEstQq2egXPD8gz0-1)

#### Tech Details:

- Front-end redesign based on Figma
- Back-end logic adjustments to implement sorting

#### Open Questions:

- How seamless will the transition be for existing users?
- What is the roll-back plan if users find issues with the new design?

#### Notes/Assumptions:
- Assume that users are familiar with the concept of stamp cards
- The overarching sorting mechanism is:
  - The first section should display cards that haven't been verified yet.
  - The second section should display verified cards.
  - Within each section, cards should be arranged based on the available points left in the stamp.

**Comment by lucianHymer** [comment]
Here's the code to make the disabled icons green!                

<div
                  style={{
                    filter: "invert(31%) sepia(13%) saturate(1992%) hue-rotate(123deg) brightness(97%) contrast(85%)",
                  }}
                >
                  <img src={platform.icon} alt={platform.name} className="h-10 w-10 grayscale" />
                </div>

**Comment by digitalmnt** [comment]
@erichfi I wasn't able to find a design for the loading states of the cards. I modified it to be 
<img width="649" alt="Screenshot 2023-09-20 at 9 55 01 AM" src="https://github.com/gitcoinco/passport/assets/6887938/b6ff92b8-2462-4416-88ba-c6e717ee233a">
but it is easy to change

**Comment by digitalmnt** [comment]
@erichfi I wasn't able to find a design for the loading state of the card so I modified it to be this:
<img width="592" alt="Screenshot 2023-09-21 at 4 43 50 PM" src="https://github.com/gitcoinco/passport/assets/6887938/b330688d-a402-413e-a292-f37168e257c6">
Its easy to change though!
