### ISSUE TITLE
Implement New Passport Logo

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1685]
### User Story:
As a user, 
I want to see the new Passport logo on all pages of passport.gitcoin.co,
So that I can identify with the updated brand identity.

### Acceptance Criteria
GIVEN a user is on any page of passport.gitcoin.co
WHEN they look at the top-left corner or any other standard position for the logo
THEN they should see the new Passport logo

#### Product & Design Links:
[Figma Drafts with New Logo](https://www.figma.com/file/Tx5sYqRNzfCuu1Lz4l7x1q/Passport-S19_Production-Ready?type=design&node-id=5211%3A1038&mode=design&t=et3svAT202CGfxUZ-1)

#### Tech Details:

- Update the logo image assets across the front-end
- Ensure compatibility with different display sizes

#### Open Questions:

- Are there specific dimensions for the new logo?
- Do we need to update the favicon as well?

#### Notes/Assumptions:
Assume that the new logo should replace the old one in all instances across the platform.

**Comment by digitalmnt** [comment]
@erichfi I updated the logo to match the designs, but the font used in the designs is not a public font and requires a license/purchase. Could you ask whoever created the designs if they have purchased the font and have the assets? Thanks!
