### ISSUE TITLE
Implement New Dashboard Structure

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1688]
### User Story:
As an end user,
I want to navigate through a newly structured dashboard,
So that I can easily find the information and features I use most frequently.

### Acceptance Criteria
GIVEN the user is logged into their account
WHEN they navigate to the dashboard
THEN they should see the new layout according to the high-fidelity Figma drafts

#### Product & Design Links:
[Figma Draft](https://www.figma.com/file/Tx5sYqRNzfCuu1Lz4l7x1q/Passport-S19_Production-Ready?type=design&node-id=5211%3A1038&mode=design&t=et3svAT202CGfxUZ-1)

#### Tech Details:
Implement the new structure in the front-end, ensure compatibility with existing back-end APIs.

#### Open Questions:
Are there any changes in the back-end APIs that need to be implemented for the new dashboard?

#### Notes/Assumptions:
High-fidelity Figma drafts are available for this redesign.

**Comment by lucianHymer** [comment]
For this ticket, the new theme has been implemented and the layout defined using generic components.

A follow up ticket has been created for filling out these components: https://github.com/gitcoinco/passport/issues/1699
