### ISSUE TITLE
Enhance NFT Stamp Verification to Prevent Duplication and Prioritize Latest NFTs

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1697]
### User Story:
As a user holding various NFTs,
I want the Passport system to track individual NFTs in my wallet,
So that I can't claim the stamp multiple times across different wallets by moving the same NFT.

### Acceptance Criteria
GIVEN a user has multiple wallets
AND the user owns an NFT that was previously used to claim a stamp
WHEN the user attempts to claim the stamp with another wallet containing the same NFT
THEN the system should deduplicate the second instance of the stamp, recognizing that this NFT was used before.

GIVEN a user has an NFT in their wallet
WHEN they claim the stamp
THEN the system should select the most recently added NFT for verification.

#### Tech Details:

- Implement tracking based on chain ID, contract, and NFT ID.
- Implement a deduplication mechanism.
- Prioritize the most recently added NFT for verification.

#### Notes/Assumptions:
The changes will only apply to future stamp claims and won't retroactively affect stamps that have already been claimed.

**Comment by lucianHymer** [comment]
Ticket #1640 could be knocked out as part of this

**Comment by lucianHymer** [comment]
I confirmed with Alchemy support that for the getContractsForOwner endpoint, the `displayNft.tokenId` field will show us the ID of the NFT that the user owns with this contract.

We can tell it to return the most recently acquired NFT first using the `orderBy=transferTime` parameter
