### ISSUE TITLE
Loading Passport App Fails if HW Wallet Not Connected to Metamask

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1722]
**Overview**
When a user's hardware wallet is not connected but selected in Metamask, attempting to log into the Passport app results in an indefinite loading icon and console error, without any user-friendly message or indication.

**Steps To Reproduce**

1. Make sure the address selected in Metamask is for a Hardware Wallet (HW Wallet).
2. Ensure the HW Wallet is not connected to your laptop or PC.
3. Navigate to the Passport app and attempt to log in.

**Observed  behavior**
Upon trying to log in, the loading icon appears and continues indefinitely. An error is also logged in the console.

**Expected behavior**
The system should display a clear error message, suggesting that the user either connects their hardware wallet or selects another wallet in Metamask.

**Screenshots**
![Image](https://github.com/gitcoinco/passport/assets/8137830/567a4cf9-6930-415f-b485-ddd583a8c7c0)

**Comment by digitalmnt** [comment]
When my hardware wallet is not connected and I try to login, it still prompts me for a signature so if @nutrina if you can recreate this it might be worth trying! Either way, https://github.com/gitcoinco/passport/pull/1733 should send the user back to the landing page and show a toast with whatever error is encountered while signing the message to login to ceramic

**Comment by digitalmnt** [comment]
Moving this to blocked until reviewed.
