### ISSUE TITLE
Inconsistent Stamp Display on Initial Load vs. Update in Passport App

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1723]
**Overview**
The number of stamps displayed varies between the initial load and subsequent updates of the Passport app. This inconsistency seems related to the improper filtering of stamp types (EIP-712 / non-EIP-712) and a bug in `CeramicContext` affecting expired stamps.

**Steps To Reproduce**

1. Use a Passport account with a mix of EIP-712 and non-EIP-712 stamps from previous testing.
2. Initially load the Passport app and note the number of stamps displayed.
3. Update the Passport within the app.

**Observed  behavior**
The initial load of the Passport app displays a different number of stamps compared to the stamps shown after updating the Passport.

**Expected behavior**
The number of stamps displayed should be consistent between initial load and subsequent updates. Stamps should also be filtered correctly by their type (EIP-712 / non-EIP-712).

**Screenshots**
![Image](https://github.com/gitcoinco/passport/assets/8137830/3183516c-2251-4126-8b7c-7dec91e97bc1)

![Image](https://github.com/gitcoinco/passport/assets/8137830/ea7db640-48ae-4ae9-978b-e3a5466e4e02)

**Additional context**
This issue might be related to how the `CeramicContext` handles expired stamps and how the app filters stamps based on their type.

**Comment by digitalmnt** [comment]
I'm unable to replicate this. I receive the same credentials when initially loading a passport that contains only VCs signed with `did:pkh:eip155:1:0xC79ABB54e4824Cdb65C71f2eeb2D7f2db5dA1fB8` as when I switch the signature type and the credentials are aut populated with EIP712 signatures.

**Comment by nutrina** [comment]
The problem is that in the "/bulk" request handlers does not filter the stamps by their type before returning:
`updated_passport_state = CeramicCache.objects.filter(address=address)`

The filter condition should include `type=CeramicCache.StampType.V1`
