### ISSUE TITLE
Resolve Technical Ambiguities around ComposeDB Upgrade: Passport x GraphQL Compatiblity

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1731]

**Comment by nutrina** [comment]
The current work in progress can be found in: https://github.com/nutrina/compose-db

**Comment by nutrina** [comment]
Waiting for link to testnet node instance.
So far have tested on local node, all seems good.

**Comment by nutrina** [comment]
Blocked: waiting for our key to be added to the server.

**Comment by nutrina** [comment]
Waiting for feedback from peers.

**Comment by nutrina** [comment]
This is done, closing.
