### ISSUE TITLE
Enable On-chain Passport Movement for Linea / Verax

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#1732]
### User Story:
As a user of Linea / Verax,
I want to move my Passport on-chain,
So that I can take advantage of Linea / Verax-specific features without compromising my Passport's integrity.

### Acceptance Criteria
GIVEN I am on the Linea / Verax interface
AND I have a Passport
WHEN I click on the chain icon (or push onchain using the new UI)
AND select "Move On-chain for Linea"
THEN my Passport should be moved on-chain and be available on both EAS (Linea Mainnet) and Verax (via the EAS module)

**Additional Note:** A single transaction will be initiated, in which users will pay 2x the standard gas fees to push to both EAS & Verax.

#### Product & Design Links:
[How to Set Up On-Chain Passport on a New Network](https://docs.google.com/document/d/138FioRq8VxSmkuy5kR0wjhlTAfwYDiWERY1fRf12yWo/edit#heading=h.2sunu84dovm4)

#### Tech Details:
This feature builds upon previous work carried out in spike #1666.

#### Notes/Assumptions:
We assume that users are familiar with both Linea and Verax platforms and understand the implications of moving their Passport on-chain.

**Comment by Jeremy-Gitcoin** [comment]
Need to ping EAS once we've deployed to ensure they have schema names updated to be as clean as possible

**Comment by Jeremy-Gitcoin** [comment]
@lucianHymer Here's the SAFE contract address for Linea: 
linea:0x9A40A259B441C942A22227D5D22bA86dD2E7BFe0

**Comment by lucianHymer** [comment]
Once this has been merged (will happen shortly) and tested, I'll do the mainnet deployment and one more small PR to check in those new mainnet contract addresses.
