### ISSUE TITLE
Implement AWS Alarm for Error Logs in Scheduled Tasks

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1735]
### User Story:
As a Developer,
I want an AWS alarm to be triggered in case of an error log for any ScheduledTask,
So that I can promptly address the issue and ensure system reliability.

### Acceptance Criteria
**CloudWatch Error Logging**
GIVEN: I am a Developer
WHEN: An error occurs in one of the commands executed during a scheduled task
THEN: An error log describing the issue should be written to AWS CloudWatch

**PagerDuty Notification**
GIVEN: I am a Developer
WHEN: An error log is written to CloudWatch
THEN: A PagerDuty notification alert is triggered and sent to the designated team members

GIVEN I am a Developer
WHEN a scheduled job is not executed according to its schedule
THEN a Pager Duty notification alert is triggered and sent to the designated team members.

#### Tech Details:

- Utilize AWS SDK for logging
- Integrate PagerDuty API for alerting

#### Open Questions:

- What permissions are needed to access CloudWatch logs?
- How should the alert be configured in PagerDuty? High priority, escalation policies, etc.

#### Notes/Assumptions:

- Assumes that the team members receiving the PagerDuty alerts are trained to handle the issues.
- Assumes that AWS CloudWatch and PagerDuty are fully integrated into our system.

**Comment by lucianHymer** [comment]
Blocked on engineering discussion
