### ISSUE TITLE
Customized Verax Dashboard for Easy Onchain Push

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1747]
### User Story:
As a Gitcoin Passport or Linea Verax user,
I want to land on a Verax-branded dashboard when using https://passport.gitcoin.co/#/dashboard/verax,
So that I can directly initiate transactions to push my stamps and score to Linea/Verax.

### Acceptance Criteria
GIVEN the user accesses via https://passport.gitcoin.co/#/dashboard/verax
WHEN they view the dashboard
THEN they see a Verax-branded component next to their score.

GIVEN the user has no stamps on their Passport
WHEN they view the Verax component
THEN the 'Push to Verax' button is disabled.

GIVEN the user has stamps or makes changes to their Passport
WHEN they view the Verax component
THEN the 'Push to Verax' button is enabled.

GIVEN the user clicks the 'Push to Verax' button
WHEN they have a Passport with stamps
THEN an onchain transaction is initiated immediately.

GIVEN the user has already pushed their Passport onchain and made no changes
WHEN they view the Verax component
THEN the 'Push to Verax' button is labeled "Already Pushed".

GIVEN the user has made changes to their Passport after pushing it onchain
WHEN they view the Verax component
THEN the 'Push to Verax' button is labeled "Update".

GIVEN a user accesses the dashboard via a Verax-specific link
WHEN they land on the dashboard
THEN the visit is tracked for analytics purposes.

Language of the Verax component:
Verax is a community maintained public attestation registry on Linea. Bring your Passport onto Verax so projects in the Linea ecosystem can read your score onchain. (This will be in the normal font of the component)

This action requires ETH bridged to Linea Mainnet to cover network fees, as well as a $2 mint fee which goes to the Gitcoin treasury. (This will be in smaller font as shown in the design)

#### Product & Design Links:
Figma files
- [Dashboard incl. Verax widget](https://www.figma.com/file/FOOlLEFaBt87atw6CPkA5P/Passport-S19?type=design&node-id=4915%3A13161&mode=design&t=8VOTwjWHzMQ1cVVR-1)
- [The three states of the Verax widget](https://www.figma.com/file/FOOlLEFaBt87atw6CPkA5P/Passport-S19?type=design&node-id=3761%3A36672&mode=design&t=8VOTwjWHzMQ1cVVR-1)

Wording for widget text blurb:

> Verax is a community maintained public attestation registry on Linea. Bring your Passport onto Verax so projects in the Linea ecosystem can read your score onchain.

#### Tech Details:
- Implementation should be modular to accommodate similar future campaigns.
- Tracking the number of visits through the Verax-specific link via Google Analytics, potentially get help from MMM.
- Ping @lucianHymer re color assistance.

#### Notes/Assumptions:
Tracking the number of visits through the Verax-specific link for analytics purposes.

**Comment by lucianHymer** [comment]
Hey @erichfi, so that's the text that shows up in our tooltip if the user is not connected to the chain that they will push to. This is to make sure they're not confused by the fact that a single button press is going to trigger multiple Metamask interactions (switching chain, then signing the transaction).

I do think it's important to include this. I have it only showing up if you're not connected to the right chain (in this case Linea Goerli, but that will change to mainnet Linea).

Do you think there's another spot where it would be better to include this info?
