### ISSUE TITLE
Update and Expand GTC Community Staking Credentials in Passport Sidebar

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1757]
### User Story:
As a Gitcoin Passport user,
I want the GTC community staking credentials to be updated,
So that I can engage with a more refined and inclusive staking system.

### Acceptance Criteria
GIVEN the user is in the Gitcoin Passport application's GTC staking stamp sidebar
WHEN they view the 'Community Staking Credentials'
THEN they see the new credentials—Beginner Community Staker, Experienced Community Staker, Trusted Citizen—listed below the old self-staking credentials.

GIVEN the new staking credentials are visible
WHEN the user reads the criteria
THEN they see:

- "Beginner Community Staker: Stake 5 GTC on at least 1 account or have 1 account stake 5 GTC on you."
- "Experienced Community Staker: Stake 10 GTC on at least 2 accounts or have 2 accounts stake 10 GTC on you. If someone stakes 10 GTC on you and you stake 10 GTC on them, that also qualifies."
- "Trusted Citizen: Receive stakes from 5 unique users, each staking a minimum of 20 GTC on you."

#### Product & Design Links:
<links>

#### Tech Details:
- Keep database records of the old credentials for analytics purposes.
- Verify the staking levels and relationships through the staking records in our own DB.

#### Notes/Assumptions:
- Existing credentials should be archived but not deleted for analytics purposes.
- Migrate the existing GTC Community Staking scoring weights to these new credentials and score the deprecated credentials with zero weight.

**Comment by nutrina** [comment]
This will introduce new provider names, this should be kept in mind , the on-chain bitmap also needs to be updated.
