### ISSUE TITLE
Google Analytics Configuration on Gitcoin Passport Dashboard

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1761]
### User Story:
As a Product Manager at Gitcoin Passport,
I want to ensure that Google Analytics accurately tracks visits to `https://passport.gitcoin.co/#/dashboard` and its variants with query parameters,
So that I can gather precise user interaction data to make informed product decisions.

### Acceptance Criteria
GIVEN that the Google Analytics code is properly installed on the website
WHEN a user visits `https://passport.gitcoin.co/#/dashboard`
THEN Google Analytics should register a unique pageview for that URL

GIVEN that the Google Analytics code is properly installed on the website
WHEN a user visits `https://passport.gitcoin.co/#/dashboard/verax`
THEN Google Analytics should register a unique pageview for that specific URL, separate from the base `/dashboard`

#### Tech Details:
1. For Single Page Applications (SPA), implement logic to trigger virtual pageviews on hash changes. Example code snippet for GA4:
`window.addEventListener('hashchange', function() {
  gtag('config', 'GA_MEASUREMENT_ID', {'page_path': location.pathname + location.search + location.hash});
});
`
2. Test the setup using Google Tag Manager's Preview Mode or Google Analytics' Real-Time report.
3. Monitor the Analytics reports post-implementation to confirm data collection.

#### Notes/Assumptions:

- Assumes that the Google Analytics code is already installed on the webpage. If it's not, install it as part of this issue.
- The example code snippet is for Google Analytics 4 (GA4). Adapt the snippet according to the version you're using.

**Comment by digitalmnt** [comment]
I believe I have this configured correctly from within Google Analytics and I ahve updated the analytics tag on the production site. I documented the steps here https://www.notion.so/gitcoin/Google-Analytics-2fb9f14e97d14e028ee90389294faa8a 

From what I'm reading it takes up to a couple days for this data to propogate to google analytics

**Comment by digitalmnt** [comment]
Events were not showing up today as expected. I made an additional update to trigger dashboard events from the the client code via the linked PR.

**Comment by digitalmnt** [comment]
Just waiting on a reivew

**Comment by digitalmnt** [comment]
This was reviewed and nothing real changed besides how events are being propogated. Moving it to ready to deploy since it was already reviewed by @erichfi
