### ISSUE TITLE
Update Fancy New Support Banner with New Design

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1762]
### User Story:
As a Product Manager at Gitcoin Passport,
I want to update our fancy new support banner with the latest design,
So that we can maintain visual consistency across our platform and enhance user engagement.

### Acceptance Criteria
GIVEN that the new design has been approved
WHEN a user visits any page with the support banner
THEN the banner should display the updated design

#### Product & Design Links:
[Link to the new support banner design](https://www.figma.com/file/FOOlLEFaBt87atw6CPkA5P/Passport-S19?type=design&node-id=5220%3A4998&mode=design&t=je74DnxOI38gtFHW-1)

#### Tech Details:

1. Update the HTML and CSS to reflect the new design elements.
2. Ensure compatibility across multiple browsers and screen sizes.

#### Notes/Assumptions:
This update assumes the new design has been finalized and approved.

**Comment by lucianHymer** [comment]
Blocked on review
