### ISSUE TITLE
Enable Testnet On-Chain Passport Access via Special Dashboard Link

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1771]
### User Story:
As a developer,
I want to access a testnet version of my on-chain Passport via a special link,
So that I can test functionalities on Base Goerli and Linea Goerli.

### Acceptance Criteria
GIVEN a user accesses https://passport.gitcoin.co/#/dashboard/testing
WHEN they interact with the onchain features on the dashboard
THEN those features should operate on the specified testnets (Base Goerli, Linea Goerli, and OP Goerli when live #1987).

#### Tech Details:
- This will require changes to the on-chain environment configuration both in the front-end and back-end.
- Restructure how we structure the onchain info file since currently we only have one production for chain.
- When loading the chain info, we are doing that at the top level of the domain so will need to make some corresponding changes.

#### Open Questions:
@lebraat should include a guide in our documentation to explain how to use this feature.

#### Notes/Assumptions:

- This feature is intended for developers.
- The special link is permanent.

**Comment by lucianHymer** [comment]
Blocked on engineer review

**Comment by lucianHymer** [comment]
Remember to update secrets manager
