### ISSUE TITLE
Implementation of New Onchain Sidebar Design

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1777]
### User Story:
As a Passport user,
I want to see a refreshed onchain sidebar with clear states for each chain button,
So that I can easily understand my Passport's status on each respective chain.

### Acceptance Criteria
GIVEN I am on the Passport dashboard,
WHEN I look at the onchain sidebar,
THEN I should see the new design and easily distinguishable states for each chain button.

GIVEN I have completed an action for a specific chain,
WHEN I look at that chain's button on the sidebar,
THEN the state of the button should accurately reflect the status of my action.

#### Product & Design Links:
[Link to the design on Figma](https://www.figma.com/file/FOOlLEFaBt87atw6CPkA5P/Passport-S19?type=design&node-id=5220%3A5959&mode=design&t=XFJ28mVKpqQfgVdZ-1)

#### Tech Details:

- The sidebar should be responsive and maintain its design integrity across different viewport sizes.
- Button states include: Coming Soon, Claim, Claimed, Update, Updated.

#### Open Questions:

- Are there any chains that have unique states or behaviors that need special consideration?
- Is there any animation or transition effect between states?

#### Notes/Assumptions:

- The design has taken into consideration the user feedback from previous versions.
- Backend will provide accurate status to frontend to display the appropriate button state.

**Comment by digitalmnt** [comment]
👋 @erichfi should I include the `Moved` text? I'm seeing it the full sidebar design but not in the individual designs

![Image](https://github.com/gitcoinco/passport/assets/6887938/4bcd9bbb-bc41-44d2-8f49-4e9188cc6f64)
