### ISSUE TITLE
Data pools for Stamps Analyses and score Updates

### ISSUE THREAD

**Issue by stefi-says** [gitcoinco/passport#1786]
### User Story:
As a PM / Data Scientist
I want to able to have clean data on Sybil vs Human stamps and its distribution
So that I can analyse and  take the decision to keep it, drop , increase, decrease the score for every VC

### Acceptance Criteria
GIVEN ...
WHEN ...
THEN ...

#### Product & Design Links:
<links>

#### Notes/Assumptions:
- Given we have a drive with other sybil  list , should we organize this list ( concentrating them on one with labels for where they came from) for this task or should this be a task by itself?

**Comment by Jeremy-Gitcoin** [comment]
@stefi-says I think I have replaced this one with #1792 with more details. If this is from our discussion last week, we can close or delete this one and work that one! :)

**Comment by stefi-says** [comment]
@Jeremy-Gitcoin agreed, lets close this one.
