### ISSUE TITLE
Remove Hypercerts Stamp Feature

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1789]
### User Story:
As a product manager,
I want to remove the current Hypercerts stamp feature,
So that we can mitigate the vulnerability to Sybil attacks and improve the platform's security.

### Acceptance Criteria
GIVEN that the user is on the Passport dashboard,
WHEN the user attempts to interact with or view the Hypercerts stamp,
THEN the stamp should no longer be visible or accessible.

#### Product & Design Links:
<links>

#### Tech Details:

- Deactivate or remove any code that is enabling the Hypercerts stamp feature.
- Ensure that the removal does not negatively affect other functionalities.

#### Notes/Assumptions:
- Assumption is that removing the Hypercerts stamp will not have adverse effects on other system components.
- Keep database records of Hypercerts stamps for analytics purposes.

**Comment by digitalmnt** [comment]
Just waiting on a review
