### ISSUE TITLE
Implement External Cache to Enable Efficient Autoscaling and API Calls

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1790]
### User Story:
As a Backend Developer at Gitcoin Passport,
I want an external Redis cache integrated into our system,
So that I can improve the efficiency and scalability of API calls and overall application performance.

### Acceptance Criteria
**Scenario 1:** API Data Persistence
GIVEN I am a Backend Developer at Gitcoin Passport
WHEN I need to store data temporarily between API calls
THEN I should be able to write this data into an external Redis cache
AND I should be able to retrieve this data in follow-up API calls, irrespective of the ECS task instance serving the request.

**Scenario 2:** Efficient Autoscaling Under High Load
GIVEN I am a Backend Developer at Gitcoin Passport
WHEN the IAM server experiences high CPU and/or memory load
THEN the system should automatically scale up by initiating additional ECS task instances to distribute the load.

**Scenario 3:** Cost-Efficiency Under Normal Load
GIVEN I am a Backend Developer at Gitcoin Passport
WHEN the IAM server is under normal or low load
THEN moderately-sized ECS task instances should be active to minimize CPU idle costs
AND the system should scale up as required when load increases.

#### Product & Design Links:
N/A

#### Tech Details:

- Implement a new, small Redis instance within the Passport repo
- Refactor existing session data caching logic to utilize Redis instead of local memory
- Configure ECS task instances with balanced CPU and memory allocations to optimize costs

#### Open Questions:
None

**Comment by digitalmnt** [comment]
just waiting on review
