### ISSUE TITLE
Deprecate Second Read Replica for Analytics

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1799]
### User Story:
As a Product Manager focused on scaling plural technologies,
I want to deprecate the second read replica for analytics,
So that I can streamline data retrieval and reduce unnecessary operational costs.

### Acceptance Criteria
GIVEN the presence of two read replicas for analytics,
WHEN the feature is successfully deployed,
THEN only one read replica should be active, and the second should be safely deprecated without data loss or performance issues.

#### Tech Details:
- Ensure data consistency is maintained while deprecating the second read replica.
- Monitor performance metrics to ensure that the remaining read replica can handle all the data requirements.

#### Notes/Assumptions:

- The second read replica is currently not providing significant added value and its maintenance incurs operational costs.
- The remaining read replica should be able to handle the existing load without requiring additional resources.
- See #1798 for more context.

**Comment by nutrina** [comment]
Duplicate, this will be handled here: https://github.com/gitcoinco/passport-scorer/issues/440
