### ISSUE TITLE
Update Onboarding Flow Design

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1805]
### User Story:
As a new user,
I want to experience a visually engaging onboarding flow,
So that I feel welcomed and well-guided through the Gitcoin Passport environment.

### Acceptance Criteria
GIVEN a new user has signed up,
WHEN they are directed to the onboarding flow,
THEN they should see the new design, including the animated video and fallback SVG.

#### Product & Design Links:

- Figma File: 
  - [New Onboarding Design](https://www.figma.com/file/FOOlLEFaBt87atw6CPkA5P/Passport-S19?type=design&node-id=5371%3A2208&mode=design&t=oRgFGBZ425pC9RV8-1) 
  - [Mobile Version](https://www.figma.com/file/FOOlLEFaBt87atw6CPkA5P/Passport-S19?type=design&node-id=5429-1595&mode=dev)
- Animated Video: 
[onboarding-hero.webm](https://github.com/gitcoinco/passport/assets/59769856/e8c247d5-f3fa-4683-ab57-714bf0825f91)

- Fallback SVG: 
![onboarding-hero-fallback (1)](https://github.com/gitcoinco/passport/assets/59769856/0e729d7e-3c2c-47e3-9375-c92b4f2b358b)

#### Tech Details:

- Implement new design assets from Octavian's Figma into the existing onboarding flow.
- Ensure compatibility across major browsers.

#### Open Questions:
Any backward compatibility issues to consider?

#### Notes/Assumptions:
Assume modern browser support for animations.

**Comment by digitalmnt** [comment]
A way to detect that the video has loaded https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/readyState
