### ISSUE TITLE
Updated Verax Implementation

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#1809]
### User Story:
As a user,
I want to push only my Passport score to Linea Verax,
So that I can participate in upcoming Linea campaigns without sharing my full Passport details.

### Acceptance Criteria
GIVEN a user navigates to the Linea Verax Dashboard with their Passport.
WHEN they click the 'update' button either on the Verax Dashboard OR within the Verax card on the Sidebar post "Bring Passport Onchain" action.
THEN Schema #107 (Gitcoin Passport Scores v1) should be the only data pushed to both EAS and Linea Mainnet.

**Changes:**
1. **UI Changes:**
  - [x] Rename the button 'Bring stamps onchain' to 'Bring Passport onchain' across all supported chains.
  - [x] Update Sidebar 'cards' as follows:
    - [x] For Optimism: Append "(Score & Passport)" next to "Ethereum Attestation Service."
    - [x] For Linea: Append "(Score only)" next to "Verax, Ethereum Attestation Service."
2. **Functional Changes:**
  - [x] Modify the 'update' button in both Verax Dashboard and Sidebar to push only the first schema to EAS & Verax. It should only push the score and the scorer ID, not the full Passport bitmap & credentials.
3. **Content Changes:**
  - [ ] Align the language on the [Verax Dashboard](https://passport.gitcoin.co/#/dashboard/verax) to be consistent across all states ('update', 'already pushed', and 'Push to Verax'). Specific language details are outlined in the original request.

#### Open Questions:

- What are the performance implications of pushing only specific parts of the Passport?
- How will this change interact with existing data on Verax?

#### Notes/Assumptions:

- Assumes that the user has sufficient ETH bridged to Linea Mainnet to cover network fees.
- Assumes that the user is aware of the $2 mint fee for the Gitcoin treasury.

**Comment by nutrina** [comment]
@Jeremy-Gitcoin @erichfi 

How shall we determine and display the on-chain status?

I guess that indicating for a user that bringing stamp on-chain only makes sense if he improved his score, or if onchain attestation is to old.

But how should we show the onchain status in the UI? Maybe a green dot next to the score?

**Comment by nutrina** [comment]
following up on my previous comment, @Jeremy-Gitcoin  can you please confirm these acceptance criteria for determining the on-chain state:

**GIVEN** I am a passport user, with a score > 0
**AND** I have not yet written the score on-chain on Linea
**THEN** I want to see the "Push to Verax" button in the dashboard
**AND** the "Go" button in the sidebar

**GIVEN** I am a passport user, with a score > 0
**AND** I have already written my score on-chain on Linea previously
**AND** my current score is <= than the one on Linea
**THEN** I want to see the "Up to date" label on the button in the dashboard and in the sidebar
**AND** both buttons should be disabled

**GIVEN** I am a passport user, with a score > 0
**AND** I have already written my score on-chain on Linea previously
**AND** my current score is > than the one on Linea
**THEN** I want to see the "Update" label on the button in the dashboard and in the sidebar
**AND** both buttons should be enabled

**Comment by Jeremy-Gitcoin** [comment]
@nutrina Agree with @erichfi update to the Acceptance criteria. We do NOT have the green dot for the stamps since they are technically not onchain with Linea. I think we're fine with the visual indications being the button state in the new Verax component + the sidebar
