### ISSUE TITLE
[BUG]  Passport connection broken on Guild.xyz

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#1810]
The Gitcoin passport connection on guild is broken. Users cannot qualify for the OG Maxis role. 

![image](https://github.com/gitcoinco/passport/assets/88308638/45837f39-ed8e-4292-8f7c-3f7b161520e0)
![image](https://github.com/gitcoinco/passport/assets/88308638/6d7ca8bf-d7d7-4893-bdbb-37e74abb2e3b)

To reproduce, go to https://guild.xyz/gitcoinpassport

**Comment by digitalmnt** [comment]
@jesuloluwao and @erichfi The error is being thrown within Guild's internal api located [here](https://docs.guild.xyz/guild/guides/guild-api-alpha) I pulled down their UI but it makes requests to the same service which does not appear to be open source. Do you all by chance have a contact at Guild I could reach out to? Happy to work with them to resolve the issue within the guild system. 

I also monitored the scorer api's logs while triggering the error from Guild's UI and was unable to see anything come through which continues to point to the error being within Guild's system

**Comment by jesuloluwao** [comment]
@lebraat might have an idea

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/66168?view=List

**Comment by digitalmnt** [comment]
@jesuloluwao  This should be resolved now. It looks like it was a rate limiting issue that was fixed this morning.

**Comment by nutrina** [comment]
This is solved. It turned out to be a rate limiting issue for Guilds API Key
