### ISSUE TITLE
Unintentional Wallet Signature Prompt on Session Expiry in passport.gitcoin.co

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1812]
**Overview**
When a user's session expires in the passport.gitcoin.co app, they are automatically prompted to sign a wallet signature upon their return. This could lead to unintentional or blind signing, posing a security risk.

**Steps To Reproduce**

1. Log into passport.gitcoin.co.
2. Allow session to expire (do not manually log out).
3. Return to passport.gitcoin.co.
4. Observe that a wallet signature prompt appears automatically.

**Observed  behavior**
The system immediately prompts the user to sign a wallet signature for reauthentication when they return to the site after their session has expired.

**Expected behavior**
The user should be directed to the splash page to click the 'Sign In with Ethereum' button before seeing the wallet signature prompt. This additional step makes the reauthentication process intentional and secure.

**Screenshots**

**Additional context**

- **Browser Information:** This behavior has been observed across multiple browsers.
- **User Feedback:** Users have noted that the immediate prompt feels abrupt and have expressed security concerns.
- **Security Considerations:** Prompting for a signature immediately upon return may encourage users to blindly sign messages, which is not good security practice.

**Comment by lucianHymer** [comment]
Blocked on reviewing options w/ other engineers

**Comment by lucianHymer** [comment]
To review this, you can test it out by changing the connected account in your wallet. This should trigger the same mechanism which kicks you back to the home page.
