### ISSUE TITLE
GG19 Score Update for Enhanced Accuracy

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1817]
### User Story:
As a Passport user,
I want the scoring system to accurately reflect the latest scoring metrics and user behaviors,
So that my identity and contributions are represented more precisely.

### Acceptance Criteria
GIVEN the current scoring algorithm,
- THEN Google, LinkedIn, and Civic Captcha point values should be decreased as per the GG19 Score Changes.
- THEN specific outdated metrics like GrantsStack3Projects, GrantsStack5Projects, and others mentioned in the GG19 Score Changes should be entirely removed.
- THEN point values for Lens, ethPossessionsGte#1, TrustaLabs, Holonym, and CivicUniquenessPass should be increased as specified in the GG19 Score Changes.

#### Product & Design Links:

- [Score Change Specs](https://docs.google.com/document/d/1KVwf1W0baIg2CRI5iiZ6qPIgPqGXxUV8u0GBYlJ4GWI/edit?usp=sharing)
- [Rescoring Procedure](https://www.notion.so/gitcoin/Staging-Production-Release-Process-dd19f52007cf401892e22f81748ba89f?pvs=4#b4876428681b4278be72c7c689a31a25)

#### Tech Details:

- Backend task: Update scoring algorithm values as detailed in the GG19 Score Changes.
- Ensure frontend displays are in sync with these changes. If any discrepancies exist, frontend adjustments might be necessary.
- Post-deployment action: Run the rescoring command.

#### Notes/Assumptions:

- It is expected that genuine users might notice a slight reduction in their scores due to the decrement of Google and LinkedIn point values.
- The increment in TrustaLabs points aims to offset this decrease, ensuring a more balanced reflection of user contributions and identity.

**Comment by nutrina** [comment]
When these changes are pushed to production, one will also need to run the rescoring command:  https://www.notion.so/gitcoin/Staging-Production-Release-Process-dd19f52007cf401892e22f81748ba89f?pvs=4#b4876428681b4278be72c7c689a31a25


The total running time for this would be ~ 4h

**Comment by lucianHymer** [comment]
In the doc, the score was removed for the numGrants#25. But the numGr14#1 is the one we actually should've dropped. So we're over by 1.41 with the current values (sum is 101.41)

**Comment by lucianHymer** [comment]
Haha interesting, I guess you've claimed more points than it's now worth, and we haven't done a rescore! I can change it so that it shows 0 if the result is < 0. But it should only affect things in the brief period between the release and the rescore.
