### ISSUE TITLE
Block ecc.eth ENS names from the ENS stamp

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#1833]
### User Story:
As a Passport Product Manager,
I want to restrict users with ENS names from the domain "ecc.eth" and its associated subdomains (e.g., *.ecc.eth) from obtaining the ENS stamp credential,
So that I can maintain the integrity of our stamp system and prevent potential misuse.

### Acceptance Criteria
GIVEN I am on passport.gitcoin.co,
WHEN I attempt to obtain the ENS stamp credential using a name from the domain "ecc.eth" or its associated subdomains,
THEN I will be denied the ENS stamp.

Additionally, a failure message should be displayed to the user stating: "Apologies! ENS subdomains from OptiNames, specifically those under `ecc.eth`, are not eligible for the ENS stamp. We appreciate your understanding as we strive to uphold the integrity of our platform. If you have other valid ENS domains, please proceed with those."

#### Tech Details:
For more information on the service that provides these free ENS subdomains, refer to: https://optinames.xyz/

#### Notes/Assumptions:

- It's essential to ensure that only valid and verified ENS names are granted the ENS stamp to uphold the platform's credibility.
- Users might not be aware of the restriction and could benefit from the displayed failure message.

**Comment by lucianHymer** [comment]
So these names are free because they're using an offchain resolver for the ecc.eth record on mainnet.

This is something anybody could do, they just need to deploy the offchain resolver contract and register the root ENS name (e.g. ecc.eth).

So, I think we should instead restrict our ENS stamp to only names that use the default public ENS resolver at 0x231b0Ee14048e9dCcD1d247744d114a4EB5E8E63.

**Comment by lucianHymer** [comment]
Alright I was able to do what I described above.

How do you guys feel about this error message?

Apologies! Your primary ENS name uses an alternative resolver and is not eligible for the ENS stamp. We appreciate your understanding as we strive to uphold the integrity of our platform. If you have another ENS name which uses the public ENS resolver, you can claim this stamp with that as your primary ENS name.

**Comment by Jeremy-Gitcoin** [comment]
@lucianHymer Good with the change to restrict to just the ENS resolver. 

Let's simplify the error message:
"Apologies! Your primary ENS name uses an alternative resolver and is not eligible for the ENS stamp."

I think we can arm support with the details and they can answer any questions if they really come up!
