### ISSUE TITLE
[SC Review] Fix issues for GitcoinPassportDecoder

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1835]
### Overview
Link to the relevant section of the review document: https://github.com/thelostone-mc/eas-proxy/blob/review/review.md#gitcoinpassportdecoder

- [ ] fix the **low priority** issues
- [ ] TO BE CLARIFIED: consider merging in the changes from https://github.com/gitcoinco/eas-proxy/pull/40 which add the helper for the score attestation

### Acceptance Criteria
GIVEN ...
WHEN ...
THEN ...

#### Product & Design Links:
n.a.

#### Tech Details:
n.a.

#### Notes/Assumptions:

Regarding the **high priority** issues, this are probably not a critical point atm:
- in our current setup, the number of stamp providers that we have is < 100. This means, that all the providers that we have will be encoded in only 1 element of the providers array in the attestation
- it is highly unlikely that we will reach more than 256 providers anytime soon, we are not in a race to increase our number of providers
- we are revamping some of our stamps, which has the effect that we are removing some providers and introducing new ones. This is precisely why we have introduced a versioning for the stamps, for each version we will have a specific list of providers that can be stored in a passport attestation and a specific bitmap indicating how the bits in the providers array are allocated
- so it seems that in the nested for-loop implementation in the `getPassport` implementation, the outer loop will never loop more than 1 element for the foreseeable future. The possibility to have more elements in the array still exists, but it is not yet on the horizon, and by the time we get to that point, there will probably be things to consider as well
- regarding the suggestion `L167: as opposed to hardcoding it to 256 , could we instead have a provider count variable / something else equivalent?`
  - this is not necessary, as that count would be equal to the length of any of the other arrays (`hashes`, `issuanceDates`, `expirationDates`), and in the current line 170 we already exit the loop if any of those lengths is reached:
```sol
        // Check to make sure that the hashIndex is less than the length of the expirationDates array, and if not, exit the loop
        if (hashIndex >= expirationDates.length) {
          break;
        }
```

#### Open Questions:
- shall we also add additional validations when getting a passport like:
  - check for revocation status
  - check for expiry of attestation
  - see related changes here (wip): https://github.com/gitcoinco/eas-proxy/pull/40
-shall we also add helpers to get the score for a given ETH address:
  - https://github.com/gitcoinco/eas-proxy/pull/40

**Comment by digitalmnt** [comment]
**Low**
- `L20`: Mark the visibility of IEAS as `public` / `private` and then add a external function to read that
- `Pausable` is imported, initialized, but never used. Recommendation: remove Pausable
- `L58`: `setEASAddress` can be marked as external
- `L58`: Emit event `setEASAddress`. Add zero check
- `L66`: `setGitcoinResolver`  can be marked as external
- `L67`: Emit event `setGitcoinResolver`. Add zero check
- `L74`: `setSchemaUID`  can be marked as external
- `L74`: Emit event `setSchemaUID`. Add zero check
- `L82`: `addProvider` can be marked as external
- `L82`: Emit event `addProvider`. Add zero check
- `L95`: `getAttestation` should be marked as external and function logic should be moved into internal function to call it in line 116
- `L90`: Emit event `createNewVersion`.
- `L106`: `getPassport`  can be marked as external
- `L146`, `L147`: Store .length as variables as use them in the for loop to save gas

**Comment by digitalmnt** [comment]
I also added a getter to return the provider array for the iAM server.

@nutrina I think these would be great to add. Happy to add them on Monday if you don't get to it

shall we also add additional validations when getting a passport like:
- check for revocation status
- check for expiry of attestation see related changes here (wip): https://github.com/gitcoinco/eas-proxy/pull/40
-shall we also add helpers to get the score for a given ETH address:
https://github.com/gitcoinco/eas-proxy/pull/40

**Comment by nutrina** [comment]
@digitalmnt regarding pausable, yes you are right, let's keep that
