### ISSUE TITLE
Gitcoin Identity Staking System Documentation Enhancement

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1855]
### User Story:
As a developer, product manager, or auditor involved with the Gitcoin Passport project,
I want comprehensive and clear documentation for the Identity Staking smart contract,
So that I can fully understand, maintain, enhance, and audit the system, including its use cases, permissions, roles, responsibilities, staking/unstaking mechanisms, and slashing processes.

### Acceptance Criteria
GIVEN a need for in-depth understanding and operational clarity,
WHEN I access the documentation in the Gitcoin repository,
THEN I should find a detailed guide that includes:

- Complete functionalities and features from tickets #1837 and #1838.
- Detailed descriptions of use cases, permissions, roles, and responsibilities within the Identity Staking system.
- In-depth explanation of staking/unstaking mechanisms and slashing processes, including contested slashing decisions.
- Guidelines for future integrations, such as implementing voting strategies and using staked GTC for voting on proposals.

#### Product & Design Links:
[Existing Slashing Mechanism Documentation](https://github.com/gitcoinco/eas-proxy/blob/1839-merkle-payout/docs/07-identity-slashing.md)

#### Tech Details:

- Technical specifications, smart contract addresses, ABIs, and integration points.
- Rationale behind design decisions, operational flows, and potential edge cases.

#### Open Questions:

- Should the staking contract be moved to its own repository, or integrated into an existing one?
- How can we streamline the documentation for clarity and ease of understanding, especially for auditors?

#### Notes/Assumptions:

- Assume familiarity with Ethereum smart contracts and basic staking mechanisms.
- Ensure the documentation is accessible and up to date, reflecting changes in repository locations or structures.

**Comment by nutrina** [comment]
Have broken out the integration with Governor here: https://github.com/gitcoinco/passport/issues/1864

**Comment by digitalmnt** [comment]
I went ahead and picked up https://github.com/gitcoinco/passport/issues/1838 first since this ticket depends on it.

**Comment by digitalmnt** [comment]
The linked PR includes the updated docs. In order to validate array's vs enumerable set I did some testing on this [branch](https://github.com/gitcoinco/eas-proxy/tree/enumerable-set-gas-test) it could be useful when building out the final contracts

**Comment by digitalmnt** [comment]
waiting on review

**Comment by digitalmnt** [comment]
Here is a link to the new repo with the initial contract https://github.com/gitcoinco/id-staking-v2
