### ISSUE TITLE
[BUG] Linea Onchain stamp show 01/01/1970

### ISSUE THREAD

**Issue by YukiPL** [gitcoinco/passport#1858]
**Overview**
 Linea Onchain stamp show 01/01/1970 instead of the actual date.

**Steps To Reproduce**
1. Go to passport.gitcoin.co
2. Click on 'Bring Passport Onchai'
3. Click on Linea, put stamps onchain

**Observed  behavior**
The date for onchain stamps are wrongly displayed as 01/01/1970

**Expected behavior**
It should shows the date the stamps are being put onchain.

**Screenshots**
![image](https://github.com/gitcoinco/passport/assets/92294305/f75f1872-f33e-468d-9020-e2b07e5e38ef)

**Additional context**
https://linea.easscan.org/address/0x69ce8d79dfa9d025000e589af0331fec12048111

**Comment by YukiPL** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/66644?view=List

**Comment by lucianHymer** [comment]
Hey! This is strange, but we're dropping those dates from the UI anyways with the release that's happening tomorrow.
