### ISSUE TITLE
Enhanced Coinbase Verification with Dual Criteria

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#1889]
### User Story:
As a Gitcoin Passport user,
I want a clear and concise method to verify my Coinbase account and associated identity attestation,
So that I can confidently prove my identity and enhance the trustworthiness of my digital passport.

### Acceptance Criteria
GIVEN I am engaging with the Coinbase stamp in my Gitcoin Passport,
WHEN I proceed with the verification,
THEN the system should verify that I have a Coinbase account and check if my ETH account on Base has a Coinbase Identity Verification attestation.

#### Product & Design Links:
- Redesign the Coinbase stamp interface to support the new verification requirements.
- Sidebar subheader: "Verify Your Coinbase Account & Associated Identity".
- Direct link for identity verification: Coinbase Identity Verification Portal.

#### Tech Details:

- Deprecate the existing Coinbase credential while preserving its data for analytics.
- Introduce a new credential that verifies:
  a. The existence of the user’s Coinbase account.
  b. The presence of a Coinbase Identity Verification attestation linked to the user’s ETH account on Base.
- Use the Coinbase account ID as a unique context hash for verification.
- Credential Name: "Coinbase Account & Identity Check"
- Subtitle: "Dual Verification Credential"
- Attestations Issuer = 0x357458739F90461b99789350868CD7CF330Dd7EE (verifications.coinbase.eth) 
- Verified Account Schema - https://base.easscan.org/schema/view/0xf8b05c79f090979bf4a80270aba232dff11a10d9ca55c4f88de95317970f0de9
- Verified Country Schema - https://base.easscan.org/schema/view/0x1801901fabd0e6189356b4fb52bb0ab855276d84f7ec140839fbd1f6801ca065
- Attestation Contract - https://basescan.org/address/0x357458739F90461b99789350868CD7CF330Dd7EE

#### Open Questions:

- How do we ensure a seamless integration of the new verification process with the existing Passport system?
- What measures are necessary to guide users through the updated process effectively?

#### Notes/Assumptions:
- Assumes that users require a straightforward, easy-to-understand verification process.
- Assumes the need to maintain data integrity and security throughout the transition to the new system.

**Comment by nutrina** [comment]
@Jeremy-Gitcoin: this should be pretty straight forward, but it will be an EVM stamp

This means that we should probably not include this new stamps in the old "Coinbase" platform / group as the old one is OAuth based (it is not clear how difficult it would be to mix a EVM stamp with an OAuth 1, considering also the 1-click verification flow)

But getting this stamps could be part of the 1-click authentication flow.
We would use the EAS off-chain indexer (graphql).

Doing deduplication based on the coinbase account will not be possible.

**Comment by digitalmnt** [comment]
@erichfi how many point should we assign to this new credential?

**Comment by digitalmnt** [comment]
@erichfi Here is a screenshot of the stamp and the description I added clarifying how we are verifying the user's account. These are the links that I added [Coinbase Onchain Verification](https://help.coinbase.com/en/coinbase/getting-started/getting-started-with-coinbase/id-doc-verification)
, [Ethereum Attestation Service](https://base.easscan.org/schema/view/0xf8b05c79f090979bf4a80270aba232dff11a10d9ca55c4f88de95317970f0de9)

The way I have it setup the verification is only checking for the existence of `Verified Account Schema attestation`. Its easy to add an additional check for `Verified Country Schema` but I wasn't sure if we wanted to include that as part of the verification.

![Image](https://github.com/gitcoinco/passport/assets/6887938/00d9a303-5785-4a1a-8f53-64c004633743)

**Comment by nutrina** [comment]
@erichfi  I have made the changes

And this link:  _Coinbase Onchain Verification_ points now to  https://www.coinbase.com/onchain-verify


![Image](https://github.com/gitcoinco/passport/assets/8137830/f491829e-90b7-4eff-962c-746e709e6a86)

**Comment by nutrina** [comment]
Waiting for feedback before merging to main

**Comment by nutrina** [comment]
@erichfi  I've changed it according to our discussion:



![Image](https://github.com/gitcoinco/passport/assets/8137830/c77d98be-c123-4435-a117-8a21a99c8567)

**Comment by nutrina** [comment]
@erichfi , here is the next iteration



![Image](https://github.com/gitcoinco/passport/assets/8137830/cf17ef03-a562-44c6-ab6b-53209a04a2a0)
