### ISSUE TITLE
Automated Update of Gitcoin Stamp Post-Grants Round

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1891]
### User Story:
As a Product Manager at Gitcoin Passport,
I want to implement a simplified function in our Django app that can be manually executed to update the Gitcoin stamp after every grants round,
So that I can efficiently recognize legitimate contributions from the latest round in the Gitcoin Passport stamp criteria.

### Acceptance Criteria
GIVEN a grants round operated by Gitcoin has concluded,
WHEN a team member executes the new Django function,
THEN the Gitcoin stamp in the Gitcoin Passport should automatically update to include and recognize the contributions from that round, after filtering contributions based on specific criteria (such as unique humanity threshold and deduplication script results).

#### Tech Details:

- The function should retrieve contribution data from the allo indexer and transfer it to the scorer service.
- Only include grants rounds operated by Gitcoin by specifying on-chain IDs of those rounds.
- Run @stefi-says’s deduplication script on these contributions to filter out participants involved in any duplication event. Convert @stefi-says’s Jupiter notebook script into a Django Python function. >>> https://drive.google.com/file/d/19LpNdaUbBbnIOfY-_9OJ6iY8muKg5zn1/view?usp=sharing
- Exclude contributions involving passports with scores below the unique humanity threshold or involved in deduplication events.
- After filtering, incorporate the remaining contributions into the dataset against which we check conditions for Gitcoin stamp credentials.

#### Open Questions:
Are there any potential performance impacts when executing this new function?

#### Notes/Assumptions:

- This feature assumes that the deduplication script and humanity threshold are reliable indicators of legitimate contributions.
- The process is assumed to be executed manually to maintain control over when the updates are applied.

**Comment by stefi-says** [comment]
hey ! here is the notebook with the process to find the address that are not eligible. I cleaned it and commented it to make it clear but if someone have doubts, just let me know! @erichfi 
https://drive.google.com/file/d/19LpNdaUbBbnIOfY-_9OJ6iY8muKg5zn1/view?usp=sharing

**Comment by nutrina** [comment]
First, it is difficult to implement a way to import this data from the Django admin.
Hence we propose the following process:

1. The data **team / PMs** provide the data for the new Grants Round (donations & squelched addresses) to the engineering team, by uploading this data in a google drive folder (we already have a folder where we keep historical data).

2. Create a ticket for the **engineering team** to import the data into the scorer DB

**Notes:**  it will probably be best to import all the donation records (and do not filter out any squelched addresses), and have different table for squelched addresses in a round. We will filter out the squelched addresses before checking donations from a particular address.
