### ISSUE TITLE
Collecting Links to Linea Contracts, Schemas, and Verax Portal ID

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1893]
**Objective:**
To efficiently gather links to the Linea contracts, EAS schemas, and Verax portal ID related to Gitcoin Passport.

**Timebox:**
25 minutes

**Details:**
- Find and list the links to the Linea contracts and EAS schemas for Gitcoin Passport.
- Include the Verax portal ID for easy access.

**Expected Outcome:**
A concise list of links for Linea contracts, EAS schemas, and the Verax portal ID, providing a quick reference for technical team members and developer relations.

**Comment by lucianHymer** [comment]
The source of truth for this info is [here](https://github.com/gitcoinco/eas-proxy/blob/main/deployments/onchainInfo.json)!

```
GitcoinAttester: 0xBC778313E52b1184A15D163b5d3a72AEF8d510A2
GitcoinVerifier: 0xc94aBf0292Ac04AAC18C251d9C8169a8dd2BBbDC
GitcoinResolver: 0x0a774AECE542a1A819107Eb3a06E9D515C67257a
GitcoinVeraxPortal: 0xCAa9E817f02486cE076560B77A86235Ef91c5d5D

EAS: 0xaEF4103A04090071165F78D45D83A0C0782c2B2a

EAS Schemas: 
  passport: 0x69b9d63ff6b161097cb4930e197a722bcf423f832d4e4cd3692449d5a1e1319f
  score: 0x4da1eaac6346b8b79a705e3898a308062ca607f56c07762ef7b7ff8a7661843c
  
Verax AttestationRegistry: 0x3de3893aa4Cdea029e84e75223a152FD08315138

Verax Schemas: 
    passport: 0x501e6fcade7e3483d0ae7fcfebb732907ebda12b209f5116e52c02697062a50e
    score: 0x01f031da36192c34057c764239eb77bb6ec8ebfb808f72a7bb172f37a5bec31f
```
