### ISSUE TITLE
[BUG] Twitter OAuth Issue on Metamask Mobile iOS

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1901]
**Overview**
Users are experiencing an issue with Twitter OAuth on Metamask mobile for iOS. When attempting to authenticate with Twitter, the process does not complete, leaving users stuck on a 'verifying' screen with a spinning indicator. This issue prevents iOS users from completing the necessary authentication steps through Twitter via Metamask.

**Steps To Reproduce**

1. Open Metamask mobile app on an iOS device.
2. Navigate to the Twitter stamp.
3. Initiate the Twitter stamp OAuth process.
4. Observe the lack of response beyond the 'verifying' screen with a spinning indicator.

**Observed  behavior**
When users on Metamask mobile for iOS attempt to use Twitter OAuth, they encounter a persistent 'verifying' screen with a spinning indicator. The process does not progress beyond this point, preventing successful Twitter authentication.

**Expected behavior**
The expected behavior is for the Twitter OAuth process to proceed smoothly, leading to a successful authentication and redirect back to the application with the appropriate credentials or confirmation.

**Screenshots**

**Additional context**
- Issue observed on Metamask mobile for iOS.
- This issue may relate to specific security or pop-up settings in the iOS version of Metamask.

**Comment by lucianHymer** [comment]
See https://github.com/gitcoinco/passport/issues/2008
