### ISSUE TITLE
[BUG] Staked GTC is not visible on dashboard

### ISSUE THREAD

**Issue by YukiPL** [gitcoinco/passport#1915]
**Overview**
Users who staked GTC in Season 19 are not able to view them on the staking dashboard. 

**Steps To Reproduce**
1. Go to https://www.staking.passport.gitcoin.co/
2. Click on stake
3. Once successfull, it shows '0'

**Observed  behavior**
Staking dashboard is showing '0' staked GTC after users successfully staked

**Expected behavior**
Users should be seeing the amount of GTC that they staked and able to verify the GTC staking stamp on Passport.

**Screenshots**
![image](https://github.com/gitcoinco/passport/assets/92294305/3cec5bb2-6ded-4451-ba40-528a56b9cb35)

https://etherscan.io/tx/0x4a84e56076d3364a600e34381c8d735cd4d83461dd239ec93835c2557ab97950

**Additional context**
Could be relevant, console log is buzzing with errors. getting a 404 for ethgasstation.info
![image](https://github.com/gitcoinco/passport/assets/92294305/cf3e4507-8a6c-47b6-883d-6f3551f002f8)

**Comment by lucianHymer** [comment]
Looks like the indexer did not pick this up

**Comment by lucianHymer** [comment]
This user's stake has now been indexed, so the UI should be working for them

**Comment by digitalmnt** [comment]
Yeah it looks like the indexer stopped indexing but didn't throw an error of any kind. Ideally we can determine where/why it stopped indexing and fix that, or throw more errors causing the indexer to crash restart

**Comment by digitalmnt** [comment]
I've added additional checks for the websocket connect that should trigger a restart of the service and a new connection. We've also re-enabled the pager duty alerts so that if the connection is lost someone will investigate immediately
