### ISSUE TITLE
Implement Gradient Design in Score Bar for Enhanced Dashboard Aesthetics

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1927]
### User Story:
As a user of the Gitcoin Passport Dashboard,
I want to see a visually appealing score bar with a gradient design,
So that I can enjoy an enhanced and aesthetically pleasing user interface.

### Acceptance Criteria
GIVEN I am a user accessing the Passport Dashboard,
WHEN I view the score bar,
THEN I should see a gradient design that aligns with the specifications in the provided Figma designs.

#### Product & Design Links:
[Link to Figma Designs](https://www.figma.com/file/FOOlLEFaBt87atw6CPkA5P/Passport-S19?type=design&node-id=5220%3A4998&mode=design&t=f1WA4aruuez2ZV0J-1)

#### Tech Details:
- Ensure compatibility with current front-end technologies used in the Passport Dashboard.
- Test across multiple browsers and devices for consistent rendering.

#### Open Questions:
- Are there specific color codes or gradient ratios in the design that need special attention?
- Are there any accessibility considerations with the new design?

#### Notes/Assumptions:
- Assumes that the dashboard's current layout and functionality remain unaffected by the design update.
- The gradient should not impact the readability of the score bar.

**Comment by lucianHymer** [comment]
Or maybe something like this? https://css-tricks.com/my-struggle-to-use-and-animate-a-conic-gradient-in-svg/
