### ISSUE TITLE
Onchain Function to Return Exact Humanity Score Within 90-Day Validity

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1928]
### User Story:
As a smart contract developer,
I want an onchain function that retrieves a user's exact humanity score,
So that I can use up-to-date and accurate data for onchain logic.

Depends on: #1924

### Acceptance Criteria
GIVEN a user's onchain passport with a humanity score,
WHEN I query the score using the `getScore(address user)` function in the `GitcoinPassportDecoder` SC,
THEN the exact score should be returned if it's issued within the last 90 (actually within the `maxScoreAge` attribute) days
AND the score value is returned as an `uint256`

GIVEN I am the owner of the `GitcoinPassportDecoder` SC
WHEN I call the `setMaxScoreAge(uint256 _maxScoreAge)` function
THEN the new `_maxScoreAge` value is set 
AND this value is applied for all following calls to the `getScore(address user)` function to check for the max age of the score

#### Product & Design Links:
<links>

#### Tech Details:
- Implementation of an onchain function to fetch the humanity score
- Logic to ensure the score is within the 90-day validity window
- requires a `getScore(address user)` implementation in the `GitcoinPassportDecoder` SC
   - this function should use the `getCachedScore(address user)` from the GitcoinResolver SC
   - if a cached scored does not exist it should fall back to reading the score from the attestation
- drop the current `function getScore(address userAddress) external returns (Score memory);` in the `IGitcoinPassportDecoder`
- `getScore(address user)` needs to be added to `IGitcoinPassportDecoder` interface
- open point:
  - does this affect the precision of the score, given that in the Score attestation and in the Score cache we would use different precisions? We should probably define what is the precision we would like to use long-term
- update the documentation: https://github.com/gitcoinco/eas-proxy/blob/main/docs/05-querying-passport-attestations-onchain.md

#### Notes/Assumptions:
Assumes all scores are stored onchain with issuance dates.

**Comment by nutrina** [comment]
Waiting for review

**Comment by nutrina** [comment]
Security gap related to public members and inheritance:

https://ethereum.stackexchange.com/questions/79417/what-is-an-example-of-when-a-solidity-variable-must-not-be-public-where-it-woul

**Comment by nutrina** [comment]
This is currently only pending the docs update & review
After that it is ready  to deploy.

**Comment by nutrina** [comment]
This PR already contains the deployment of the SC to `optimism-sepolia` (see this commit ): af3bf8d7b42d63ca208f11030290de772de7526e

Checklist for deployment to main nets:
- [ ] for each network
  - [ ] upgrade the verifier (if required, for the withdraw function)
  - [ ] upgrade resolver
  - [ ] set resolver score schema
  - [ ] deploy decoder
  - [ ] setup decoder & write provider information to chain
