### ISSUE TITLE
Update Loading Animation/Spinner in Gitcoin Passport App

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1947]
### User Story:
As a Gitcoin Passport app user,
I want to see a smoother and more engaging loading animation when the app is loading,
So that I can have a more pleasant and visually appealing experience while waiting for the app's content to load.

### Acceptance Criteria
GIVEN I am a user opening the Gitcoin Passport app,
WHEN the app is loading,
THEN I should see the new, fluid loading animation instead of the current jumping icon.

#### Product & Design Links:
![passport-loader](https://github.com/gitcoinco/passport/assets/59769856/aec86bee-82b5-4abc-b623-db957d2fade8)

#### Tech Details:
- The new animation should be optimized for performance to ensure it does not negatively impact load times.
- Compatibility with all supported devices and screen sizes must be maintained.

#### Notes/Assumptions:

- The update is aimed at enhancing user experience and aligning with the overall aesthetic of the app.
- The current loading times should not be adversely affected by the introduction of the new animation.
- All existing functionalities of the app remain unaffected by this change.

**Comment by lucianHymer** [comment]
Blocked waiting on some feedback from Octavian

**Comment by lucianHymer** [comment]
Feedback: Bigger logo, drop the "Loading" text
