### ISSUE TITLE
[BUG] Unable to claim Lens Stamp

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#1949]
A number of users have reached out about not being able to claim lens stamp. e.g

 @academia.lens
0xB00C0De4E355686564641A7E3082d65fEADF6F34

**Link:** [Conversation with bkjhwatern000@gmail.com](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/67346)

**Customer:** [bkjhwatern000@gmail.com](https://app.intercom.com/a/apps/xaafeyri/users/64f6e94c539bb2abae7d87e6/all-conversations)
**Customer ID:** 8685a333-4e78-4fde-ad7f-4f19a3a51297
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/67346) when this issue is closed.

**Comment by digitalmnt** [comment]
Hi @jesuloluwao it doesn't look like 0xB00C0De4E355686564641A7E3082d65fEADF6F34 is the current owner of @academia I was able to see it for sale on rarible https://rarible.com/token/polygon/0xe7e7ead361f3aacd73a61a9bd6c10ca17f38e945:9888080991470448255578759258513136401989109607392321820707410587118627538027 where it says that it is currently owned by [0x0636F974D29d947d4946b2091d769ec6D2d415DE](https://polygonscan.com/address/0x0636F974D29d947d4946b2091d769ec6D2d415DE). I was also able to check its ownership via the smart contract at https://polygonscan.com/address/0xe7E7EaD361f3AaCD73A61A9bD6C10cA17F38E945#readProxyContract
![Image](https://github.com/gitcoinco/passport/assets/6887938/38c0b808-801a-4b18-a810-e49b3c67c6d1) and verify the results against my lens handle

**Comment by digitalmnt** [comment]
happy to check other example!

**Comment by jesuloluwao** [comment]
Hey @digitalmnt @erichfi here's another user who's unable to claim the stamp
Wallet: 0x9f75582d2be13b5ee454161ee394daada8b39efa.
lens: 0xflypeztic
I checked Rarible and it looks like they do own it. https://rarible.com/token/polygon/0xe7e7ead361f3aacd73a61a9bd6c10ca17f38e945:106914592472621001604108012913312789298469069131428100411430919707391616823854. Also checked the same from the smart contract like you did

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/67764?view=List

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/66805?view=List
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/67041?view=List

**Comment by digitalmnt** [comment]
just waiting on review
