### ISSUE TITLE
[BUG] Unable to claim Civic stamp

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#1963]
Some users reported that they are unable to claim the civic stamp. Particularly the Captcha.
![image](https://github.com/gitcoinco/passport/assets/88308638/910961be-8e08-4086-85c0-83723c1d6615)

I could see from here https://civic.me/0x68a01835ba7073cD2efBbF7741Bf6D5B1B00e927 that they got the civic captcha but they can't get the stamp

**Link:** [Conversation with andresorte75@gmail.com](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/66548)

**Customer:** [andresorte75@gmail.com](https://app.intercom.com/a/apps/xaafeyri/users/64f25c567e7204709f1d6244/all-conversations)
**Customer ID:** df17ed5d-063b-424c-98ec-e480d601482c
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/66548) when this issue is closed.

**Comment by jesuloluwao** [comment]
Hey @lucianHymer how come on Civic website, it still appears as a valid stamp? How would the users know to reclaim their stamp? e.g https://civic.me/0x7bA350d775969325BedBD8f43e24d97Be0E42B3f

**Comment by lucianHymer** [comment]
Hey @jesuloluwao I'll ask the Civic team if there's a way to see this in their UI.

But, the API reports it as expired and our UI will tell the user that it is expired if they look at the detailed response.

**Comment by jesuloluwao** [comment]
Hello @lucianHymer Also, for this user 0x6d1dCfD657961B9481050EbB78eEa0b58208be75 they are unable to claim the stamp but their civic passes are not up to 90 days (https://civic.me/0x6d1dCfD657961B9481050EbB78eEa0b58208be75)

**Comment by lucianHymer** [comment]
@jesuloluwao Civic said they are considering adding this to the UI at civic.me, but the info is not there yet.

They said that users should be able to see their expiration status here https://getpass.civic.com/

Regarding the user 0x6d1dCfD657961B9481050EbB78eEa0b58208be75 it looks like the Liveness and CAPTCHA passes expired after 30 days. The Uniqueness pass doesn't expire until Feb. 12th. They should be able to claim the Uniqueness stamp, I tried it locally and it worked.

I can make an update to remove the "(older than 90 days)" part from the error message, since it appears the credentials are sometimes valid for less than 90 days.

**Comment by lucianHymer** [comment]
This is how I was finding that info ```curl https://api.civic.com/pass-lookup/0x6d1dCfD657961B9481050EbB78eEa0b58208be75\?includeTestnets\=true\&includeExpired\=true```

**Comment by lucianHymer** [comment]
Blocked on review with other engineers

**Comment by lucianHymer** [comment]
@jesuloluwao The civic team said that if the user connects their wallet at civic.me, it'll show them a "Refresh" button if the pass is expired

**Comment by jesuloluwao** [comment]
Thanks @lucianHymer 

Can you give me credentials to make a lookup request to civic api so I can just always verify without having to bother you.

**Comment by lucianHymer** [comment]
Hey @jesuloluwao! You actually don't need any credentials, you can use this terminal command:

```
curl https://api.civic.com/pass-lookup/0x6d1dCfD657961B9481050EbB78eEa0b58208be75\?includeExpired\=true
```

Just replace the address segment with the user's address that you're interested in.

Let me know if you have any questions!
