### ISSUE TITLE
Universal Removal of Facebook Stamp and Global Adjustment of Credential Weights in Gitcoin Passport

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1991]
### User Story:
As a Product Manager at Gitcoin Passport, I aim to remove the Facebook stamp from the Gitcoin Passport interface for all users due to technical challenges with the Facebook API. In addition, I propose a global adjustment in the weights of other credentials in our unique humanity scoring model. This change will evenly distribute the 1.38 points, previously allocated to the Facebook stamp, across all other credentials for every user, ensuring a balanced and effective scoring system.

### Acceptance Criteria
**Universal Removal of Facebook Stamp:**
GIVEN any user has or has had a Facebook stamp in their Gitcoin Passport,
WHEN viewing the Gitcoin Passport,
THEN the Facebook stamp should not be visible to any user.

**Global Weight Adjustment of Other Credentials:**
GIVEN the Facebook stamp contributed 1.38 points to the scoring model,
WHEN this stamp is universally removed,
THEN the weights of all other credentials should be globally adjusted to evenly absorb the 1.38 points, enhancing their individual weight for every user.

**Scoring System Integrity and Fairness:**
GIVEN the global adjustment in weights of other credentials,
WHEN any user views their Gitcoin Passport,
THEN the scoring should reflect the new weight distribution uniformly, ensuring that the overall scoring balance and fairness are maintained for all users.

#### Tech Details:

- Implement the removal of the Facebook stamp from the Gitcoin Passport UI for all users.
- Globally adjust the scoring algorithm to redistribute the 1.38 points from the Facebook stamp to other credentials for every user.
- Ensure all changes comply with data handling and privacy regulations.
- Conduct thorough testing to ensure the updated scoring system works correctly and maintains the integrity and fairness of the Gitcoin Passport for all users.

#### Open Questions:

- What strategies can we use to communicate these changes effectively to our user base?
- How do we monitor and evaluate the impact of these changes on the overall user engagement and trust in the Gitcoin Passport system?

**Comment by Jeremy-Gitcoin** [comment]
@NadjibBenlaldj and @stefi-says I don't know if you've seen this but @erichfi is proposing with the removal of Facebook we'll just adjust all of the other stamps to increase slightly to take on the new weights. Are you both OK with making this change for now and we'll look at a more in-depth rebalancing of weights in Jan? Or do you want us to hold off on this change?

**Comment by NadjibBenlaldj** [comment]
I had a quick look and put some observations [here](https://docs.google.com/document/d/1uRK-GOrUbT2YwC1EfhexjQdWJjeAGM6TLQXwobnvkSY/edit) 

We can make the change now. Created a [ticket](https://github.com/gitcoinco/Passport-Data-Science/issues/1) for us to monitor the impact

**Comment by digitalmnt** [comment]
There are 66 VCs left after the facebook removal. These were the previous facebook point points ("Facebook": "0.689", "FacebookProfilePicture": "0.689") with a total of `1.378`. Distributing this to the remaining stamps will be `1.378 / 66 = 0.02087878788`

This PR increments these weights https://github.com/gitcoinco/passport-scorer/pull/482/files

**Comment by digitalmnt** [comment]
This was deployed on the 12/28 release
