### ISSUE TITLE
Custom Dashboard Interface and URL Path Configuration

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1992]
### User Story:
As a product manager/administrator of Gitcoin Passport,
I want to develop a user-friendly interface for customizing dashboard experiences,
So that I can efficiently manage and personalize dashboard links and URL paths.

### Acceptance Criteria
GIVEN the Django admin panel,
WHEN I configure the dashboard settings,
THEN I should be able to easily set up and edit unique URL segments/paths for different dashboard configurations.

GIVEN a new URL path gets creating
WHEN setting it up
THEN the admin should be able to specify the name and descripiton that will show up in the socring widget in the top right corner https://github.com/gitcoinco/passport/issues/1994

#### Tech Details:
- UI/UX design improvements for dashboard customization
- Development of URL path management functionality

#### Open Questions:
What UI elements can enhance the intuitiveness of the customization process?

#### Notes/Assumptions:
The design should be simple yet flexible for future enhancements.

**Comment by lucianHymer** [comment]
The code in `useDashboardCustomization.tsx` is set up for us to swap out the `requestDynaicCustomizationConfig` hardcoded example for a call to our backend. There are some notes in the code about some things to consider, but there shouldn't be much work required for this on the frontend.

**Comment by Jeremy-Gitcoin** [comment]
@erichfi I think this is already live?!
