### ISSUE TITLE
Custom Credential Management and Scoring System

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1993]
### User Story:
As a product manager/administrator,
I want to manage custom credential visibility and a custom scoring system on custom dashboards,
So that the scoring is intuitive and accurately reflects each passport holder's credentials on partner dashboards.

### Acceptance Criteria
**Hiding Stamps**
GIVEN the Django admin panel and credential weighting system,
WHEN I assign weights to credentials and calculate a passport holder's score,
THEN only credentials with a weight greater than 0 should be visible, and the score should reflect the sum of these weighted credentials.

**Points and Score Adjustments**
GIVEN the admin configured weights different from the default scorer,
WHEN the user loads the dashboard on the client,
THEN they will see the points per card and credential in accordance with the new weights and have a scoring widget in the top left corner representing that score instead of the default score

#### Tech Details:

- Implementation of a hidden list feature for credential visibility
- Development of a dynamic scoring algorithm

#### Open Questions:
How do we handle stamp addition or removal in the scoring system?

#### Notes/Assumptions:
Scoring system updates should reflect immediately and accurately on the user interface.

**Comment by nutrina** [comment]
Need to discuss any further requirements

**Comment by nutrina** [comment]
Also need to add test cases ...
