### ISSUE TITLE
Update MagicSquare Score weights

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#1995]
### User Story:
As Magic Square, a Passport integration partner
I want to make it easier for my users to get through Passport so there's less friction
So that I can onboard users without user drop off

### Acceptance Criteria
GIVEN a user gets either Coinbase, Civic Uniqueness, OR Holonym KYC stamps
WHEN they have a Gitcoin Passport
THEN they will pass with a score > 18

#### Product & Design Links:

Update the following for Magic Square's Scorer ID: 5803
"CoinbaseDualVerification": "1.35" to "18.01"
"CivicUniquenessPass": "3.2685", to "18.01"
"HolonymGovIdProvider": "5.0185", to "18.01"

Rescore all addresses for the 5803 scorer ID based on the new updated score weights

#### Tech Details:
- [ ] Create a document in Notion for "Customising Dashboard and Scorers" and add a section that explains how to update a scorers weights, so that non-dev can do this in the future

**Comment by digitalmnt** [comment]
Link to notion document: https://www.notion.so/gitcoin/Update-Custom-Weights-90bceada76d14198866ca1032b258651

Will need to create button within scorer page of admin to initiate rescoring of the desired scorer. Probably should run this on a lambda or celery task

**Comment by digitalmnt** [comment]
@erichfi noting that any rescoring that happens before this ticket is completed will reset magic's custom weights. It would be good to get this completed as soon as possible so this is not missed

**Comment by lucianHymer** [comment]
We need to add an "Exclude from Automatic Re-weighting" checkbox and then filter out those scorer when automatically propagating new scorer weights

**Comment by lucianHymer** [comment]
Tasks

- [ ] Add "Exclude from Weight Updates" checkbox and logic
- [ ] Add django [Admin Action](https://docs.djangoproject.com/en/5.0/ref/contrib/admin/actions/) to add communit(y/ies) to an SQS queue for rescoring
- [ ] Add [lambda triggered by SQS queue](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-configure-lambda-function-trigger.html) to run rescoring

**Comment by lucianHymer** [comment]
Blocked on dev review
