### ISSUE TITLE
[BUG]  Civic expiration date is longer than 90 days

### ISSUE THREAD

**Issue by lebraat** [gitcoinco/passport#2011]
**Overview**
The Civic Stamps expiration date is currently showing as being in 2050 for me and another user. 

**Steps To Reproduce**
1. Go to the Passport app
2. Make sure you've verified the Civic stamp
3. Open up the verified Stamp drawer for Civic
4. See the expiration date, which is further out than 90 days. 

**Observed  behavior**
I'm seeing an expiration date of 11/21/2050. Anne over at Civic is seeing 12/10/2050.

**Expected behavior**
This date should be 90 days or less away from today's date. 

**Screenshots**
![Screenshot 2024-01-02 at 7 12 16 PM](https://github.com/gitcoinco/passport/assets/36083598/90ef99fd-ad8a-443d-8691-3c5bc0f5ab48)

**Additional context**
Reported by Civic via our TG channel.

**Comment by lucianHymer** [comment]
This is happening from revoked passes. It's resolved by this! https://github.com/gitcoinco/passport/issues/1963
