### ISSUE TITLE
Adding Optimism and Sepolia, Removing Goerli Support

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2017]
### User Story:
As a Gitcoin Passport holder and developer, I want the Passport features to support data portability to the Optimism and Base Sepolia networks, while deprecating the Base Goerli test network integration. This will enable me to seamlessly transition and test my data across different blockchain networks, enhancing the flexibility and utility of the Passport in diverse environments.

### Acceptance Criteria
GIVEN that I am a Gitcoin Passport holder using the review, staging, or dedicated testing mode of the app,
WHEN I choose to port my data to the Optimism or Base Sepolia networks,
THEN I should be able to do so smoothly, with all relevant data successfully migrated and the Base Goerli network option no longer available.

#### Product & Design Links:
<links>

#### Tech Details:

- @nutrina already deployed Optimism Sepolia -- only the contracts though.
- Implement data portability features for Optimism and Base Sepolia networks.
- Ensure compatibility with existing Passport features and data structures.
- Remove support for the Base Goerli test network.
- Update the app's review, staging, and dedicated testing mode to reflect these changes.
- Conduct thorough testing to ensure data integrity and smooth operation across networks.

#### Open Questions:

- Are there any specific technical challenges in integrating with the Optimism and Base Sepolia networks?
- What measures are in place to ensure data security during the migration process?

#### Notes/Assumptions:

- It is assumed that users require flexibility in choosing blockchain networks for their data, and the addition of Optimism and Base Sepolia networks will meet these needs.
- The deprecation of the Base Goerli test network is based on its reduced relevance and usage within the Gitcoin Passport ecosystem.
- The changes should be accessible in the review, staging, and dedicated testing modes to allow for comprehensive testing and user feedback before full deployment.

**Comment by digitalmnt** [comment]
@erichfi I incorporated these changes into https://github.com/gitcoinco/passport/pull/2005 because @nutrina had already started on them. Happy to move them to a separate file as the linked PR will need to be deployed with the latest changes to the passport decoder sc.

**Comment by digitalmnt** [comment]
@erichfi looking at the EAS telegram it appears EAS will try to deploy to base sepolia next week. Moving to blocked until this is complete.
