### ISSUE TITLE
Database Maintenance - Read Replica Synchronization and Vacuuming

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2022]
### Description:
It has come to our attention that the read replica of our database is significantly lagging, evident from the discrepancies in data outputs. This issue is affecting the reliability of our data and may lead to incorrect decision-making.

### Primary Objectives:
**1. Diagnose the Read Replica Lag:** Investigate the cause of the current lag in the read replica. Determine if it's a synchronization issue or related to another underlying problem.
**2. Implement a Vacuum Process:** Based on the findings, execute a vacuuming process to clean up the database and improve efficiency. This should help in bringing the read replica up-to-date with the primary database.
**3. Develop a Maintenance Task:** Establish a routine maintenance task to periodically check and ensure synchronization between the primary database and the read replica. This task should also include regular vacuuming to prevent data discrepancies in the future.
**4. Documentation:** Document the process and the findings. Include steps taken to resolve the current issue and guidelines for the ongoing maintenance task.

**Comment by lucianHymer** [comment]
I have not been able to replicate this on my end, do you have a reproducible example @nutrina

**Comment by nutrina** [comment]
All is good. The query I was interested in was executed against another DB clone ...
