### ISSUE TITLE
Integration of New ETH Stamp Model with Simplified User Verification Flow in Passport App

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2027]
### User Story:
As a Product Manager at Gitcoin Passport,
I want to integrate the new ETH stamp model from issue #2016 into the Passport app, providing a user-friendly verification flow that automatically checks Ethereum credentials and awards points based on new, branded tiers,
So that users can have a seamless and engaging experience in validating their Ethereum accounts, with Eth Maxi as the pinnacle of authenticity.

### Acceptance Criteria
GIVEN a user initiates the Ethereum account verification in the Passport app,
WHEN they click the "Verify" button,
THEN the app should automatically perform checks based on the new ETH stamp model, award points according to the highest credential tier achieved, and update the "points gained" and "available points" accordingly, without presenting a selection of specific credentials.

**Credential Tiers and Names:**

- '**Eth Advocate**': Awarded for a model score rounded down to 0.5, receiving 1/3 of total points.
- '**Eth Pioneer**': Awarded for a model score rounded to 0.75, receiving 1/3 of total points.
- '**Eth Maxi**': Awarded for a model score rounded to 1, receiving 1/3 of available points.

In the background, the scoring logic remains the same, basically awarding 1/3 of the 10.62 total points (i.e. 3.54 each), to each of the tiers.

#### Product & Design Links:

- New ETH Stamp Model Integration: [Issue #2016](https://github.com/gitcoinco/passport/issues/2016)
- Verification Flow Design Updates: <link to design updates>

#### Tech Details:

- Remove individual credential selection in favor of a single verification action.
- Integrate with the backend logic of the new ETH stamp model to calculate and award points.
- Preserve historical data of old credentials and continue computing and logging old scores for model evaluation.

#### Open Questions:

- How will we ensure that users understand the new verification process and the meaning of each tier?
- What steps are we taking to communicate the deprecation of the old credentials to the users?

#### Notes/Assumptions:

- By streamlining the verification process and integrating with the new ETH stamp model, we aim to enhance user trust and clarity.
- Maintaining historical records and continuing to log old scores are critical for assessing the long-term effectiveness of the model.

**Comment by digitalmnt** [comment]
@erichfi just wanted to confirm that we will be keeping the existing sidebar UI and giving each stamp its own credential i.e. `EthAdvocate: 3.54`?

**Comment by digitalmnt** [comment]
@erichfi one more question, in terms rounding(`Eth Maxi: Awarded for a model score rounded to 1`), should we be rounding down? For example if the user has a score of 0.80 they should qualify Eth Pioneer,  but if they have a score of 0.74 they should qualify for Eth Advocate?

**Comment by NadjibBenlaldj** [comment]
I updated the model's score to be between 0 and 100, here's how to award the credentials: 
- score from 50 to 62: Eth Advocate 
- score from 63 to 87 : Eth Pioneer
- score above 88:  Eth Maxi

**Comment by digitalmnt** [comment]
Just waiting on API deployment
