### ISSUE TITLE
Enable Passport Holders to Unstake GTC from Legacy Staking Contracts Using the New Client

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2051]
### User Story:
As a Gitcoin Passport holder,
I want the ability to unstake my GTC tokens from the old GTC staking contracts through the new client interface,
So that I can easily transition my tokens and manage my staking activities within a unified and user-friendly environment.

### Acceptance Criteria
GIVEN I am a Gitcoin Passport holder with GTC tokens staked in the legacy staking contracts,
WHEN I access the Gitcoin Passport platform,
THEN I should have the following functionality available to unstake my GTC tokens from the old staking contracts:

- A dedicated button or option to "Unstake All" prominently displayed within the new client interface.
- The option to connect my wallet to the platform securely if not already connected.
- A confirmation dialog or step to verify my intent before proceeding.
- A notification or confirmation once the unstaking process is completed.

**Comment by nutrina** [comment]
@erichfi : Does this also apply to the very first staking contract?

**Comment by nutrina** [comment]
waiting for design
