### ISSUE TITLE
Toy Script for Tracking Deduplication Events in Gitcoin Passport

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2055]
### User Story:
As a Gitcoin administrator,
I want to develop and execute a script that efficiently identifies duplication events within active credentials tied to specific scorer IDs,
So that I can gather insights on automated address tracking, which will be instrumental in streamlining the slashing process.

### Acceptance Criteria
GIVEN a set of active credentials associated with a specified scorer ID (or IDs),
WHEN the script runs to detect duplication events,
THEN it should generate a list of Ethereum addresses involved in these duplications,
AND this list should be accurate, verifiable, and usable for potential automation in the slashing process.

#### Product & Design Links:
<links>

#### Tech Details:
- The script should be capable of sifting through active credentials, excluding expired or removed ones.
- Criteria for identifying duplications need to be clearly defined and implemented in the script.
- The output should be a well-structured list of Ethereum addresses involved in the duplications.

#### Open Questions:
What specific criteria will we use to define a 'duplication event' for this purpose?
Are there any known limitations or challenges in tracking these events that we should consider?

**Comment by digitalmnt** [comment]
The script in the linked pr will generate this file just taking into deduplication events within the passport system. Waiting on clarification regarding taking into account donations to grants rounds

https://discord.com/channels/562828676480237578/1073190200404103218/1200506876308234361

**Comment by digitalmnt** [comment]
Hey @stefi-says here is the deduplication export https://passport-scorer.s3.us-west-2.amazonaws.com/deduplication_export/335_deduplication_export.csv
