### ISSUE TITLE
OP and Mainnet Deployment of ID Staking V2

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2061]
### User Story:
As a user,
I want the Identity Staking V2 contracts to be deployed on Optimism and Ethereum Mainnet,
So that I can benefit from enhanced staking features and improved security on both networks.

### Acceptance Criteria
GIVEN a user is interested in staking,
WHEN they choose to interact with the Identity Staking V2 feature,
THEN they should be able to do so seamlessly on both Optimism and Ethereum Mainnet, benefiting from the updated contract functionalities and security enhancements.

#### Tech Details:

- The deployment includes smart contract updates for Identity Staking V2, focusing on enhanced security measures and feature improvements.
- The contracts must undergo rigorous testing on both networks' testnets before the mainnet deployment.
- Integration with the Gitcoin Passport interface to ensure a seamless user experience when accessing the staking feature.

#### Notes/Assumptions:

**Comment by nutrina** [comment]
We are waiting on the mit review on this one, tbd on the 29th.
