### ISSUE TITLE
⭐️ [FEATURE] As a passport holder, I want to remove stamps in my passport, so that I can control my passport verifications

### ISSUE THREAD

**Issue by yonocan** [gitcoinco/passport#208]
GIVEN that I am a Gitcoin passport holder
WHEN I click "remove stamp" on any stamp in my passport
THEN my passport no longer has access to that stamp 
AND we delete the Ceramic stream holding the stamp

**Notes**
- Ideally, remove the data from the Ceramic Network cohesively if possible. At least, remove it from any Gitcoin technology premises.

**Comment by leoneric** [comment]
@Etovardesign

**Comment by Etovardesign** [comment]
@leoneric 

Figma: https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/Passport?node-id=2528%3A46587

**Comment by shavinac** [comment]
Research on deleting Ceramic/IPFS content: https://github.com/gitcoinco/dPopp/issues/280

Questions to ask Ceramic team:

1. How does Ceramic team handle content deletion requests? In the Ceramic privacy policy, it says
> If you shared User Content which you no longer want to share publicly or privately using our Products, Services, or Network, you must either revoke access or delete that User Content. By making such deletion, other participants in the network will be notified to remove the content and it will be deleted from any nodes run by 3Box Labs. However, this may not permanently erase the existence of or substance of any User Content from all aspects of the network entirely. In a distributed network, it is not possible for us to guarantee that all node operators will delete content.

so presumably there is a way to delete content from nodes run by 3Box Labs...

2. When unpinning streams from our Ceramic node, does this also unpin the content from the attached IPFS node? Or does the IPFS unpinning need to be done separately?
