### ISSUE TITLE
[BUG] Passport Connection Error

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#2086]
We have users reaching out regarding this error. However I am unable to reproduce. 

They get an error that says "list" argument must be an Array of Buffers. It appears on Metamask as reported by some of the users. Not sure if it affects other wallets yet.

Some addresses affected:
- 0xf5A1Cf1A7656fd1C2a40c539C6a355050489C620
- 0x9788D64c39E2B104265c89CbbCa2a2350e62701d

 > <div class="intercom-container"><img src="https://downloads.intercomcdn.com/i/o/946456308/3fa98728053dbea4c6eaf5db/image.png"></div>

**Link:** [Conversation with Silver Bus from Hwaseong-si](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/70762)

**Customer:** [Silver Bus from Hwaseong-si](https://app.intercom.com/a/apps/xaafeyri/users/656a20a6512e333a8e2ef3c3/all-conversations)
**Customer ID:** c63b9644-5759-46d8-af1f-a453efd9af05
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/70762) when this issue is closed.

**Comment by digitalmnt** [comment]
@jesuloluwao I'm unfortunately unable to replicate this either. Could you please try to get more information from the users? Screenshots of the console if possible. Thanks!

**Comment by jesuloluwao** [comment]
@digitalmnt 
![image](https://github.com/gitcoinco/passport/assets/88308638/3c3e40d7-67ec-42b9-8f14-6cf004b38299)
 Could it be related to country restrictions?

**Comment by nutrina** [comment]
This is the relevant message we need to track down:


![Image](https://github.com/gitcoinco/passport/assets/8137830/61a35a6c-5695-4b17-94cf-e18d1c12abbf)
