### ISSUE TITLE
[BUG] A wallet was given ETH Enthusiast but then it disappeared

### ISSUE THREAD

**Issue by YukiPL** [gitcoinco/passport#2129]
**Overview**
A user who had the ETH Enthusiast verified but then it is gone. He tried to reverify but failed. 
0x5F2640F86Dd08285100583A9b9C3B84D6e4304bE

On Redash, it showed on the past verification, but not on his current stamps
<img width="671" alt="Screenshot 2024-02-02 at 08 58 50" src="https://github.com/gitcoinco/passport/assets/92294305/492adc3a-3fa5-4fa5-8a97-29726863b181">

User has another passport with wallet 0xb18d2e2f690ab2d8079cf2c1d865e15d1b65746f.

Other affected wallets:
0x3ddEa72DFFA8A00EF56aadA0c002b9b32f383897
0x557F1f3b1e658b01D35294D79f6D9fA76259218f
0x2D1a1FB1E3C145aCFa46bCFD63ffB08f0B1CA769
0xf108873EE11f850CE982B5aFA624C734212d3745
0x548BB0C189A1A5A9edA2cd8eF93dcb9285235041
0x59cCAf56c84b5194B2C8f4B84caa6320C2D98c3C
0xA1dC4B89b56E7172c983a87ea3962EA3c430a2e3
0x524Df16aD3EA0F184DDfa6D43e4bC9De82FEb08E

**Comment by YukiPL** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/search/conversation/71446?query=0x5F2640F86Dd08285100583A9b9C3B84D6e4304bE&view=List

**Comment by Canawan** [comment]
Same problem

**Comment by YukiPL** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/team/6471950/conversation/72186?view=List

**Comment by YukiPL** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/72001?view=List

**Comment by YukiPL** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/72182?view=List

**Comment by YukiPL** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/72536?view=List

**Comment by YukiPL** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/72513?view=List

**Comment by YukiPL** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/72684?view=List

**Comment by nutrina** [comment]
I have restored the affected addresses

**Comment by YukiPL** [comment]
@nutrina I have one more address here: can you help?
0x9402153457C7FA0A7521864d308e944C90233b22

Thank you.
