### ISSUE TITLE
Not verifying Community Stake

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#2137]
Experienced Community Stake not verifying. User staked on 2 different wallets for 5 &amp; 6GTCs. 

These are the txids of the two stakes:
- https://etherscan.io/tx/0xfcb41aed3f4891902a1e8c6dd8a4b096a3a4e51e58423ef0c6a0ce5963340e0a
- https://etherscan.io/tx/0x6fdad258cccd8c7b7a54d69cddf64a902b7a147ceac32ccdb5c514470cb0f941

![image](https://github.com/gitcoinco/passport/assets/88308638/a50e8435-b985-4624-ad1d-a18bce458ecd)
![image](https://github.com/gitcoinco/passport/assets/88308638/0c71ad5a-9d78-470e-aa9f-6f478d782103)

I attached the json response they got from the platform
[passport (10).json](https://github.com/gitcoinco/passport/files/14157411/passport.10.json)

**Link:** [Conversation with arashmi726@gmail.com](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/70279)

**Customer:** [arashmi726@gmail.com](https://app.intercom.com/a/apps/xaafeyri/users/6503ee4ba0be1b7612719ef7/all-conversations)
**Customer ID:** e1f74555-73c5-400b-b29f-d1ca1300da24
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/70279) when this issue is closed.

**Comment by lucianHymer** [comment]
Hey @jesuloluwao ! So the actual criteria is that there have to be at least two stakes *that are each at least 10 GTC*. The error message is a bit clearer about this than the sidebar: "There are currently 0 community stakes of at least 10 GTC on/by your address, you need a minimum of 2 relevant community stakes to claim this stamp"

@erichfi Should we adjust the sidebar language?
