### ISSUE TITLE
Eth Activity score caching

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#2148]
### User Story:
As a user
I want to be able to refresh my Eth stamp
So that I can see if I qualify for new credentials without losing previous credentials

### Acceptance Criteria
GIVEN a user retrys the Eth stamp
WHEN they have previously tried the stamp within the last 30 days
THEN they should receive the same score

As per the discussion in standup on Thurs Feb 8th, lets cache the score for the Eth activity stamp for 30 days so that:
- we dramatically reduce the # of Alchemy calls we're making per day
- we don't have the bad user experience of user gets the stamp one day and looses it the next

#### Product & Design Links:
<links>

**Comment by lucianHymer** [comment]
Waiting on review

**Comment by lucianHymer** [comment]
Alright this is working, but needs some follow up. I haven't quite pieced together how to get migrations working smoothly.

It seems that if we have our permissions and roles set up correctly (which I believe I've done [here](https://github.com/gitcoinco/Passport-Data-Science/pull/94)) then we should be able to generate AWS credentials (without needing to use our own credentials or a generic account) and pull from the ECR.

Here's some info
https://docs.aws.amazon.com/AmazonECR/latest/userguide/security_iam_service-with-iam.html
https://docs.aws.amazon.com/AmazonECR/latest/userguide/security_iam_id-based-policy-examples.html
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html

I am able to produce tokens using the strange looking command towards the bottom of the page with the last link. It has all the same data as a credential generated locally with the AWS CLI and my AWS tokens (`aws ecr get-login-password --region us-west-2`), but it's not in the same format (rearranged fields, then base64 encoded).

I think I'm close to figuring this out, but don't want to hold up the release any longer.

**Comment by lucianHymer** [comment]
Figured the rest out! Waiting on review

**Comment by lucianHymer** [comment]
This is already deployed
