### ISSUE TITLE
Eth Activity cache backfill 

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#2184]
### User Story:
As a Product Manager at Gitcoin Passport
I want to restore all users who previously qualified for the Eth activity stamp
So that I can reduce user frustrations AND
So that I can reduce support questions

### Acceptance Criteria
GIVEN a user previously had an Eth Activity stamp credential
WHEN they re-verify their Eth Activity stamp
THEN it should cache the previous credentials and not give the user a lower score with less credentials

Per Gerald in Discord:
Backfilling the cache should be possible. We would need to dump the ETH* stamps from our ceramic_cache tables, filter out the values that should be in the cache, and compute a "score" for the cache that would get the user the same set of stamps when he gets back.

#### Product & Design Links:
<links>

**Comment by lucianHymer** [comment]
This is done! I'll check in and link the scripts I used for this tomorrow.
