### ISSUE TITLE
Update Lens Side Bar Text

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2190]
### User Story:
As a Gitcoin Passport holder
I want to accurate information about the Lens stamp
So that I can better understand why (not) I qualify for the Lens stamp

### Acceptance Criteria
GIVEN a Passport holder opens the Lens stamp sidebar
WHEN they see the info text box
THEN they should see the following information:

> To add the Lens Stamp to your Gitcoin Passport, ensure you're using your Lens Handle, not your profile. A Lens Handle is your unique identifier on Lens, required for verification. Obtain a Handle either through the Lens beta or by purchasing one from NFT marketplaces. Note: Verification may be delayed after claiming your Handle.

AND a "Learn more" CTA button link leading to the dedicated TBD Knowledge base link: https://support.gitcoin.co/gitcoin-knowledge-base/gitcoin-passport/guide-to-add-lens-stamp-to-gitcoin-passport

#### Product & Design Links:
<links>

#### Notes/Assumptions:

**Comment by lucianHymer** [comment]
To review shortly
