### ISSUE TITLE
[BUG] Some Stamps are excluded when user try to put the passport onchain

### ISSUE THREAD

**Issue by YukiPL** [gitcoinco/passport#2191]
**Overview**
Users who tried to bring stamps onchain but when the tx went through, zksync, lens, gnosis and  gtc staking stamps are excluded.

**Steps To Reproduce**
1. Go to passport.gitcoin.co
2. Click on Bring Passport Onchain
3. Click on Mint on Optimism chain

**Observed  behavior**
Onchain attestation exclude some stamps.

**Expected behavior**
All the stamps should be included in the onchain attestation.

**Screenshots**
![image](https://github.com/gitcoinco/passport/assets/92294305/6290793c-8d38-469a-ad61-4b5e9b4b9564)

![image](https://github.com/gitcoinco/passport/assets/92294305/a8ffbdc8-8c24-40f2-b07b-c42aa25eb0d7)

**Additional context**
1. Wallet address: 0xBFd1d57D3CFE884f9952E432c336ac9317457099
txids: https://optimistic.etherscan.io/tx/0x6ee2a61ee1325d025eb1fbf02a03d6925431e2279a3b6091c4e69c25f9da8886
https://optimistic.etherscan.io/tx/0x5c747971383687b2f55c64af2ecdc584dccb0af4747061d6bd710f5b46eb51f6
https://optimistic.etherscan.io/tx/0x7481ec782a142a359408c83def9c75541b58b574e9f3a78b2119cfa8eeb3b4ab

2. Wallet address: 0xc1986f776f20e1ac92152cc2f4004a345212473d
txid: https://optimistic.etherscan.io/tx/0x215a685ac4e01a8f49803c3b3052c803e3840da1f790ac7c8bd131066daf647d

3. Wallet address: 0x89c5F71C167434F9F108ce220F23b3c2a8cA76cA
Txid: https://optimistic.etherscan.io/tx/0xe7c34f3729159b5648330146fa02a944a86c3a17a1595863805421576b59fe36

**Comment by YukiPL** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/73594?view=List

**Comment by YukiPL** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/73664?view=List

**Comment by YukiPL** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/team/6464831/conversation/73893?view=List

**Comment by lucianHymer** [comment]
This should be resolved as of Thursday 2/15. When we switched to the new signature type, newly issued stamps were not being included in the onchain Passport attestation. The score attestation still worked correctly and included stamps that were not writing onchain correctly, and the score attestation is the one that has been used by integrators so far.
