### ISSUE TITLE
Update Holonym Side Bar Text

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2193]
### User Story:
As a Gitcoin Passport holder
I want to accurate information about the Holonym stamp
So that I can better understand why (not) I qualify for the Holonym stamp

### Acceptance Criteria
GIVEN a Passport holder opens the Holonym stamp sidebar
WHEN they see the info text box
THEN they should see the following information:

> To add the Holonym Stamp to your Gitcoin Passport: Have a smartphone, valid ID, and an Ethereum wallet with ~$10 in ETH or AVAX. Go to Holonym's page, verify your ID by connecting your wallet, pay the verification fee, and follow prompts to take ID and selfie photos. After verification, mint the SBT to your wallet, then link it to your Gitcoin Passport by verifying it.

AND a "Learn more" CTA button link leading to the dedicated TBD Knowledge base link: TBD

#### Product & Design Links:
<links>

#### Notes/Assumptions:

**Comment by lucianHymer** [comment]
To review shortly
