### ISSUE TITLE
Automated Rescore on User Login with Notification for Score Changes Due to Stamp Expiry

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2204]
### User Story:
As a Gitcoin Passport user,
I want the system to automatically trigger a rescore upon my login if there are any expired stamps in my Passport, and receive a notification if there's a change in my score due to expiry,
So that I can always be assured my Passport score is accurate and up-to-date, and I am well-informed about any changes.

### Acceptance Criteria
GIVEN a user has one or more expired stamps in their Passport,
WHEN the user logs into their Gitcoin Passport account,
THEN the system automatically triggers a rescore of their Passport to reflect the most current score based on active stamps.

AND

GIVEN a rescore results in a change to the user's score due to the expiry of stamps,
WHEN the score change occurs,
THEN the user receives a notification through the existing banner mechanism alerting them of the score change and its cause.

#### Tech Details:

- The rescore trigger should be integrated into the existing login process, checking for stamp expiries as part of the authentication and session initialization steps.
- Utilize the existing notification system to implement the score change alert, ensuring consistency in user experience and leveraging established patterns for user alerts.

**Comment by nutrina** [comment]
@erichfi  what about attaching an expiry date to the score, which should be the same as the first stamp that expires. This is something that would be useful also for API users, as they know that the score is out of date ...

**Comment by nutrina** [comment]
Whoever picks up this ticket: 
- we should store the score expiration in the DB as a field
- include this in the payloads returned via internal and external APIs

@lebraat  FYI - new field in score being returned ...
@NadjibBenlaldj  @stefi-says  not sure if this is relevant for any of your analysis, tagging you here so that you are aware of this

**Comment by lebraat** [comment]
@nutrina -- Big +1

We recently heard from partners that this would be helpful, as they can surface this information via their UI to let users know if Stamps are expiring soon. 

Which endpoints do we plan to add this to, and do we know how it will look in the payloads yet? Happy to influence decisions around this.

**Comment by nutrina** [comment]
Waiting for code review.
