### ISSUE TITLE
Ethereum Connection with Wallet Provider Parity to Passport App

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2208]
### User Story:
As a user of Identity Staking v2,
I want to connect my wallet, 
So that I can access the platform.

### Acceptance Criteria
GIVEN I'm at the Identity Staking v2 splash page,
WHEN I select "Connect Wallet",
THEN the connection process should offer the same wallet providers as the passport app.

#### Product & Design Links:
[Design Spec](https://www.figma.com/file/FOOlLEFaBt87atw6CPkA5P/Passport-App?type=design&node-id=7366%3A2467&mode=design&t=APKO9bP2r3H9Wgq4-1)

**Updated Copy**

> **Increase Your Passport Score**
> Reinforce your identity and increase your unique humanity score by staking GTC. Secure your Passport Score with ease, safeguarding against Sybil threats.
> 
> 1.5M+ GTC Staked
> 123K+ Stakers
> 100K+ Passport Stamps

#### Tech Details:
- #2210 will take care of the header and main layout.
- Integrate Web3 authentication providers that are also availble in passsport app

#### Notes/Assumptions:

**Comment by nutrina** [comment]
@erichfi  do we have a use-case / requirement for this already? Technically we do not need the sign-in in the identity staking app,  unless we want to interact with our DB or with Ceramic ...
But we should design this around a specific requirement first.

**Comment by nutrina** [comment]
1. ok
2. can we drop it for the initial release, this is not that trivial?
3. Ok, will fix
4, 5. can we create a chore to fix this?

I think we should focus on function first, fixing design later. We are still missing a lot of functionality. I would rather do that first.

**Comment by nutrina** [comment]
Glow is still missing behind card ...
