### ISSUE TITLE
Main Layout Design for Identity Staking v2

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2210]
### User Story:
As a developer for the Identity Staking v2 app,
I want to create a header and footer layout that is consistent with the entire platform,
So that users experience uniform navigation and brand continuity.

### Acceptance Criteria
GIVEN I am developing the Identity Staking v2 app,
WHEN I implement the header and footer,
THEN they should match the design and functionality of the platform-wide components, ensuring a cohesive user experience.

#### Product & Design Links:
[Design Spec
](https://www.figma.com/file/FOOlLEFaBt87atw6CPkA5P/Passport-App?type=design&node-id=7366%3A2360&mode=design&t=APKO9bP2r3H9Wgq4-1)

Let's deploy a review version of the master branch at `review.stake.passport.xyz` and a staging version at `staging.stake.passport.xyz`. A separate issue will take care of the production domain / deployment pipeline => `stake.passport.xyz`

#### Tech Details:

- Develop responsive header and footer components.
- Ensure components integrate well with the existing layout and navigation schema.

**Comment by lucianHymer** [comment]
This includes setting up routing, tailwind + theme control, etc.

**Comment by nutrina** [comment]
Latest comment is addressed by this PR: https://github.com/gitcoinco/id-staking-v2-app/pull/9
