### ISSUE TITLE
Your Stake Section UI Implementation

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2211]
### User Story:
As a staker on Identity Staking v2,
I want to input custom amounts and select lock-up periods for my stakes,
So that I can tailor my staking strategy to my preferences.

### Acceptance Criteria
GIVEN I am on the "Your Stake" page,
WHEN I enter a staking amount and choose a lock-up period,
THEN the UI should reflect my input and provide options for submitting the stake.

#### Product & Design Links:
[Design Spec](https://www.figma.com/file/FOOlLEFaBt87atw6CPkA5P/Passport-App?type=design&node-id=7366%3A2360&mode=design&t=APKO9bP2r3H9Wgq4-1)

#### Tech Details:

- Input fields for custom staking amounts.
- Dropdown or selection for lock-up periods.
- Validation to ensure input amounts and periods are within allowable ranges.

**Comment by adykrni** [comment]
I can take on this task as well as it aligns more with my experience :)

**Comment by lucianHymer** [comment]
This includes the chain selection dropdown and the "folding" functionality to show/hide the section

**Comment by adykrni** [comment]
okay, I think I have an idea of what is expected, can you assign this task to me?

**Comment by adykrni** [comment]
hey @lucianHymer, I'm new here, so still leaning how Github works, do I just get started with the design, or will you assign this issue to me?

**Comment by lucianHymer** [comment]
> hey [@lucianHymer](https://github.com/lucianHymer), I'm new here, so still leaning how Github works, do I just get started with the design, or will you assign this issue to me?

Hey @adykrni! So this project board is public, but it is only used for issues that the core contributor team is working on. Citizen contributions usually start over on the Gitcoin governance forum https://gov.gitcoin.co/

**Comment by nutrina** [comment]
Have fixed styling partially.
Have also fixed a bug related to the total stake not being displayed.

But need a bit of help regarding button heights & alignment.
@lucianHymer would like to pair with you on this later.
