### ISSUE TITLE
Update Stake Functionality Integration for Self-Staking

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2213]
### User Story:
As a user of Identity Staking v2,
I want an integrated functionality to update the stakes on my own identity,
So that I can increase my investment and trust score within the platform as needed.

### Acceptance Criteria
GIVEN I have already staked GTC on my identity in the Identity Staking v2 app,
WHEN I navigate to the "Your Stake" section and choose to update my stake,
THEN I should be able to input a new stake amount and confirm the transaction, which will adjust my total staked amount accordingly.

#### Product & Design Links:
[Design Spec](https://www.figma.com/file/FOOlLEFaBt87atw6CPkA5P/Passport-App?type=design&node-id=7525%3A3768&mode=design&t=APKO9bP2r3H9Wgq4-1)

#### Tech Details:

- Implement front-end functionality allowing users to input new stake amounts within the "Your Stake" section.
- Ensure that the updated stake amount is accurately sent to the blockchain for processing.
- Update the user interface to reflect the new total stake amount post-transaction confirmation.

**Comment by nutrina** [comment]
For this ticket, we should wait for the new stake amount to e reflected in the indexer, in order to show the updated data in the UI (and not rely on the blockchain events from the Wallet Provider).

**Comment by nutrina** [comment]
Blocked by https://github.com/gitcoinco/passport/issues/2211
