### ISSUE TITLE
Implementation of Quarterly Staking Round (March 1st - May 31st)

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2225]
### User Story:
As a Gitcoin Passport user,
I want to participate in a staking round that runs for three months, starting from March 1st to May 31st,
So that I can have more flexibility and opportunities to engage with the platform over a longer period.

### Acceptance Criteria
GIVEN I am a user on the Identity Staking platform,
WHEN I navigate to the staking section during the period of March 1st to May 31st,
THEN I should be able to participate in the staking round that is actively running for the specified three months.

#### Tech Details:

- The staking round's start and end dates need to be set in the system for March 1st to May 31st.
- Ensure that the staking functionality is seamlessly available throughout the specified period without interruptions.
- Update any cron jobs or scheduled tasks related to staking rounds to accommodate the new timeline.

**Comment by nutrina** [comment]
Waiting to pair with Lucian on this

**Comment by lucianHymer** [comment]
https://etherscan.io/tx/0x7ee85303aaf76ecd4a4bf30ede77be21043afa2aa9a330f0fd02acd88a347f0f

**Comment by lucianHymer** [comment]
- [ ] Update staking app code
- [ ] Update passport ENV var
- [ ] Update staking ENV var (tomorrow)
