### ISSUE TITLE
🚗 [GRANTS] As a gitcoin.co/trust visitor, I want to know the network status of Ceramic

### ISSUE THREAD

**Issue by brentmartin** [gitcoinco/passport#223]
GIVEN that I have created a passport and completed stamps
WHEN I visit gitcoin.co/trust to connect my passport
THEN I see a banner that informs me of the network status

Notes:
- We need to find out if we can push the dates back to do the matching by a couple of days
    - If we can push dates, we need messaging to reflect that 1.) informs the user of the network issues, and 2.) tells them they have until end of round AND 3.) two to three extra days before matching
    - If we can't, we need messaging to reflect that 1.) informs the user of the network issues, and 2.) tells them they have until end of round

**Notes**
- Instead of pinging Ceramic every five seconds or so, let's ping it in irregular, increasing intervals as a Trust Bonus web client is up.

**Comment by brentmartin** [comment]
@leoneric do you have any update on whether or not we can push those dates back?

**Comment by Etovardesign** [comment]
@leoneric 

Figma: https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/Passport?node-id=2505%3A46450
