### ISSUE TITLE
Documentation for Public Ethereum Activity Endpoint

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2231]
### User Story:
As a developer and team member involved in the Gitcoin Passport project,
I want to have access to comprehensive documentation for the Public Ethereum Activity Endpoint,
So that I can understand its functionality, integrate it seamlessly into our Go-To-Market (GTM) strategies, and support educational efforts for the team and broader community.

### Acceptance Criteria
GIVEN the need for detailed understanding and integration of the Ethereum Activity Endpoint into our projects,
WHEN I access the documentation,
THEN I should find clear, concise, and complete descriptions of the endpoint's capabilities, use cases, request/response formats, error codes, and best practices for integration.

#### Tech Details:

- The Public Ethereum Activity Endpoint will provide real-time data on Ethereum transactions relevant to the Gitcoin Passport users.
- It includes filters for transaction types, wallet addresses, and other parameters critical for assessing user activity on the blockchain.
- This endpoint supports RESTful API standards and offers JSON-formatted responses.

**Comment by lucianHymer** [comment]
@lebraat The docs (will be) available here! https://api.scorer.gitcoin.co/passport/docs

Already on staging here: https://api.staging.scorer.gitcoin.co/passport/docs

They should use the same API key as the /registry API, i.e. the one generated in the scorer UI.

**Comment by lebraat** [comment]
Acknowledged! Looking forward to playing around with it!
