### ISSUE TITLE
Integration of Citizen Rounds into Gitcoin Stamp Eligibility Set

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2233]
### User Story:
As a Gitcoin developer,
I want to integrate contributions from Citizen Round 1 and 2 into the Gitcoin Stamp model,
So that I can ensure these contributions are accurately reflected in the Gitcoin Stamp eligibility and points system.

### Acceptance Criteria
GIVEN the lists of eligible and not eligible addresses for Citizen Round 1 and 2,
WHEN a user's contributions from these rounds are assessed for Gitcoin Stamp points,
THEN the contributions should be included or excluded based on the criteria outlined for eligibility and the provided lists.

#### Product & Design Links:
[Citizen Round 1 Eligible Addresses](https://docs.google.com/spreadsheets/d/17Wq4VqrL__uupSZ-PGtuNEt4OJfpEyou7UFAyed67g0/edit?usp=sharing)
[Citizen Round 1 Not Eligible Addresses](https://docs.google.com/spreadsheets/d/1QECbRzaKyRTTSa2EIyBd2lbJ509BmIF6M4gXHPDhbYE/edit?usp=sharing)
[Citizen Round 2 Eligible Addresses](https://docs.google.com/spreadsheets/d/1SRLxo8wRAXIUyBJHaq2-KDGcUtKZFXfKdjlrss6PckM/edit?usp=sharing)
[Citizen Round 2 Not Eligible Addresses](https://docs.google.com/spreadsheets/d/1xdktg1EC8fmSyifhr34Q5HGeQHbdQ9901iMUOjeUWu8/edit?usp=sharing)

#### Tech Details:

- The integration requires updating the Gitcoin Stamp model to include checks against the provided lists for determining eligibility.
- Criteria for eligibility include a passing score above 15 for Round 1 and above 20 for Round 2, and the absence of voting via wallets involved in deduplication events.
- The engineering team needs to handle cases where addresses might have been flagged for deduplication post the Citizen Rounds but are using the same identification (e.g., Twitter account), potentially considering them as part of a sybil cluster at the time of voting.

**Comment by stefi-says** [comment]
hey @nutrina here in this [folde](https://drive.google.com/drive/folders/1FZ9Pu6byUz8rUy4mKPhplAG2cEdcj0Ky?usp=drive_link)r I dropped the jsonl files, 2 for each round, one containing all the transactions and another with only the transactions of eligible address. Let me know if that is what you need or if need any adjustments.

**Comment by nutrina** [comment]
Hey @stefi-says  Thanks. That already looks better.

But would you be able to use this format for the data in the JSONL files, and also please make sure to include all these fields (the id and the projectId as hex are currently missing):
```json
{
  "roundId": "0x0F0b9d9F72C1660905C57864e79CeB409ADa0C9e",
  "voter": "0x606d04e5adf86dF181262cD571bf1463e05c343f",
  "grantAddress": "0xda04c025F4d8Ac555Fdb3497B197D28FCEcf4d41",
  "projectId": "0x086b7e3593fbd2ca102ec240b5ccdd1f69a85f923845160cf875314e24f37fd6",
  "amount": 500000000000000000,
  "blockNumber": 155233057,
  "token": "0x912CE59144191C1204E64559FE8253a0e49E6548",
  "transaction": "0x73d7beb485d5f2ec9146732843511acd4a6eef1787f615da74f46e24d7a96c29",
  "amountUSD": 0.50848998,
  "amountRoundToken": 507985,
  "applicationId": 11,
  "id": "0x4a3912299aa803f37c408025d35d1f8b5b84848fea63ddbf07b3373b2c09d473"
}
```

This is the format we used in previous imports as well, it would be helpful to stick to the same format.

**Comment by stefi-says** [comment]
hey @nutrina, have followed the docs you have send me as an example: 
- https://drive.google.com/drive/folders/1lRkypFhBN1VqYv_Sq9GBSJrQxhqQTFai
-  https://www.notion.so/gitcoin/cGrants-Data-Grants-Data-onchain-82e0bbff530241778119d546b65bc072?pvs=4#354c18000273453282c8744e1a9d055a  

and here is de docs produced with all the transactions data for the round with the specified columns and not eligible address with their signals and scores. 

https://drive.google.com/drive/folders/1FZ9Pu6byUz8rUy4mKPhplAG2cEdcj0Ky?usp=drive_link

let me know if that works ( hope so )
