### ISSUE TITLE
Error while updating stamps onchain with OP

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#2251]
I get the following error while moving stamps on Optimism.

I have enough ETH to complete the transaction

_app-e089260706b44287.js:1 error syncing credentials to chain:  Error: could not coalesce error (error={ "code": -32603, "message": "Internal JSON-RPC error." }, code=UNKNOWN_ERROR, version=6.3.0)
    at makeError (_app-e089260706b44287.js:619:354528)
    at BrowserProvider.getRpcError (_app-e089260706b44287.js:619:336194)
    at BrowserProvider.getRpcError (6118-4a028461017d8794.js:1:35426)
    at _app-e089260706b44287.js:619:330085

<img width="1184" alt="Screenshot 2024-03-03 at 6 11 10 PM" src="https://github.com/gitcoinco/passport/assets/88308638/bacb9bf5-3771-448b-8aae-804a97f54885">

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/73901?view=List

**Comment by nutrina** [comment]
Closing this, as the issue seems to have been not enough funds in the Metamask
And Metamask does a bad job (probably a bug) reporting the total cost of the transaction. The L1 fee does not seem to be included.
