### ISSUE TITLE
UI Development for "Stake for Others" Feature

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2288]
### User Story:
As a user of the Identity Staking v2 app,
I want to stake GTC on multiple addresses through a user-friendly interface in the "Stake for Others" section,
So that I can support others' credibility and participate in the ecosystem more actively without technical barriers.

### Acceptance Criteria
GIVEN I am on the Identity Staking v2 app,
WHEN I navigate to the "Stake for Others" section,
THEN I can easily stake GTC on multiple addresses simultaneously through a clear and intuitive UI that updates in real time without needing to reload the page.

#### Product & Design Links:
https://www.figma.com/file/FOOlLEFaBt87atw6CPkA5P/Passport-App?type=design&node-id=7366%3A2360&mode=design&t=JblYkjSaQNFLirNu-1

#### Tech Details:

- Implement real-time UI updates for staking actions.
- Ensure the UI supports an unlimited number of address inputs for staking.

#### Notes/Assumptions:
The feature must be mobile-responsive to ensure accessibility across devices.

**Comment by nutrina** [comment]
Blocked by https://github.com/gitcoinco/passport/issues/2211
