### ISSUE TITLE
Development of History Component for Stakes Made on Others

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2289]
### User Story:
As a user of the Identity Staking v2 app,
I want to view a history of stakes I've made on others,
So that I can track my contributions and manage my stakes more effectively.

### Acceptance Criteria
GIVEN I have previously staked GTC on other addresses,
WHEN I navigate to the "Stake for Others" section,
THEN I can see a history of my stakes without the need for pagination or infinite scrolling.

#### Product & Design Links:
https://www.figma.com/file/FOOlLEFaBt87atw6CPkA5P/Passport-App?type=design&node-id=7366%3A2360&mode=design&t=JblYkjSaQNFLirNu-1

#### Tech Details:
Integration with third-party services or APIs for this component is currently undecided.

#### Open Questions:

- [ ] How should the history data be stored and retrieved?

#### Notes/Assumptions:
The UI should be designed with mobile responsiveness in mind.

**Comment by nutrina** [comment]
History data will be retrieved using the same API as for the history of self-stakes (returning data from new indexer).
To be formatted in the UI: amounts & dates

**Comment by nutrina** [comment]
@erichfi  what format shall we use for date? Like: `MM.DD.YYYY` ? Or shall we use a local format (will be different for each user?
