### ISSUE TITLE
Update Stake Functionality Integration for Staking on Others

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2290]
### User Story:
As a user of Identity Staking v2,
I want an integrated functionality to update the stakes I've made on others' identities,
So that I can adjust my support and investment in their trust scores as needed.

### Acceptance Criteria
GIVEN I have already staked GTC on other identities in the Identity Staking v2 app,
WHEN I navigate to the "Stake for Others" section and choose to update a stake I've made,
THEN I should be able to select an existing stake, input a new stake amount, and confirm the transaction, which will adjust the total staked amount on that identity accordingly.

#### Product & Design Links:
https://www.figma.com/file/FOOlLEFaBt87atw6CPkA5P/Passport-App?type=design&node-id=7366%3A2360&mode=design&t=JblYkjSaQNFLirNu-1

**Comment by nutrina** [comment]
This is currently blocked by #2289
