### ISSUE TITLE
Implementation of "Trust in You" Display

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2291]
### User Story:
As a user of the Identity Staking v2 app,
I want to see who has staked on me in the "Trust in You" section,
So that I can understand my standing within the community and acknowledge the support from others.

### Acceptance Criteria
GIVEN stakes have been made on me by other users,
WHEN I navigate to the "Trust in You" section,
THEN I can see detailed information about each stake, including the staking party's identity (if available) and the amount staked, in a mobile-responsive layout.

**Comment by lucianHymer** [comment]
There are a couple minor issues, e.g. the history section title, which are fixed in #2292
