### ISSUE TITLE
Social Sharing and DM Copy Invitation Feature with Dynamic Address Insertion

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2292]
### User Story:
As a user of the Identity Staking v2 app,
I want to easily share an invitation link to stake on me via a "copy" option, which automatically includes my unique address in the URL,
So that I can invite others to support me directly through social platforms or direct messages, simplifying the process for them to stake on me.

### Acceptance Criteria
GIVEN I am on my profile or a specific section designed for sharing within the Identity Staking v2 app,
WHEN I click on the "copy" option,
THEN a predefined message including a link to stake on me is copied to my clipboard. This link must dynamically include my unique address (e.g., stake.passport.xyz/[MyAddress]), ensuring friends or followers who open the link are directed to the "Stake for Others" section with my address pre-filled, even after signing in.

#### Product & Design Links:
https://www.figma.com/file/FOOlLEFaBt87atw6CPkA5P/Passport-App?type=design&node-id=5159-7049&mode=design (share with friends)

#### Tech Details:

- Implement functionality to dynamically insert the user's unique address into the sharing link at the time of copying.
- Ensure the app captures the address from the link after sign-in and navigates the user directly to the "Stake for Others" section with the address pre-filled in the appropriate input field.

#### Open Questions:
What is the most efficient method to ensure the shared link persists through the sign-in process and correctly populates the "Stake for Others" widget?

#### Notes/Assumptions:

- The message format to be copied is: "Support me on Passport! Click this link to stake on my digital identity and help boost my trust score: stake.passport.xyz/[YourAddress] - It's quick and makes a big difference. Thank you! 🌟"
- This feature must be designed with a focus on mobile responsiveness and simplicity, especially considering ESL users.

**Comment by nutrina** [comment]
@erichfi  do we have a design for this?

**Comment by lucianHymer** [comment]
Note to self: update favicon
