### ISSUE TITLE
Update Coinbase Stamp Sidebar

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2294]
### User Story:
As a Gitcoin Passport holder
I want to accurate information about the Coinbase stamp
So that I can better understand why (not) I qualify for the Coinbase stamp

### Acceptance Criteria
GIVEN a Passport holder opens the Civic stamp sidebar
WHEN they see the info text box
THEN they should see a link at the end of the info text box saying "Learn more" incl. a hyperlink leading to the dedicated TBD Knowledge base article for Coinbase: https://support.gitcoin.co/gitcoin-knowledge-base/gitcoin-passport/how-do-i-add-passport-stamps/guide-to-add-coinbase-stamp-to-passport

Text for the text box before the Learn More link:

> Secure the Coinbase Stamp by completing a Coinbase attestation onchain. Ensure you have an active Coinbase account with a verfied government ID to mint your onchain attestation, elevating your Passport's credibility and trust.

Keep the CTA button as is

#### Product & Design Links:
<links>

#### Notes/Assumptions:

**Comment by lucianHymer** [comment]
Do we want to keep the old call to action? So it looks like this?


![Image](https://github.com/gitcoinco/passport/assets/19908762/b2201d71-1f44-4cac-943a-9308b4c16e16)
