### ISSUE TITLE
[Rate Limit Elevation] -- soul.club

### ISSUE THREAD

**Issue by lebraat** [gitcoinco/passport#2301]
Address: 0xa4B8decBe1a2D8600Dc5346c7E3BE5163A7D984a
Scorer ID: 6539
API key name:  h0MlK6nz
API key: 
IP Address (optional but recommended): 46.101.88.169
Date exempted: 
Primary Contact: [gmgn@souls.club](mailto:gmgn@souls.club) or TG

**Comment by lucianHymer** [comment]
Set to tier 3 (2000 req/15 min)
