### ISSUE TITLE
Coming Soon on ID Staking v2 Menu Options

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2302]

**Comment by octanaiv** [comment]
@erichfi There are two ways of doing this. Attaching here both.
1. A coming soon tooltip on hover
2. On hover the text changes to coming soon

![Image](https://github.com/gitcoinco/passport/assets/154508657/bb5d5728-d2e8-4e0e-9ced-eae8646be21f)
https://github.com/gitcoinco/passport/assets/154508657/3b41d86b-4a92-4bc3-908c-12d25371dda3
