### ISSUE TITLE
Terms of Service Agreement

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2306]
### User Story:
As a Passport user intending to stake identity on the platform,
I want to be presented with a clear and concise Terms of Service agreement,
So that I can understand and acknowledge the rules and potential penalties for misuse before proceeding with the staking process.

### Acceptance Criteria
GIVEN I am a user who has connected my wallet to the Passport platform,
WHEN I attempt to navigate to the app to stake my identity,
THEN a Terms of Service agreement widget should pop up requiring me to acknowledge the possibility of being slashed for bad behavior, accept the specifics of slashing and wallet rules, and agree to the Terms and Conditions before I can proceed.

#### Product & Design Links:
https://www.figma.com/file/FOOlLEFaBt87atw6CPkA5P/Passport-App?type=design&node-id=7398%3A3882&mode=design&t=Kej8Na1MTkjQq3ca-1

Copy: 

> **Title: Acknowledge and Agree to Continue**
> 
> **Before Staking Your Identity, Please Agree to the Following:**
> 
> - [ ] I acknowledge that I may be subject to slashing for non-compliant behavior. The rules governing such behavior may change. [Learn more about slashing](PLACEHOLDER).
> - [ ] I understand that using specific Passport Stamps (e.g., Holonym, Civic, and Google Stamps) are allowed only in one active Passport that I use in Passport-protected apps, and misuse may lead to slashing. [Learn more about Passport Stamps and wallets](PLACEHOLDER).
> - [ ] I have read, understood, and agree to the [Terms and Conditions](PLACEHOLDER) of Passport's Identity Staking.
> 
> **Please note:** All three boxes must be checked to enable the "Proceed" button and continue to the app.
> 
> [Proceed] [Decline]

#### Tech Details:

- The pop-up should be triggered post-wallet connection pre-app navigation.
- All three checkboxes within the widget must be ticked for the "Proceed" button to become active.
- Link to detailed information about slashing rules and behavior expectations.
- Ensure that the information about only using a specific Passport Stamp in one active Passport on the Gitcoin Grants stack is highlighted.

#### Open Questions:

- [ ] How will updates to the slashing rules be communicated to the user post-agreement?
- [ ] Is there a need for users to re-acknowledge the terms if they change?

**Comment by nutrina** [comment]
We will store the user confirmation in the browsers localstorage (with a version).
If the version changes (we have new terms), we will prompt the user again

**Comment by nutrina** [comment]
@erichfi in our meeting we have discussed to make the user sign a message in metamask, and store the signature as proof in the DB

Can you please confirm that this is still valid, and if so what is the text that the user needs to sign in Metamask (at least a draft)?
