### ISSUE TITLE
Terms and Conditions Page Deployment for Identity Staking v2

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2307]
### User Story:
As a developer for Passport,
I want to set up a dedicated Terms and Conditions (TaC) page,
So that users can easily access, read, and understand the conditions before staking their identity on the platform.

### Acceptance Criteria
GIVEN I am a developer tasked with the implementation of the Terms and Conditions page,
WHEN I deploy the TaC page on the Passport platform,
THEN the page should be accessible through a clear and identifiable link, contain all relevant terms in a readable format, and offer a placeholder link for future documentation such as a comprehensive Google Doc.

#### Product & Design Links:
WIP Terms: https://docs.google.com/document/d/1NrpK-3u8ngJw84phARXLgK8-mzi5f-ZkoyhLKkp99ys/edit?usp=sharing

Design for page: https://www.figma.com/file/FOOlLEFaBt87atw6CPkA5P/Passport-App?type=design&node-id=7402%3A4208&mode=design&t=d03kasMytzqYRVI3-1

#### Tech Details:  

- Create a web page within the Passport domain for the TaC.
- Ensure the page is mobile-responsive and follows the design language of Passport.
- Incorporate a readable font and size for user comfort.

#### Open Questions:

- [ ] What is the timeline for finalizing the content of the TaC to replace the placeholder link?

**Comment by nutrina** [comment]
Page is available at: https://stake.review.passport.xyz/#/terms
