### ISSUE TITLE
Single Password Implementation for Identity Staking v2 Private Beta Access

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2309]
### User Story:
As a developer of the Identity Staking v2 App,
I want to implement a single password entry point on the main splash page for the private beta,
So that we can control access and ensure that only participants with the shared password can enter the beta environment.

### Acceptance Criteria
GIVEN I have the shared private beta password,
WHEN I visit the main splash page of the Identity Staking v2 app,
THEN I am prompted to enter the shared password, and upon correct entry, I gain access to the private beta.

#### Product & Design Links:
[Figma design for Private Beta Access Page](https://www.figma.com/file/FOOlLEFaBt87atw6CPkA5P/Passport-App?type=design&node-id=3761-36672&mode=design)

#### Tech Details:

- The private beta password page will authenticate against a single shared password.
- The password should be securely stored and encrypted in the backend system.
- Implement basic security measures like rate-limiting to prevent brute force attacks.
- Ensure that the login failure messages do not reveal whether the password is incorrect.
- Password field should mask input for privacy and security.

#### Open Questions:

- [ ] Should the password be changed periodically, and if so, what is the process for updating it and notifying users?

#### Notes/Assumptions:

- It is assumed that the shared password has been securely communicated to all authorized private beta users.
- We assume that there is a process in place for users to obtain the password if they are joining the beta at a later stage.
- The shared password is currently located in a secure Google Docs file accessible by the team [here](https://docs.google.com/document/d/1gChjlgazrkjhg2bKtb0b470MaX_dSz8t8PTdj4beMvU/edit?usp=sharing).

**Comment by nutrina** [comment]
This was already covered in: https://github.com/gitcoinco/passport/issues/2210

**Comment by nutrina** [comment]
The desired design from Figma is this one: 



![Image](https://github.com/gitcoinco/passport/assets/8137830/203f64ee-bb6c-4035-9e27-dfdbebf5c791)
