### ISSUE TITLE
Update GTC Staking Stamp to Include Identity Staking v2 Verification

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2310]
### User Story:
As a Passport backend developer,
I want to update the GTC Staking Stamp functionality,
So that it captures and verifies stakes from Identity Staking v2 as part of the stamp verification process.

### Acceptance Criteria
GIVEN a user has staked GTC in Identity Staking v2,
WHEN the user's Passport is being verified,
THEN the GTC Staking Stamp should reflect the user's staking activities from Identity Staking v2.

#### Tech Details:

- Integrate Identity Staking v2 smart contract interactions with the Passport's GTC Staking Stamp verification logic.
- Ensure that the Stamp verification process queries both the original and v2 staking contracts.
- Update backend services to handle additional data from Identity Staking v2.
- Modify the Stamp generation logic to incorporate v2 stakes in the computation of staking levels and credentials.
- Retain the ability to distinguish between v1 and v2 stakes if necessary for future functionality or analytics.

#### Open Questions:

- [ ] Will there be any UI changes required on the Passport front-end to accommodate the inclusion of Identity Staking v2 stakes?

#### Notes/Assumptions:

- It is assumed that the Passport system currently has access to the smart contract of Identity Staking v2 for querying stake information.
- We are assuming that the inclusion of v2 stakes will not change the underlying security model of the Stamps.
- We presume there is a clear understanding of how Identity Staking v2 stakes should influence credentials and overall Passport score.

**Comment by nutrina** [comment]
The provider will have to check both staking smart contracts:
- old one (as the current round ends end of May)
- new one (v2)
