### ISSUE TITLE
 Implement an FAQ Section

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2312]
### User Story:
As a user of the Identity Staking v2 App,
I want an FAQ section that is easily accessible and informative,
So that I can quickly find answers to common questions and understand the staking process better.

### Acceptance Criteria
GIVEN I am a user looking for information on the Identity Staking v2 App,
WHEN I navigate to the FAQ section,
THEN I see a list of questions and answers formatted and displayed as specified in the provided design and text resources.

#### Product & Design Links:
- [FAQ Design in Figma](https://www.figma.com/file/FOOlLEFaBt87atw6CPkA5P/Passport-App?type=design&node-id=7393%3A3130&mode=design&t=J7j0ntyFR62VaiBj-1)
- [FAQ Content Document](https://docs.google.com/document/d/1HSD3hSYoVTYhJpNvOMkANkfvggHDz_nPB30Q44M0wmA/edit?usp=sharing)

#### Tech Details:

- The FAQ section should be implemented as a collapsible accordion to maximize space efficiency.
- Should ensure the section is dynamically updated from a managed content source for easy updates.

#### Open Questions:

- [ ] How often will the FAQ content be updated and who is responsible for the updates?
- [ ] Will there be a search function within the FAQ for users to find specific information?

#### Notes/Assumptions:

- Assumes the FAQ will reduce the volume of common support queries.

**Comment by digitalmnt** [comment]
Just waiting on a review
