### ISSUE TITLE
Alert for growing number of DB connections

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#2321]
### User Story:
As a Product and Engineering team
I want to see when DB connections are growing
So that I can understand if the system isn't healing correctly

### Acceptance Criteria
GIVEN the DB connections in the system
WHEN the connections grow past a threshold of X
THEN send issue a PagerDuty allert

#### Product & Design Links:
<links>

#### Tech Details:
- the threshold X remains to be determined (would be ideal if it could be calculated as a % of total number of connections, which depends on the instance memory)

**Comment by nutrina** [comment]
This is covered in https://github.com/gitcoinco/passport/issues/2403#issue-2252168116

**Comment by nutrina** [comment]
Closing because it is duplicate
