### ISSUE TITLE
Alert on data model changes

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#2324]
### User Story:
As a Gitcoin Passport Engineer or data Scientist
I want to know when there are changes that impact the data science models
So that I can prevent issues from happening

### Acceptance Criteria
GIVEN a change to our systems
WHEN there are changes to the data model 
THEN send an email to the Passport alias with changes

Team wants to make sure we're not throwing off Data Science and the team is aware of the changes we're making to be able to manually verify the changes to prevent issues and react:

Email sent to Passport alias when:
Adding or excluding columns from data model send an email with table and column impacted + any other info that would be helpful for the data science team to know

Check Github, send alert on model change

#### Product & Design Links:
<links>

**Comment by nutrina** [comment]
Interesting. This is a topic for the next Hangout.

**Comment by nutrina** [comment]
@Jeremy-Gitcoin 

If I understand correctly, we want an automated notification to be sent out, whenever engineering is making changes to the DB model, that could impact the data team?

**Comment by nutrina** [comment]
Closing this, as there is no actual action item for eng on this.
We should communicate model changes to the data team whenever these are happening.
