### ISSUE TITLE
Mocaverse Custom Passport Dashboard

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#2327]
### User Story:
As the Mocaverse program owner of Moca ID
I want to have a customized Passport experience for my end users
So that I can continue our branding and utilize Gitcoin Passport as Sybil defense for our Moca ID

### Acceptance Criteria
GIVEN a user goes to the /#/dahsboard/mocaverse link
WHEN they arrive on the Passport site
THEN they receive the custom Moca ID experience

The URL for the custom pages will be:
https://passport.gitcoin.co/#/mocaverse/
https://passport.gitcoin.co/#/mocaverse/welcome
https://passport.gitcoin.co/#/mocaverse/dashboard

Update CTA Button 'Join Mocaverse'

They will need the ability to hide all stamps that have 0 score (they will be using those stamps
It's TBD what score weight changes they might want and which stamps they will want to remove. Handle this through work on this dedicated issue: https://github.com/gitcoinco/passport/issues/1993

#### Product & Design Links:

Screenshot of their figma
<img width="519" alt="Screenshot 2024-03-20 at 9 22 13 AM" src="https://github.com/gitcoinco/passport/assets/129878085/d48752d4-7498-4dea-b73d-0c829625c401">

[Moca ID custom component](https://www.figma.com/file/l1mKDZtVzvSC9NqqSyCL9P/Mocaverse?type=design&node-id=0%3A9&mode=design&t=O6Yit0dwqVBPuu9J-1)

Body Text: Moca ID is our decentralized identity (DID) that gives you access to Animoca Brands' 450+ portfolio companies alongside our ever-growing partner ecosystem.

blue: #2450EE

#### Tech Details:
Implement with a dedicated customization db schema etc as specified in this document: https://docs.google.com/document/d/1al3-9oEBwm7wN696KnpTdpDz-yzrh-cmzmjyYJZXa3w/edit

#### Open Questions:

- [ ] Link to Join Mocaverse
- [ ] How to hide stamps with 0 weight

**Comment by Jeremy-Gitcoin** [comment]
@erichfi This is the card for Mocaverse, it's at the back of the backlog (for now), but I'll let you drive prioritization while i'm out.

**Comment by nutrina** [comment]
Some tech documentation: https://docs.google.com/document/d/1al3-9oEBwm7wN696KnpTdpDz-yzrh-cmzmjyYJZXa3w/edit
