### ISSUE TITLE
Stamp and Credential Removals

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2330]
### User Story:
As a Passport development team member, I want to remove specific credentials and their associated stamps from the Passport dashboard and scoring model, while ensuring these credentials and stamps are preserved in the database for analytics purposes. This is to streamline the scoring system for users without losing historical data on credential verification and stamp allocation.

### Acceptance Criteria
GIVEN a list of credentials to be removed,
WHEN we deploy the next update to the Passport platform,
THEN the specified credentials and their solely associated stamps (if the stamp contains no other credentials) are no longer visible or considered in the scoring model for users but are retained in the database for analytics.

#### Tech Details:
- Credentials to be removed:
  - CommunityStakingBronze
  - CommunityStakingGold
  - CommunityStakingSilver
  - GitcoinContributorStatistics#numGrantsContributeToGte#1
  - GitcoinContributorStatistics#numGrantsContributeToGte#10
  - GitcoinContributorStatistics#numGrantsContributeToGte#25
  - GitcoinContributorStatistics#numGrantsContributeToGte#100
  - githubAccountCreationGte#90
  - githubAccountCreationGte#365
  - githubAccountCreationGte#180
  - GuildMember
  - IdenaAge#10
  - IdenaAge#5
  - IdenaStake#100k
  - IdenaStake#10k
  - IdenaStake#1k
  - PHIActivityGold
  - PHIActivitySilver
  - Poh
  - SnapshotVotesProvider
  - twitterAccountAgeGte#180
  - twitterAccountAgeGte#365
  - twitterAccountAgeGte#730
  - ZkSync
  - CyberProfilePremium
  - CyberProfilePaid
  - CyberProfileOrgMember
  - ETHPioneer
- Ensure that data related to these credentials and stamps is preserved in the database for historical analysis and insights.
- Update the dashboard UI to reflect the removal of these credentials and associated stamps.
- Modify the scoring model to exclude these credentials and their solely associated stamps from calculations.
  
#### Notes/Assumptions:

- Assumes that the user base does not need to take any specific actions in response to these removals.
- Assumes the removal process is reversible if needed in the future.
- The database schema and analytics queries will be updated to differentiate between active and decommissioned credentials/stamps for accurate historical analysis.

**Comment by nutrina** [comment]
Questions:
- do we want to remove this stamps from the code? Or via a configuration in admin?
- also we will need to change the weights in the scorers, and recalculate
  - shall we also change the weights in the scorers that are marked as exempt?
  -

**Comment by nutrina** [comment]
Waiting for PR review
