### ISSUE TITLE
Eth Stamp Changes

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2331]
### User Story:
As a Passport user focused on Ethereum (ETH) engagement, I need transparent, updated criteria for the ETH stamp that are easy to understand and follow. This will help me tailor my activities within the Ethereum ecosystem to improve my stamp score efficiently.

### Acceptance Criteria
GIVEN I am aiming to improve my ETH stamp,
WHEN I explore the ETH stamp criteria on the Passport platform,
THEN I find detailed, refreshed criteria with explicit points thresholds, empowering me to grasp how my Ethereum activities influence my score accurately.

#### Product & Design Links:
[Placeholder for links to detailed model documentation and user guidance on the Eth stamp changes]

#### Tech Details:
The Data Team has meticulously prepared an update for the ETH stamp criteria, introducing quantifiable engagement levels for users. This revamp is designed to demystify the path to achieving or enhancing the ETH stamp by providing clear, measurable targets. The updated criteria are categorized into two main sections for clarity and ease of understanding:

1. **Engagement Milestones**
  a. **ETH Enthusiast:** Marks the initiation of engagement within the Ethereum ecosystem. (INTERNAL: ETHScore > 50)
  b. **ETH Advocate:** Represents a higher level of commitment and activity. (INTERNAL: ETHScore > 75)
  c. **ETH Maxi:** Denotes exceptional involvement and dedication. (INTERNAL: ETHScore > 90)
2. **Your Ethereum Activity Metrics**
  a. **Spend more than 0.25 ETH on gas:** Highlights significant financial engagement with the network.
  b. **Execute over 100 transactions:** Indicates a robust level of transactional activity.
  c. **Active on over 50 distinct days:** Showcases sustained interaction with Ethereum.

#### Open Questions:

- [ ] What additional support or resources will be provided to users to help them understand and meet the new criteria?
- [x] What coordination between the Data and Eng Teams is needed to deploy the new model alongside the stamp update?
- [ ] How will feedback from users be collected and used to iterate on the ETH stamp criteria updates?

#### Notes/Assumptions:

- The update aims to enhance user satisfaction by making ETH stamp achievements more attainable and understandable.
- Users are expected to respond positively to clear, actionable criteria, which should drive increased engagement with the Ethereum ecosystem.

**Comment by nutrina** [comment]
For #2 stamps we, need API changes.

**Comment by lucianHymer** [comment]
Pending review
