### ISSUE TITLE
NFT Model Integration and Stamp Update

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2332]
### User Story:
As a Passport user, I'm eager to engage with the NFT model newly introduced to the platform. I aim to comprehend how this model integrates with the NFT stamp adjustments, enabling me to utilize my NFT holdings to enhance my score effectively.

### Acceptance Criteria
GIVEN the deployment of a new NFT model,
WHEN I investigate the influence of NFTs on my Passport score,
THEN I discover thorough insights on the interplay between the NFT model and the existing NFT stamp alterations and their collective impact on my score.

#### Product & Design Links:
NFT model spec by the Data Team: https://docs.google.com/document/d/1-joHQZdLMC7N0pDshFmjsZ1SJgduwfUNG9o4u0y1iv8/edit

#### Tech Details:

The implementation of the NFT model brings a fresh perspective to evaluating NFT holdings within the Passport ecosystem. This model, akin to the ETH model's strategic deployment, introduces nuanced, model-based credentials that reflect the diversity and intrinsic value of users' NFT collections. The integration aims to augment the current NFT stamp by incorporating these new criteria:

1. **Collector's Journey**
  a. **Digital Collector:** Recognizes users beginning to explore the NFT space with a budding collection. (INTERNAL NFTScore > 50)
  b. **Art Aficionado:** Highlights users with a significant, more curated NFT portfolio that demonstrates their deeper involvement and appreciation for digital art and assets. (INTERNAL NFTScore > 75)
  c. **NFT Visionary:** Distinguishes users at the forefront of the NFT movement, showcasing exceptional collections that set trends within the community. (INTERNAL NFTScore > 90)
2. **NFT Ownership Verification**
  a. **NFT Holder:** Verifies users possessing at least one NFT on the Ethereum mainnet, serving as the foundational credential within the NFT stamp category.

**Note:**
- Similar to the ETH model's implementation, the NFT model should be deployed and integrated into the Passport platform privately, with a focus on accurately reflecting the value and diversity of NFT holdings.
- All rules implemented regarding score caching (30 days) and the removal of stamps only upon expiration for the ETH stamp should equally apply to the NFT stamp, ensuring consistency across stamp criteria and user experience.

#### Open Questions:

- [ ] How will users be informed of the value of their NFTs within this new scoring framework?

#### Notes/Assumptions:

- Assumes the NFT model accurately captures the varied landscape of NFT holdings among users.
- Anticipates a smooth transition with comprehensive support and resources available for users to adapt to the new NFT stamp criteria.

**Comment by nutrina** [comment]
What happens to the existing `NFT Holder` stamp? Do we keep that?
Also, when going live with this we'll need to adjust the scorer weights & rescore.

**Comment by lebraat** [comment]
"Similar to the ETH model's implementation, the NFT model should be deployed and integrated into the Passport platform privately, with a focus on accurately reflecting the value and diversity of NFT holdings."

What do you mean by this?

-- 

Also, very glad to hear we are keeping the 'own 1 NFT' as a credential. Nice job on that!
