### ISSUE TITLE
zkSync Model Integration and Enhanced Scoring in zkSync Era

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2373]
### User Story:
As a zkSync Era user,
I want to understand how the zkSync model integrates into the zkSync Stamp,
So that I can leverage my zkSync interactions to enhance my zkSync Era score and access new levels of engagement and rewards.

### Acceptance Criteria
GIVEN the introduction of a new zkSync model,
WHEN I engage with features within the zkSync Era ecosystem,
THEN I should see my interactions reflected in my zkSync Era score, with clear information on the integration of zkSync model tiers and the benefits this brings.

#### Product & Design Links:
[zkSync model specifications link](https://docs.google.com/document/d/1Peq26Ki5XzEfuvUeOHK6k0d_T7Wqf6VaKfLij3JgZb8/edit?usp=sharing)

#### Tech Details:
The zkSync model introduces a tiered system designed to evaluate and reward user engagement based on their activity level and transaction status within the zkSync Era. It comprises three model tiers and a hard-coded section focusing on transaction verification:

**Engagement Levels in zkSync Era**
- **Engagement Explorer:** For users who are actively exploring various features of zkSync Era. (INTERNAL zkSyncScore ≥ 5)
- **L2 Believer:** For users who regularly transact and demonstrate reliance on the zkSync Era platform. (INTERNAL zkSyncScore ≥ 20)
- **zkSync Champion:** For leading users who significantly contribute to and influence the zkSync community. (INTERNAL zkSyncScore ≥ 50)

**Transactional Verification:**
- **Verified Transactor:** Recognizes users whose transactions on zkSync Era have achieved verified status, confirming their active participation and trust in the platform.

**Internal Note:** The model includes standard score caching for 30 days and maintains stamps unless expired, ensuring consistency and fairness.

#### Open Questions:

- [ ] What methods will be used to communicate these model adjustments to the users effectively?
- [ ] Are there plans to introduce additional incentives for users to reach higher engagement tiers within the zkSync community?

#### Notes/Assumptions:

- It is assumed that the zkSync model will accurately measure and reward user engagement based on their interactions with zkSync Era.
- Integration is expected to be user-friendly, facilitating a smooth transition for users to adapt to the new model tiers and scoring criteria.

**Comment by lucianHymer** [comment]
Pending engineer review
