### ISSUE TITLE
Update zkSync sidebar text

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2380]
### User Story:
As a Gitcoin Passport holder
I want to accurate information about the zkSync stamp
So that I can better understand why (not) I qualify for the zkSync stamp

### Acceptance Criteria
GIVEN a Passport holder opens the Civic stamp sidebar
WHEN they see the info text box
THEN they should see a CTA below -- "Learn more" -- incl. a hyperlink leading to the dedicated Knowledge base article for zkSync: https://support.passport.xyz/passport-knowledge-base/how-do-i-add-passport-stamps/zksync-stamp

Text for the text box before the Learn More link:

> Click verify to process your zkSync Era transactions. Passport uses a constantly evolving model to review your transaction history and compare against known Sybil behavior. The number of points you'll receive is based on many factors related to the overall activity of the address.

#### Tech Details:

####Open Questions:

#### Notes/Assumptions:

**Comment by lucianHymer** [comment]
Need the article link when it's ready 🤘

**Comment by lucianHymer** [comment]
@erichfi Do we want to change that URL to something else? Right now it says "-gitcoin-gratnts-to-passport-2" instead of e.g. "-zksync"
