### ISSUE TITLE
Update NFT stamp sidebar text

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2381]
### User Story:
As a Gitcoin Passport holder
I want to accurate information about the NFT stamp
So that I can better understand why (not) I qualify for the NFT stamp

### Acceptance Criteria
GIVEN a Passport holder opens the Civic stamp sidebar
WHEN they see the info text box
THEN they should see a CTA below -- "Learn more" -- incl. a hyperlink leading to the dedicated TBD Knowledge base article for NFT: TBD

Text for the text box before the Learn More link:

> Click verify to process your Ethereum Mainnet NFTs. Passport uses a constantly evolving model to review your NFT activity and compare against known Sybil behavior. The number of points you'll receive is based on many factors related to the overall NFT portfolio of the address.

#### Tech Details:

####Open Questions:

#### Notes/Assumptions:

**Comment by lucianHymer** [comment]
@erichfi There are a few texts that are probably affected by this. What do you think we should do for these? Maybe this?

Current Description: Connect your Ethereum wallet to verify that you own an Ethereum-based NFT. Currently, we only recognize NFTs (ERC-721s).

New Description: Connect your Ethereum wallet to verify your Ethereum Mainnet NFTs.

Current Banner Text: Currently, we only recognize NFTs on the Ethereum main network. So you can't get that stamp through your NFTs on other networks.

New Banner Text: (from above) Click verify to process your Ethereum Mainnet NFTs. Passport uses a constantly evolving model to review your NFT activity and compare against known Sybil behavior. The number of points you'll receive is based on many factors related to the overall NFT portfolio of the address.

Then we maybe change the text for the existing credential from "Holds at least 1 NFT" to "Holds at least 1 NFT (ERC-721)"? That all fits cleanly on one line. We can add "on Ethereum Mainnet" and it'll break across two lines, which still looks fine. But we do clarify Ethereum Mainnet above already.

The platform is also called "NFT Holder", is that still a good name? Or should we just do "NFT" or something?

**Comment by lucianHymer** [comment]
> * Let's keep the text box as it currently is. The information provided aligns well with the functionality described.

So by this, do you mean that we're not going to include the text from the original request? I.e. we will leave it as "Currently, we only recognize NFTs on the Ethereum main network. So you can't get that stamp through your NFTs on other networks." instead of changing it to "Click verify to process your Ethereum Mainnet NFTs. Passport uses a constantly evolving model to review your NFT activity and compare against known Sybil behavior. The number of points you'll receive is based on many factors related to the overall NFT portfolio of the address."

**Comment by lucianHymer** [comment]
Sweet! This needs to be merged after #2332, so I'll wait on that.

One last question @erichfi - should the Learn More link go to the existing NFT article?
https://support.passport.xyz/passport-knowledge-base/how-do-i-add-passport-stamps/connecting-gitcoin-grants-to-passport-2
That one also has the "-grants-..." URL if we want to fix that.

Thanks!
