### ISSUE TITLE
Update Blocknative to include Arbitrum

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#2398]
### User Story:
As an Arbitrum end user
I want to be able to login to Passport
So that I can create and use Pssport

### Acceptance Criteria
GIVEN a user comes to the Passport Dashboard
WHEN they are on the Arbitrum network
THEN they can login and use Passport the same as OP, Eth L1, or any other supported chain

Remove the warning triangle when a user comes to Gitcoin Passport and attempts to login from the Arbitrum network

#### Product & Design Links:
<links>

**Comment by Jeremy-Gitcoin** [comment]
@erichfi I added this 1 point card (per Lucian) to the backlog and put it after the work needed to support the launch next week, feel free to move around as needed.

**Comment by nutrina** [comment]
@Jeremy-Gitcoin Which Arbitrum network exactly?

1. Arbitrum One
2 Arbitrum Nova
3. or both
