### ISSUE TITLE
Support for Multiple Wallets in the Staking App

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#2417]
### User Story:
As an end-user,
I want to connect to the staking app using Metamask, WalletConnect, Brave Wallet, and Coinbase Wallet,
so that I can seamlessly stake and unstake GTC from multiple devices.

### Acceptance Criteria
GIVEN I am an end-user,
WHEN I navigate to the staking app at http://stake.passport.xyz/,
THEN I should be presented with options to connect using:

- **Metamask** (on both desktop and mobile devices)
- **WalletConnect** (across all compatible devices)
- **Brave Wallet** (on supported devices)
- **Coinbase Wallet** (on supported devices)

#### Tech Details:
- Switch over to using Web3Modal, offering support for the four above specified wallet providers.
 
#### Notes/Assumptions:
Ensure compatibility and testing across different platforms and devices for each wallet type.

**Comment by lucianHymer** [comment]
Taking a break from this task.

Right now, you can log in with walletconnect. But switching chains is only sometimes working. And there are some unhandled errors I haven't tracked down yet in (for example sometimes if you manually switch chains in the metamask mobile app connected with walletconnect).

Also, only a handful of testnets are supported by Rainbow wallet mobile, and OP sepolia isn't one of them.

Browser injected wallets seem to work fine still.

**Comment by lucianHymer** [comment]
From Erich, report of issue in `main` branch. Should check this in this branch:

get wagmi error toast and it pops up brave wallet when sign in with ethereum although i didn't select brave

**Comment by lucianHymer** [comment]
Above PR needs to be merged before deployment, but the necessary update has already been done manually in the review env.
