### ISSUE TITLE
Layer3 API Elevation Request

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#2439]
Updated API Elevation request for Layer3

(see details in [Discord](https://discord.com/channels/562828676480237578/1073190200404103218/1235992519213318154))

**Comment by lebraat** [comment]
Updated details are located at the top of this doc: https://docs.google.com/document/d/18ob40SWcJme_RidJzAhhUF5Fbux5o1uGcfV4qH4LNec/edit?usp=sharing

**Comment by nutrina** [comment]
Done
