### ISSUE TITLE
Enable Onchain Passport Push to Arbitrum

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2445]
### User Story:
As a Passport holder,
I want to push my onchain Passport to the Arbitrum network,
So that I can utilize my identity and credentials seamlessly across multiple blockchains and enhance my interoperability within the crypto ecosystem.

### Acceptance Criteria
GIVEN I am a user with a Passport,
WHEN I choose to push my Passport to Arbitrum via the Passport interface,
THEN my Passport should be successfully pushed to the Arbitrum network and verifiable through Arbitrum compatible services.

#### Tech Details:

- Integration of Arbitrum as a supported network in the existing Passport infrastructure.
- ARB - 0xc5093228529547272bE5E58db15a5d36fb2C0424 - validated multisig in SAFE for Passport

**Comment by Jeremy-Gitcoin** [comment]
ARB Safe is validated, I executed the transaction this morning so we should be all set. Let me know you need ARB eth to deploy?!

**Comment by nutrina** [comment]
Putting this on hold
