### ISSUE TITLE
Remove Passport JSON Pop-up Button

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2454]
### User Story:
As a Passport user,
I want the Passport JSON button to be removed from the user interface,
So that I can experience a cleaner and more streamlined interface without unnecessary features.

### Acceptance Criteria
GIVEN I am using the Passport interface,
WHEN I navigate through the platform,
THEN I should no longer see the Passport JSON button that triggers a pop-up displaying the Passport JSON.

#### Tech Details:
- Removal of the button may require changes in both the frontend code where the button is rendered and any backend support that serves the JSON data exclusively for this feature.
- Ensure the removal does not affect other functionalities that may rely on the same JSON data internally.

**Comment by nutrina** [comment]
This is UI only task.
