### ISSUE TITLE
Redesign of Passport Stamp Sidebars for Optimized Credential Verification

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2455]
### User Story:
As a Passport user,
I want the sidebar of each stamp in my Gitcoin Passport to be redesigned,
So that the verification process is more intuitive and efficient, enhancing my overall user experience.

### Acceptance Criteria
**Redesigned Sidebar Interface:**
GIVEN I access any stamp's sidebar in my Gitcoin Passport,
WHEN I view the sidebar,
THEN I should see a newly designed interface that simplifies the process of credential verification, enhancing visual appeal and usability.

**Intuitive Verification Initiation:**
GIVEN the redesigned sidebar is displayed,
WHEN I click the "Verify" button,
THEN the verification process should initiate smoothly with clear visual feedback provided by the new "verifying" state design.

**Re-Verification Enablement on Sidebar Reopen:**
GIVEN I have previously verified a stamp and closed the sidebar,
WHEN I reopen the sidebar,
THEN the "Verify" button should be enabled, allowing me to re-initiate the verification process effortlessly.

**Dynamic and Responsive Feedback System:**
GIVEN that a verification process has been initiated within the redesigned sidebar,
WHEN the process completes,
THEN the sidebar should update the user with dynamic feedback, showing either a success indicator or detailed error messages via an integrated toast notification system.

**Credential Reissuance and Expiry Timer Reset:**
GIVEN a credential is successfully re-verified,
WHEN the verification is confirmed,
THEN the credential should be reissued, and the countdown timer for expiry should reset, reflecting the new validity period directly in the sidebar.

#### Product & Design Links:
[Link to Figma](https://www.figma.com/design/FOOlLEFaBt87atw6CPkA5P/Passport-App?node-id=7194%3A1889&t=x4SDsiMrPaOveUvf-1) for redesigned sidebars

#### Tech Details:

- Implement UI updates to ensure the sidebar is responsive and adheres to new design specifications.
- Optimize backend processes to handle initiation and re-initiation of verifications, including the efficient logging of such events.

#### Notes/Assumptions:

- Assumes that the redesigned sidebars will provide a more streamlined experience, reducing cognitive load and making the process more accessible.
- Assumes that all users will benefit from a clearer, more direct interaction model for managing their credentials.

**Comment by digitalmnt** [comment]
@erichfi Do we have content for what I circled in this screenshot?


![Image](https://github.com/gitcoinco/passport/assets/6887938/11cd4f26-4df6-4a95-92ea-a9aa648139f0)

**Comment by nutrina** [comment]
@erichfi 2 questions:

1. I see we do not have any `onchain` indicator in this design, is this correct?
2. also the remove button has been dropped. I just want o make sure this was on purpose and not omitted.
