### ISSUE TITLE
Enhanced Visual Cues and Information Display on Passport Stamp Cards

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2456]
### User Story:
As a Passport user,
I want clear visual distinctions and informative displays on my stamp cards,
So that I can easily understand and manage the verification status of my stamps.

### Acceptance Criteria
GIVEN I am logged into my Passport account and on the "My Stamps" page,
WHEN I examine individual stamp cards,
THEN I should observe the following enhancements:

- **Progress Bar:** Each stamp card should feature a progress bar indicating the number of points it contributes to my overall score, with visible numeric value for clarity.
- **Color Coding and Labeling:**
  - Stamps that have been verified should be highlighted in green with a "Verified" label.
  - Stamps that have expired should be indicated in red with an "Expired" label and an accompanying "Update" button to initiate re-verification.
  - Stamps that are not yet verified should be presented in a neutral color without any initial labels, signifying that they are awaiting verification.
- **Expiration Information:** Each verified stamp should display the number of days until expiration prominently on the stamp card, providing clear and actionable information to the user.
- **Actionable Steps:** Directly from the stamp card, users should be able to update or reverify their stamps through opening the stamp sidebar.

#### Product & Design Links:
- Link to detailed UI/UX designs for updated stamp cards: https://www.figma.com/design/FOOlLEFaBt87atw6CPkA5P/Passport-App?node-id=8705%3A1398&t=x4SDsiMrPaOveUvf-1

#### Tech Details:

- Update the frontend component library to include new visual elements like progress bars and enhanced color coding.
- Adapt backend APIs to handle enhanced data delivery, including detailed expiration dates and verification status updates.
- Ensure that changes are scalable and maintainable within the existing Passport infrastructure.

#### Notes/Assumptions:

- Assumes that clearer visual cues and detailed information will lead to better user engagement and management of identity verifications.
- Assumes that the system's performance will not be adversely affected by these updates.

**Comment by nutrina** [comment]
Just to be clear, this task does not refer to also change the "Expored stamps" or "Valid stamps" sections in the lower part of the screen.
