### ISSUE TITLE
Implement Robust In-App Notification System for Enhanced User Engagement and Compliance (Frontend)

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2457]
#### User Story:
As a Passport user,  
I want to receive specific, clear, and actionable in-app notifications for my stamp and Passport activities,  
So that I can maintain an up-to-date and compliant identity verification status efficiently.

#### Acceptance Criteria

**Stamp Expiry Notification**  
GIVEN a user has stamps that are about to expire or have expired,  
WHEN the system detects an expiry,  
THEN the user receives a distinct in-app notification for each expired stamp instructing them to reverify.

**On-chain Passport Expiry Notification**  
GIVEN a user’s on-chain Passport on any blockchain (e.g., Arbitrum) is nearing expiration or has expired,  
WHEN they click on the received expiration notification,  
THEN the system should automatically redirect them to the on-chain sidebar where [the expired status is displayed with a clear 'Update' button](https://www.figma.com/design/FOOlLEFaBt87atw6CPkA5P/Passport-App?node-id=6923%3A2896&t=x4SDsiMrPaOveUvf-1).

**Duplicate Stamp Claim Notification**  
GIVEN a user claims a duplicate stamp for the same account across different Passports,  
WHEN the system identifies the duplicate during verification,  
THEN the user receives a notification detailing which wallet contains the original stamp, with a link to learn more about the deduplication policy, and an advisory that removing the duplicate will not affect their score until the other stamp expires.

**Custom Ecosystem Notification**  
GIVEN the PMs configure custom notifications via Django admin for specific events or promotions,  
WHEN such events occur,  
THEN the user receives a notification with a clear message and a hyperlink directing them to an external site or action.

#### Product & Design Links:
Notification UI Designs: [Figma Design - Passport App Notifications](https://www.figma.com/design/FOOlLEFaBt87atw6CPkA5P/Passport-App?node-id=3761%3A36672&t=x4SDsiMrPaOveUvf-1)

#### Tech Details:

- Implement notifications using a combination of sidebar, toaster, and in-app notification mechanisms to ensure visibility and accessibility.
- Ensure the notification system is integrated with real-time monitoring of stamp and Passport statuses.

#### Notes/Assumptions:

- Notifications should prioritize clarity and simplicity to accommodate ESL users effectively.
- The system should be capable of handling multiple notification types without overwhelming the user, adhering to a well-defined priority and urgency system.
- Analytical tracking of user interactions with notifications is necessary to gauge effectiveness and improve future notifications.

#### Notification Event Table:

| Event                                 | User Notification Copy                                                                                | Action                                                  |
|---------------------------------------|-------------------------------------------------------------------------------------------------------|---------------------------------------------------------|
| Stamp Expiry                          | "Your [Stamp Name] stamp has expired. Please reverify to keep your Passport up to date."               | Click "Reverify" to start the reverification process.   |
| On-chain Passport Expiry              | "Your on-chain Passport on [Blockchain Name] has expired. Update now to maintain your active status." | Click on the notification to open the on-chain sidebar with an update button. |
| Duplicate Stamp Claim                 | "You have claimed the same [Stamp Name] stamp in two Passports. We only count your stamp once. This duplicate is in your wallet [Wallet Name]. Learn more about deduplication [here](link)." | No action needed; deduplication will resolve when the older stamp expires. |
| Custom Ecosystem Notification (example) | "Check out this new passport integration! Learn more [here](link)."                                     | Click the hyperlink to visit the partner site.           |

**Comment by nutrina** [comment]
Discussion on how to check & create notifications:
- **Stamp Expiry** - create this notification on the fly, we should have all data required in the ceramic-cache table
- **On-chain Passport Expiry** - create this notification on the fly, it should be possible to query the Decoder SC or the EAS GraphQL service (this would be preffered)
- **Duplicate Stamp Claim** - the notification should be created when the deduplication event occurs in the events table.
- **Custom Ecosystem Notification (example)** - this notifications will be entered manually by the admin and should be assigned to all users

All the detections shall be made in the backend, the UI should be kept as simple as possible. It should only read the list of notifications from the backend.

**Comment by nutrina** [comment]
Brainstorming how the data model should look like with the team:

```py


class Notification(models.Model):
    """

    Stamp Expiry - create this notification on the fly, we should have all data required in the ceramic-cache table
    On-chain Passport Expiry - create this notification on the fly, it should be possible to query the Decoder SC or the EAS GraphQL service (this would be preffered)
    Duplicate Stamp Claim - the notification should be created when the deduplication event occurs in the events table.
    Custom Ecosystem Notification (example) - this notifications will be entered manually by the admin and should be assigned to all users
    """
    # type values:
    # GENERIC - shall be displayed for all addresses
    # ADDRESS_BOUND - should only be displayed for that specific ETH address, and the `address` field is required
    type = models.CharField()
    
    address = EthAddressField()
    message = models.TextField()

    # The time range in which to display notification.
    # Ignore this constraint if null
    start_date = models.DateTimeField(null=True)
    end_date = models.DateTimeField(null=True)


class NotificationDismissal(models.Model):
    notification = models.ForeignKey(Notification)
    address = EthAddressField()
    dismissed = models.BooleanField("")

```

**Comment by octanaiv** [comment]
> @erichfi what is the action that changes the status of the notification from read to unread?

@digitalmnt Here's a link to the figma section
https://www.figma.com/design/FOOlLEFaBt87atw6CPkA5P/Passport-App?node-id=9492-5736&t=NaPL7IWJuI6gbcPc-1

**Comment by digitalmnt** [comment]
Moving to blocked until backend ticket is complete

**Comment by digitalmnt** [comment]
@erichfi  Should we remove the expired notification since stamps are automatically refreshed when the app is loaded?

**Comment by digitalmnt** [comment]
Moving to blocked. Waiting for clarification
