### ISSUE TITLE
 Integrate zkSync, NFT, OP, ARB, and Polygon Scoring Models into API Analysis Endpoint with 30-Day Cache and Single Model Query Restriction

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2459]
### User Story:
As a developer utilizing the Passport API,
I want to retrieve scores for zkSync, NFT, OP, ARB, and Polygon models alongside the existing Ethereum activity scores through the API analysis endpoint,
So that I can assess blockchain addresses comprehensively using predefined scoring metrics.

Additionally, I want to leverage a 30-day cache of scores per model per user and be restricted to querying a single model per request,
So that I can efficiently retrieve individual model scores and follow clear query guidelines.

### Acceptance Criteria
GIVEN a request is made to the API analysis endpoint with a valid Ethereum address,
WHEN the system processes the request using the private zkSync, NFT, OP, ARB, and Polygon models,
THEN the response should include a score from 0 to 100 for the specified model (Ethereum, zkSync, NFT, OP, ARB, or Polygon) based on the respective scoring metrics.

GIVEN a request is made to retrieve a model score for a user,
WHEN the system checks for cached scores,
THEN the response should utilize the cached individual model score if available within the 30-day period.

GIVEN a request is made to the API,
WHEN a developer attempts to query multiple models in a single request,
THEN the system should throw an error and provide a link to documentation on how to choose the right model.

#### Tech Details:

- Update the endpoint to use the private zkSync, NFT, OP, ARB, and Polygon scoring models.
- Ensure the scoring models are accurately applied and securely handled.
- Adjust the API documentation to include details on how scores are calculated and presented.
- Validate the response to ensure a score from the specified model (Ethereum, zkSync, NFT, OP, ARB, or Polygon) is included.
- Implement a caching mechanism to store individual model scores per user for 30 days.
- Ensure the cache is checked before calculating new scores to optimize performance.
- Restrict API requests to query only one model at a time and update documentation with error handling and guidelines.
- Utilize the existing cache for NFT and Ethereum model scores for stamp verification.

#### Open Questions:

- [ ] How will the inclusion of zkSync, NFT, OP, ARB, and Polygon models affect response times?

#### Notes/Assumptions:

- The existing infrastructure is capable of supporting additional scoring models without significant modifications.
- Appropriate permissions for data access and processing are in place for private model usage.
- Lambdas running the models are already provided and operational.
- One cache across API and Stamps is sufficient for storing model scores.

**Comment by lebraat** [comment]
Another open q -- How will the inclusion affect cost?

**Comment by nutrina** [comment]
Tech notes:
- for each model we need the score, we should get the data by calling that models internal API
- also make the requests in parallel by using something like: https://github.com/spyoungtech/grequests

**Comment by nutrina** [comment]
This is solved and already in production
