### ISSUE TITLE
Evaluate Operational Costs for zkSync, NFT, OP, ARB, and Polygon Scoring Integration in API

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2460]
### Objective:
To analyze the operating costs associated with integrating zkSync, NFT, OP, ARB, and Polygon models into our API, focusing on the incremental cost per compute unit and total cost per scoring of an Ethereum address, including data and computation costs.

### Approach:

- Identify the required compute resources for zkSync, NFT, OP, ARB, and Polygon data processing.
- Calculate the cost per compute unit using Alchemy or similar services.
- Estimate the total additional costs per API call, breaking down by data retrieval and processing.

**Timebox:**
Half a development day.

**Deliverables:**

- A cost analysis report detailing:
  - Compute resource usage per API call for Ethereum, zkSync, NFT, OP, ARB, and Polygon models.
  - Cost per compute unit.
  - Total estimated cost per API call including data retrieval and processing.

**Tech Details:**

- Utilize cloud function logs and Alchemy API metrics to gather compute resource data.
- Calculate cost impacts based on current pricing models from cloud and API service providers.

**Notes/Assumptions:**

- The spike assumes that detailed logs and metrics are accessible for the current Ethereum model processing.
- Assumes current pricing from Alchemy or alternative providers is applicable.

**Comment by lucianHymer** [comment]
Added Alchemy costs in Discord thread. Will pair with others to follow up on AWS costs.
