### ISSUE TITLE
Redirect from staking.passport.gitcoin.co to stake.passport.xyz

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2486]

**Comment by lebraat** [comment]
Can we also have staking.passport.xyz point towards stake.passport.xyz?

Wasn't sure if it'd make sense to have that be in-scope for this ticket or open up another ticket.

**Comment by nutrina** [comment]
We'll need to set up some HTTP 302 redirects.

**Comment by lebraat** [comment]
Correct!
