### ISSUE TITLE
[BUG] Staking GTC on OP Not Updating After Six Minutes in Staking V2 App

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2500]
**Overview**
When staking GTC on OP in the Staking V2 app, both in self-staking and staking for others, the GTC balance is reduced accordingly. However, the staked amount does not show up in the staking widgets even after waiting for approximately six minutes. This issue is observed on both Layer 2 solutions and mainnet. The stakes should show up immediately. While the stakes are not displayed, a loading state should indicate that the system is waiting or still processing.

**Steps To Reproduce**

1. Navigate to the Staking V2 app.
2. Select the option for staking GTC on OP.
3. Choose to either self-stake or stake for others.
4. Confirm the staking transaction.
5. Observe the GTC balance reduction.
6. Wait for approximately six minutes.
7. Check the staking widgets for the updated staked amount.

**Observed  behavior**
After staking GTC, the GTC balance decreases as expected, but the staked amount does not appear in the staking widgets even after waiting for approximately six minutes. There is no loading state indicating that the system is processing the transaction.

**Expected behavior**
The staked amount should appear immediately in the staking widgets after the GTC balance is reduced. If the staking process is still ongoing, a loading state should be displayed to indicate that the system is processing the transaction.

**Screenshots**

**Additional context**

**Comment by nutrina** [comment]
@erichfi 

Typically this should work, the new transaction should be shown in about 10 seconds in history.
However, as a fallback, if the transaction is not shown after 3 minutes let's say, shall we indicate to the user to refresh the page or reach out to support if that does not help?

**Comment by nutrina** [comment]
Waiting for review
