### ISSUE TITLE
ENS Names Not Supported for Staking in Staking V2 App

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2501]
**Overview**
When staking GTC for others in the Staking V2 app and inputting an ENS name such as "vitalik.eth", the transaction fails and returns an error indicating that the ENS name is invalid. The app should support ENS names on both ENS and Ethereum mainnet. Additionally, the interface should display ENS names wherever available, instead of normal addresses.

**Steps To Reproduce**

1. Navigate to the Staking V2 app.
2. Select the option for staking GTC for others.
3. Input an ENS name (e.g., "vitalik.eth").
4. Confirm the staking transaction.
5. Observe the error message returned.

**Observed  behavior**
After confirming the transaction using an ENS name, an error message is displayed stating:

```
Stake transaction failed
Error: InvalidAddressError, Details: Address "vitalik.eth" is invalid. - Address must be a hex value of 20 bytes (40 hex characters). - Address must match its checksum counterpart. Version: viem@2.10.3
```

**Expected behavior**
1. The app should allow staking using ENS names on both ENS and Ethereum mainnet without returning an error.
2. For any address with an active ENS name, the app should display the ENS name rather than the normal address in the following places:
  - Stake history
  - Section displaying stakes others made on you
  - Staking modals
  - User's own address
  - Any other relevant interface elements controlled by the app

**Screenshots**

**Additional context**

**Comment by digitalmnt** [comment]
Just waiting for review
