### ISSUE TITLE
Update Terms Agreement Process Copy and Link Identification

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2504]
**Overview**
Update the terms agreement process copy on the staking page. Replace the "Learn more about slashing" link with a placeholder for a work-in-progress link and ensure all links are clearly identifiable as clickable links.

**Current Copy**

> **Acknowledge & Agree to continue**
> Before staking on your identity, please agree to the following:
> 
> I understand that I may be slashed for what is deemed Sybil behavior when using Passport. Slashing criteria will continue to evolve over time. Learn more about slashing conditions.
> 
> I understand that credentials/Stamps may be verified on multiple Passports (ie, the same google account can be verified on two wallets), BUT those wallets should never be submitted to the same application. Learn more about Passport Stamps and wallets.
> 
> I have read, understand, and agree to the Terms and Conditions of Passport's Identity Staking.
> 
> Please note: All three boxes must be checked to enable the "Proceed" button and continue to the app.
> 

**Proposed Copy**

> Acknowledge & Agree to continue
> Before staking on your identity, please agree to the following:
> 
> I understand that I may be slashed for what is deemed Sybil behavior when using Passport. Slashing criteria will continue to evolve over time. [Learn more about slashing conditions.](https://support.passport.xyz/passport-knowledge-base/gtc-staking/passport-slashing)
> 
> I understand that credentials/Stamps may be verified on multiple Passports (i.e., the same Google account can be verified on two wallets), BUT those wallets should never be submitted to the same application. [Learn more about Passport Stamps and wallets.](https://docs.passport.xyz/building-with-passport/major-concepts/deduplicating-stamps)
> 
> I have read, understand, and agree to the [Terms and Conditions of Passport's Identity Staking.](https://stake.passport.xyz/#/terms)
> 
> Please note: All three boxes must be checked to enable the "Proceed" button and continue to the app.

**Steps To Implement**

1. Navigate to the terms agreement process section on the staking page.
2. Replace the current copy with the proposed copy.
3. Ensure that the "Learn more about slashing" link is replaced with a placeholder link ("#") until the final link is available.
4. Verify that all links are clearly identifiable as clickable links in the UI.
5. Confirm that all three checkboxes must be checked to enable the "Proceed" button.

**Acceptance Criteria**

- The current terms agreement process copy is replaced with the proposed copy.
- The placeholder link for "Learn more about slashing" is implemented.
- All links are clearly identifiable as clickable links.
- The "Proceed" button is enabled only when all three checkboxes are checked.

**Comment by nutrina** [comment]
@erichfi  this is updated.

Just to double-check, is the message in MM that we sign ok?



![Image](https://github.com/gitcoinco/passport/assets/8137830/cf0843eb-c24b-4246-bfb9-276637588e65)
