### ISSUE TITLE
[BUG] Staking V2 error: Error loading Community stakes

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#2511]
**Overview**
There's an error while loading the Stake for Others section.

**Steps To Reproduce**
1. Go to staking v2 app
2. Click on the Stake for Others card
3. See error

**Observed  behavior**
https://www.loom.com/share/f9a0e91de32042a7b82318aff0127c0e
As seen in the video, I get a lot of errors in the console similar to this:

GET https://stake.passport.xyz/undefined0x567cfbb92148076a05BbA166dB9Ca781CFBB6816/1 404 (Not Found)
i @ instrumentMethod.js:63
o @ instrumentMethod.js:32
Show 37 more frames

StakeForOthersHistory.tsx:150 Error getting StakeHistory: U {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}code: "ERR_BAD_REQUEST"config: {transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}message: "Request failed with status code 404"name: "AxiosError"request: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}response: {data: '<!DOCTYPE html><html lang="en"><head><meta charSet…p":true,"scriptLoader":[]}\x3C/script></body></html>', status: 404, statusText: '', headers: eb, config: {…}, …}stack: "AxiosError: Request failed with status code 404\n    at https://stake.passport.xyz/_next/static/chunks/pages/_app-b6b3d1b0cc49955b.js:9491:32195\n    at XMLHttpRequest.h (https://stake.passport.xyz/_next/static/chunks/pages/_app-b6b3d1b0cc49955b.js:9491:32335)\n    at eU.request (https://stake.passport.xyz/_next/static/chunks/pages/_app-b6b3d1b0cc49955b.js:9491:37845)\n    at async Object.queryFn (https://stake.passport.xyz/_next/static/chunks/708-4e10c6bc9db2ab6c.js:1:44763)"[[Prototype]]: Error

**Comment by nutrina** [comment]
This is most likely a configuration error in amplify, related to the fact that the latest changes are not yet applied in prod.
