### ISSUE TITLE
[Rate Limit Elevation] Initia XYZ

### ISSUE THREAD

**Issue by lebraat** [gitcoinco/passport#2521]
Email: beer-1@codingcats.xyz
Wallet: 0x3e38EDB8a9Aaa37427E5B1Dbaecce1D252c622ec
API Key name: initia-faucet 
Requested tier: Tier 4

"˝"btw, currently our hourly access users are exceeding 6000. so I think Tier 3 may be slightly lacking.
If possible, we want to get Tier 4 and decrease it to Tier 3 after a few weeks based on demand."

Scorer ID: 7328
IP Address: 35.198.209.57
API Key: 9SJyXmqj

**Comment by nutrina** [comment]
@lebraat 
@larisa17 did take care of this

**Comment by lebraat** [comment]
Thank you!
