### ISSUE TITLE
Implement Robust Notification System for Enhanced User Engagement and Compliance (Backend)

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2523]
#### User Story:
As a Passport user,  
I want to receive specific, clear, and actionable in-app notifications for my stamp and Passport activities,  
So that I can maintain an up-to-date and compliant identity verification status efficiently.

#### Acceptance Criteria

**Stamp Expiry Notification**  
GIVEN a user has stamps that are about to expire or have expired,  
WHEN the system detects an expiry,  
THEN the user receives a distinct in-app notification for each expired stamp instructing them to reverify.

**On-chain Passport Expiry Notification**  
GIVEN a user’s on-chain Passport on any blockchain (e.g., Arbitrum) is nearing expiration or has expired,  
WHEN they click on the received expiration notification,  
THEN the system should automatically redirect them to the on-chain sidebar where [the expired status is displayed with a clear 'Update' button](https://www.figma.com/design/FOOlLEFaBt87atw6CPkA5P/Passport-App?node-id=6923%3A2896&t=x4SDsiMrPaOveUvf-1).

**Duplicate Stamp Claim Notification**  
GIVEN a user claims a duplicate stamp for the same account across different Passports,  
WHEN the system identifies the duplicate during verification,  
THEN the user receives a notification detailing which wallet contains the original stamp, with a link to learn more about the deduplication policy, and an advisory that removing the duplicate will not affect their score until the other stamp expires.

**Custom Ecosystem Notification**  
GIVEN the PMs configure custom notifications via Django admin for specific events or promotions,  
WHEN such events occur,  
THEN the user receives a notification with a clear message and a hyperlink directing them to an external site or action.

#### Tech Details:
- see the details for this implementation here: https://docs.google.com/document/d/11Inya3_iksJesEnOaTRWU3Xn45FBATiFoDg0gHalgrU/edit?usp=sharing
- create a separate **django app** for notifications, implement the models in this new app
- ensure the notification system is integrated with real-time monitoring of stamp and Passport statuses.
- Deduplication checks should be automated and linked to user account data across multiple Passports.

#### Notes/Assumptions:

- Notifications should prioritize clarity and simplicity to accommodate ESL users effectively.
- The system should be capable of handling multiple notification types without overwhelming the user, adhering to a well-defined priority and urgency system.
- Analytical tracking of user interactions with notifications is necessary to gauge effectiveness and improve future notifications.

#### Notification Event Table:

| Event                                 | User Notification Copy                                                                                | Action                                                  |
|---------------------------------------|-------------------------------------------------------------------------------------------------------|---------------------------------------------------------|
| Stamp Expiry                          | "Your [Stamp Name] stamp has expired. Please reverify to keep your Passport up to date."               | Click "Reverify" to start the reverification process.   |
| On-chain Passport Expiry              | "Your on-chain Passport on [Blockchain Name] has expired. Update now to maintain your active status." | Click on the notification to open the on-chain sidebar with an update button. |
| Duplicate Stamp Claim                 | "You have claimed the same [Stamp Name] stamp in two Passports. We only count your stamp once. This duplicate is in your wallet [Wallet Name]. Learn more about deduplication [here](link)." | No action needed; deduplication will resolve when the older stamp expires. |
| Custom Ecosystem Notification (example) | "Check out this new passport integration! Learn more [here](link)."                                     | Click the hyperlink to visit the partner site.           |

**Comment by nutrina** [comment]
Details can be found in this document: https://docs.google.com/document/d/11Inya3_iksJesEnOaTRWU3Xn45FBATiFoDg0gHalgrU/edit?usp=sharing

**Comment by larisa17** [comment]
Moved to blocked until https://github.com/gitcoinco/passport/issues/2457 is code complete

**Comment by digitalmnt** [comment]
https://discord.com/channels/562828676480237578/1132962156015525999/1260985568469323888

**Comment by digitalmnt** [comment]
Reason for blocked: @erichfi or @lebraat we need to know where to direct the user when they have been deduplicated: The link in this ticket links to the github project board "You have claimed the same [Stamp Name] stamp in two Passports. We only count your stamp once. This duplicate is in your wallet [Wallet Name]. Learn more about deduplication [here](https://github.com/orgs/gitcoinco/projects/6/views/link)."

**Comment by lebraat** [comment]
Actually I'd suggest a different location. 

All content in the docs is intended for a developer audience. 

I suggest that we use this link instead: https://support.passport.xyz/passport-knowledge-base/using-passport/common-questions/why-is-my-passport-score-not-adding-up

It likely needs an update to better describe the deduplication, but it's a more appropriate location for the audience.
