### ISSUE TITLE
Create and Extend New Identity Staking Round from June 1 - 30

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2524]
### User Story:
As a user participating in Identity Staking,
I want to continue staking without interruption by having a new staking round from June 1 - 30,
So that I can seamlessly extend my participation and manage my stakes effectively.

### Acceptance Criteria
GIVEN the current Identity Staking round ends on the last day of May,
WHEN the system transitions to June 1,
THEN a new Identity Staking round will automatically start and be the default from June 1 to June 30,
AND the new round should be visible in the user interface as the current active staking round.

#### Tech Details:

- Update the backend logic to create a new staking round starting June 1 and ending June 30.
- Ensure the frontend automatically reflects the new round as the default active round starting June 1.
- Test for smooth transition between rounds without user intervention.
- Update relevant API endpoints to support the new staking round.

#### Notes/Assumptions:

- Assume all backend systems and databases support the creation of new staking rounds without downtime.
- Assume the user interface can handle the transition to a new default round without requiring manual refreshes by users.

**Comment by lucianHymer** [comment]
I added an ENV var, REACT_APP_DISPLAY_V2_OVERLAY, to enable/disable the v2 overlay. This can be managed in the AWS Amplify console

**Comment by lucianHymer** [comment]
This is already deployed, but you can check by choosing the new round from the dropdown in the production UI.

Will set the new round to be the default round tomorrow evening
