### ISSUE TITLE
Arbitrum Not Listed in Networks

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2529]
**Overview**
When a user first logs into the system, the Arbitrum network is not listed among the available networks, despite staking on Arbitrum being implemented.

**Steps To Reproduce**
1. Go to the Staking login page.
2. Log in with valid credentials.
3. Navigate to the networks selection list.
4. Observe the list of available networks.

**Observed  behavior**
The Arbitrum network is missing from the list of available networks.

**Expected behavior**
The Arbitrum network should be included in the list of available networks, allowing users to select it for staking.

**Screenshots**

**Additional context**

**Comment by nutrina** [comment]
This seems to have been fixed already
