### ISSUE TITLE
AllowList Score Weight Assignment and Uploading Address List

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2531]
### User Story:
As a partner,
I want to create a custom stamp that pre-approves users based on a predefined list of addresses,
So that I can streamline the verification process for trusted users in my campaign.

### Acceptance Criteria
**Score Weight Assignment**
GIVEN the product team is configuring the score weights of the partner's custom dashboard
WHEN the product team sets a score weight for the stamp
THEN the system should accept any two decimal number greater than 0 as the score weight.

**Uploading Address List**
GIVEN the product team has received a list of addresses from a partner
WHEN the product team accesses the Django admin interface
THEN the product team should be able to upload a CSV file containing a simple list of addresses
AND the system should validate the format and store the list securely.

#### Tech Details:

- **Admin Interface:** Implement CSV upload functionality in Django admin for the product team to upload address lists received from partners.
- **Score Weight Configuration:** Allow the product team to set a numeric weight with two decimal precision greater than 0 on behalf of the partners.

**Comment by nutrina** [comment]
https://docs.google.com/document/d/1wFnZyq_UfA0PDc_Doh3srVPAFnTzLYkgPVgK1gZ5xww/edit?usp=sharing

**Comment by nutrina** [comment]
- move the model to the `account` app
- make the AllowList owned by an account (ad link to Account)
- make sure there is 1-1 relation between customisation and scorer (we want to avoid conflicts)
- in the customisation dashboard allow the admin to link multiple allow-lists
- also allow the admin to set the weight for the stamps from each allowlist in the customisation django admin (use django admin inline)
- forget about the `status` field

**Comment by lucianHymer** [comment]
@nutrina I think I'll skip the account owner for now, since we aren't using it yet and it'll be easy to add in the future, when we have a better idea of exactly how we'll handle allowing users to do these customizations themselves. Let me know if you disagree! It would be easy to add this to the followup ticket https://github.com/gitcoinco/passport/issues/2578

**Comment by lucianHymer** [comment]
Instructions here https://docs.google.com/document/d/1wFnZyq_UfA0PDc_Doh3srVPAFnTzLYkgPVgK1gZ5xww/edit

Currently, my changes are only suggestions in this doc so I'm not sure if you'll be able to see them. You should see a few screenshots in the "Preparing the Allow-List" section.
