### ISSUE TITLE
AllowList Verification Process and Integration with Web3 1-Click Flow

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2532]
### User Story:
As a partner,
I want to create a custom stamp that pre-approves users based on a predefined list of addresses,
So that I can streamline the verification process for trusted users in my campaign.

### Acceptance Criteria
**Verification Process**
GIVEN a user clicks the Verify button on a custom dashboard
WHEN the system checks the user's address against the uploaded list
THEN if the address is on the list, the user should be awarded points as per the configured score weight
AND if the address is not on the list, an error message should be displayed: "You are not on the allowlist of this campaign."

**Integration with Web3 1-Click Flow**
GIVEN a user is undergoing the web3 1-click verification process
WHEN the process includes the AllowList Stamp check
THEN the system should seamlessly integrate this check within the existing onboarding flow.

#### Tech Details:

- Verification Integration: Incorporate the AllowList Stamp check within the established web3 1-click verification flow.
- Error Handling: Display a specific error message if a user is not on the allowlist.

**Comment by digitalmnt** [comment]
Does this include building the endpoint within the scorere?

**Comment by digitalmnt** [comment]
@erichfi could you please point me to the designs abd description for the custom stamp? We could also use the logo from the custom dashboard?
