### ISSUE TITLE
Setting Up Separate Rate Limits for the MBD Endpoint

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2540]
### User Story:
As a developer utilizing the MBD endpoint of the Passport API,
I want to have clearly defined rate limits,
So that I can manage my usage effectively while allowing for flexibility in adjusting limits as needed.

### Acceptance Criteria
GIVEN a request is made to the MBD endpoint,
WHEN the system processes the request,
THEN the response should adhere to the set rate limits for the respective tiers.

GIVEN a request is made to the MBD endpoint,
WHEN the system processes the request,
THEN the request should count towards the rate limit, regardless of whether the score was cached or not.

#### Tech Details:

- Implement separate rate limits for the MBD endpoint.
- Initial rate limits to be set as follows:
  - Base Tier: 15 requests per 15 minutes, up to 1440 requests per day.
  - Tier 2: 350 requests per 15 minutes, up to 33600 requests per day.
  - Tier 3: 2000 requests per 15 minutes, up to 192000 requests per day.
- Ensure these rate limits are completely separate from the existing Passport API rate limits.
- Count every request to the MBD API towards the rate limit, regardless of whether the score was cached.
- Allow flexibility for future adjustments to the rate limits based on usage patterns and pricing strategies.

#### Open Questions:

- [ ] How will we monitor and enforce the rate limits effectively?
- [ ] What mechanisms will be in place to handle requests that exceed the rate limits?

#### Notes/Assumptions:

- These rate limits are introduced to manage partner usage and to test different pricing options without allowing partners to become accustomed to higher limits prematurely.
- The tier system is designed to support varying levels of usage, from small campaigns to larger projects.

**Comment by lebraat** [comment]
@erichfi -- Let's reduce the base tier for the rate limit to 15 per 15 minutes.
