### ISSUE TITLE
Make all hyperlinks in the Passport app consistent with the standard style

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2544]
### User Story:
As a Passport user,
I want to see consistent hyperlink styles across the app,
So that I can easily identify and interact with links, enhancing my overall user experience.

### Acceptance Criteria
GIVEN I am navigating the Passport app,
WHEN I view any hyperlink,
THEN the hyperlink should follow the standard style shown in the attached screenshot, including color, font, and underline.

GIVEN I am in the sidebar,
WHEN I view any hyperlink,
THEN the hyperlink should follow the standard style shown in the attached screenshot, ensuring consistency throughout the app.

#### Product & Design Links:
Example:
![Image](https://github.com/gitcoinco/passport/assets/59769856/a8a6714b-35c4-47fe-b6c8-f89a1492f8d9)

#### Tech Details:

- Ensure all hyperlinks in the Passport app use the CSS class defined for the standard hyperlink style.
- Audit existing hyperlinks to identify and update those not following the standard style.
- Test the hyperlinks across various screens and components to ensure consistency.

**Comment by lucianHymer** [comment]
@erichfi Do we also want to change the links in the footers? I'm guessing not



![Image](https://github.com/gitcoinco/passport/assets/19908762/ce86abde-1fdc-413c-b4d5-f0fba7d2437e)
