### ISSUE TITLE
Exclude Leaderboard from ID Staking Footer

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2547]
**Overview**
Currently, the ID Staking footer contains a link to the Leaderboard. Since the Leaderboard feature is not yet implemented, this link should be removed to avoid confusion.

**Steps To Reproduce**

- Go to the ID Staking page.
- Scroll down to the footer section.
- Observe the available links in the footer.

**Observed  behavior**
The footer contains a link to the Leaderboard, which leads to a non-existent page or placeholder.

**Expected behavior**
The footer should not contain a link to the Leaderboard until the feature is implemented and ready for use.

**Screenshots**

**Additional context**

**Comment by nutrina** [comment]
I cannot see the Leaderboard in the footer any more, this seems to have been taken care of.
