### ISSUE TITLE
GTC Staking App Not Updating GTC Balance on Arbitrum

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2548]
**Overview**
The GTC Staking app is not updating the GTC balance on the Arbitrum network promptly after a trade. The network selector modal fails to display the updated GTC balance several seconds after the transaction. The balance should be updated in near real-time to reflect accurate information.

**Steps To Reproduce**

1. Perform a trade involving GTC on the Arbitrum network.
2. Wait for several seconds after the trade is completed.
3. Open the network selector modal.
4. Observe the displayed GTC balance.

**Observed  behavior**
The GTC balance in the network selector modal does not update promptly after the trade. The balance remains unchanged for several seconds or more, failing to show the correct amount of GTC held on the Arbitrum network.

**Expected behavior**
The GTC balance should update in near real-time after a trade, accurately reflecting the current amount of GTC held on the Arbitrum network in the network selector modal.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by nutrina** [comment]
This works now in review & staging
