### ISSUE TITLE
Staking GTC on Self Fails on Arbitrum

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2549]
**Overview**
When attempting to stake GTC on oneself on the Arbitrum network, the transaction fails with an error message indicating a contract function execution error.

**Steps To Reproduce**

1. Go to the GTC Staking app.
2. Ensure you are on the Arbitrum network.
3. Attempt to stake GTC on your own account.
4. Observe the error message that appears.

**Observed  behavior**
The following error message is encountered when trying to stake GTC:

```
Failed
Spending approval transaction failed

Error: ContractFunctionExecutionError, Details: HTTP request failed. URL: wss://arb-mainnet.g.alchemy.com/v2/a7epCjM_Z26K1-muhP-E686PldO6wUeX Request body: {"method":"eth_call","params":[{"data":"0x095ea7b3000000000000000000000000d2747b3e715483a870793a6cfa04006c00cd597d0000000000000000000000000000000000000000000000004563918244f40000","from":"0xdd80F1387D10B55525D390849264cFdE938dC8de","to":"0x7f9a7DB853Ca816B9A138AEe3380Ef34c437dEe0"},"latest"]} Raw Call Arguments: from: 0xdd80F1387D10B55525D390849264cFdE938dC8de to: 0x7f9a7DB853Ca816B9A138AEe3380Ef34c437dEe0 data: 0x095ea7b3000000000000000000000000d2747b3e715483a870793a6cfa04006c00cd597d0000000000000000000000000000000000000000000000004563918244f40000 Contract Call: address: 0x7f9a7DB853Ca816B9A138AEe3380Ef34c437dEe0 function: approve(address _spender, uint256 _value) args: (0xd2747B3e715483A870793a6Cfa04006C00Cd597D, 5000000000000000000) sender: 0xdd80F1387D10B55525D390849264cFdE938dC8de Docs: https://viem.sh/docs/contract/simulateContract Details: Failed to fetch Version: viem@2.10.3

```

**Expected behavior**
The GTC staking transaction should succeed, allowing users to stake GTC on themselves without errors.

**Screenshots**

**Additional context**

**Comment by nutrina** [comment]
@erichfi  this has worked for me. Can you please try again? If it consistently fails, then we should pair and debug together.
