### ISSUE TITLE
Unable to Sign Into GTC Staking App

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2551]
**Overview**
Users are unable to sign into the GTC Staking app. This issue prevents access to staking functionalities and needs immediate resolution.

**Steps To Reproduce**

1. Go to the GTC Staking app login page.
2. Connect valid wallet.
4. Attempt to sign in.
5. Observe the behavior after attempting to sign in.
 
**Observed  behavior**
Users are unable to sign in to the GTC Staking app. The sign-in process fails, and users remain on the login page without access to the app's features.

**Expected behavior**
Users should be able to sign in to the GTC Staking app with valid credentials and gain access to all functionalities.

**Screenshots**

**Additional context**

**Comment by nutrina** [comment]
This is working now @erichfi
