### ISSUE TITLE
Include Citizens Round 3 and GG20 in Gitcoin Stamp

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2561]
### User Story:
As a Gitcoin user,
I want to have my contributions and achievements from Citizens Round 3 and GG20 reflected in the Gitcoin stamp,
So that I can showcase my full participation and support within the Gitcoin community.

### Acceptance Criteria
GIVEN a user has participated in Citizens Round 3 and/or GG20,
WHEN they check their Gitcoin stamp,
THEN their contributions and achievements from these events are accurately reflected in the stamp.

#### Product & Design Links:
Round data: https://drive.google.com/drive/folders/11l5lEo-_7n_WdhS1Y0Xr6ynqHfcqhi0M

#### Tech Details:

- Integrate data from Citizens Round 3 and GG20 events into the Gitcoin stamp.
- Ensure compatibility with existing Gitcoin stamp infrastructure.
- Validate data accuracy and consistency.

#### Open Questions:

- [ ] How will updates to the Gitcoin stamp be communicated to users?

#### Notes/Assumptions:

- It is assumed that data from Citizens Round 3 and GG20 is readily available and accessible.
- User interface adjustments may be required to display the new data points.

**Comment by nutrina** [comment]
See guide for importing data here: https://www.notion.so/gitcoin/cGrants-Data-Grants-Data-onchain-82e0bbff530241778119d546b65bc072?pvs=4#45cffa0fadf84ab9b13e58608b321d90

**Comment by nutrina** [comment]
@stefi-says could you please look into this?

There are problems in the data to be imported:
1. 🔴 citizen_round_3_all_transactions.jsonl - missing or wrongly named fields: `amountUSD`  
3. 🔴 citizen_round_3_inelegible_address_updated.jsonl  - completely wrong data set, this looks like a list of transactions and not a sybil list.
4. 🔴  gg20_all_transactions.jsonl  - missing or wrongly named fields: `amountUSD`  
5. ✅  gg20_inelegible_address_updated.jsonl

**Comment by nutrina** [comment]
Also, fixes have been made in the squelched users input script command, as it was not handling the csv properly.

**Comment by stefi-says** [comment]
Hey @nutrina I have fixed the files, could you check please? They are on the same folder as before: 
https://drive.google.com/drive/folders/11l5lEo-_7n_WdhS1Y0Xr6ynqHfcqhi0M
