### ISSUE TITLE
Update the scoring function & API to also count the `allow-list` stamps

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#2578]
### User Story:
As a Passport or API user, when my Passport score is calculated for a scorer linked to a custom dashboard with allow-lists, then I want the score to also count my allow-list stamps (if I have any).

### Acceptance Criteria
GIVEN I am a passport user
WHEN I claim an allow-list stamp in Passport
THEN I want the displayed score to also account for my allow-list stamps

GIVEN I call the `/registry/submit-passport` API on a scorer linked to a custom dashboard
AND I have custom allow-list stamps
WHEN I claim an allow-list stamp in Passport
THEN I want the returned score to also account for my allow-list stamps

#### Product & Design Links:
n.a.

#### Tech Details:
n.a.

#### Open Questions:
n.a.

#### Notes/Assumptions:
n.a.

**Comment by lucianHymer** [comment]
Mostly done. To be completed after https://github.com/gitcoinco/passport/issues/2532
