### ISSUE TITLE
[Traction] Add Google Measurement IDs to the staking and passport sites

### ISSUE THREAD

**Issue by lebraat** [gitcoinco/passport#2580]
Add Google Measurement IDs to the header of the following site:

stake.passport.xyz -- G-XHXGR14F2B

**Comment by Jkd-eth** [comment]
@lebraat This isn't working properly and we should re-open?

**Comment by lebraat** [comment]
Correct -- You can see that no data has been received for this website yet here:
https://analytics.google.com/analytics/web/?authuser=0#/p440420326/reports/intelligenthome?params=_u..nav%3Dmaui

I just added the eng team's @gitcoin.co email addresses to our Google Analytics instance so they can review tagging instructions and verify if they need.

**Comment by lucianHymer** [comment]
Waiting to see if data shows up

**Comment by lebraat** [comment]
Confirming that data is showing up properly!
