### ISSUE TITLE
Claim Eth from contracts to multisig

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#2587]
### User Story:
As the Passport team
I want to move the ETH from our smart contracts to our multisigs
So that I can bridge to mainnet treasury

### Acceptance Criteria
GIVEN Eth on the following smart contracts below
WHEN we execute the withdraw function
THEN the ETH is moved to our chain multisigs

Move the following amounts from the onchain contracts to the multisigs on each chain:
[OP](https://optimistic.etherscan.io/address/0xa8eD4d2C3f6f98A55cdDEd97C5aE9B932B0633A4) = 20 ETH
[Linea](https://lineascan.build/address/0xc94aBf0292Ac04AAC18C251d9C8169a8dd2BBbDC) = 48 ETH (Let's start with 1 ETH to make sure everything is flowing well before we execute the remaining) 
[ARB](https://arbiscan.io/address/0xc4858e4d177bf0d14571f91401492d62aa608047) = 3 ETH
[zkSync](https://explorer.zksync.io/address/0xfCC2d308FD4De098D08f056c424C969d728912bF) = 3 ETH

Multisigs
[OP](https://app.safe.global/home?safe=oeth:0x16883ef6737bd243BB638Bd09b0C31c47F34D258)
[Linea](https://safe.linea.build/balances?safe=linea:0x9A40A259B441C942A22227D5D22bA86dD2E7BFe0)
[ARB](https://app.safe.global/home?safe=arb1:0xc5093228529547272bE5E58db15a5d36fb2C0424) 
[zkSync](https://app.safe.global/home?safe=zksync:0xC6D1619564DEC7bB5323D6520bfAbCb1b271D26E)

#### Product & Design Links:
<links>

**Comment by nutrina** [comment]
Waiting for feedback on transaction execution

**Comment by nutrina** [comment]
The attached branch is for the upgrade of the OP Verifier deployment, as it still uses the old version of the withdraw method (the one that withdraws all).

**Comment by nutrina** [comment]
Waiting for review

**Comment by Jeremy-Gitcoin** [comment]
@nutrina I think we can move & close this one!
