### ISSUE TITLE
Launch Outdid Stamp with 10 Points and Assign to Gov ID Category

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2601]
### User Story:
As a user of the Passport app,
I want to access the Outdid Stamp with 10 points attached and see it categorized under Gov ID,
So that I can enhance my identity verification and benefit from increased points for using government-verified credentials.

### Acceptance Criteria
GIVEN the Outdid Stamp feature is currently behind a feature flag,
WHEN the feature flag is removed,
THEN the Outdid Stamp should be available to all users with 10 points attached and categorized under the Gov ID category.

#### Tech Details:

- Ensure the Outdid Stamp is correctly moved from the feature-flagged state to general availability.
- Assign 10 points to the Outdid Stamp in the system.
- Categorize the Outdid Stamp under the Gov ID category within the app.
- Update any relevant databases, APIs, and UI components to reflect these changes.

**Comment by nutrina** [comment]
@lebraat just tagging you on this, it will probably go out with next weeks release.
Not sure if we need any doc changes.
