### ISSUE TITLE
[UI] Give users details about the wallet they are using for their current Trust Bonus score.

### ISSUE THREAD

**Issue by Etovardesign** [gitcoinco/passport#261]
As a Passport holder, I want to see the wallet and stamps saved to my Trust Bonus score.

GIVEN I have scored and saved my passport to Gitcoin.co with "wallet_address_1",
WHEN I switch to "wallet_address_2",
AND I try to refresh my Passport,
THEN I see a modal with information about "wallet_address_1", 
AND I'm able to Reset or Unlink "wallet_address_1",
THEN the Trust Bonus page defaults back to step one "Create Passport".

![Image](https://user-images.githubusercontent.com/100154376/175338325-7158a76c-d82e-4aa1-9e2d-23fcf96fb15d.png)

**Comment by Etovardesign** [comment]
@leoneric so you're in the loop, I added this ticket from some feedback we got last night.

Figma: https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/Passport?node-id=2719%3A48470

**Comment by nutrina** [comment]
A PR for this has been opened: https://github.com/gitcoinco/web/pull/10707

These are some screenshots of the various cases:
<img width="1105" alt="Screenshot 2022-06-29 at 12 06 27" src="https://user-images.githubusercontent.com/8137830/176432468-47957a00-b32b-47b4-b8de-e09a1b646f92.png">
<img width="1105" alt="Screenshot 2022-06-29 at 12 06 45" src="https://user-images.githubusercontent.com/8137830/176432474-3a367864-00b7-4b64-9497-724557f889b9.png">
<img width="1105" alt="Screenshot 2022-06-29 at 12 07 08" src="https://user-images.githubusercontent.com/8137830/176432478-63ff5226-9047-4dd2-924d-43acc8c8c15b.png">
<img width="1105" alt="Screenshot 2022-06-29 at 12 09 25" src="https://user-images.githubusercontent.com/8137830/176432482-accf3739-c8c2-49ad-bd47-f98bf92bfbc9.png">
<img width="1105" alt="Screenshot 2022-06-29 at 15 02 44" src="https://user-images.githubusercontent.com/8137830/176432486-39d255f1-9a37-4739-a9a9-26adbbb2882d.png">
<img width="1213" alt="Screenshot 2022-06-29 at 15 05 26" src="https://user-images.githubusercontent.com/8137830/176432492-98344105-e989-4dfc-b364-37ec9ef24f84.png">
<img width="1213" alt="Screenshot 2022-06-29 at 15 05 49" src="https://user-images.githubusercontent.com/8137830/176432493-7f323ccb-96ac-40d9-9b51-7ed8915d6f58.png">

**Comment by nutrina** [comment]
This has been deployed to production, however only users that recalculate their trust bonus score are able to see this.
