### ISSUE TITLE
Enable onchain Push to Scroll

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#2613]
### User Story:
As a Passport holder,
I want to push my onchain Passport to the Scroll network,
So that I can utilize my identity and credentials seamlessly across multiple blockchains and enhance my interoperability within the crypto ecosystem.

### Acceptance Criteria
GIVEN I am a user with a Passport,
WHEN I choose to push my Passport to Scroll via the Passport interface,
THEN my Passport should be successfully pushed to the Scroll network and verifiable through Scroll compatible services.

#### Product & Design Links:

[EAS deployed on Scroll](https://github.com/ethereum-attestation-service/eas-contracts?tab=readme-ov-file#deployments)

#### Tech Details:

- Integration of Scroll as a supported network in the existing Passport infrastructure.
- Scroll - scr:0xc5093228529547272bE5E58db15a5d36fb2C0424 - validated multisig in SAFE for Passport

**Comment by nutrina** [comment]
Waiting to review & discuss the changes in `eas-proxy`
