### ISSUE TITLE
Scroll Canvas: Scroll Custom Dashboard

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#2615]
### User Story:
As a Scroll Canvas user
I want to easily obtain my Passport and mint Passport onchain to Scroll
So that I can obtain the Passport Badge on Scroll Canvas

### Acceptance Criteria
GIVEN a user is on Scroll Canvas
WHEN they click the button for Passport
THEN they are brought to a custom scroll Dashboard (/scroll)

GIVEN a user comes to the Scroll custom dashboard
WHEN they click the button mint attestation or 'bring onchain'
THEN they only see the Scroll network

#### Product & Design Links:

- [ ] Need to design a custom scroll module similar to Verax

**Comment by lucianHymer** [comment]
We should probably take the custom onchain button from Verax and make it a generic component.

Then in the admin, do something like having a dropdown to choose "Simple Link" or "Onchain Push" for the action button.

**Comment by Jeremy-Gitcoin** [comment]
@lucianHymer Let's talk about this in planning tomorrow. I agree if that's not a significant amount of additional work it's probably the better way to go, but in cases like this I may not be able to design the component to look and work as well as you might, not sure if you'd just use the dashboard in that case or hard code something?

**Comment by lucianHymer** [comment]
https://www.figma.com/design/FOOlLEFaBt87atw6CPkA5P/Passport-App?node-id=10988-9115&t=7htPrSzw4ZQhQQRZ-1
