### ISSUE TITLE
Delete Non-Web3 Stamp Data for Specific User

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2620]
**User Verification:**
- Etherscan Signature Verification: [Verify the sig](https://etherscan.io/verifySig/252273)
- Wallet Address: 0x7ca5eee289d429a26f7f5dbe8e233f6c67ec0e44

**Objective:**
Remove all non-web3 stamp data associated with the specified user in the Passport system.

**Acceptance Criteria:**

1. **User Verification:** 
  - Confirm that the user verification is valid using the provided Etherscan signature verification link.
2. **Data Identification:** 
  - Identify all stamp data entries for the user with wallet address `0x7ca5eee289d429a26f7f5dbe8e233f6c67ec0e44`.
  - Filter out all stamp data that is classified as non-web3. Ensure that web3-related stamp data is not affected.
3. **Data Deletion:**
  - Delete all identified non-web3 stamp data entries from the Passport system.
  - Ensure the integrity and consistency of the remaining user data.
4. **Testing and Validation:**
  - Verify that all non-web3 stamp data has been successfully deleted.
  - Confirm that no web3 stamp data for the user has been unintentionally removed or altered.
  - Perform thorough testing to ensure no adverse effects on the Passport system.
5. **Documentation:**
- Document the process, including methods used for identifying and deleting the non-web3 stamp data.
- Record any issues encountered and how they were resolved.

**Communication:**
- Inform the user via Yuki upon successful completion of the task.
- Provide a summary of the actions taken and confirm that the non-web3 stamp data has been cleared.

**Comment by nutrina** [comment]
Waiting for response on question in DM
