### ISSUE TITLE
Infra Week: Pull Secrets & Env Vars from 1Password

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2626]
**User Story:**
As a **developer**, I want to **pull secrets and environment variables from 1Password in our GitHub Actions**, so that I can **securely manage secrets and environment variables in the new Passport XYZ organization**.

**Acceptance Criteria:**
GIVEN the new Passport XYZ organization,
WHEN I configure GitHub Actions,
THEN secrets and environment variables should be pulled from 1Password using the specified reference syntax.

**Tech Details:**
- Integrate 1Password with GitHub Actions.
- Use secrets reference syntax: `op://Passport-CI/[repo-name]-[environment]/[app/service]/field-name`.
- Test integration with example secrets from the 1Password vault.

**Open Questions:**
- [x] Are there any specific secrets that need to be tested first?

**Notes/Assumptions:**
- Assume the 1Password integration documentation is up-to-date.

**Comment by nutrina** [comment]
Starting this work on the passport repo.

**Comment by nutrina** [comment]
Closing this as it will be covered by other tasks.
