### ISSUE TITLE
Infra Week: Automate AWS Secret Manager Values Update in 1Password

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2627]
**User Story:**
As a **devops engineer**, I want to **automate the update of AWS secret manager values in 1Password**, so that I can **ensure secrets are always up-to-date without manual intervention**.

**Acceptance Criteria:**
GIVEN the automated script,
WHEN it runs,
THEN secret manager values should be updated in 1Password automatically and accurately, excluding the VC secrets / signers though.

**Tech Details:**
- Develop a script to update secret manager values in 1Password.
- Test the automation process for accuracy and reliability.

**Open Questions:**
- [ ]  How frequently should the script run to update secrets?

**Notes/Assumptions:**
- Assume the script will be run in a secure environment.

**Comment by lucianHymer** [comment]
This will pull values from 1P into AWS Secrets Manager during the CI pipeline
