### ISSUE TITLE
Infra Week: Rework and Modularize Workflows for Passport Repos - passport-scroll-badge-service

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2629]
**User Story:**
As a **devops engineer**, I want to **rework and modularize the workflows for the passport repositories**, so that I can **ensure efficient and maintainable CI/CD processes**.

**Acceptance Criteria:**
GIVEN the modularized workflows,
WHEN they are set up,
THEN they should cover the following tasks efficiently and maintainably:
  - Dockerize Workflows for Review, Staging, and Production
  - Deploy App Workflows
  - Deploy IAM Workflows
  - CI Workflow
  - Release & Deploy Workflow
  - Verify On-Chain State

**Tech Details:**
- Implement and modularize the following workflows based on detailed documentation:
  - `dockerize-review.yml`, `dockerize-staging.yml`, and `dockerize-production.yml`
  - `deploy-app-review.yml`, `deploy-app-staging.yml`, and `deploy-app-production.yml`
  - `deploy-iam-review.yml`, `deploy-iam-staging.yml`, and `deploy-iam-production.yml`
  - `ci.yml`
  - `release-and-deploy.yml`
  - `verify-onchain-state.yml`
- Ensure each workflow runs the necessary test suites and checks for inconsistencies in the on-chain state.

**Open Questions:**

- [ ]  Are there specific test suites that need to be run for each environment?

**Notes/Assumptions:**
- [Detailed documentation](https://docs.google.com/document/d/1hs6iPijICbSVRd9H39Vpw6oe3gZ7IQsPJBuErqS8pyo/edit?usp=sharing) is available and up-to-date here.

**Comment by nutrina** [comment]
### Prerequisites
- repos are moved to `passportxyz` org

### Tech notes
- drop usage of env vars & secrets managed in GH, pull them directly from 1P instead
- for private repos we shall keep the pattern as in the `passport-scroll-badge-service` repo (no pause steps)
- for the public repo we should keep the release workflow as we have in the `passport` repo with the pause steps to confirm:
  - staging has been tested
  - db changes have been applied
  - pulumi preview

**Comment by nutrina** [comment]
@erichfi we should split this up, make 1 task for each repo:

1. `passport-scroll-badge-service`
2. `passport-data-science`
3. `passport`
4. `identity-staking-app`
5. `passport-scorer`

**Comment by Jeremy-Gitcoin** [comment]
Split the original card into several stories

@erichfi we should split this up, make 1 task for each repo:

1. `passport-scroll-badge-service` 2 points - #2629
2. `passport-data-science` 2 points - #2685 
3. `passport` 3 points - #2684 
4. `identity-staking-app` 3 points - #2683 
5. `passport-scorer` 3 points - #2682

**Comment by nutrina** [comment]
This is in a good spot ( https://github.com/passportxyz/passport-scroll-badge-service/actions/runs/10008414868 ), what is still open:
- merge in the lates fixed from the gitcoinco org
- test the release to production
- test the release workflow

Picking up #2682 first to test that the same concepts / actions can be reused on other repos as well.
