### ISSUE TITLE
Scroll Canvas: Eligibility API + claim API

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#2640]
### User Story:
As a Scroll Canvas user
I want to be able to claim a badge 
So that I can prove my humanity within the Scroll ecosystem

### Acceptance Criteria
GIVEN a user goes to Passport and has a valid Passport (score > 0)
GIVEN a user has already minted a Scroll Canvas
WHEN they have a passport score > 0
THEN they can mint the Passport Badge in their Canvas

Originally part of issue #2614 

Link to [Badge Contract](https://github.com/scroll-tech/canvas-contracts/blob/master/docs/badges.md)

- [ ]  Deploy an `AttesterProxy`
- [ ]  **Provide these pieces of information for the Scroll team:**
    - eligibility API
    - claim API

#### Product & Design Links:
<links>

**Comment by Jeremy-Gitcoin** [comment]
@nutrina @digitalmnt I created the story to break the original apart. I _think_ this is in progress but leaving it here for you to move!

**Comment by digitalmnt** [comment]
These changes are merged! Will definitely want to test once contracts are deployed
