### ISSUE TITLE
Redirect from staking.passport.gitcoin.co to stake.passport.xyz and from staking.passport.xyz to stake.passport.xyz

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2641]
### User Story:
As a user of Passport's staking service,
I want to be automatically redirected to the correct URL,
So that I can have a seamless and consistent experience when accessing staking services.

### Acceptance Criteria
GIVEN the user accesses `staking.passport.gitcoin.co`
WHEN the user enters the URL in their browser
THEN they are redirected to `stake.passport.xyz`

GIVEN the user accesses `staking.passport.xyz`
WHEN the user enters the URL in their browser
THEN they are redirected to `stake.passport.xyz`

#### Product & Design Links:
N/A

#### Tech Details:

- Implement server-side redirects for both URLs.
- Ensure HTTPS is properly configured and maintained during the redirection.
- Test the redirection to ensure no loss of functionality or security issues.

#### Open Questions:

- [ ] Are there any specific analytics or tracking parameters that need to be preserved during the redirection?
- [ ] Should we inform users of the change, or will the redirect be sufficient?

#### Notes/Assumptions:

- It is assumed that all services currently available at `staking.passport.gitcoin.co` are also available at `stake.passport.xyz`.
- No user data should be lost during the redirection process.
- This change aims to unify the URLs for better user experience and brand consistency.

**Comment by larisa17** [comment]
staking.passport.xyz -> is live 
for making staking.passport.gitcoin.co redirect to stake.passport.xyz , make sure you modify the related records in the AWS Production account : for details see: https://docs.google.com/document/d/1uqmspYQ59LbsisQDrZ5q04DM40ywKnHX2aOf1KYuPxs/edit
