### ISSUE TITLE
GTC Staking Expiry and Missing Sidebar Details

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2642]
**Overview**
When GTC staking expires, the user is prompted to verify. After verification, points are awarded, but the expiry status does not change. Additionally, the sidebar information is missing and does not display the expected details.

**Steps To Reproduce**

1. Ensure you have an expired GTC Staking stamp.
2. Go to the 'GTC Staking' section.
3. Observe the 'expired' status notification.
4. Click on the 'Verify' button.
5. Notice the points awarded after verification.
6. Observe that the expiry status remains unchanged.
7. Check the sidebar for details and observe missing information.

**Observed  behavior**

- The staking status remains 'expired' even after re-verifying.
- The sidebar does not display the expected details related to the GTC staking status.

**Expected behavior**

- The expiry status should update and no longer show as 'expired' after re-verifying.
- The sidebar should display all relevant details about the GTC staking status as it did previously.

**Screenshots**
NA

**Additional context**
NA

**Comment by nutrina** [comment]
Waiting for clarification on https://discord.com/channels/562828676480237578/1073190200404103218/1257665313747763250
