### ISSUE TITLE
Increase onchain mint fee to $3

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#2650]
### User Story:
As the Passport business
I want to increase the onchain mint fee to $3
So that we can test pricing elasticity  

### Acceptance Criteria
GIVEN a user with a Passport Score 
WHEN they push the Passport onchain
THEN it should charge a $3 fee in Eth

#### Product & Design Links:
<links>

**Comment by Jeremy-Gitcoin** [comment]
@erichfi I was talking to @lucianHymer today and it looks like this is a single variable change that's pretty easy in case we need to change it back. I was also talking with @Kweiss about testing this change now, before we add additional chains to test this before we add additional variables into the mix. I think this could be a good one to run an experiment around as well. 

I moved this up to towards the top of the backlog, but let me know if you don't feel that's correct and we can adjust!

**Comment by lucianHymer** [comment]
Already updated secrets manager in all environments
