### ISSUE TITLE
Reverified Civic Stamp Not Showing as Verified

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2694]
**Overview**
After re-verifying the Civic Stamp following its expiration, the system showed a 'success' pop-up but still indicates that the Stamp has not been verified. The 'verify' button remains active.

**Steps To Reproduce**

1. Go to the verification page for Civic.
2. Click on 'Verify' after the Stamp has expired.
3. Complete the verification process.
4. See the 'success' pop-up.
5. Observe that the Stamp still shows as not verified and the 'verify' button is still active.

**Observed  behavior**
Despite the 'success' pop-up, the Civic Stamp remains unverified, and the 'verify' button is still active.

**Expected behavior**
The Civic Stamp should show as verified, and the 'verify' button should no longer be active after a successful re-verification.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by lucianHymer** [comment]
Looks like the issue is that we are saying "successfully reverified" even when unsuccessful! Will dig into this
