### ISSUE TITLE
Integrate Aggregate Model into MBD Endpoint as Default Parameter

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2719]
### User Story:
As a developer integrating Passport,
I want to have the default option to use the aggregate model in the MBD endpoint,
So that I can enhance my application's data processing capabilities with advanced aggregation.

### Acceptance Criteria
GIVEN the need for advanced data aggregation,
WHEN a request is made to the MBD endpoint,
THEN the system should offer the option to execute the aggregate model, providing the aggregated data in the API response.

#### Product & Design Links:
N/A

#### Tech Details:
1. Setup the Lambda Model:
  - Create a Lambda function to host the aggregate model developed by Nadjib.
  - Ensure the Lambda function can be triggered via the API endpoint.
2. Executing the Model:
  - Integrate the aggregate model execution within the Lambda function.
  - Ensure the model runs efficiently and returns results within acceptable timeframes.
3. API Endpoint Integration:
  - Update the MBD endpoint to include an option for the aggregate model.
  - Ensure the endpoint can handle requests for the aggregate model and return appropriate responses.
4.Testing and Validation:
  - Write unit and integration tests for the Lambda function and the API endpoint.
  - Validate the model's output against expected results.

#### Open Questions:
- [ ] How do we want to name this parameter?
 
#### Notes/Assumptions:

- Assumes that the data team's aggregate model is already developed and can be integrated with minor adjustments.
- Assumes existing infrastructure supports the addition of a new Lambda function and API endpoint updates.
- Collaboration with the data team and relevant team members will be required to ensure smooth integration and deployment.

**Comment by nutrina** [comment]
I have clarified some details with @lebraat 👍 

- name for the aggregate model name: `aggregate`
- default value for `model_list`: `aggregate`.  (so we return the aggregate field by default)
- name of the field in the result struct: `aggregate`:
```json
{
  "address": "0x85fF01cfF157199527528788ec4eA6336615C989",
  "details": {
    "models": {
      "ethereum_activity": {
        "score": 35
      }
    }
  }
}
```
