### ISSUE TITLE
Update Indexer/JSONL File to Parquet for Gitcoin Grants GG21

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2720]
### User Story:
As a data analyst working with Gitcoin Grants,
I want to update the indexer/JSONL file to include all models across all chains and convert the output to a parquet file,
So that I can efficiently analyze and process the data for the upcoming GG21 grants round.

### Acceptance Criteria
GIVEN the current indexer/JSONL file, which previously included only the Eth activity model,
WHEN it is updated,
THEN it should include the scores for each address from all models across all chains, including the aggregate model, and output as a parquet file.

#### Product & Design Links:
N/A

#### Tech Details:

- Ensure the indexer includes all models: individual, aggregate, and any new models added for all supported chains.
- For each address, retrieve and include the score from each model we have.
- Convert the current JSONL output to parquet format.
- Validate the parquet file for compatibility and performance improvements.
- Update the data pipeline to accommodate the new file format.

#### Open Questions:
N/A

#### Notes/Assumptions:

- Assumes that all current models are well-documented and there is a clear understanding of their structure.
- Assumes no major changes in the data schema that would require significant rework of the indexer logic.
- Assumes that the team has experience and familiarity with the parquet file format and its integration within the existing pipeline.

**Comment by nutrina** [comment]
Waiting for code review.

@erichfi  the format has changed slightly, to make the export of all models to parquet format easier.
