### ISSUE TITLE
Create and Manage Custom GitHub Stamp within Custom Dashboard Settings - Admin + Scorer (customization endpoint) Updates

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2784]
### User Story:
As a Gitcoin Team Member,
I want to create and manage a custom GitHub verification stamp within the custom dashboard settings in Django,
So that I can offer tailored verification processes tied to specific custom dashboards.

### Acceptance Criteria
GIVEN a Gitcoin team member is in the custom dashboard settings within Django admin,
WHEN they navigate to the "Custom GitHub Stamp" section under a specific dashboard,
THEN they should be able to create a new custom GitHub stamp tied to that dashboard and define the verification criteria.

**Examples of Verification Criteria:**
- Contributors to a specific GitHub repository.
- Members of a specific GitHub organization.

#### Product & Design Links:
N/A

#### Tech Details:
- the custom GitHub stamp must be managed within the settings of a specific custom dashboard in Django admin.
- ~~Integrate with GitHub OAuth to verify user memberships either by repository or organization.~~ this is part of #2787 
- the customisation returned by the scorer needs to include the new custom github stamps

#### Open Questions:
N/A
#### Notes/Assumptions:
N/A

**Comment by lucianHymer** [comment]
We can probably just use this one endpoint https://docs.github.com/en/rest/collaborators/collaborators?apiVersion=2022-11-28#list-repository-collaborators

**Comment by lucianHymer** [comment]
Probably have a linked list similar to the AllowList where we can specify the points to assign. And set the stamp name and settings in a GithubCustomStamp record or something.

**Comment by nutrina** [comment]
- provider name: 
  - `CustomGithub#repo#<repo-name>` 
  - `CustomGithub#org#<org-name>`
- this stamp can be shared between communities / custom dashboards  
- the passport app would then request the verification of this provider in the IAM, and the IAM has all the information required to query the GH API (no need to read something from the scorer)
- @erichfi: we should add a note in the stamp that the link between repo / org and the ETH address will be exposed
