### ISSUE TITLE
Assign Binary Point Value to Custom GitHub Stamp

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2785]
### User Story:
As a Gitcoin Team Member,
I want to assign a binary point value to the custom GitHub verification stamp,
So that it reflects whether or not the user meets the defined criteria.

### Acceptance Criteria
GIVEN a Gitcoin team member has created a GitHub stamp within a custom dashboard,
WHEN they configure the stamp,
THEN they should be able to assign a binary (yes/no) value based on the verification criteria (e.g., either the user is a contributor/member or not).

#### Product & Design Links:
N/A

#### Tech Details:

- Only a binary point value should be configurable, reflecting whether the criteria are met.

#### Open Questions:
N/A
#### Notes/Assumptions:
N/A

**Comment by nutrina** [comment]
As per the example model here, the weight of the custom stamp would be included in the new model: https://github.com/passportxyz/passport/issues/2784#issuecomment-2310899939

The scorer however might need some adjustment to pull this `dynamic` weight, see the example for allow list: https://github.com/passportxyz/passport-scorer/blob/5a426f0bf5eb3693c29c27e7e845dbf7b830d59a/api/account/models.py#L545
