### ISSUE TITLE
As a builder on passport.gitcoin.co, I want to find documentation for working with Passport.

### ISSUE THREAD

**Issue by leoneric** [gitcoinco/passport#282]
Link builders out to this link: https://docs.passport.gitcoin.co/gitcoin-passport-sdk/getting-started

**Comment by Etovardesign** [comment]
@leoneric currently the FAQ links out to the documentation. Would it be wise to substitute that button with a more general "Documentation" button where users can also find the FAQ section? Or do we need 2 distinct buttons for a specific reason?

**Comment by leoneric** [comment]
@Etovardesign, that makes sense 💯

**Comment by Etovardesign** [comment]
@leoneric 

Figma: https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/Passport?node-id=2808%3A47071
