### ISSUE TITLE
Optional Parameter skip_refresh

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2932]
### User Story:
As a developer,
I want an optional parameter to skip the score refresh,
So that I can retrieve the previously delivered score without refreshing it.

### Acceptance Criteria
GIVEN the optional parameter `skip_refresh = True`,
WHEN included in the request,
THEN the API should return the score from the previous request without refreshing.

#### Product & Design Links:
N/A

#### Tech Details:

- Update `GET /v2/stamps/{scorer_id}/score/{address}` to include `skip_refresh` parameter.
- Return the previous score if `skip_refresh = True`.

#### Open Questions:
N/A

#### Notes/Assumptions:
- This option is for developers wanting to use the previous score without a refresh.

**Comment by nutrina** [comment]
@erichfi : @lebraat  has removed the recommendation for introducing this parameter
