### ISSUE TITLE
[BUG] Github stamp not verifying

### ISSUE THREAD

**Issue by YukiPL** [gitcoinco/passport#2959]
**Overview**
Users with more than 30/60 distinct days contributions are not able to get the Github stamp. 

**Observed  behavior**
The Error message showing users have lower distinct days contributions than what they actually have
![image](https://github.com/user-attachments/assets/ad64ab7d-59cb-4ed1-b191-5e8980185d18)
![image](https://github.com/user-attachments/assets/e7a4d832-277a-4da6-8b54-1fdf2cd4260f)

**Expected behavior**
Users with more than 30 distinct days contributions should be able to claim the Github stamp.

**Screenshots**
![image](https://github.com/user-attachments/assets/73ec0763-d593-49f7-bcae-7d5f9f2d7754)

**Additional context**
Users:
1. https://github.com/pazhandd - 0xa286e3129924eab74c8d7640300c0756a1cc4def
2. https://github.com/esmitoo - 0x251823F1E0dC22d59a3fE3f08A53864a182D8844
3. https://github.com/bustedware - 0x2969e7bAaC4C99C867cc93e2aBf2289099A91254

**Comment by YukiPL** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/82755?view=List
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/82656?view=List
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6464550/conversation/82679?view=List

**Comment by lucianHymer** [comment]
https://discord.com/channels/1201910237238399006/1293099708876853279/1293679846135824414
