### ISSUE TITLE
[RESEARCH] Verifying ENS stamp from different Ethereum account

### ISSUE THREAD

**Issue by leoneric** [gitcoinco/passport#298]
**Passport reader**
GIVEN that I'm a Passport reader,
AND Passport holders may have connected ENS stamps through different Ethereum accounts linked to their Passport,
WHEN I assess these stamps
THEN I want to verify that the ENS stamp was legitimitely issued to that Passport holder
AND I want to verify whether that same ENS stamp ("same" as in based on the same ENS token) has been submitted by multiple Passport holders.

To do
Summarize possible attack vectors to this process and how we might mitigate them. Based on your research, we can start specifying the Acceptance Criteria for https://github.com/gitcoinco/dPopp/issues/297

**Comment by nutrina** [comment]
> THEN I want to verify that the ENS stamp was legitimitely issued to that Passport holder

... TODO

> AND I want to verify whether that same ENS stamp ("same" as in based on the same ENS token) has been submitted by multiple Passport holders.

This shall be verified in the app that integrates the passports & the stamps.
Each stamp contains a unique hash. It is possible to track the usages of the stamps by this hash (as we do it for the trust bonus calculation).
