### ISSUE TITLE
As a passport holder, I want my DID Session to be persisted when I revisit Passport, so that I don't need to re-sign to authorize myself

### ISSUE THREAD

**Issue by shavinac** [gitcoinco/passport#304]
GIVEN that I am a Gitcoin passport holder
AND I have already signed a message with my wallet to "log in" to Passport
WHEN I revisit Passport within 24 hours
THEN I should still be "logged in"
AND I should not re-sign a message with my wallet to "log in" again

Dev notes:
* ([ceramic discord message](https://discord.com/channels/682786569857662976/963185659638607982/994044410176217260)) did-session@0.1.1 - can serialize/store a session now, can check if a session isExpired or not before making writes
* some initial docs -https://developers.ceramic.network/reference/accounts/did-session/

**Comment by leoneric** [comment]
Here's an example for using these functions: https://developers.ceramic.network/reference/accounts/did-session/#typical-usage-pattern

Using localStorage is just for illustrative purposes though, we should take care of properly securing the storage of sessions.

**Comment by zachferland** [comment]
In the latest release of `@self.id/framework@0.3.3` you can now access the session and then manage it as described in docs above and pass it when connecting/auth.

For example with self.id framework
```ts
...
const [connection, connect, disconnect] = useViewerConnection()
...
// get session string you serialized and stored before, check if still valid (or how much longer)
const sessionStr = ...
const selfid = await connect(new EthereumAuthProvider(window.ethereum, accounts[0]), sessionStr)
...
// get session to serialize and store 
const session = selfid.client.session //or connection.selfID.session
session.serialize()
```

**Comment by nutrina** [comment]
Waiting for feedback from ceramic on this: https://discord.com/channels/682786569857662976/963185659638607982/1011583783067189268
