### ISSUE TITLE
[CHORE] Update Fleek environment variable names in production app (passport.gitcoin.co) before shipping 0af3131 to production

### ISSUE THREAD

**Issue by leoneric** [gitcoinco/passport#307]
in #288 there was a refactoring of `dpopp` -> `passport`, including renaming some front end environment variables. the prod deployment in Fleek should have the new environment variable names before 0af3131
 commit is shipped into production

**Comment by nutrina** [comment]
Changes have been done.
Will close this ticket after the next successful deploy of passport.
