### ISSUE TITLE
[DOCS] As a builder in Passport docs, I want a walkthrough of the example SDK application

### ISSUE THREAD

**Issue by leoneric** [gitcoinco/passport#313]
GIVEN I'm a builder
AND what to play around with the Passport SDK 
WHEN I go to the [Passport Gitbook docs](https://docs.passport.gitcoin.co/)
THEN I want to find a page dedicated to the [example application of the SDK](https://github.com/gitcoinco/passport/issues/183)
AND I want a video walkthrough of how to install the exmaple app locally

**Comment by farque65** [comment]
Simple walkthrough of the passport verifier and passport reader walk through

https://user-images.githubusercontent.com/8276680/180050283-c969c977-a060-4895-82cb-4ccbae48053e.mov
