### ISSUE TITLE
[CHORE] Upgrade Ceramic node to most recent stable

### ISSUE THREAD

**Issue by leoneric** [gitcoinco/passport#322]
* Upgrade Ceramic node to latest stable-version ([requested by ceramic team](https://discord.com/channels/682786569857662976/963185659638607982/994263939523293324) for better logging/debugging)

May be needed: upgrading Ceramic library versions in our Passport repo as well

**Comment by kammerdiener** [comment]
The node in Staging has been upgraded to the latest SHA: https://github.com/gitcoinco/passport/tree/ceramic-updates

Waiting to deploy to Production till we can validate in Staging.
