### ISSUE TITLE
[BUG] Broken stamp loading

### ISSUE THREAD

**Issue by leoneric** [gitcoinco/passport#330]
Bug:
Currently, if a stamp cannot be loaded (for what reason ever), the passport cannot be used.
The user gets into a loop where he is prompted to "Try again" over and over again ....

Story:
GIVEN I am a user that has a passport, but loading one stamp from the passport fails
WHEN I enter the passport app
THEN I expect the stamp that was not loaded properly to indicate an error state
AND to allow me to perform the verification again

**Comment by leoneric** [comment]
@nutrina, can you provide reproduction steps to confirm that this is fixed?

**Comment by leoneric** [comment]
i guess we should figure out the tests via this ticket: https://github.com/gitcoinco/passport/issues/346

**Comment by nutrina** [comment]
PR with integration test is open: #395

**Comment by nutrina** [comment]
> @nutrina, can you provide reproduction steps to confirm that this is fixed?

@leoneric Reproducing this is not possible any more, since the fix was deployed (also reproducing the context for the bug was tricky). But there is now a test that checks this case. See #395
