### ISSUE TITLE
[IAM] As an IAM server, I want to issue stamps for  >=100 Facebook friends

### ISSUE THREAD

**Issue by leoneric** [gitcoinco/passport#353]
GIVEN I'm the Gitcoin IAM server,
AND Passport holder wants to verify their number of Facebook friends
WHEN I run them through the Facebook oAuth process
THEN I call the Facebook API for their number of friends
AND WHEN their account has >= 100 Facebook friends
THEN I issue them a VC that verifies that they have >= 100 Facebook friends

**Notes**
- https://developers.facebook.com/docs/graph-api/reference

**Comment by nutrina** [comment]
Open point for `app` (the UI part): the friend list requires the scope `user_friends`:

```
  const onClick = () => {
    setLoading(true);
    //@ts-ignore assuming FB.init was already called; see facebookSdkScript in pages/index.tsx
    FB.login(
      function (response) {
        if (response.status === "connected") {
          onFacebookSignIn(response.authResponse);
        } else {
          setLoading(false);
        }
      },
      { scope: "user_friends" }
    );
  };
```
