### ISSUE TITLE
Load testing Ceramic infrastructure

### ISSUE THREAD

**Issue by leoneric** [gitcoinco/passport#360]
Set up load testing environment

Context:
- Notes on load testing Ceramic in Passport staging: https://github.com/gitcoinco/passport/issues/294
- Find data on Gitcoin Grants Round 14 traffic in the #gitcoin collaboration channel on the Ceramic Discord server
- Expected activity in GR15. On the number of streams front: we're expecting 50,000 Passport holders, who will have a Passport containing stamps. So 50,000 * 30ish stamps

**Comment by leoneric** [comment]
@stbrody, @ukstv, and @willex, please let me know if you need anything else to work on this.

**Comment by willex** [comment]
@leoneric we started kickoff today and will follow up shortly if anything is needed from your end.

**Comment by leoneric** [comment]
Thank you for taking this on, @willex 🙌
