### ISSUE TITLE
[IAM] As an IAM server, I want to issue stamps for whether somebody has a Facebook profile picture

### ISSUE THREAD

**Issue by leoneric** [gitcoinco/passport#369]
GIVEN I'm the Gitcoin IAM server,
AND Passport holder wants to verify that they have a Facebook profile picture
WHEN I run them through the Facebook oAuth process
THEN I call the Facebook API to see whether they have a Facebook profile picture
AND WHEN they have a profile picture
THEN I issue them a VC that verifies that they have a Facebook profile picture

**Comment by nutrina** [comment]
PR is open #397
