### ISSUE TITLE
[SPIKE] WalletConnect Mobile Support

### ISSUE THREAD

**Issue by Drewsapple** [gitcoinco/passport#391]
When connecting a wallet to passport.gitcoin.co, the walletconnect prompt only provides a QR code. To better support mobile users, it seems like very little work needs to be done to add wallet apps to the modal.

[Web3-Onboard docs](https://github.com/blocknative/web3-onboard/blob/v2-web3-onboard-develop/packages/walletconnect/README.md#usage) show that instead of calling `walletConnectModule()` with no args, you could pass it the object 
```
{
  qrcodeModalOptions: {
    mobileLinks: ['rainbow', 'metamask', 'argent', 'trust', 'imtoken', 'pillar']
  },
}
``` 
or similar to support these mobile wallets.

I think this only merits a change here https://github.com/gitcoinco/passport/blob/1b781a9eb4e54221ff442164e356bb77b2305ebb/app/utils/onboard.ts#L14

**Comment by chibie** [comment]
@erichfi @Kweiss 

the above change isn't required. it will limit the list of available wallet connect options on iOS which currently is as shown below:

![image](https://user-images.githubusercontent.com/6025509/225933777-200386e6-0e9d-4e5c-848d-9d68e127287e.png)

i assume @Drewsapple tried connecting with an android device which works differently from iOS.

in android, the user only sees a "Connect" button which is a deep link that brings up a list of **already installed wallet apps** for the user to select one. if the user doesn't have any installed wallets installed, then the qr code is the only option.

![image](https://user-images.githubusercontent.com/6025509/225934797-97cf23b9-1424-48ad-ae06-5ebb5e18f219.png)

![image](https://user-images.githubusercontent.com/6025509/225934908-feef28be-f6e8-4c48-82fa-dac26f931106.png)

**Comment by Kweiss** [comment]
Awesome! Thanks for investigating!
