### ISSUE TITLE
New parameter for ceramic: CERAMIC_STREAM_CACHE_LIMIT

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#434]
It was suggested to bump the value for this parameter: CERAMIC_STREAM_CACHE_LIMIT to 2000 (default value is 500).
This is expected to improve our throughput.

**Comment by kammerdiener** [comment]
Changes are available in Staging and have been pushed to this branch: https://github.com/gitcoinco/passport/tree/ceramic-updates

Holding off deploying to Production till we can validate in Staging

**Comment by nutrina** [comment]
I can confirm this is deployed on on staging.
@leoneric we can confirm to ceramic that they can verify this on staging. Also the ipfs topic on staging was also solved
