### ISSUE TITLE
[GRANTS] As a gitcoin.co visitor, I want to see a banner with my current Trust Bonus and info and links to increase it to 150%

### ISSUE THREAD

**Issue by leoneric** [gitcoinco/passport#535]
GIVEN that I'm a gitcoin.co visitor
AND my Trust Bonus is below 150%
WHEN I navigate the gitcoin.co
THEN I want to see a banner that highlights my current Trust Bonus and info and links to increase it to 150%
AND WHEN I click on the link
THEN it take me to gitcoin.co/MYUSERNAME/trust

Notes:
- @willsputra to add banner

**Comment by willsputra** [comment]
here's what I found from GR10 file:
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/19514207/188461038-989b4602-4e7d-4114-9ad1-f158606952d9.png">

figma link: https://www.figma.com/file/CP57XgGQwC9ChPCMkTuQ7i/GR10?node-id=193%3A6514

@Etovardesign do you know if there were any changes here?
