### ISSUE TITLE
[CHORE] Anchoring ceramic documents

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#563]
- anchor the ceramic documents (passport and also individual stamps???)
- verify the anchor status in the passport app
- issue anchoring requests in case the passport & stamps are not confirmed to be anchored after a given time (1 hour for example)

**Comment by nutrina** [comment]
@willsputra Hy there. In order to implement this we also need to think if we want to show something to the user or not, and how we show something to the user. So basically a document has this states:
- anchor pending (or not anchored) => the document is not secured
- anchored => the document is safe

@gdixon what do you think?

**Comment by GTChase** [comment]
Blocked due to:
- Designs for when a successful storage
- Designs for when a failed storage
- Decision if we should store local storage as a backup to ceramic failing
