### ISSUE TITLE
As a Passport holder, I want to remove a stamp alltogether

### ISSUE THREAD

**Issue by leoneric** [gitcoinco/passport#579]
GIVEN that I'm a Passport holder and have verified a stamp
WHEN I click the context-menu of the associated stamp on the stamp dashbord
AND when I click remove stamp
THEN the app opens a pop up asking whether I want to really continue removing the stamp
AND WHEN i hit continue
THEN the stamp gets removed from my stamp and Passport, visually and on Gitcoin's Ceramic node

- Designs: https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/Passport?node-id=4287%3A67597
- Context from past implementation: starhttps://github.com/gitcoinco/passport/issues/208

**Comment by aminah-io** [comment]
Re-closing this as it actually is already implemented on Review (calm-term) and can be tested on complete abstracted stamps 👍
