### ISSUE TITLE
[PASSPORT] As a Passport holder, I want to remove a data point from a stamp

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#580]
GIVEN that I'm a Passport holder and have verified a data point within a stamp
WHEN I toggle off a verified data point
THEN the continue button gets enabled
AND WHEN i hit continue
THEN the data point gets removed from my stamp and Passport, visually and on Gitcoin's Ceramic node

- Designs: https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/Passport?node-id=4287%3A67597
- Context from past implementation: https://github.com/gitcoinco/passport/issues/208

**Comment by aminah-io** [comment]
Removing stamp data points and removing whole stamps is implemented!

**Comment by aminah-io** [comment]
This looks good to test again
