### ISSUE TITLE
[BUG] Users should see ‘update’ tags on only Twitter, Github, or Facebook stamps which have they verified before GR15

### ISSUE THREAD

**Issue by leoneric** [gitcoinco/passport#589]
**Scenario**
- Users should only see ‘update’ tags on Twitter, Github, or Facebook stamps which have they verified before GR15

**Expected result**
Only the Twitter, Github, or Facebook stamp shouldn't show any update tags

**Actual result**
The Google stamp and others from GR14 as well show update tags for Passport holders who verifed these before GR15

**Comment by farque65** [comment]
> On https://calm-term-4626.on.fleek.co/#/dashboard, I get an "update" tag for the Gitcoin Grants stamp.
> 
> ![Image](https://user-images.githubusercontent.com/59769856/201923518-be400d0f-7252-4edd-a16a-cfcbcb316ef1.png)
> 
> Is this intendend @farque65? If not, how might we fix this?

This should not be occurring there is a PR to resolve this in review #730
