### ISSUE TITLE
[Chore] Abstract Platforms from app

### ISSUE THREAD

**Issue by farque65** [gitcoinco/passport#607]
Platforms Dir Structure
------------------------
<img width="353" alt="Screen Shot 2022-09-30 at 3 00 35 PM" src="https://user-images.githubusercontent.com/8276680/193338923-ca9effc2-816f-46cb-88f0-39579656b3c2.png">

**Comment by farque65** [comment]
Tasks TODO with regards to pieces of passport:

- Ceramic Context
  --- use the platform config to generate starting state
- Cardlist
  --- use the platform config to generate the element
- Platform Cards
- Config 
  --- Move config to Providers directory
- Index Broadcast card redirect

- Types
   --- Move to Providers directory and import 

- Move Platform/Provider specific parts to Platforms Directory

**Comment by GTChase** [comment]
@leoneric @nutrina - we need to explore if this needs to be split out into multiple chores
