### ISSUE TITLE
Abstract Google platform from Passport app

### ISSUE THREAD

**Issue by GTChase** [gitcoinco/passport#621]
This story is to break down this parent [ticket](https://github.com/gitcoinco/passport/issues/607) to smaller issues.. The goal is the same, but to abstract just this single platfor from passport.

For further details:
https://github.com/gitcoinco/passport/issues/607

**Comment by nutrina** [comment]
Unable to test this since review and staging environments are not working (IAM service is down).

Troubleshooting he review environment first.
