### ISSUE TITLE
Prompt users to create a passport when prompted to calculate score and no passport present

### ISSUE THREAD

**Issue by kevinrolsen** [gitcoinco/passport#64]
Failure case - calculate the did, and the score from the wallet connection

GIVEN I am on a page requesting my passport
AND I DO NOT have a passport created
WHEN I connect my wallet
AND I sign the transaction to calculate my did from my wallet
THEN I should see the page update to "calculating score"
AND I should receive a "no passport found" message
AND I should have a prompt to create a passport
AND I should see additional information if the wallet was not found for other reasons

Help text:

Your passport could not be found
If you have already created a passport, please check you are using the same wallet you initially used to create your passport.
If you are still having trouble, connect with us in our dpopp support discord channel: https://discord.com/channels/XXX

**Comment by shavinac** [comment]
Completed
