### ISSUE TITLE
[INFRA] Update Fleek permissions

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#644]
This relates to a ticket opened with Fleek, when we were not able to pull in & deploy some repos.
@farque65 has more context here.

**Comment by farque65** [comment]
![Screen Shot 2022-10-21 at 9 20 08 AM](https://user-images.githubusercontent.com/8276680/197205476-ba4d9d92-bac5-4a23-ae0b-d24ef1d2e20d.png)

**Comment by farque65** [comment]
@nutrina @kevinrolsen The response from their support team indicates that we should try resetting the permissions for fleek.

**Comment by farque65** [comment]
After a call with @kevinrolsen we found that the repositories accessible by fleek are determined by the user's github permissions . Since Fleek is a shared resource for various product groups every team lead should have admin status so they can help add github repositories to Fleek when needed.

**Comment by nutrina** [comment]
@farque65 it sounds like we can close this. Or do we need to update some docs / usage guides for this?

**Comment by farque65** [comment]
> @farque65 it sounds like we can close this. Or do we need to update some docs / usage guides for this?

Yes, that would be best to update docs/usage guides
