### ISSUE TITLE
[BUG] Passport holders should be able to verify stamps without them disappearing shortly thereafter

### ISSUE THREAD

**Issue by leoneric** [gitcoinco/passport#680]
**Scenario**
- A Passport holder logs in and navigates to a stamp on the Passport dashboard.
- Selects data points in the sidebar and proceeds with the verification steps.

**Expected result**
Upon successful verification, the corresponding stamp should show verified on the Passport dashboard. 

**Actual result**
When the sidebar is closed, the corresponding stamps are not verified on the dashboard and in the sidebar.

**Comment by nutrina** [comment]
The issue seems to be that these users have at least one stamp in an invalid state.
Waiting for feedback from ceramic on this issue.

**Comment by nutrina** [comment]
We need to allow the passport to load faulty stamps, and silently ignore them.
Currently nothing is loaded if one of the stamps in the passport is borked.

Proposed change:
from:
```
const loadedStamps = await Promise.all(stampsToLoad);
```

to:
```
const loadedStamps = await Promise.allSettled(stampsToLoad);
```

and adjust the rest of the code

**Comment by nutrina** [comment]
A PR has been opened: https://github.com/gitcoinco/passport/pull/708
