### ISSUE TITLE
[API] As a developer, I want to fetch the score of a Passport holder via an API Configuration ID when I input the checksummed Ethereum address of a Passport holder.

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#697]
GIVEN that I’m developer that has configured and integrated the API Passport into my community
WHEN my application requests the API including:
- My API key
- My Community ID
- An Ethereum address and an associated signature

THEN the API is called with the community's scoring configurations applied to the specified Ethereum address
AND the API returns the score of that Ethereum address based on the corresponding scoring configurations
AND stores the score mapped to the Eth account under the Community ID directory

**Comment by nutrina** [comment]
@leoneric assuming this API request is done from the Browser (which I think might be at least half of the use-cases) we will also need the user to sign a challenge. So in this case the flow is:
1. make request to get the challenge from the scorer
2. make the request mentioned above, with the adjustment:
```
WHEN my application requests the API including:

My API key
My Community ID
An Ethereum address
Signature of challenge message
```
