### ISSUE TITLE
[BUG] Need to fix loading borked stamps in the SDK

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#731]
The SDK needs the same fix as here: https://github.com/gitcoinco/passport/commit/34d8cd4ebed10ae60b21d30dfef99c68171a159c   

Also we should probably move away from tulons for easier maintenance of the SDK.

**Comment by farque65** [comment]
How should the types in the passport-sdk be maintained?
- Should they be duplicated in the sdk from passport or should the passport types folder be module?

**Comment by aminah-io** [comment]
A preliminary decision has been made to fork the Tulons repo over to Gitcoin and extend it to prevent the borked stamps situation

**Comment by nutrina** [comment]
The follow-up task for this is: #800
