### ISSUE TITLE
[CHORE] Fix flaky tests in database-client

### ISSUE THREAD

**Issue by schultztimothy** [gitcoinco/passport#735]
List of skipped tests can be found here: https://github.com/gitcoinco/passport/pull/727/files#diff-9088bb68e9f73f3d910701543326250474768009d56978004ac38afba84a1b66R59

**Comment by nutrina** [comment]
@schultztimothy can you please double check this?
I think we do not need to skip tests any more, this was something I missed when making changes in the database client

**Comment by nutrina** [comment]
This is fixed.
