### ISSUE TITLE
[BUG] Passport holders should not be able to "resubmit" their Passport to their Gitcoin.co profile

### ISSUE THREAD

**Issue by leoneric** [gitcoinco/passport#738]
Passport holders should not be able to "resubmit" their Passport to their Gitcoin.co profile

**Scenario**
- Log in to cGrants and navigate to 'Trust Bonus' section.
- Hit the disabled "Re-submit Passport" button.

**Expected result**
The "Re-submit Passport" button should be disabled, i.e., grayed out and not clickable.

**Actual result**
The "Re-submit Passport" is clickable and starts the submission, scoring, and saving process.

**Comment by aminah-io** [comment]
Resolved with https://github.com/gitcoinco/web/pull/10965
