### ISSUE TITLE
[BUG] Failed message toast displayed on success

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#749]
Steps to reproduce on: https://calm-term-4626.on.fleek.co/#/dashboard

1. I am already verified on google
2. I want to re-verify my stamp
3. The verification is successful (I can see this in the network traffic)

Problem:
The error toast gets displayed

![Image](https://user-images.githubusercontent.com/8137830/203764043-1ed8969c-a9cb-439d-a1fe-2fb6cbdffae1.png)
![Image](https://user-images.githubusercontent.com/8137830/203764042-b8254000-be81-46d5-a417-372443c32122.png)

**Comment by nutrina** [comment]
@aminah-io This still happens for me on staging

**Comment by aminah-io** [comment]
> @aminah-io This still happens for me on staging

If this is the staging branch you're checking, `staging-app`, it looks like those updates didn't get pushed to staging
