### ISSUE TITLE
[BUG] [README] Discord link invalid

### ISSUE THREAD

**Issue by xjjda22** [gitcoinco/passport#780]
please check the discord link, on redirection showing invalid
https://github.com/gitcoinco/passport/blob/0d8a900ebf3e5ae7ceccaffdb50f23cf095b8819/README.md?plain=1#L17
<img width="666" alt="Screenshot 2022-12-11 at 12 20 10 PM" src="https://user-images.githubusercontent.com/35558569/206886225-739d7e87-0b62-48c9-b1e1-1f1bcf63a9a6.png">

**Comment by harryranakl** [comment]
PR: https://github.com/gitcoinco/passport/pull/781
