### ISSUE TITLE
Issue in verifying my ens adress

### ISSUE THREAD

**Issue by pppkartik** [gitcoinco/passport#785]
When m trying to verify my ens there is an issue showing that fulfi all requirements but m already completed everything kindly please come out on that issue 
![Screenshot_2022-12-13-07-17-10-22_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/119148206/207206649-890ed994-59da-47e5-885b-33a48dd5331d.jpg)

**Comment by Kweiss** [comment]
Thanks for the report - can you hop on the support thread on our discuss to review?
https://discord.gg/gitcoin
