### ISSUE TITLE
[API] Create and run automated acceptance tests

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#787]
Scenarios to test:
- [x] https://github.com/gitcoinco/passport/issues/689
- [x]  https://github.com/gitcoinco/passport/issues/692
- [x]  https://github.com/gitcoinco/passport/issues/693

**Comment by schultztimothy** [comment]
https://github.com/gitcoinco/passport-scorer/pull/30 Has been merged and all tests are running as expected

**Comment by schultztimothy** [comment]
@erichfi jsut lmk if you would like to go over and verify the tests
