### ISSUE TITLE
[API CHORE] Update frontend to high-fidelity designs

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#789]
As part of our effort to improve the user experience of our API configuration application, @Etovardesign has conducted user interviews and created updated wireframes with higher touch. You can find these updated designs at the following link 👉 **https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/Passport?node-id=7513%3A68517&t=NRe856T40lnKHezR-1**

The task in this ticket is to update the application's front end to match these new designs, including any necessary changes to layout, color scheme, font, and other visual elements. Please review the updated designs and make any changes required to the application's frontend.

**Acceptance Criteria:**
- The frontend of the application matches the high-fidelity designs provided by the designer, including layout, color scheme, font, and other visual elements.
- The application functions correctly and is usable by users.

**Comment by Kweiss** [comment]
Going to close this given the work happening on scorer already
