### ISSUE TITLE
[API] Make Passport holder signature for scoring optional

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#796]
As a developer using the Gitcoin Passport API, I want to be able to configure whether my application requires the signature of a Passport holder when scoring their Passport. This will allow me to better tailor the API to the needs of my application.

**Acceptance Criteria:**

GIVEN I'm a developer in the Gitcoin Passport API
WHEN I go to the community configuration view
THEN the option of the "Require signature" is not checked (the default state)

GIVEN I'm a developer in the Gitcoin Passport API
WHEN I'm in the community configuration view
THEN I can check the "Require signature" box

GIVEN I'm developer who has enabled the signature requirement for scoring Passports in their application
WHEN I make a request to score a Passport
THEN the API will only score the Passport if the request includes a signature by the Passport holder

GIVEN I'm a developer who has disabled the signature requirement for scoring Passports in their application
WHEN I make a request to score a Passport
THEN the API will score the Passport regardless of whether the request includes a signature by the Passport holder or not

**Notes:**

- The existing functionality of the API, which requires Passport holder signature for scoring, should not be affected by this change.
- Adequate documentation and clear instructions should be provided to developers on how to use the new configuration option.

**Comment by nutrina** [comment]
GIVEN I'm a developer in the Gitcoin Passport API
WHEN I go to the community configuration view
THEN the option of the "Require signature" is not checked (the default state)
