### ISSUE TITLE
[SPIKE] Research IAM Dependencies and Frontend for GTC Staking App for GR16

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#798]
**Objective:** The objective of this spike is to research and evaluate the dependencies and frontend requirements for the GTC staking app in preparation for Grants Round 16 (GR16).

**Description:**

- Research and identify the necessary IAM dependencies for the GTC staking app, including any third-party libraries or services that may be required, with a focus on preparing the app for GR16.
- Evaluate the frontend requirements for the GTC staking app, including the design and user experience, with a focus on preparing the app for GR16.
- Document the findings and recommendations in a report.

**Acceptance Criteria:**

- A report detailing the necessary IAM dependencies for the GTC staking app, including any specific requirements for GR16.
- A report detailing the frontend requirements for the GTC staking app, including design and user experience considerations, with a focus on preparing the app for GR16.
- Recommendations for implementing the IAM dependencies and frontend for the GTC staking app in preparation for GR16.

**Risks:**

- There may be a lack of information or documentation available on the necessary IAM dependencies and frontend requirements for the GTC staking app in preparation for GR16.
- The specific requirements for GR16 may be difficult to determine without sufficient research or consultation with relevant stakeholders.

**Outputs:** A report detailing the necessary IAM dependencies and frontend requirements for the GTC staking app in preparation for GR16.

**Notes:**
- Link to repo: https://github.com/moonshotcollective/id-staking

**Comment by schultztimothy** [comment]
iAM Changes
- Update iam to make requests to new subgraph - url
- Update subgraph queries to filter for GR16 round https://github.com/gitcoinco/passport/blob/main/platforms/src/GtcStaking/Providers/communityStaking.ts#L48
- Create different provider/stamp for each round?

Staking FE changes
- Remove passport expiration checks, and error handling when connecting wallet
  - it checks for a passport and if passport is found it should route to the staking dashboard, but it is a bit clunky
- If we want to check for the existence of a passport check for issued stamps
- Pull current round from subgraph

All in all it won't be that hard to make the adjustments once the updated contract and subgraph are deployed.
