### ISSUE TITLE
As Ned, I want to see the ENS stamp so that I know it's available for me to take action on

### ISSUE THREAD

**Issue by brentmartin** [gitcoinco/passport#8]
*Ned = Ned the newbie to web3
(This story is only seeing the service, not interacting at all)
*signed in with my wallet address is not apart of the acceptance so it can be built independently 

Given I visit (URL)
When I refresh the page 
Then I see an ENS stamp

**Comment by shavinac** [comment]
Closed - ENS stamp completed in https://github.com/gitcoinco/dPopp/issues/46
