### ISSUE TITLE
🎨 [UI] As a user, I want to see a redesigned homepage for dPopp, so that I know what dPopp is

### ISSUE THREAD

**Issue by yonocan** [gitcoinco/passport#80]
GIVEN that I am viewing the passport landing page
THEN I should see a redesigned landing page, which includes:
- updated background color
- tiles for verifications
- updated copy 
- a single button to create the passport

**Notes**
- Remove the link below the block of text 

**Mockup**
https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/dPopp?node-id=1735%3A44092

![Image](https://user-images.githubusercontent.com/5656217/170097537-b3e846b8-a02d-469e-ac25-64e523af6c67.svg)

**Comment by brentmartin** [comment]
Changes needed:
- Background color needs to be the dark layout color.
- We need to remove the link - "Why use your wallet as your identity?"
- Add the SVG for the logo's
- Can we check the fonts one more time - they may be wrong

![Image](https://user-images.githubusercontent.com/5798446/170097503-a03130e5-1e24-4820-be6e-dd290e5d0fa4.png)

**Comment by farque65** [comment]
These changes have not been pushed to stage

**Comment by farque65** [comment]
The updated landing page is now available on staging
