### ISSUE TITLE
[API] Remove Ethereum address signature requirement for Passport scoring

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#805]
**Description:** The API currently requires a signature from an Ethereum address in order to score the associated Gitcoin Passport. This is causing inconvenience for some developers.

**Solution:** Remove the requirement for an Ethereum address signature when scoring a Passport.

**Steps:**

- Review the current codebase to determine where the Ethereum address signature is being validated.
- Update the codebase to remove the signature validation requirement.
- Test the changes to ensure that the Ethereum address signature is no longer required when calling the scoring function of the Passport Scoring API.

**Comment by lucianHymer** [comment]
https://github.com/gitcoinco/passport-scorer/pull/38
