### ISSUE TITLE
[API] Retrieve Paginated List of Passport Scores Within a Community

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#808]
As a developer using the API, I want to be able to retrieve a paginated list of all Passport scored within a speicfic community

**Acceptance Criteria:**
GIVEN I have a community to which users have submitted passports
WHEN I make a request calling  `/score/community/{community-id}` API endpoint with my API Key
THEN I get a paginated list of scores is returned for that community

**Notes**
- Depending on what the Django Ninja framework supports out of the box, we should decide whether go with `next_page` and `prev_page` arguments to navigate response or limit and offset arguments.

**Comment by nutrina** [comment]
@erichfi I have a question about this: is it required to have the list of eth addresses? Or is it sufficient for the caller to provide the community ID and get back all passports scored for that community?
Also is it required to validate the ETH addresses? I would say we should make this an assumption: it should be done on the callers side.

**Comment by nutrina** [comment]
I would propose to adjust the course of action here based on the feedback from @thelostone-mc: https://discord.com/channels/562828676480237578/1042785636333146204/1062304080573255710

I would adjust the story as follows:

        GIVEN I a community where users have submitted passports to
        THEN I can call the `/score/community/{community-id}` API endpoint with my API Key
        AND a paginated list of scores is returned for that community
