### ISSUE TITLE
Upgrade version of ceramic node

### ISSUE THREAD

**Issue by GTChase** [gitcoinco/passport#819]
This depends on #811 and should not be done before #811

Desired ceramic version: 2.18.0  https://hub.docker.com/layers/ceramicnetwork/js-ceramic/2.18.0/images/sha256-84a0f204753a273baaeb61315cb6067237a831ba19d06d04ae31ea3c690f550c?context=explore

**Comment by GTChase** [comment]
@nutrina could you add details to this based on your convos with ceramic

**Comment by nutrina** [comment]
This has been done.
