### ISSUE TITLE
Adjustments for IAM changes for Identity Staking App

### ISSUE THREAD

**Issue by GTChase** [gitcoinco/passport#820]
- [x] Update iam to make requests to new subgraph - url
- [x] Update subgraph queries to filter for GR16 round https://github.com/gitcoinco/passport/blob/main/platforms/src/GtcStaking/Providers/communityStaking.ts#L48
- [x] Ensure existing staking stamp will expire in 3 months.. Point being to prevent duplicate stamps if rounds arent running every 3 months
- [x] Redeploy changes to IAM server

**Comment by nutrina** [comment]
This works for me.
