### ISSUE TITLE
Enhance Scorer Admin

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#824]
The Django Admin for the scorer should allow inspection of all entities (scorers, communities, passport, scores, etc ...).

- [x] weighted scorer and  binary scorer are missing
- [x] replace dropdowns / select for object relations with raw id fields: https://docs.djangoproject.com/en/4.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.raw_id_fields
- [x] add search fields for all list views (like for the passport list view)

**Comment by lucianHymer** [comment]
This is on the review server

**Comment by nutrina** [comment]
I don't see this .... have checked https://api.scorer.dpopp.gitcoin.co/admin/
Let us pair on this. Ping me when you come online.

**Comment by lucianHymer** [comment]
https://github.com/gitcoinco/passport-scorer/pull/47

**Comment by nutrina** [comment]
@lucianHymer  could you please remove the APU scorer from the admin

**Comment by nutrina** [comment]
![image](https://user-images.githubusercontent.com/8137830/214840989-af8edd2e-30bb-44f1-abb7-992d43f2d4ff.png)

**Comment by nutrina** [comment]
![image](https://user-images.githubusercontent.com/8137830/214841326-caf640ba-a2c9-49e8-be03-dd94d38171f7.png)

**Comment by lucianHymer** [comment]
Hey Gerald, I made these updates! The scorer link was tricky because of the subclassing, but I figured out a pretty good way to do it. Please check out the updates on review and let me know if there's anything else you'd like me to tweak

https://github.com/gitcoinco/passport-scorer/pull/55

**Comment by nutrina** [comment]
Looks good :)
This is good to be deployed.
