### ISSUE TITLE
[CHORE] Fix TODOs in scorer

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#826]
when implementing recent features, we logged a couple of open todos in different files of the passport-scorer source code. find out more there

**Comment by lucianHymer** [comment]
Mostly complete and merged. https://github.com/gitcoinco/passport-scorer/pull/67

Remaining TODOs on hold while addressing more pressing issues

**Comment by lucianHymer** [comment]
These are just refactorings. There shouldn't be any noticeable changes. Can be left on review while some other changes are tested
