### ISSUE TITLE
Create Metabase query for cGrants Passport data

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#846]
As a data analyst, I need to be able to retrieve cGrants Passport data in order to support my work. In order to do this, I need a Metabase query that can pull the following data, with each row representing a Gitcoin cGrants handle and the other columns more info about that user:
- Gitcoin cGrants handle
- donatedInGr14 (boolean)
- donatedInGr15 (boolean)
- Passport DID
- One column for each Passport data point / stamp / Verifiable Credential (boolean; if true, Passport holder's personal hash of that stamp)

**Acceptance Criteria**
GIVEN: We have a Metabase instance set up and running.
WHEN: A request is made to retrieve cGrants Passport data.
THEN: A Metabase query will be run to retrieve the above specified data

**Note:** The query should give us an overview of all the Passports ever submitted to cGrants.

**Example query:** https://metabase.gitcoin.co/question/1208

**Comment by Kweiss** [comment]
I am going to close this as I think the new API access the teams have will solve this problem.
