### ISSUE TITLE
Display Git Commit in Gitcoin Passport and Scorer App

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#860]
As a user, I want to be able to easily see which git commit corresponds to the current version of the Gitcoin Passport app, so that I can easily dig into the corresponding code

GIVEN that I am a user of the Gitcoin Passport app or Gitcoin Passport Scorer app
WHEN I access any page of these apps
THEN I should see a link to the git commit (hosted via GitHub) prominently displayed in the footer of the apps

Design files can be found at the following link: https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/Passport?node-id=8679%3A71865

**Comment by Kweiss** [comment]
I dont quite follow the value of this. Can you say more on what problem we are trying to solve with this?

**Comment by nutrina** [comment]
This is not working for passport in review and staging.
