### ISSUE TITLE
Design Passport Footer Variations and Remove Built by the Gitcoin Community UI

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#861]
- Design all Passport Footer variations based on the page type (e.g. homepage, profile page, etc.)
- Remove Built by the Gitcoin Community UI from all pages

**Acceptance Criteria**
GIVEN that I'm a user on one 
WHEN I navigate to any of the footers across the app
THEN it will always have the same contents adjusted to the page designs

**Notes:**
Updated design file: https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=281%3A8898&t=7LKU6jDgyKg9dc2v-1

**Comment by Kweiss** [comment]
testing visibility

**Comment by Etovardesign** [comment]
**Open Questions**
- [ ] What should the footer variation be for Identity Staking? @erichfi

**Comment by Etovardesign** [comment]
@Kweiss @erichfi can you please review these when you have a moment? 

https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=281%3A8898&t=7LKU6jDgyKg9dc2v-1

**Comment by garysheng** [comment]
Looks good to me.
