### ISSUE TITLE
[SPIKE] Ninja Docs for the scoring API are not working

### ISSUE THREAD

**Issue by Kweiss** [gitcoinco/passport#865]
Current behavior:
When I access the scorer API docs: https://api.scorer.gitcoin.co/docs#/default/registry_api_signing_message

I authorize using the created API key

I "execute" a signing request and it returns : `{
  "detail": "Invalid API Key."
}`

Expected Behavior:
This request returns data and I can test the API interactively.

**Comment by nutrina** [comment]
This is already fixed and in production
