### ISSUE TITLE
Reset the error field in the score when the score has been successfully calculated

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#871]
GIVEN I am a user whose passport scoring resulted in an error
AND the `error` field in the score contain the error text
WHEN I am successfully scoring my passport afterwards
THEN the error field is reset to ``

**Current** state of a passport state that was successfully scored after it initially had an error:
```json
{
  "address": "...",
  "score": "1.000000000",
  "status": "DONE",
  "last_score_timestamp": "2023-01-25T18:01:05.509974+00:00",
  "evidence": {
    "type": "ThresholdScoreCheck",
    "success": true,
    "rawScore": "27.32733523641860351460763922",
    "threshold": "21.75812"
  },
  "error": "No Passport found for this address."
}

```

**Desired** state of a passport state that was successfully scored after it initially had an error:
```json
{
  "address": "...",
  "score": "1.000000000",
  "status": "DONE",
  "last_score_timestamp": "2023-01-25T18:01:05.509974+00:00",
  "evidence": {
    "type": "ThresholdScoreCheck",
    "success": true,
    "rawScore": "27.32733523641860351460763922",
    "threshold": "21.75812"
  },
  "error": ""
}

```

**Comment by nutrina** [comment]
Waiting to pair with somebody to close this off.

**Comment by nutrina** [comment]
PR is here: https://github.com/gitcoinco/passport-scorer/pull/57

**Comment by omkarc150** [comment]
![image](https://user-images.githubusercontent.com/91680446/216660553-7faebb15-335c-44c8-92ec-85dd58951129.png)


slove this
