### ISSUE TITLE
Display Passport Stamps from Ceramic and Passport Scorer DB

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#884]
As a Passport holder, I want to be able to view the stamps on my passport in the Passport app.

**Acceptance Criteria**
GIVEN that a Passport holder is logged into the Passport app
WHEN we load their Passport
THEN we should load the stamps from both Ceramic and the Passport Scorer DB, compare and merge the two sources, and display the stamps to the user
AND if we are unable to access Ceramic
THEN display a message to the user that their complete passport may not be displayed due to the inability to access the Ceramic Passport, but their backup on the Gitcoin infrastructure is available.

**Notes**
 It should be possible for anybody to retrieve all stamps stored for a specific address in the Scorer DB via a `GET` request to the API endpoint `https://api.scorer.gitcoin.co/stamp_cache/0x_your_eth_address_here/`.

**Comment by nutrina** [comment]
Putting this on blocked, as we need a UI concept.
