### ISSUE TITLE
Score Eth addresses based on their stamps in Ceramic and the Passport Scorer DB

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#885]
As a Passport dev, I want to be able to score Eth addresses based on the stamps Passport holders have on both the Ceramic network and the Passport Scorer DB.

**Acceptance Criteria:**

- The API call to score an Eth address will load the Passport from the Scorer DB and Ceramic, and compare the two sets of stamps.
- If both sets of stamps are identical, score one or the other set.
- If the stamps have the same metadata but the stamp version in the DB is more recent, score the stamp from the Scorer DB.
- If the stamps have the same metadata but the stamp from Ceramic is more recent (this is unlikely), score the stamp from Ceramic.

**Notes:**

The developer making the API call must have a Gitcoin Passport API account and community configured and specify them in their API calls.

**Comment by lucianHymer** [comment]
Pending process review
