### ISSUE TITLE
Investigate FDD Data Retrieval for Passports Submitted in Alpha Rounds

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#893]
**Objective:** To determine the most efficient method for retrieving FDD data on passports submitted in the Alpha Rounds.

**Background:** We need to obtain the following data for every Passport submitted in the Alpha Rounds: `wallet address` and corresponding `passport score` and `boolean value for each possible stamp` indicating whether they have it or not.

**Method:**
- Research and compare the options of exporting the data from the Django backend versus having the Grants Protocol make the corresponding API call.
- Identify the pros and cons of each approach.
- Determine the best approach for retrieving the required data.

**Expected Outcome:** A clear recommendation on the most efficient method for retrieving FDD data on passports submitted in the Alpha Rounds, including any necessary steps for implementation.

**Comment by chibie** [comment]
@erichfi @nutrina 

We are considering the following approaches as an alternative to the reliance on the Passport team for exporting the required data. We hope this will be normalized going forward.

### Fetch the passport scores via the Scorer REST API
To implement this approach, FDD will need to generate an account, a community ID, and an API key through the Scorer interface. The data will be obtained by making an API call with the Auth key to the /registry/scorer/{community_id} endpoint. The Scorer will identify the Ethereum address associated with FDD and return the scores of all users.

#### Pros of using REST API:
* The API is already in place, reducing the time and effort required to implement a new solution.
* Accessing the data through the API can ensure a consistent and controlled interface, with well-defined parameters and response format.
* This can prevent unauthorized access to sensitive data stored in the database.
* The API can be easier to maintain and update compared to direct database access.

#### Cons of using REST API:
* Depending on the complexity of the required data and the current API design, it might be time-consuming to extract the required data.
* Performance could be an issue, as the API layer could add latency to the data retrieval process.
* The API could also limit the flexibility and control the FDD team has over the data, as they may not be able to directly query the data in the way they need it.

### Direct database read access to all tables and fetch scores via SQL
This approach involves providing direct database read access to all relevant tables. FDD can then retrieve the passport scores by executing an SQL query against the database. This method eliminates the need for an API call and provides a more direct and potentially faster means of accessing the data.

#### Pros of direct database read access via SQL:
* Direct database access offers the most flexible and efficient way to retrieve the required data.
* The FDD team can directly run complex queries to extract the data they need.
* Direct database access can result in faster data retrieval times compared to going through the API.

#### Cons of direct database read access via SQL:
* Direct database access could result in security and privacy concerns, as the FDD team would have access to the entire database and sensitive information.
* Maintenance and updates could be more challenging as direct database access would bypass any API layer that provides a controlled interface.
