### ISSUE TITLE
Load Scorer DB Stamps + Automated Stamp Migration for Passport App Users

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#912]
As a Passport app user, I can sign into the app and have my stamps automatically loaded from the Scorer DB. If my stamps are not found in the Scorer DB, the app will try to connect to Ceramic and migrate my stamps over to the Scorer DB.

**Acceptance Criteria**
GIVEN the Passport app user has signed into the app
WHEN the app checks for stamps in the Scorer DB
THEN the stamps should be successfully loaded if they exist in the Scorer DB
AND we don't try to load their Passport from Ceramic

GIVEN no stamps exist in the Scorer DB
WHEN the app tries to connect to Ceramic
THEN the connection should be successful

GIVEN the connection to Ceramic is successful
WHEN the app migrates stamps over to the Scorer DB
THEN the stamps should be successfully migrated and available in the Scorer DB

GIVEN that we cannot connect to Ceramic
WHEN we time out after ten seconds
THEN we assume the Passport is blank

GIVEN that the user sees the Ceramic loading toast
WHEN they hit "Cancel"
THEN we cancel the loading process 
AND assume their Passport is blank

GIVEN the Passport of the user is blank
WHEN we realized that
THEN we display a closable popup window with stamp verification directions

**Notes**
- Design assets are here: https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=299%3A8775&t=qbiTtCN0Jl2UP5DN-0
- Previous adjacent work done here: https://github.com/gitcoinco/passport/issues/884

**Comment by schultztimothy** [comment]
It looks like https://github.com/gitcoinco/passport/issues/884 was never started and the endpoint referenced in that ticket will be necessary to complete this ticket. I'm planning on completing the following note for 884 as part of this ticket

`
Notes
It should be possible for anybody to retrieve all stamps stored for a specific address in the Scorer DB via a GET request to the API endpoint https://api.scorer.gitcoin.co/stamp_cache/0x_your_eth_address_here/.
`
