### ISSUE TITLE
Passport Scoring using Stamps from DB and Ceramic

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#913]
The API user wants to score a Passport based on its stamps stored in the Scorer DB and only if they don't have stamps in the DB try Ceramic. The API needs to be able to connect to Ceramic and retrieve stamps if they are not available in the Scorer DB. The API also needs to update the Scorer DB with the stamps retrieved from Ceramic.

**Acceptance Criteria:**

GIVEN that the API user submits a Passport to score
WHEN the Passport has stamps stored in the Scorer DB
THEN the API should score the Passport based solely on the stamps stored in the DB

GIVEN that the Passport does not have stamps stored in the Scorer DB
WHEN the API tries to connect to Ceramic
THEN it should retrieve stamps from Ceramic if available

GIVEN that the API is able to connect to Ceramic and retrieve stamps
WHEN the API has retrieved the stamps
THEN it should copy the stamps to the Scorer DB
AND score the Passport based on the stamps stored in the DB.

GIVEN that the API is not able to connect within ten seconds
WHEN the ten seconds passed
THEN we treat the Passport as empty

**Notes:**
Previous work done here: https://github.com/gitcoinco/passport/issues/885

Checklist for scenarios above:
- [x] score stamps from db
- [x] score stamps from ceramic as fallback
- [ ] stores stamps from ceramic in DB
- [ ] use 10s timeout for ceramic API calls

**Comment by nutrina** [comment]
The point  `stores stamps from ceramic in DB` was not covered, but I don't think that was that important.
@erichfi closing this issue
