### ISSUE TITLE
Implement Google sign in for scorer admin

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#934]
GIVEN I am a member of the support staff
WHEN I got to https://api.scorer.dpopp.gitcoin.co/admin/
AND I am not yet logged in
THEN I can log in using Google authentication provider
AND I am only granted access if I have a `@gitcoin.co` email address

**Comment by Kweiss** [comment]
- [ ] Research Django plugins to accommodate the oAuth flow

(this may be helpful) 
- https://www.section.io/engineering-education/django-google-oauth/
- https://pypi.org/project/social-auth-app-django/

**Comment by schultztimothy** [comment]
Docs on creating google auth credentials: https://developers.google.com/identity/gsi/web/guides/get-google-api-clientid

**Comment by nutrina** [comment]
This works nicely for me.
