### ISSUE TITLE
Datadog sends to many "Passport error rate exceeded" alerts

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#938]
It is not clear where / how the metrics that trigger this event have been created.

**Comment by schultztimothy** [comment]
It looks like the events are meant to track successful and unsuccessful fetching of passports and are triggered when ratio is above 1:1. When we added the new database client we just added the error event.

This adds the successful log to the passport client and it should bring the ratio far below 1 https://github.com/gitcoinco/passport/pull/945
