### ISSUE TITLE
Verify Functionality of Eth Gas Spent Gitcoin Passport Stamp

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#949]
**Description:**
There have been issues regarding the Passport stamp, which is supposed to verify that a Passport holder has spent 0.5 Eth gas fees on the Eth mainnet. Our development team needs to investigate this issue and determine whether the stamp is functioning as intended.

**Objectives:**

- Review the current implementation of the Passport stamp for 0.5 Eth gas fees spent on Eth mainnet.
- Conduct thorough testing to determine whether the stamp properly verifies 0.5 Eth gas fees spent.
- Identify and resolve any issues found in the implementation or functionality of the stamp.

**Expected Outcome:**
A properly functioning Passport stamp that accurately verifies the spending of 0.5 Eth gas fees on the Eth mainnet.

**Comment by nutrina** [comment]
We are using the etherscan API to check the transactions performed by the user and calculate the ETH spent.
We should however check both, the:
- [ ] list of normal transactions
- [ ] list of internal transactions

**Comment by Kweiss** [comment]
@nutrina - When I use this app to determine how much Eth I have spent, it tells me I have spent over 5 Eth 😢 but I still dont get the stamp...

![Image](https://user-images.githubusercontent.com/1017776/229346887-e8ce2793-3d39-417f-aab1-62528b7872f1.png)

This is for my wallet address: 0xc2E2B715d9e302947Ec7e312fd2384b5a1296099

Can we confirm this is working?
