### ISSUE TITLE
From Discord: Passport Scoring Inaccuracy - admin improvements

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#963]
Discord thread: https://discord.com/channels/562828676480237578/1070849254895132742

Opening this ticket as I recognise we need to improve the admin to allow better investigation of such topics:
- [x] add score to admin
- [x] score should be searchable by address
- [x] add hash to ceramic cache model (also in the admin)
- [x] enable search by hash in admin for ceramic cache model

**Comment by lucianHymer** [comment]
![Image](https://user-images.githubusercontent.com/19908762/219806987-7c128a15-049f-4eac-b52d-3a9c530e56b9.png)

The hash is stored in the Stamp JSON field, so we have to just show the whole field.
It doesn't look too bad. We could hide it from the list view, but still allow it to be searchable by the Stamp field. But I think I'd rather just include it in the list.
