### ISSUE TITLE
API Access Guide for Researchers

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#967]
As part of our ongoing efforts to support identity researchers (like FDD) in their work, we need to draft a step-by-step guide for accessing the Scorer DB research API. This guide should include instructions on how to obtain reseach API access, as well as information on how to use the API with the Alpha Rounds data set as an example.

**Steps:**

- [ ] Research and gather information on the Scorer DB research API and its capabilities
- [ ] Draft a clear and concise guide for obtaining research API access
- [ ] Draft a step-by-step guide for using the research API with the Alpha Rounds data set
- [ ] Have @erichfi and @kbw review and provide feedback on the guide
- [ ] Make necessary revisions based on feedback
- [ ] Finalize and post the API access guide for researchers as a comment in this ticket

**Engineering work done to build the research API:**

  - https://github.com/gitcoinco/passport/issues/922 
  - https://github.com/gitcoinco/passport/issues/923
  - https://github.com/gitcoinco/passport/issues/924

**Comment by chibie** [comment]
Hey @erichfi,

We just pushed the analytics API documentation to the review environment => https://api.scorer.dpopp.gitcoin.co/analytics/docs

Could you review it and let us know if it's sufficient on the engineering side?

**Comment by lucianHymer** [comment]
Steps to add a researcher to the system:

1. Have the user create an account on the site and send us their address.
2. Log in to the admin console with superuser privileges.
3. Under Users, find the user with this address and add them to the Researcher group.
4. Under the Account section, add an API key for this account.
