### ISSUE TITLE
Create staging environment for scorer (UI & BE)

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#970]
Please deploy staging to fleek.
The BE should go to AWS ECS (same as review & production)

**Comment by lucianHymer** [comment]
We created a new "scorer" public ECR in the staging environment.

Should we delete the "dpopp" private ECR in the staging environment?

**Comment by schultztimothy** [comment]
I believe this is 99% complete.

- UI was deployed https://billowing-art-0068.on.fleek.co/ -> still need dns routing
- Route 53 zone has been created for `staging.scorer.gitcoin.co`
- scorer ECR registry was created 
- staging environment was setup in github and environment variables were added
  - with the EXCEPTION of `SCORER_SERVER_SSM_ARN`
- pulumi file should be setup correctly 🤞

**Comment by schultztimothy** [comment]
Manual deployments to [stagingscorergitcoinco.on.fleek.co](https://stagingscorergitcoinco.on.fleek.co/) should be all set 🚀
