### ISSUE TITLE
scorer.gitcoin.co - Sign in with Ethereum

### ISSUE THREAD

**Issue by Kweiss** [gitcoinco/passport#972]
### User Story:
As a developer looking to integrate with Gitcoin Passport
I want to land on a branded site that reflects the rest of Gitcoin's branding
So that I can trust the resources and have a consistent experience

### Acceptance Criteria
GIVEN someone navigates to scorer.gitcoin.co
WHEN they click the "sign in with Ethereum" button
THEN the new authorization flow should be presented to connect a wallet and sign a Tx.

#### Product & Design Links:
[Landing page designs after clicking "sign in with Ethereum"](https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=677%3A29587&t=SnTALj6Kc4pCCoAf-1)

[Landing Page wallet selection screen 2](https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=677%3A29427&t=SnTALj6Kc4pCCoAf-1)

[Landing page message signature request](https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=677%3A29757&t=SnTALj6Kc4pCCoAf-1)

#### Notes/Assumptions:
- [x] Sign in with Ethereum button shows the wallet selection dialog
- [x] The mask on the site is enabled (ie, the site is grey out a bit more while the wallet interaction is popped up)
- [x] After selecting a wallet, the signature request is immediately popped up
- [x] The status text is displayed while we wait for a signature message to be sent
   - [x] The message request - The website URL and favicon should be visible on the signature request message
   - [x] The message request - The message signature text should match the mockup.

**Comment by schultztimothy** [comment]
I'm remembering we talked a little about changing the signature message and just wanted to confirm this is the final message


![Image](https://user-images.githubusercontent.com/6887938/221256030-e9973a16-6094-489d-a875-e92f0217c032.png)
