### ISSUE TITLE
Scorer signed in landing page - update dashboard

### ISSUE THREAD

**Issue by Kweiss** [gitcoinco/passport#973]
### User Story:
As a developer looking to integrate with Gitcoin Passport
I want to create a scorer and define scoring mechanisms
So that I implement Passport in my app and protect my community from Sybil attacks

### Acceptance Criteria
GIVEN a developer has authenticated with the app (signed in with Ethereum)
WHEN the page loads to a blank "scorer" page
THEN we should showcase how to create a scorer

#### Product & Design Links:
[Scoring as a service - scorer - none](https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=678%3A21414&t=SnTALj6Kc4pCCoAf-1)

#### Notes/Assumptions:
- [ ] New logo is present in the header (white header, etc)
- [ ] The user's wallet connection is present in the top right of the webpage (and they have the ability to disconnect their wallet)... follow the norms of what we are using on passport.gitcoin.co
- [ ] Page heading and copy text is updated. spacing is consistent with mockup, etc.
- [ ] Community is rebranded to Scorer
- [ ] New call to action included to create a scorer
- [ ] ethereum account validation message at the footer is incorporated on appropriate authentication.
- [ ] Mobile friendly scaling is incorporated and followed.

**Comment by Etovardesign** [comment]
@lucianHymer Adding mobile view for this page:

[Mobile - Scoring as a Service - Scorer - none](https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=715%3A20659&t=XkWpOtO3L31z8wGG-1)

**Comment by lucianHymer** [comment]
draft here http://clever-dogs.surge.sh/
