### ISSUE TITLE
scorer.gitcoin.co - new scorer - use case selection 

### ISSUE THREAD

**Issue by Kweiss** [gitcoinco/passport#974]
### User Story:
As an authenticated developer who is trying to create a scorer for the firs time
I want help understanding what scorer is, and which one to select for my community
So that I can move quickly to testing the integration

### Acceptance Criteria
GIVEN a developer has authenticated with the app (signed in with Ethereum)
WHEN they click to create a scorer
THEN the use case selection dialog appears and guides them through creating a scorer

#### Product & Design Links:
[Scoring as a service - scorer - Use case](https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=693%3A21887&t=SnTALj6Kc4pCCoAf-1)

[Scoring as a service - scorer - Use case2](https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=693%3A22025&t=SnTALj6Kc4pCCoAf-1)

#### Notes/Assumptions:
- [x] New wizard appears on the button press of "+ Scorer"
- [x] the use cases should be selectable when clicking anywhere on the button/option (ie, clicking anywhere in the div should select it). Store this data with each scorer created so we can showcase it on the UI and report on it later.
- [x] Clicking continue will move us to the second frame (ideally with a motion slider... ie, the frame slides right  in the wizard and the new dialog is present)
- [x] "Use Case Details" dialog enable us to record a scorer name, and description.
- [ ] continuing past the details presents the new scoring mechanism selection page (that scope is in the next story)
- [x] Mobile-friendly scaling is incorporated and followed.

**Comment by Etovardesign** [comment]
@nutrina adding Mobile versions to these pages:

[Mobile - Scoring as a Service - Scorer - New - use case](https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=775%3A22955&t=NJAhfpPiOeOOM4vi-1)

[Mobile - Scoring as a Service - Scorer - New - use case2](https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=775%3A23054&t=NJAhfpPiOeOOM4vi-1)
