### ISSUE TITLE
scorer.gitcoin.co - new scorer - choosing mechanism

### ISSUE THREAD

**Issue by Kweiss** [gitcoinco/passport#975]
### User Story:
As an authenticated developer who is trying to create a scorer, after going through the use case selection
I want to see the scoring mechanisms available and select the mechanism that works best for my community
So that I offer the best experience for my users as possible

### Acceptance Criteria
GIVEN a developer has completed the use case selection dialog 
WHEN they land on the scorer creation page
THEN we should make a recommendation on which score to use and offer details on the deduplication methods available.

#### Product & Design Links:
[Scoring as a service - scorer - new - selection](https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=677%3A29315&t=SnTALj6Kc4pCCoAf-1)

#### Notes/Assumptions:
- [x] the Name and description are present in the header (with use case) for developers to reference.
- [x] Our default scoring mechanism it presented and selected.
- [x] the Scorer ID is present in the top right to ensure this can be found when trying to integrate.
- [x] Copy text is updated on deduplication, and the info icon is added to link out to the docs
- [x] We have a "coming soon" flag on the cost of forgery and custom scoring options and it is not selectable
- [x] Clicking "Create Scorer" records the scorer and returns the user back to the Scorer dashboard.
- [x] Mobile-friendly scaling is incorporated and followed.

**Comment by chibie** [comment]
Mobile - [Scoring as a service - scorer - new - selection]( https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=798%3A22477&t=m5lHLFRrSNeriX25-0)

**Comment by Etovardesign** [comment]
@chibie Something I realized might not be super clear, is that the Cancel and Create Scorer buttons should have a fixed position on Desktop and mobile. Let me know if you have any questions/concerns.
