### ISSUE TITLE
scorer.gitcoin.co - scorer dashboard with scorers created

### ISSUE THREAD

**Issue by Kweiss** [gitcoinco/passport#976]
### User Story:
As an authenticated developer who has created scorers
I want to see those scorers on a dashboard 
So I can easily reference them and their details (ie, access my scorer ID or review API request usage, etc.)

### Acceptance Criteria
GIVEN a developer has created at least one scorer 
WHEN they land on the scorer dashboard
THEN we should show those scorers in a list for them to review

#### Product & Design Links:
[Scoring as a service - scorer - success](https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=693%3A21635&t=SnTALj6Kc4pCCoAf-1)

#### Notes/Assumptions:
- [ ] If someone just created a scorer, the dialog at the bottom of the screen should appear. If they are landing here after signing in with ethereum, no dialog should be present.
- [ ] If a developer has a scorer, then we should also display the Quick Links and the Sample Applications
- [ ] the scorer should show the use case, name and other details

**Comment by nutrina** [comment]
Open points:
- [ ] test patch api
- [ ] update UI tests

**Comment by nutrina** [comment]
This has been merged and should be available on review.
