### ISSUE TITLE
scorer.gitcoin.co - navigate to API key page

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#980]
### User Story:
As a developer looking to integrate with Gitcoin Passport
I want to navigate to the API key page
So that I can create an API key to use the API in my app

### Acceptance Criteria
GIVEN a developer has authenticated with the app (signed in with Ethereum)
WHEN they click on "API keys"
THEN the app loads to a blank "API" page

#### Product & Design Links:
[Design Files](https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=678%3A21664&t=jK9Q5aZonuIFLRvr-1)

#### Notes/Assumptions:
- [ ] New logo is present in the header (white header, etc)
- [ ] The user's wallet connection is present in the top right of the webpage (and they have the ability to disconnect their wallet)... follow the norms of what we are using on passport.gitcoin.co
- [ ] Page heading and copy text is updated. spacing is consistent with mockup, etc.
- [ ] the updated visuals and wording informing users about the five-key-limit should be there

**Comment by chibie** [comment]
Mobile design: https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=715%3A21205&t=XozIAQy67eKlvdlP-0
