### ISSUE TITLE
Zksync non-transfer transactions

### ISSUE THREAD

**Issue by lucianHymer** [gitcoinco/passport#983]
We're using the zksync API to search for a users most recent 100 transaction in zksync.

Clarify the following in a sidebar banner for the zkSync 1.0 credential in the zkSync stamp.

> We look for a transaction with a _finalized_ status and an _op.from_ field that matches the user's address.

However, op.from seems to only exist on Transfer type transactions (which is the only type shown in the [docs](https://docs.zksync.io/apiv02-docs/#accounts-api-v0.2-accounts-{accountidoraddress}-transactions-get)).

Other transactions like MintNFT or Swap are quite different.

I'm not sure what all the different types and schemas are. Do we want to support some additional types? Or just leave it as-is? If leaving it as-is, we may want to add some info to the UI to explain all this.

**Comment by lucianHymer** [comment]
The transaction types and associated schemas don't seem to be documented anywhere. We should likely just leave as-is and add more clarification to the UI.

**Comment by michaelgreen06** [comment]
This is the copy I landed on:

"We currently only recognize finalized "TRANSFER" type transactions on ZkSync 1.0. This means that other transactions like MintNFT, Swap etc aren't recognized."

Happy to change if desired.
