### ISSUE TITLE
Redesigned home page for mobile version of scorer.gitcoin.co

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#994]
Here is the mobile view to the home page - mobile-friendly scaling is incorporated and followed.

[Mobile Landing Page Figma Designs](https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=924%3A23919&t=XkWpOtO3L31z8wGG-1)

**Comment by lucianHymer** [comment]
Ready for review at https://main.d26qkvvv9tu48j.amplifyapp.com/
